import type { HelpArticle } from './index';

export const COMPLIANCE_AUDIT: HelpArticle[] = [
  {
    slug: 'audit-trail',
    title: 'Audit Trail — How It Works',
    category: 'compliance-audit',
    purpose: 'The audit trail is an append-only, hash-chained log of every state-changing action in eCIgn.',
    whenToUse: 'Whenever a surveyor, compliance officer, or counsel needs to reconstruct who did what, when, from where, on what document version.',
    systemBehavior: 'Every event row stores: event_id, prev_hash, hash = SHA-256(prev_hash | canonical(payload)), occurred_at_utc, actor (user_id, name, role, email, auth_method, mfa_verified_at), network (ip, user_agent, geo, device), subject (kind, id, document_version_id, document_hash), action, payload. Rows are inserted via POST /api/audit (internal) only; UPDATE/DELETE grants are revoked in production.',
    complianceImpact: 'Satisfies HIPAA 164.312(b) audit controls and CMS 42 CFR § 484 survey reconstruction requirements.',
    evidence: 'Every signing event, edit attempt, lock, void, export, and access denial is on the chain.',
    related: { endpoints: ['GET /api/audit/events?subject_id=...', 'POST /api/audit/verify-chain'] },
  },
  {
    slug: 'verify-chain',
    title: 'Verifying the Audit Chain',
    category: 'compliance-audit',
    purpose: 'Detect tampering of the audit log.',
    whenToUse: 'Daily (scheduled job), before every survey export, and on demand from the AuditModePage.',
    steps: [
      'Issue POST /api/audit/verify-chain (optionally with ?subject_id=...).',
      'Inspect the response: `{ ok: boolean, first_break?: event_id, verified: number }`.',
      'If `ok=false`, escalate immediately — the chain is broken from `first_break` onward.',
    ],
    systemBehavior: 'Server walks every event from genesis recomputing SHA-256(prev_hash | canonical(body)) and comparing to the stored hash. Any mismatch returns the offending event_id.',
    complianceImpact: 'Demonstrates integrity for ESIGN record retention and CMS audit defensibility.',
    evidence: 'Verification response timestamped and logged as an internal `integrity.check` event.',
    related: { endpoints: ['POST /api/audit/verify-chain'] },
  },
  {
    slug: 'compliance-objects',
    title: 'Compliance Objects & State Transitions',
    category: 'compliance-audit',
    purpose: 'A signature is a state transition on a regulated compliance object — never just a UI action.',
    whenToUse: 'Whenever a signed document must unlock a downstream effect (billing, HR compliance, event closure).',
    systemBehavior: 'On lock, evaluateOnLock() inspects the form_id, picks the matching rule, computes (object_kind, object_id, state_before → state_after), verifies dependencies (consent, identity, review_ack, document_hash, all_required_signed), and writes a row to `compliance_states` plus a `compliance.transitioned` audit event.',
    complianceImpact: 'Enables surveyors to answer "Why was this action allowed at this time, and what made it compliant?" by replaying compliance_states + audit_events for the object.',
    evidence: 'compliance_states.jsonl row + compliance.transitioned audit event.',
    related: {
      endpoints: ['GET /api/compliance/objects/:kind/:id', 'GET /api/compliance/blocked'],
      workflows: ['POC → billable', 'policy_ack → acknowledged', 'QAPI → closed', 'HR → signed'],
    },
  },
  {
    slug: 'survey-packet',
    title: 'Generating a Survey Packet',
    category: 'compliance-audit',
    purpose: 'Bundle every artifact a CMS surveyor needs into a single, hash-stamped ZIP.',
    whenToUse: 'On request from a CMS surveyor or as part of internal mock-survey drills.',
    steps: [
      'Open the AuditModePage at `/audit`.',
      'Select the POC, employee, or QAPI event.',
      'Click "Generate Survey Packet" — GET /api/ecign/instances/:id/bundle (extended).',
    ],
    systemBehavior: 'Bundle contains: signed PDF (template + watermark + appended pages), audit trail PDF + JSON, governing policy snapshot, dependency-check results, and the manifest hash.',
    complianceImpact: 'Provides reconstruction evidence aligned with the 42 CFR Part 484 survey protocol.',
    evidence: '`export.generated` audit event with kind="survey_packet".',
    related: { components: ['AuditModePage'], endpoints: ['GET /api/ecign/instances/:id/bundle'] },
  },
  {
    slug: 'guardrails',
    title: 'Failure Prevention Guardrails (G1–G8)',
    category: 'compliance-audit',
    purpose: 'Eight server-enforced rules that prevent any non-compliant outcome regardless of UI state.',
    whenToUse: 'Reference whenever a request is rejected with one of the canonical error codes.',
    systemBehavior: 'G1 CONSENT_REQUIRED · G2 NOT_AUTHENTICATED / STEP_UP_REQUIRED · G3 SIGNATURES_INCOMPLETE · G4 DOCUMENT_LOCKED · G5 DUPLICATE_SIGNATURE · G6 risk.late_signature flag (verbal-order window) · G7 INVALID_STATE_TRANSITION · G8 chain verification failure.',
    complianceImpact: 'Each guardrail maps to a specific ESIGN/UETA/CMS/HIPAA requirement; violations are themselves recorded as `access.denied` or `integrity.mismatch` audit events.',
    evidence: 'For every rejected request, an audit event with reason and offending payload diff.',
    related: { endpoints: ['POST /api/ecign/instances/:id/signatures', 'PATCH /api/ecign/instances/:id/fields'] },
  },
];
