import type { HelpArticle } from './index';

export const GETTING_STARTED: HelpArticle[] = [
  {
    slug: 'first-login-set-permanent-password',
    title: 'First Login: Set Your Permanent Password',
    category: 'getting-started',
    purpose: 'Guides a newly approved user through signing in with an administrator-provided one-time temporary password and replacing it with a permanent password.',
    whenToUse: 'Use this article when a user has been created or reset by an administrator and their Cognito account is in the first-login password-change state.',
    steps: [
      'Open the Care Indeed sign-in page.',
      'Enter the registered email address exactly as provided by the administrator.',
      'Enter the one-time temporary password provided by the administrator, then select Sign In.',
      'When the Set New Password page opens, enter a new permanent password.',
      'Re-enter the same permanent password in Confirm Password.',
      'Select Set Password & Continue.',
      'After the password is accepted, continue into the dashboard. If the app returns to sign-in, sign in again with the new permanent password.',
    ],
    screenshots: [
      {
        src: '/help/auth-new-password-flow/first-login-email.png',
        alt: 'Sign-in page with the registered email address entered.',
        caption: 'Enter the registered email address on the sign-in page.',
      },
      {
        src: '/help/auth-new-password-flow/first-login-temp-password.png',
        alt: 'Sign-in page with the temporary password field masked.',
        caption: 'Enter the administrator-provided temporary password. The field is masked for security.',
      },
      {
        src: '/help/auth-new-password-flow/set-new-password-empty.png',
        alt: 'Set New Password page with empty password fields.',
        caption: 'A valid temporary password opens the Set New Password page.',
      },
      {
        src: '/help/auth-new-password-flow/set-new-password-filled.png',
        alt: 'Set New Password page with both password fields masked.',
        caption: 'Enter and confirm the permanent password, then continue.',
      },
    ],
    systemBehavior: 'The login API returns a Cognito NEW_PASSWORD_REQUIRED challenge for a valid temporary password. The app routes the user to /set-new-password with the opaque challenge session held only in route state. The set-new-password form sends the email, challenge session, and new password to /auth/respond-challenge. On success, Cognito confirms the user and the app receives a normal authenticated session.',
    complianceImpact: 'Supports controlled account provisioning by forcing users to replace administrator-issued temporary credentials before normal use. This avoids email-dependent reset workflows and preserves least-privilege authentication controls.',
    evidence: 'Cognito changes the user from FORCE_CHANGE_PASSWORD to CONFIRMED after the password challenge is completed. No temporary password, permanent password, or Cognito challenge session is stored in Help Center content.',
    complianceRequirement: 'Temporary passwords must be single-use and administrator-delivered through an approved channel. Users must set a permanent password before accessing protected app content.',
    enforcementRules: [
      'Do not use the forgot-password flow for first-login setup.',
      'Do not reuse old temporary passwords.',
      'Do not share temporary passwords in screenshots, tickets, reports, or source files.',
      'Do not store the Cognito challenge session in localStorage or sessionStorage.',
    ],
    requiredActions: [
      'Confirm the user is using the exact registered email address.',
      'Confirm the temporary password was copied exactly.',
      'Generate a fresh temporary password if the first-login challenge does not appear.',
      'After successful setup, instruct the user to sign in only with the new permanent password.',
    ],
    auditLogging: 'Administrators should record the target email, actor, timestamp, reset/recovery method, and forceChangeOnFirstLogin=true. Audit entries must never include temporary or permanent password values.',
    failureImpact: 'If the temporary password is expired, already consumed, copied incorrectly, or replaced by a newer reset, the user will not reach the Set New Password page. Generate a new one-time temporary password and retry.',
    traceability: {
      policy_id: 'IT-AC-001',
      workflow_id: 'IT-WF-02',
      evidence_id: 'Cognito UserStatus and active registration record',
    },
    related: {
      policies: ['IT-AC-001'],
      workflows: ['IT-WF-02'],
      endpoints: ['POST /auth/login', 'POST /auth/respond-challenge'],
      components: ['LoginPage', 'SetNewPasswordPage', 'AuthProvider'],
    },
  },
  {
    slug: 'overview',
    title: 'Welcome to CI-App eCIgn',
    category: 'getting-started',
    purpose: 'CI-App eCIgn is the legally enforceable, audit-ready electronic signature subsystem of CI-App for Care Indeed Home Health Care, Inc.',
    whenToUse: 'Any time a Care Indeed document requires a signature: Plans of Care, physician orders, policy acknowledgments, QAPI minutes, HR onboarding records, or mandatory event reports.',
    systemBehavior: 'eCIgn enforces a six-step workflow (Disclosure → Identity → Review → Signature → Attestation → Lock) at the server boundary. Templates are byte-preserved; evidence is added via a footer watermark and four appended pages (Certificate, Identity & Device, Audit Trail, Hash Manifest).',
    complianceImpact: 'Aligns with ESIGN Act (15 U.S.C. §§ 7001–7031), UETA, HIPAA (45 CFR §§ 164.308 / 164.312), and CMS Home Health Conditions of Participation (42 CFR Part 484).',
    evidence: 'Every signing event produces: signed PDF (template + watermark + appended pages), audit trail report, signature certificate page, and a survey packet ZIP.',
    related: {
      policies: ['EN-CM-001', 'CO-CP-001', 'CL-CC-001'],
      components: ['CommandCenterLayout', 'FormSigningWorkspace', 'AuditModePage'],
    },
  },
  {
    slug: 'roles-and-tiers',
    title: 'Roles, Tiers & Permissions',
    category: 'getting-started',
    purpose: 'CI-App uses a four-tier role model that governs who can sign what, who can request a second signature, and who can void a signed document.',
    whenToUse: 'Before assigning an approver, requesting a second signature, or attempting to void a signed instance.',
    systemBehavior: 'Tier 1 = Administrator; Tier 2 = Administrator Designee; Tier 3 = Compliance Officer; Tier 4 = Clinical Manager / Liaison. Second-signature requests must target a tier strictly above the requester. Void operations require tier ≤ 2 (server-enforced in /api/ecign/instances/:id/void).',
    complianceImpact: 'Prevents unauthorized approvals (HIPAA 164.312(a) access control) and ensures separation of duties for CMS survey defensibility.',
    evidence: 'Every tier check generates either a successful audit event or an `access.denied` event with the offending payload.',
    related: {
      endpoints: ['POST /api/ecign/instances/:id/second-signature', 'POST /api/ecign/instances/:id/void'],
      components: ['FormSignatureFlow.SecondSignatureModal'],
    },
  },
  {
    slug: 'navigation',
    title: 'Navigation & Workspace Layout',
    category: 'getting-started',
    purpose: 'CI-App uses a single-pane shell with a left command rail and a two-panel content area: document on the left, audit/signer/workflow context on the right.',
    whenToUse: 'Always — this is the design contract. No workflow uses hidden navigation or layered cards.',
    systemBehavior: 'Routes: `/dashboard` (Command Center) · `/forms` (forms dashboard) · `/forms/:id` (signing workspace) · `/audit` (admin compliance view) · `/help` (this Help Center) · `/workflows` · `/library` · `/calendar` (Master Calendar).',
    complianceImpact: 'Visibility supports the "all critical data within 1–2 interactions" rule from §01 Design Enforcement.',
    evidence: 'No persisted artifact — UI behavior only.',
    related: { components: ['CommandCenterLayout', 'UniversalNavControls'] },
  },
];
