/** Onboarding V2 — Help Center articles. */
import type { HelpArticle } from './index';

const C = 'onboarding-v2';

export const ONBOARDING_V2: HelpArticle[] = [
  {
    slug: 'ov2-overview',
    title: 'Onboarding v2 — What it is and why it exists',
    category: C, subcategory: 'Getting Started',
    purpose: 'Explain the audit-grade onboarding execution module that replaces the legacy journey for compliance-bound activations.',
    whenToUse: 'Read first when learning the v2 surface. Compliance officers, supervisors, administrators, and surveyors should all start here.',
    steps: [
      'Open Onboarding v2 → Dashboard for the live posture across all subjects.',
      'Use Activate Subject to trigger a NEW_HIRE, ROLE_CHANGE, ANNUAL_REVALIDATION, POLICY_VERSION_UPDATE, or VENDOR_ONBOARD.',
      'Open any batch to inspect gates, phases, units, evidence, signatures, and the immutable audit chain.',
      'Use Audit Readiness to export a per-subject dossier verifiable against hash-chained events.',
    ],
    systemBehavior: 'Activation is deterministic: a single trigger emits one batch, one set of units, and a hash-chained sequence of audit events. Every state transition writes an event keyed by sequence number with prevHash → eventHash linkage.',
    complianceImpact: 'Replaces ad-hoc onboarding checklists with surveyor-defensible execution: every requirement is bound to a published policy version, every artifact is content-hashed, every gate is computed from contributing requirements.',
    evidence: 'Snapshot of the dashboard, exported per-subject dossier (JSON), and the live audit feed with hash-chain verification status.',
    related: { components: ['DashboardPage', 'ActivationPage', 'AuditReadinessPage'] },
  },
  {
    slug: 'ov2-roles',
    title: 'Role-based onboarding — 17 roles, one engine',
    category: C, subcategory: 'Role-Based Onboarding',
    purpose: 'Document how role taxonomy drives the requirement set per subject.',
    whenToUse: 'When activating a new hire or changing a role; when reconciling why two subjects with the same trigger received different units.',
    steps: [
      'Open Activate Subject and pick the subject.',
      'Choose roles (multi-select). Each role contributes its template requirements.',
      'Inspect the reconciliation preview — already-valid evidence within window will be suppressed.',
      'Activate — one batch is created with the union of role-driven requirements.',
    ],
    systemBehavior: 'Each role maps to an OnboardingTemplate filtered by trigger type. Templates resolve to RoleRequirements and EvidenceRequirements; the engine emits one OnboardingExecutionUnit per requirement with policy-version binding.',
    complianceImpact: 'Guarantees that every role gets the regulator-mandated checklist, never less. Branch- and license-scoped requirements are added by the same template logic, not by manual edits.',
    evidence: 'Activation audit trail: TRIGGER_RECEIVED → PROFILE_RESOLVED → TEMPLATE_SELECTED → BATCH_CREATED → REQUIREMENT_EMITTED.',
    related: { components: ['ActivationPage', 'BatchViewPage'] },
  },
  {
    slug: 'ov2-ces-integration',
    title: 'CES integration — sprints, calendar, reports',
    category: C, subcategory: 'CES Integration',
    purpose: 'Explain how Onboarding v2 units surface inside the Compliance Execution System.',
    whenToUse: 'When planning sprints; when verifying that an activation generated calendar items; when reviewing CES reports.',
    systemBehavior: 'Each unit emits CES-compatible events (REQUIREMENT_EMITTED) that the existing CES engine can ingest. Due dates are computed from cadence.initialWithinDays.',
    complianceImpact: 'Maintains one source of truth for compliance work: onboarding does not create a parallel queue.',
    evidence: 'Cross-link from /onboarding-v2/batches/:id to the CES Sprint Board filtered by subject.',
    related: { components: ['BatchViewPage'] },
  },
  {
    slug: 'ov2-evidence',
    title: 'Evidence & Forms — capturing immutable artifacts',
    category: C, subcategory: 'Evidence & Forms',
    purpose: 'Explain how evidence is captured, validated, and bound to units and policy versions.',
    whenToUse: 'When uploading a credential, attesting a form, or recording a training completion.',
    steps: [
      'Open a unit drawer → Evidence tab.',
      'Select the required object type (PSVResult, TrainingRecord, FormSubmission, etc.).',
      'Provide the filename. The system computes a content hash and binds the artifact to the unit, batch, subject, and policy version.',
      'On capture, the unit auto-transitions if all evidence + signature requirements are satisfied.',
    ],
    systemBehavior: 'EvidenceObjects are immutable; rejection or supersession does not delete prior records. The reconciler checks freshness (annual / biennial / monthly) before suppressing future requirements.',
    complianceImpact: 'Surveyors can verify that the artifact presented today is the same artifact captured at the time of attestation (identical contentHash).',
    evidence: 'EVIDENCE_CAPTURED audit event with hash; download record with policyVersionRef.',
    related: { components: ['EvidencePanel', 'UnitDrawer'] },
  },
  {
    slug: 'ov2-competency',
    title: 'Competency validation — the 12-subject HHA artifact',
    category: C, subcategory: 'Competency Validation',
    purpose: 'Document how clinical and HHA competency requirements are tracked to artifact-level completion.',
    whenToUse: 'When a HHA, RN, LVN, PT, OT, ST, MSW completes initial or annual competency.',
    systemBehavior: 'CompetencyArtifact evidence binds to a CompetencyView which enumerates required subject codes. The unit cannot reach Completed until every required subject is attested by a qualified observer.',
    complianceImpact: 'Maps directly to CMS §484.80 competency requirements; supports the 12-subject HHA list used by surveyors during chart review.',
    evidence: 'CompetencyArtifact with subject codes, observer signature, and policy version.',
    related: { policies: ['CL-CC-001', 'CL-CC-002'] },
  },
  {
    slug: 'ov2-acknowledgments',
    title: 'Policy acknowledgments — version-bound, never bulk',
    category: C, subcategory: 'Policy Acknowledgments',
    purpose: 'Explain how policy acknowledgment requirements are emitted and signed.',
    whenToUse: 'During NEW_HIRE, after every POLICY_VERSION_UPDATE, and during ANNUAL_REVALIDATION.',
    systemBehavior: 'Each acknowledgment unit is bound to PolicyId@PolicyVersion + contentHash. Re-publishing a policy emits a fresh POLICY_VERSION_UPDATE trigger that creates new acknowledgment units only for affected subjects.',
    complianceImpact: 'Prevents stale-version drift: an acknowledgment signed against v2025.10 does not satisfy v2026.01.',
    evidence: 'SignatureRecord with bindsToType=PolicyVersion, bindsToRef=POLICY_ID@VERSION, signedArtifactHash.',
    related: { components: ['SignerStrip'] },
  },
  {
    slug: 'ov2-ecign',
    title: 'eCIgn signatures — identity-verified attestation',
    category: C, subcategory: 'eCIgn Signatures',
    purpose: 'Document the eCIgn binding for onboarding signatures.',
    whenToUse: 'For every signature unit (Subject acknowledgment, supervisor attestation, dual override).',
    systemBehavior: 'A signature envelope is created for each SignatureRequirement; on completion the engine stores signedArtifactUri + signedArtifactHash + timestamp + authMethod.',
    complianceImpact: 'Each signature is identity-verified, time-stamped, and re-verifiable years later from the audit chain alone.',
    evidence: 'SIGNATURE_REQUESTED + SIGNATURE_COMPLETED audit events with hash.',
    related: { components: ['SignerStrip', 'SignaturePanel'] },
  },
  {
    slug: 'ov2-audit',
    title: 'Audit Readiness — the surveyor dossier',
    category: C, subcategory: 'Audit Readiness',
    purpose: 'Explain the per-subject dossier and hash-chain verification.',
    whenToUse: 'During internal audit prep, mock surveys, or live regulator visits.',
    steps: [
      'Open Audit Readiness and pick the subject.',
      'Verify the hash-chain integrity badge reads Verified.',
      'Walk the tabs (Credentials → Acknowledgments → Competencies → Trainings → Gates → Overrides → Evidence → Audit chain) to demonstrate full provenance.',
      'Click Export dossier (JSON) to hand the surveyor a self-contained, machine-verifiable record.',
    ],
    systemBehavior: 'The dossier composes from snap.audit, snap.evidence, snap.signatures, snap.gateEvaluations, and snap.overrides for the subject; verifyChain re-derives every event hash.',
    complianceImpact: 'Replaces hours of paper chart pulls with a single deterministic export.',
    evidence: 'Exported dossier file plus the verifyChain result.',
    related: { components: ['AuditReadinessPage'] },
  },
  {
    slug: 'ov2-revalidation',
    title: 'Recurring revalidation — annual, biennial, monthly',
    category: C, subcategory: 'Recurring Revalidation',
    purpose: 'Document how the engine handles cadence-driven re-emission.',
    whenToUse: 'When approaching an annual due date or revalidating after an extended leave.',
    systemBehavior: 'Each requirement carries a Cadence (initialWithinDays + recurrence). The reconciler suppresses new emission while the prior evidence is within window; on expiry, the next ANNUAL_REVALIDATION trigger emits a fresh unit.',
    complianceImpact: 'No requirement is ever silently skipped; lapse is auto-detected and flagged.',
    evidence: 'REQUIREMENT_RECONCILED audit event when suppressed; REQUIREMENT_EMITTED when re-emitted.',
    related: { components: ['ActivationPage', 'DashboardPage'] },
  },
  {
    slug: 'ov2-vendor',
    title: 'Vendor & Governance — Business Associate onboarding',
    category: C, subcategory: 'Vendor & Governance',
    purpose: 'Explain VENDOR_ONBOARD and the governance surface.',
    whenToUse: 'When onboarding a Business Associate, 1099 contractor, or other third party.',
    systemBehavior: 'VENDOR_ONBOARD trigger emits a vendor-scoped batch (BAA execution, insurance verification). Vendor units feed the VendorEngagement gate.',
    complianceImpact: 'Prevents PHI exposure to vendors without an executed BAA.',
    evidence: 'BAA SignatureRecord and VendorAgreement evidence with hash.',
    related: { components: ['ActivationPage', 'GovernancePage'] },
  },
  {
    slug: 'ov2-overrides',
    title: 'Overrides — when and how to use Conditional clearance',
    category: C, subcategory: 'Compliance Enforcement & Overrides',
    purpose: 'Document the override flow with dual-signature governance.',
    whenToUse: 'Only when continuing operations is necessary and a mitigating control is in place.',
    steps: [
      'Open Governance → Request override.',
      'Pick subject + gate; provide a justification (becomes part of the audit record).',
      'Set the validity window (default 30 days).',
      'Submit. The gate now evaluates as Conditional; the underlying breach is preserved.',
    ],
    systemBehavior: 'OverrideRecord is appended to snap.overrides; the gate evaluator returns outcome=Conditional + active override id; an OVERRIDE_GRANTED audit event is written.',
    complianceImpact: 'Overrides never erase a failure — they record an informed risk acceptance with named accountable signers.',
    evidence: 'OverrideRecord (subjectId, gateId, reason, signers, validFrom/To) and OVERRIDE_GRANTED audit event.',
    related: { components: ['GovernancePage', 'GateTile'] },
  },
  {
    slug: 'ov2-troubleshooting',
    title: 'Troubleshooting — common scenarios',
    category: C, subcategory: 'Troubleshooting',
    purpose: 'Resolve common questions raised by supervisors and compliance officers.',
    whenToUse: 'When a unit appears stuck or a gate is unexpectedly Pending.',
    steps: [
      'Unit stuck in AwaitingSignature → check Signatures tab; envelope may be Sent but not Viewed.',
      'Unit Blocked → open the unit drawer; the dependencies list shows unmet pre-conditions.',
      'Gate Pending → no contributing requirements have been emitted; check that the activation actually created a batch.',
      'Reconciliation suppressed unexpectedly → review the existing EvidenceObject; if outside window, re-trigger ANNUAL_REVALIDATION.',
    ],
    systemBehavior: 'Every state has a deterministic upstream cause that is visible in the audit chain.',
    complianceImpact: 'Reduces ticket volume and supports self-service triage.',
    evidence: 'UNIT_STATE_CHANGED + GATE_EVALUATED audit events.',
    related: { components: ['UnitDrawer', 'BatchViewPage'] },
  },
  {
    slug: 'ov2-surveyor-quick',
    title: 'Surveyor quick answers',
    category: C, subcategory: 'Surveyor Quick Answers',
    purpose: 'One-pager of common surveyor prompts and where to find the answer.',
    whenToUse: 'During an active survey.',
    steps: [
      '“Show me {employee name}\'s onboarding file.” → Audit Readiness → pick subject → Export dossier.',
      '“What policy version was acknowledged?” → Acknowledgments tab → policy chip shows POLICY_ID v2026.01.',
      '“How do you know they did 12-subject HHA training?” → Competencies tab → CompetencyArtifact with subject codes and observer signature.',
      '“Show me a hire who got Conditional clearance.” → Governance → Active overrides; or Audit Readiness → Overrides tab.',
      '“Prove the audit log is intact.” → Audit Readiness → Hash-chain integrity = Verified.',
    ],
    systemBehavior: 'All answers come from a single immutable snapshot; no separate spreadsheets.',
    complianceImpact: 'Drastically shortens surveyor visits and increases first-pass clean survey rate.',
    evidence: 'Live screen-share of the Audit Readiness surface with the dossier export.',
    related: { components: ['AuditReadinessPage', 'GovernancePage'] },
  },
];
