import type { HelpArticle } from './index';

export const POLICY_LIFECYCLE: HelpArticle[] = [
  {
    slug: 'lifecycle-overview',
    title: 'Policy Lifecycle Workspace — Overview',
    category: 'policy-lifecycle',
    purpose: 'The Policy Lifecycle Workspace at /policy-lifecycle is the single screen for drafting, reviewing, approving, publishing, and archiving every Care Indeed policy. It replaces the legacy Drafts, Review Queue, and Publishing screens.',
    whenToUse: 'Any time a policy needs to be authored, advanced, signed off, distributed, or retired.',
    steps: [
      'Open Policy Lifecycle from the left rail.',
      'Use the state filter chips at the top right to narrow to a single state (DRAFT, REVIEW, APPROVED, PUBLISHED, ARCHIVED).',
      'Pick a policy from the left rail to load its envelope.',
      'Switch the workspace mode (edit · review · approve · publish · view) using the chips above the description.',
      'Use the right-rail Available Actions to advance the policy through the canonical 5-state machine.',
    ],
    systemBehavior: 'The page binds to usePolicyLifecycleStore. Every action call routes through src/policy/lifecycle/stateMachine.ts which validates the transition, enforces guards (rationale length, no self-approval, auditor-mode block), appends a hash-chained history event, and updates the envelope atomically.',
    complianceImpact: 'Provides a single auditable surface for every policy state change. Each transition produces a chained history entry that is replayable for surveyors (CMS 42 CFR Part 484, HIPAA 164.312(b) audit controls).',
    evidence: 'PolicyLifecycleEnvelope.history — append-only chain stored per policy id. Mirrors to migrations/002_policy_lifecycle_schema.sql (policy_lifecycle_history) when persisted.',
    related: {
      components: ['src/policy/pages/PolicyLifecyclePage.tsx', 'src/policy/lifecycle/lifecycleStore.ts'],
    },
  },
  {
    slug: 'lifecycle-five-states',
    title: 'The Five Canonical States',
    category: 'policy-lifecycle',
    purpose: 'Care Indeed uses exactly five lifecycle states: DRAFT, REVIEW, APPROVED, PUBLISHED, and ARCHIVED. Old versions are either superseded by a new active version or formally archived with a documented justification.',
    whenToUse: 'Reference any time you need to know what a state means or what comes next.',
    steps: [
      'DRAFT — the policy is being authored or revised. The author may freely edit sections.',
      'REVIEW — the policy is locked from author edits. Reviewers may comment; required comments must be resolved before approval.',
      'APPROVED — required signatures have been captured. The policy is publish-ready and immutable.',
      'PUBLISHED — the policy is enforceable, distributed to its audience, and accumulating acknowledgments.',
      'ARCHIVED — terminal state. Used only when a policy is being legally retired with documented justification.',
    ],
    systemBehavior: 'Allowed transitions are enumerated in stateMachine.ts. Forbidden transitions (e.g. PUBLISHED → APPROVED, ARCHIVED → anything) return an INVALID_TRANSITION rejection.',
    complianceImpact: 'The fixed vocabulary prevents enforcement gaps. Auditors can reason about a policy by inspecting one of five labels and one history chain.',
    evidence: 'src/policy/lifecycle/types.ts — LifecycleState; STATE_ORDER, STATE_LABEL, STATE_COLOR; MODES_BY_STATE.',
    related: {
      components: ['src/policy/lifecycle/types.ts', 'src/policy/lifecycle/stateMachine.ts'],
    },
  },
  {
    slug: 'lifecycle-transitions',
    title: 'Allowed Transitions & Guards',
    category: 'policy-lifecycle',
    purpose: 'Every state change is the result of an explicit, named intent. The state machine refuses any other path.',
    whenToUse: 'When you need to know what action to take to move a policy forward — or why an action you tried was rejected.',
    steps: [
      'DRAFT → REVIEW via submitForReview',
      'REVIEW → DRAFT via requestRevision (rationale required) or reject (rationale required)',
      'REVIEW → APPROVED via approve (author cannot self-approve)',
      'APPROVED → PUBLISHED via publish',
      'APPROVED → DRAFT via requestRevision',
      'PUBLISHED → DRAFT via reopenForRevision (rationale required; published copy stays enforceable until republish)',
      'Any state → ARCHIVED via archive (rationale required)',
    ],
    systemBehavior: 'Guards enforced in transition(): rationale ≥ 8 characters for revision/reject/archive/reopen; actor ≠ creator for approve; auditor mode blocks all transitions; ARCHIVED is terminal.',
    complianceImpact: 'Self-approval block (separation of duties) and rationale requirement (paper-trail completeness) are required by Care Indeed governance policy GV-GB-001.',
    evidence: 'Each rejection emits a typed code (INVALID_TRANSITION, MISSING_RATIONALE, SELF_APPROVAL_FORBIDDEN, AUDITOR_MODE_BLOCK, ALREADY_TERMINAL) shown to the user in the right-rail message strip.',
    related: {
      components: ['src/policy/lifecycle/stateMachine.ts'],
    },
  },
  {
    slug: 'lifecycle-author-attribution',
    title: 'Author Attribution & Self-Approval Block',
    category: 'policy-lifecycle',
    purpose: 'Every policy envelope is created by exactly one author whose identity is captured at creation time and immortalized in the chain.',
    whenToUse: 'Reference when triaging a "self-approval forbidden" rejection or when verifying provenance during an audit.',
    systemBehavior: 'usePolicyLifecycleStore seeds every framework policy with TJ Padilla (robertp@careindeed.com, AI Researcher) as the author. The state machine refuses approve when ctx.actor.userId === envelope.createdBy.userId.',
    complianceImpact: 'Separation of duties is foundational to CMS, HIPAA, and CA Title 22 compliance. The block is enforced at the pure-function layer, so no UI bypass is possible.',
    evidence: 'PolicyLifecycleEnvelope.createdBy is set on createEnvelope() and never mutated. SELF_APPROVAL_FORBIDDEN rejections are rendered in the right-rail action card.',
    related: {
      components: ['src/policy/lifecycle/lifecycleStore.ts', 'src/policy/lifecycle/stateMachine.ts'],
    },
  },
  {
    slug: 'lifecycle-history-chain',
    title: 'Lifecycle History Hash Chain',
    category: 'policy-lifecycle',
    purpose: 'Each transition appends one hash-chained event to PolicyLifecycleEnvelope.history. The chain hash is derived from the prior chain hash plus the current event payload, producing a tamper-evident sequence.',
    whenToUse: 'When responding to a survey or audit request that asks for the complete state history of a policy.',
    systemBehavior: 'defaultHash() in stateMachine.ts is a fast 64-bit FNV-style hash for client-side visualization. Persistence layer rewrites with the canonical SHA-256 chain stored in ecign.audit_events for legal weight.',
    complianceImpact: 'Replayable audit trails satisfy 21 CFR Part 11 e-records principles and CMS surveyor evidence requirements.',
    evidence: 'Every history entry is shown in the center pane Lifecycle History timeline with its chain hash; a hash discontinuity is a P0 incident.',
    related: {
      components: ['src/policy/lifecycle/stateMachine.ts'],
    },
  },
  {
    slug: 'lifecycle-developer',
    title: 'Developer Reference — Embedding the Lifecycle',
    category: 'policy-lifecycle',
    subcategory: 'Developer',
    purpose: 'Anything that needs to read or change a policy state must go through the lifecycle module. Direct mutations are forbidden.',
    whenToUse: 'When wiring a new screen, batch job, or webhook that touches policy state.',
    steps: [
      'Read state: const env = usePolicyLifecycleStore(s => s.getEnvelope(policyId));',
      'List by state: usePolicyLifecycleStore(s => s.byState("REVIEW"));',
      'Mutate: const r = usePolicyLifecycleStore.getState().apply(policyId, "approve", actor, rationale);',
      'Inspect rejection: if (!r.ok) handle(r.code, r.message);',
      'Author attribution: import { TJ_PADILLA } from "@/policy/lifecycle"; — used when seeding new policies.',
    ],
    systemBehavior: 'apply() routes through transition() which is a pure function. The store is the only writer. Auditor mode (useAuditorModeStore) is consulted automatically.',
    complianceImpact: 'Centralizes state transitions for static analysis: a single grep for "apply(" enumerates every code path that can mutate a policy state.',
    evidence: 'src/policy/lifecycle/index.ts exports everything required. Type LifecycleTransitionResult is a discriminated union, so TypeScript forces the caller to handle rejection.',
    related: {
      components: ['src/policy/lifecycle/index.ts', 'src/policy/lifecycle/lifecycleStore.ts', 'src/policy/lifecycle/stateMachine.ts'],
    },
  },
];
