import type { HelpArticle } from './index';

export const SIGNING_DOCUMENTS: HelpArticle[] = [
  {
    slug: 'signing-step-1-disclosure',
    title: 'Step 1 — Disclosure & Consent',
    category: 'signing-documents',
    purpose: 'Capture the user\'s explicit consent to use electronic records and signatures, as required by the ESIGN Act § 7001(c) and UETA.',
    whenToUse: 'Automatically presented before any signature can be applied, and re-presented whenever the disclosure version changes.',
    steps: [
      'Read the disclosure text in full.',
      'Tick the explicit "I agree" checkbox.',
      'Click "Accept and Continue".',
    ],
    systemBehavior: 'The current disclosure version and SHA-256 of the exact text shown are returned by GET /api/ecign/disclosures/current. POST /api/ecign/consents records consent_id, user_id, disclosure_version, disclosure_text_hash, accepted_at_utc, ip, and user_agent in the append-only `consents` store. An `consent.accepted` audit event is appended.',
    complianceImpact: 'Without a current consent row the server returns 409 CONSENT_REQUIRED on any signature attempt (Guardrail G1). This is the binding ESIGN/UETA disclosure of record.',
    evidence: 'Consent row in `consents.jsonl` and `consent.accepted` event in the audit chain.',
    related: { endpoints: ['GET /api/ecign/disclosures/current', 'POST /api/ecign/consents'] },
  },
  {
    slug: 'signing-step-2-identity',
    title: 'Step 2 — Identity Verification',
    category: 'signing-documents',
    purpose: 'Bind the signature to a specific authenticated, attributable user, satisfying ESIGN attribution under 15 U.S.C. § 7006(5).',
    whenToUse: 'Always for every signing session; an additional MFA step-up is required for high-impact forms (Plan of Care `EN-FM-485`, mandatory events `EN-FM-033`).',
    steps: [
      'Sign in to CI-App (session header `X-User-Id` carries the identity).',
      'For high-impact forms, request OTP via POST /api/ecign/identity/step-up.',
      'Submit the issued `mfa_token` as `X-MFA-Token` on subsequent calls.',
    ],
    systemBehavior: 'Every API call captures IP, user-agent, and (where available) device fingerprint. High-impact endpoints reject with 403 STEP_UP_REQUIRED if no recent MFA token is present.',
    complianceImpact: 'HIPAA 164.312(d) (person/entity authentication) and ESIGN attribution.',
    evidence: '`identity.verified` audit event with method and (hashed) token reference.',
    related: { endpoints: ['POST /api/ecign/identity/step-up', 'GET /api/ecign/identity/me'] },
  },
  {
    slug: 'signing-step-3-review',
    title: 'Step 3 — Document Review',
    category: 'signing-documents',
    purpose: 'Prevent blind-signing by requiring proof that the signer viewed the entire document.',
    whenToUse: 'After identity verification and before the signature canvas becomes active.',
    steps: [
      'Scroll through every template page, OR tick "I have reviewed all pages".',
      'Click "Acknowledge Review" — POST /api/ecign/instances/:id/review-ack.',
    ],
    systemBehavior: 'Server records `review_acknowledged_at` on the form instance and appends `document.reviewed` to the audit chain. Subsequent sign attempts validate that this timestamp exists and is later than the consent timestamp.',
    complianceImpact: 'Documentation integrity per 42 CFR § 484.110; supports the "no blind signing" rule in §02 of the eCIgn spec.',
    evidence: '`document.reviewed` audit event; instance.review_acknowledged_at field.',
    related: { endpoints: ['POST /api/ecign/instances/:id/review-ack'] },
  },
  {
    slug: 'signing-step-4-signature',
    title: 'Step 4 — Apply Signature',
    category: 'signing-documents',
    purpose: 'Capture the actual signature image and bind it to the specific document version, signer, and field.',
    whenToUse: 'Once the workspace shows "Reviewed" state and the signature panel is active.',
    steps: [
      'Choose Draw, Type, or Upload mode.',
      'Apply your signature on the canvas.',
      'Click "Apply Signature" — POST /api/ecign/instances/:id/signatures.',
    ],
    systemBehavior: 'A SignatureRecord is inserted into the append-only `signatures` store. The signature PNG is hashed (SHA-256). A `signature.applied` audit event is appended carrying the signature_id, field_id, and signature_hash. The instance state advances to `attested`.',
    complianceImpact: 'Creates the legally-binding signature artifact under ESIGN/UETA; failure of any guardrail (G1 consent, G2 auth, G5 duplicate, G7 out-of-order) results in immediate 4xx response and an `access.denied` audit event.',
    evidence: 'Row in `signatures.jsonl` + `signature.applied` audit event.',
    related: { endpoints: ['POST /api/ecign/instances/:id/signatures'], components: ['FormSigningWorkspace'] },
  },
  {
    slug: 'signing-step-5-attestation',
    title: 'Step 5 — Final Attestation',
    category: 'signing-documents',
    purpose: 'Make the signer\'s intent to sign explicit and separate from the act of drawing the signature.',
    whenToUse: 'Immediately before locking the document.',
    steps: [
      'Tick: "I agree to use an electronic signature, I have reviewed this document in full, and I intend to sign it."',
      'Click "Apply Signature & Lock Document".',
    ],
    systemBehavior: 'Server requires both the attestation_text_hash on the signature payload and a separate attestation_confirmed_at timestamp on the instance.',
    complianceImpact: 'Satisfies the ESIGN "intent to sign" requirement explicitly rather than by inference.',
    evidence: '`attestation.confirmed` payload included in the signature record and audit event.',
    related: { endpoints: ['POST /api/ecign/instances/:id/signatures'] },
  },
  {
    slug: 'signing-step-6-lock',
    title: 'Step 6 — Lock & Finalize',
    category: 'signing-documents',
    purpose: 'Freeze the document, hash it, and emit the compliance state transition.',
    whenToUse: 'After the last required signer has signed and attested.',
    steps: [
      'Click "Finalize" — POST /api/ecign/instances/:id/lock.',
      'The instance transitions to `signed_locked` (terminal).',
    ],
    systemBehavior: 'Server (a) verifies all required signers are present (G3), (b) computes SHA-256 over canonical bytes (template_snapshot ‖ sorted field_values), (c) stores document_hash + manifest_hash + locked_at_utc + retention_until_utc (lock_at + 7 years), (d) appends `document.locked`, (e) calls evaluateOnLock() which emits `compliance.transitioned` for the matching compliance object.',
    complianceImpact: 'Activates downstream effects: POC → billable, policy_ack → acknowledged, QAPI → closed, HR → signed personnel file. Subsequent PATCHes are rejected with 409 DOCUMENT_LOCKED (Guardrail G4).',
    evidence: '`document.locked` and `compliance.transitioned` audit events; document_hash and manifest_hash on the instance.',
    related: {
      endpoints: ['POST /api/ecign/instances/:id/lock'],
      workflows: ['Plan of Care', 'Policy Acknowledgment', 'QAPI Minutes', 'HR Onboarding'],
    },
  },
  {
    slug: 'second-signature',
    title: 'Send for Second Signature',
    category: 'signing-documents',
    purpose: 'Route a partially-signed instance to a higher-tier approver.',
    whenToUse: 'When a workflow requires multiple signers (e.g., clinician + administrator).',
    steps: [
      'In the post-sign action banner, click "Send for Second Signature".',
      'Pick an approver from a tier strictly above your own.',
      'Confirm — POST /api/ecign/instances/:id/second-signature.',
    ],
    systemBehavior: 'A `second_signature.requested` audit event is appended carrying the task_id, assigned_to, assigned_by, and dueDate. The instance state remains at `attested` until the second signer also signs and locks.',
    complianceImpact: 'Supports CMS expectation of supervisory countersignatures; tier-strictness enforces separation of duties.',
    evidence: '`second_signature.requested` audit event; pending task surfaced in the assignee\'s dashboard.',
    related: {
      endpoints: ['POST /api/ecign/instances/:id/second-signature'],
      components: ['FormSignatureFlow.SecondSignatureModal'],
    },
  },
];
