import type { HelpArticle } from './index';

export const WORKFLOWS_EVENTS: HelpArticle[] = [
  {
    slug: 'workflow-signature-step',
    title: 'Signature Steps Inside Workflows',
    category: 'workflows-events',
    purpose: 'Workflows trigger eCIgn whenever a step is of kind `signature`.',
    whenToUse: 'Designing or executing any compliance workflow (orientation, annual review, QAPI, etc.).',
    systemBehavior: 'The workflow engine creates a form_instance via POST /api/ecign/instances with workflow_instance_id and (optional) event_id. The instance carries those references through every audit event so the chain can be replayed in workflow context.',
    complianceImpact: 'Ties the signature to the originating workflow instance, satisfying §06 (governing tuple: policy_id, workflow_instance_id, form_instance_id, user_id, event_id?).',
    evidence: 'workflow_instance_id and event_id appear on every audit event for the form instance.',
    related: { components: ['WorkflowLibraryApp'], endpoints: ['POST /api/ecign/instances'] },
  },
  {
    slug: 'qapi-event-closure',
    title: 'QAPI Event Closure',
    category: 'workflows-events',
    purpose: 'Closing a QAPI event requires signed minutes and produces an audit-ready record.',
    whenToUse: 'At the end of every QAPI quarterly meeting or ad-hoc QAPI event.',
    steps: [
      'Open the QAPI event from `/calendar` or `/audit`.',
      'Complete the EN-FM-033 form.',
      'Sign as chair; request second signature from secretary.',
      'Lock the document — compliance object qapi_minutes transitions event_open → closed.',
    ],
    systemBehavior: 'The qapi_minutes rule in compliance.ts derives object_id from event_id and emits compliance.transitioned with state_after=`closed`.',
    complianceImpact: 'Aligns with 42 CFR § 484.65 (QAPI program requirements) by producing a defensible record of the meeting.',
    evidence: 'compliance_states row for qapi_minutes; signed minutes PDF in the survey packet.',
    related: { policies: ['CO-CP-001'], workflows: ['QAPI Quarterly Meeting'] },
  },
  {
    slug: 'plan-of-care-billing-unlock',
    title: 'Plan of Care → Billing Unlock',
    category: 'workflows-events',
    purpose: 'Billing for a POC episode is gated on a physician signature.',
    whenToUse: 'Whenever a 60-day Plan of Care episode begins.',
    systemBehavior: 'POC instance form_id matches the plan_of_care rule. On lock, if all dependencies pass, state transitions to `billable`. If any dependency fails (e.g., missing review_ack), the transition records state_after = state_before, and the object remains non-billable. /api/compliance/blocked surfaces these.',
    complianceImpact: '42 CFR § 484.60(b) — services may not be billed prior to physician authentication.',
    evidence: 'compliance_states row with object_kind=`plan_of_care`, state_after=`billable`.',
    related: { policies: ['CL-CC-001'], endpoints: ['GET /api/compliance/objects/plan_of_care/poc'] },
  },
  {
    slug: 'verbal-order-late-flag',
    title: 'Verbal Order Late-Countersign Flag',
    category: 'workflows-events',
    purpose: 'Verbal orders must be countersigned within the agency\'s policy window. Late countersigns are flagged, not blocked.',
    whenToUse: 'Whenever a verbal order is taken from a physician.',
    systemBehavior: 'If signed_at_utc exceeds the configured window from the verbal order timestamp, the lock endpoint additionally appends a `risk.late_signature` audit event so the record exists for surveyor review while operations remain unblocked.',
    complianceImpact: '42 CFR § 484.110(a)(3) timeliness expectation; flagged in AuditModePage risk feed.',
    evidence: '`risk.late_signature` audit event with delta_seconds and policy_window_seconds.',
    related: { components: ['AuditModePage'] },
  },
];
