/** V6 - references the CSS vars in src/index.css. No design hex here. */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: ["var(--font-family)"],
    },
    fontWeight: {
      light: "var(--weight-body)",
      medium: "var(--weight-title)",
    },
    extend: {
      colors: {
        canvas: "var(--surface-canvas)",
        surface: {
          DEFAULT: "var(--surface-base)",
          glass: "var(--surface-glass)",
          hover: "var(--surface-hover-teal)",
        },
        brand: {
          teal: "var(--brand-teal)",
          "teal-deep": "var(--brand-teal-deep)",
          orange: "var(--brand-orange)",
        },
        "brand-teal": "var(--brand-teal)",
        "brand-teal-deep": "var(--brand-teal-deep)",
        "brand-orange": "var(--brand-orange)",
        ecign: {
          navy: "var(--ecign-navy)",
          orange: "var(--ecign-orange)",
        },
        "ecign-navy": "var(--ecign-navy)",
        "ecign-orange": "var(--ecign-orange)",
        ink: "var(--text-primary)",
        secondary: "var(--text-secondary)",
        muted: "var(--text-muted)",
        disabled: "var(--text-disabled)",
        "on-brand": "var(--text-on-brand)",
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          disabled: "var(--text-disabled)",
          "on-brand": "var(--text-on-brand)",
        },
        tone: {
          teal: {
            bg: "var(--tone-teal-bg)",
            border: "var(--tone-teal-border)",
            text: "var(--tone-teal-text)",
          },
          orange: {
            bg: "var(--tone-orange-bg)",
            border: "var(--tone-orange-border)",
            text: "var(--tone-orange-text)",
          },
          green: {
            bg: "var(--tone-green-bg)",
            border: "var(--tone-green-border)",
            text: "var(--tone-green-text)",
          },
          amber: {
            bg: "var(--tone-amber-bg)",
            border: "var(--tone-amber-border)",
            text: "var(--tone-amber-text)",
          },
          slate: {
            bg: "var(--tone-slate-bg)",
            border: "var(--tone-slate-border)",
            text: "var(--tone-slate-text)",
          },
          blue: {
            bg: "var(--tone-blue-bg)",
            border: "var(--tone-blue-border)",
            text: "var(--tone-blue-text)",
          },
          violet: {
            bg: "var(--tone-violet-bg)",
            border: "var(--tone-violet-border)",
            text: "var(--tone-violet-text)",
          },
          red: {
            bg: "var(--tone-red-bg)",
            border: "var(--tone-red-border)",
            text: "var(--tone-red-text)",
          },
        },
        chart: {
          grid: "var(--chart-grid)",
          axis: "var(--chart-axis)",
          teal: "var(--chart-teal)",
          orange: "var(--chart-orange)",
          green: "var(--chart-green)",
          amber: "var(--chart-amber)",
          blue: "var(--chart-blue)",
          violet: "var(--chart-violet)",
        },
      },
      borderColor: {
        DEFAULT: "var(--border-card)",
        card: "var(--border-card)",
        hairline: "var(--border-hairline)",
        strong: "var(--border-strong)",
      },
      spacing: {
        xs: "var(--space-xs)",
        sm: "var(--space-sm)",
        md: "var(--space-md)",
        lg: "var(--space-lg)",
        xl: "var(--space-xl)",
        "2xl": "var(--space-2xl)",
        "3xl": "var(--space-3xl)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      boxShadow: {
        rest: "var(--shadow-rest)",
        hover: "var(--shadow-hover)",
        soft: "var(--shadow-rest)",
        focus: "var(--focus-ring)",
        "shell-dock": "var(--shadow-shell-dock)",
        "dock-action": "var(--shadow-dock-action)",
        "personal-active": "var(--shadow-personal-active)",
        sidebar: "var(--shadow-sidebar)",
        "right-rail": "var(--shadow-right-rail)",
        "glass-inset": "var(--shadow-glass-inset)",
        "glass-inset-soft": "var(--shadow-glass-inset-soft)",
        "pill-action": "var(--shadow-pill-action)",
        "sticky-tabs": "var(--shadow-sticky-tabs)",
      },
      fontSize: {
        display: ["var(--text-display)", { lineHeight: "var(--leading-display)" }],
        h2: ["var(--text-h2)", { lineHeight: "var(--leading-h2)" }],
        h3: ["var(--text-h3)", { lineHeight: "var(--leading-h3)" }],
        body: ["var(--text-body)", { lineHeight: "var(--leading-body)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-sm)" }],
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-xs)" }],
        tag: ["var(--text-tag)", { lineHeight: "var(--leading-tag)", letterSpacing: "var(--tracking-tag)" }],
      },
      lineHeight: {
        display: "var(--leading-display)",
        h2: "var(--leading-h2)",
        h3: "var(--leading-h3)",
        body: "var(--leading-body)",
        sm: "var(--leading-sm)",
        xs: "var(--leading-xs)",
        tag: "var(--leading-tag)",
      },
      letterSpacing: {
        normal: "var(--tracking-normal)",
        tag: "var(--tracking-tag)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        exit: "var(--ease-exit)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        slow: "var(--motion-slow)",
        toast: "var(--duration-toast)",
      },
      scale: {
        press: "var(--press-scale)",
      },
      translate: {
        "hover-lift": "var(--hover-lift)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        shell: "var(--z-shell)",
        backdrop: "var(--z-backdrop)",
        drawer: "var(--z-drawer)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        toast: "var(--z-toast)",
        command: "var(--z-command)",
      },
      screens: {
        narrow: "360px",
        mobile: "480px",
        "tablet-p": "640px",
        "tablet-l": "768px",
        laptop: "1024px",
        desktop: "1280px",
        large: "1536px",
      },
      width: {
        sidebar: "var(--sidebar-w)",
        "sidebar-collapsed": "var(--sidebar-collapsed)",
        drawer: "var(--drawer-w)",
        "modal-sm": "var(--modal-w-sm)",
        "modal-md": "var(--modal-w-md)",
        "modal-lg": "var(--modal-w-lg)",
        "icon-xs": "var(--icon-xs)",
        "icon-sm": "var(--icon-sm)",
        "icon-md": "var(--icon-md)",
        "icon-lg": "var(--icon-lg)",
        "icon-xl": "var(--icon-xl)",
      },
      height: {
        topbar: "var(--topbar-h)",
        row: "var(--row-h)",
        "row-compact": "var(--row-h-compact)",
        control: "var(--control-h)",
        tap: "var(--tap-min)",
        "icon-xs": "var(--icon-xs)",
        "icon-sm": "var(--icon-sm)",
        "icon-md": "var(--icon-md)",
        "icon-lg": "var(--icon-lg)",
        "icon-xl": "var(--icon-xl)",
      },
      minWidth: {
        tap: "var(--tap-min)",
      },
      minHeight: {
        row: "var(--row-h)",
        "row-compact": "var(--row-h-compact)",
        tap: "var(--tap-min)",
      },
      maxWidth: {
        content: "var(--content-max)",
        drawer: "var(--drawer-w)",
        "modal-sm": "var(--modal-w-sm)",
        "modal-md": "var(--modal-w-md)",
        "modal-lg": "var(--modal-w-lg)",
      },
      size: {
        "icon-xs": "var(--icon-xs)",
        "icon-sm": "var(--icon-sm)",
        "icon-md": "var(--icon-md)",
        "icon-lg": "var(--icon-lg)",
        "icon-xl": "var(--icon-xl)",
      },
      ringColor: {
        focus: "var(--focus-ring-color)",
      },
    },
  },
  plugins: [],
}
