import type { UserGroup } from './types';

export const USER_GROUPS: UserGroup[] = [
  {
    id: 'grp-super-admin',
    name: 'Super Admin',
    description: 'Demo bootstrap admin with full Phase A permissions.',
    permissions: [
      'policy.view', 'policy.draft', 'policy.approve', 'policy.publish',
      'form.view', 'form.sign',
      'ceu.view', 'ceu.assign', 'ceu.execute', 'ceu.complete', 'ceu.override',
      'audit.read', 'audit.export',
      'phi.read', 'phi.write',
      'user.provision', 'user.suspend',
      'system.replay',
    ],
  },
  {
    id: 'grp-admin',
    name: 'Admin',
    description: 'Operations administration and access lifecycle tasks.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'ceu.assign', 'user.provision', 'user.suspend'],
  },
  {
    id: 'grp-all-users',
    name: 'All Users',
    description: 'Baseline workforce group for authenticated staff after explicit assignment.',
    permissions: [],
  },
  {
    id: 'grp-clinicians',
    name: 'Clinicians',
    description: 'Clinical workforce parent group with non-PHI policy, form, and workflow visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-clinician-rn',
    name: 'RN',
    description: 'Registered nurse workforce group with clinical workflow participation and no default PHI grant.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-clinician-lvn',
    name: 'LVN',
    description: 'Licensed vocational nurse workforce group with clinical workflow participation and no default PHI grant.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-clinician-pt',
    name: 'PT',
    description: 'Physical therapy workforce group with clinical workflow visibility and form signing.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-clinician-ot',
    name: 'OT',
    description: 'Occupational therapy workforce group with clinical workflow visibility and form signing.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-clinician-slp',
    name: 'SLP',
    description: 'Speech-language pathology workforce group with clinical workflow visibility and form signing.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-clinician-msw',
    name: 'MSW',
    description: 'Medical social worker workforce group with clinical workflow visibility and form signing.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-clinician-hha',
    name: 'HHA',
    description: 'Home health aide workforce group with clinical workflow visibility and form signing.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-office-staff',
    name: 'Office Staff',
    description: 'Office workforce parent group with non-clinical policy, form, and workflow visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-administration',
    name: 'Administration',
    description: 'Office administration workforce group with non-clinical operational visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-scheduling',
    name: 'Scheduling',
    description: 'Scheduling workforce group with non-clinical operational visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-intake',
    name: 'Intake',
    description: 'Intake workforce group with non-clinical operational visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-hr',
    name: 'HR',
    description: 'Human resources workforce group with non-clinical operational visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-compliance',
    name: 'Compliance',
    description: 'Compliance workforce group with audit visibility and no default user-administration grant.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read', 'audit.export'],
  },
  {
    id: 'grp-office-qapi',
    name: 'QAPI',
    description: 'QAPI workforce group with quality workflow and audit visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read', 'audit.export'],
  },
  {
    id: 'grp-office-billing',
    name: 'Billing',
    description: 'Billing workforce group with non-clinical operational visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-it',
    name: 'IT',
    description: 'IT workforce group with non-clinical operational visibility and no system replay grant.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-office-operations',
    name: 'Operations',
    description: 'Operations workforce group with non-clinical operational visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view'],
  },
  {
    id: 'grp-supervisors-leadership',
    name: 'Supervisors and Leadership',
    description: 'Supervisory and leadership parent group with oversight visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read'],
  },
  {
    id: 'grp-leadership-don',
    name: 'DON',
    description: 'Director of Nursing workforce group with supervisory visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read'],
  },
  {
    id: 'grp-leadership-assistant-don',
    name: 'Assistant DON',
    description: 'Assistant Director of Nursing workforce group with supervisory visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read'],
  },
  {
    id: 'grp-leadership-administrator',
    name: 'Administrator',
    description: 'Administrator workforce group with leadership visibility and no unrestricted admin grant.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read'],
  },
  {
    id: 'grp-leadership-clinical-manager',
    name: 'Clinical Manager',
    description: 'Clinical manager workforce group with supervisory visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read'],
  },
  {
    id: 'grp-leadership-compliance-officer',
    name: 'Compliance Officer',
    description: 'Compliance officer workforce group with oversight and audit visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read', 'audit.export'],
  },
  {
    id: 'grp-leadership-governing-body',
    name: 'Governing Body',
    description: 'Governing Body workforce group with leadership oversight visibility.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read'],
  },
  {
    id: 'grp-user-access-admin',
    name: 'User Access Admin',
    description: 'Scoped user-access administration group; not equivalent to Admin or Super Admin.',
    permissions: ['user.provision', 'user.suspend'],
  },
  {
    id: 'grp-rn',
    name: 'RN',
    description: 'Clinical registered nurse role.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete', 'phi.read', 'phi.write'],
  },
  {
    id: 'grp-lvn',
    name: 'LVN',
    description: 'Clinical licensed vocational nurse role.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete', 'phi.read', 'phi.write'],
  },
  {
    id: 'grp-chha',
    name: 'CHHA',
    description: 'Clinical home health aide role.',
    permissions: ['policy.view', 'form.view', 'form.sign', 'ceu.view', 'ceu.execute', 'ceu.complete', 'phi.read'],
  },
  {
    id: 'grp-compliance',
    name: 'Compliance',
    description: 'Compliance and audit operations.',
    permissions: ['policy.view', 'policy.draft', 'policy.publish', 'form.view', 'ceu.view', 'ceu.assign', 'ceu.override', 'audit.read', 'audit.export', 'user.suspend'],
  },
  {
    id: 'grp-auditor',
    name: 'Auditor',
    description: 'Read-only evidence and audit review.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'audit.read', 'audit.export'],
  },
  {
    id: 'grp-onboarding',
    name: 'Onboarding',
    description: 'Restricted onboarding/UAT role with Taxonomy and Workflows visibility only.',
    permissions: ['user.provision'],
  },
  {
    id: 'grp-billing',
    name: 'Billing',
    description: 'Billing workflow participant role.',
    permissions: ['policy.view', 'form.view', 'ceu.view', 'ceu.execute', 'ceu.complete'],
  },
  {
    id: 'grp-director',
    name: 'Director',
    description: 'Director-level approvals and escalations.',
    permissions: ['policy.view', 'policy.approve', 'form.view', 'ceu.view', 'ceu.assign', 'ceu.override'],
  },
  {
    id: 'grp-executive',
    name: 'Executive',
    description: 'Executive approval and publish authority.',
    permissions: ['policy.view', 'policy.approve', 'policy.publish', 'form.view', 'ceu.view', 'ceu.override', 'audit.read'],
  },
  {
    id: 'grp-system',
    name: 'System',
    description: 'System-level deterministic replay permissions.',
    permissions: ['system.replay'],
  },
  {
    id: 'grp-pending-user',
    name: 'Pending User',
    description: 'Authenticated user awaiting explicit role, group, and page-access assignment.',
    permissions: [],
  },
];

export const USER_GROUP_BY_ID = Object.fromEntries(
  USER_GROUPS.map(group => [group.id, group]),
);
