/* Auto-generated by scripts/generateAchcCrosswalks.ts */
/* Source: ACHC attachment page 756 + print crosswalk validation */

export interface AchcAttachmentCrosswalkRow {
  achcStandard: string;
  requiredItem: string;
  ibmPolicyIds: string[];
  ibmPolicyTitles: string[];
  evidenceCodes: Array<"P" | "D" | "I" | "O" | "S">;
  relatedForms: string[];
  relatedWorkflows: string[];
  gapStatus: "MAPPED" | "COVERED_BY_NON_POLICY_ARTIFACT" | "GAP" | "NOT_APPLICABLE" | "NEEDS_REVIEW";
  notes: string;
  sourcePage: number;
}

export const achcAttachmentCrosswalk: AchcAttachmentCrosswalkRow[] = [
  {
    "achcStandard": "HH1-10A",
    "requiredItem": "Contracts for direct care including professional liability insurance certificates.",
    "ibmPolicyIds": [
      "GV-EA-001",
      "GV-EA-002"
    ],
    "ibmPolicyTitles": [
      "Interagency Agreements & Contracts",
      "Community Liaison & Public Relations"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-12 — STAKEHOLDER / EXTERNAL COMMUNICATION & MEDIA REQUESTS",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 2 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-11A",
    "requiredItem": "CLIA certificate of waiver for agency or CLIA certificate for reference laboratory.",
    "ibmPolicyIds": [
      "CO-RA-001",
      "RM-SS-001"
    ],
    "ibmPolicyTitles": [
      "Regulatory Change Monitoring & Implementation",
      "Staff Safety & Personal Security"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION"
    ],
    "gapStatus": "MAPPED",
    "notes": "CLIA readiness anchored to regulatory and waived-testing controls. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-12A.01",
    "requiredItem": "CMS letter of approval for branch addition (if applicable).",
    "ibmPolicyIds": [
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001",
      "GV-EA-001"
    ],
    "ibmPolicyTitles": [
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation",
      "Interagency Agreements & Contracts"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 4 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-1A",
    "requiredItem": "Copy of current applicable licenses or permits and copy of articles of incorporation/bylaws.",
    "ibmPolicyIds": [
      "GV-GB-001",
      "GV-GB-003",
      "GV-OG-001",
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001",
      "GV-EA-001"
    ],
    "ibmPolicyTitles": [
      "Governing Body Authority & Responsibilities",
      "Conflict of Interest Disclosure",
      "Organizational Structure & Reporting",
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation",
      "Interagency Agreements & Contracts"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "GV-F-001 — Governing Body Agenda",
      "GV-F-002 — Governing Body Minutes"
    ],
    "relatedWorkflows": [
      "CL-WF-01 — INTAKE & REFERRAL QUALIFICATION",
      "CO-WF-01 — ANNUAL COMPLIANCE PROGRAM ATTESTATION",
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "CO-WF-22 — COMPLIANCE METRICS & QUARTERLY REPORT TO GOVERNING BODY",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "EN-WF-10 — ENTERPRISE KPI / METRICS REPORTING",
      "EN-WF-13 — ANNUAL COMPLIANCE ATTESTATION & MANAGEMENT CERTIFICATION",
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-02 — ANNUAL GOVERNING BODY SELF-ASSESSMENT",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-05 — ANNUAL INSTITUTIONAL PLAN & BUDGET APPROVAL",
      "GV-WF-06 — ANNUAL ACCEPTANCE-TO-SERVICE POLICY REVIEW",
      "GV-WF-07 — ANNUAL PUBLIC SERVICE INFORMATION REVIEW",
      "GV-WF-08 — CONFLICT OF INTEREST DISCLOSURE (ONBOARDING & ANNUAL)",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-12 — STAKEHOLDER / EXTERNAL COMMUNICATION & MEDIA REQUESTS",
      "GV-WF-13 — GOVERNING BODY TRAINING & ORIENTATION",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-08 — NON-ADMIT / REFERRAL REJECTION MANAGEMENT",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "RM-WF-01 — ENTERPRISE RISK REGISTER & QUARTERLY RISK REVIEW",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 7 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-1A.01",
    "requiredItem": "Access to policies and procedures manual with required policies flagged.",
    "ibmPolicyIds": [
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001",
      "EN-CM-001",
      "EN-LC-001",
      "GV-PM-001",
      "GV-EA-001",
      "QA-PG-001",
      "QA-PI-001",
      "QA-AE-001",
      "RM-OS-002",
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation",
      "Enterprise Compliance Metrics Program",
      "Policy Lifecycle Control & Version Management",
      "Policy Development & Approval Process",
      "Interagency Agreements & Contracts",
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management",
      "Adverse Event Identification & Reporting",
      "Airborne Transmissible Disease (ATD) Exposure Control Plan",
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "EN-WF-01 — POLICY LIFECYCLE",
      "EN-WF-04 — MASTER POLICY INDEX / TAXONOMY REGISTER",
      "EN-WF-05 — REGULATORY CHANGE MANAGEMENT",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "QA-WF-13 — KPI DATA AGGREGATION",
      "QA-WF-14 — PERFORMANCE INDICATOR TRACKING",
      "QA-WF-15 — TREND ANALYSIS",
      "QA-WF-16 — QAPI DATA VALIDATION",
      "QA-WF-18 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-05 — ADVERSE EVENT REPORTING, RCA & CORRECTIVE ACTION",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)",
      "QA-WF-07 — LUPA PREVENTION & VISIT UTILIZATION MONITORING",
      "QA-WF-10 — QAPI SELF-ASSESSMENT (ANNUAL)",
      "QA-WF-11 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-12 — PATIENT SAFETY EVENT COMMUNICATION",
      "RM-WF-16 — INCIDENT TREND ANALYSIS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-20 — INCIDENT RESPONSE COMPLIANCE AUDIT",
      "RM-WF-10 — WORKPLACE INJURY & OSHA RECORDKEEPING",
      "RM-WF-13 — HIGH-RISK MEDICATION DOUBLE-CHECK",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 15 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-1B",
    "requiredItem": "Current 855A/CMS approval letter.",
    "ibmPolicyIds": [
      "GV-GB-001",
      "GV-GB-003",
      "GV-OG-001"
    ],
    "ibmPolicyTitles": [
      "Governing Body Authority & Responsibilities",
      "Conflict of Interest Disclosure",
      "Organizational Structure & Reporting"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "GV-F-001 — Governing Body Agenda",
      "GV-F-002 — Governing Body Minutes"
    ],
    "relatedWorkflows": [
      "CL-WF-01 — INTAKE & REFERRAL QUALIFICATION",
      "CO-WF-01 — ANNUAL COMPLIANCE PROGRAM ATTESTATION",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "CO-WF-22 — COMPLIANCE METRICS & QUARTERLY REPORT TO GOVERNING BODY",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "EN-WF-10 — ENTERPRISE KPI / METRICS REPORTING",
      "EN-WF-13 — ANNUAL COMPLIANCE ATTESTATION & MANAGEMENT CERTIFICATION",
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-02 — ANNUAL GOVERNING BODY SELF-ASSESSMENT",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-05 — ANNUAL INSTITUTIONAL PLAN & BUDGET APPROVAL",
      "GV-WF-06 — ANNUAL ACCEPTANCE-TO-SERVICE POLICY REVIEW",
      "GV-WF-07 — ANNUAL PUBLIC SERVICE INFORMATION REVIEW",
      "GV-WF-08 — CONFLICT OF INTEREST DISCLOSURE (ONBOARDING & ANNUAL)",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-12 — STAKEHOLDER / EXTERNAL COMMUNICATION & MEDIA REQUESTS",
      "GV-WF-13 — GOVERNING BODY TRAINING & ORIENTATION",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-08 — NON-ADMIT / REFERRAL REJECTION MANAGEMENT",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "RM-WF-01 — ENTERPRISE RISK REGISTER & QUARTERLY RISK REVIEW",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-1C",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001"
    ],
    "ibmPolicyTitles": [
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-2A",
    "requiredItem": "Governing body meeting minutes for past 12 months and related governance documentation.",
    "ibmPolicyIds": [
      "GV-GB-001"
    ],
    "ibmPolicyTitles": [
      "Governing Body Authority & Responsibilities"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "GV-F-001 — Governing Body Agenda",
      "GV-F-002 — Governing Body Minutes"
    ],
    "relatedWorkflows": [
      "CL-WF-01 — INTAKE & REFERRAL QUALIFICATION",
      "CO-WF-01 — ANNUAL COMPLIANCE PROGRAM ATTESTATION",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "CO-WF-22 — COMPLIANCE METRICS & QUARTERLY REPORT TO GOVERNING BODY",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "EN-WF-10 — ENTERPRISE KPI / METRICS REPORTING",
      "EN-WF-13 — ANNUAL COMPLIANCE ATTESTATION & MANAGEMENT CERTIFICATION",
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-02 — ANNUAL GOVERNING BODY SELF-ASSESSMENT",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-05 — ANNUAL INSTITUTIONAL PLAN & BUDGET APPROVAL",
      "GV-WF-06 — ANNUAL ACCEPTANCE-TO-SERVICE POLICY REVIEW",
      "GV-WF-07 — ANNUAL PUBLIC SERVICE INFORMATION REVIEW",
      "GV-WF-08 — CONFLICT OF INTEREST DISCLOSURE (ONBOARDING & ANNUAL)",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-12 — STAKEHOLDER / EXTERNAL COMMUNICATION & MEDIA REQUESTS",
      "GV-WF-13 — GOVERNING BODY TRAINING & ORIENTATION",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-08 — NON-ADMIT / REFERRAL REJECTION MANAGEMENT",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "RM-WF-01 — ENTERPRISE RISK REGISTER & QUARTERLY RISK REVIEW",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-2A.03",
    "requiredItem": "Governing body meeting minutes for past 12 months and related governance documentation.",
    "ibmPolicyIds": [
      "GV-GB-001"
    ],
    "ibmPolicyTitles": [
      "Governing Body Authority & Responsibilities"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "GV-F-001 — Governing Body Agenda",
      "GV-F-002 — Governing Body Minutes"
    ],
    "relatedWorkflows": [
      "CL-WF-01 — INTAKE & REFERRAL QUALIFICATION",
      "CO-WF-01 — ANNUAL COMPLIANCE PROGRAM ATTESTATION",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "CO-WF-22 — COMPLIANCE METRICS & QUARTERLY REPORT TO GOVERNING BODY",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "EN-WF-10 — ENTERPRISE KPI / METRICS REPORTING",
      "EN-WF-13 — ANNUAL COMPLIANCE ATTESTATION & MANAGEMENT CERTIFICATION",
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-02 — ANNUAL GOVERNING BODY SELF-ASSESSMENT",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-05 — ANNUAL INSTITUTIONAL PLAN & BUDGET APPROVAL",
      "GV-WF-06 — ANNUAL ACCEPTANCE-TO-SERVICE POLICY REVIEW",
      "GV-WF-07 — ANNUAL PUBLIC SERVICE INFORMATION REVIEW",
      "GV-WF-08 — CONFLICT OF INTEREST DISCLOSURE (ONBOARDING & ANNUAL)",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-12 — STAKEHOLDER / EXTERNAL COMMUNICATION & MEDIA REQUESTS",
      "GV-WF-13 — GOVERNING BODY TRAINING & ORIENTATION",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-08 — NON-ADMIT / REFERRAL REJECTION MANAGEMENT",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "RM-WF-01 — ENTERPRISE RISK REGISTER & QUARTERLY RISK REVIEW",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-4A.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-GB-002",
      "GV-GB-003",
      "GV-OG-001"
    ],
    "ibmPolicyTitles": [
      "Board Meeting & Minutes Requirements",
      "Conflict of Interest Disclosure",
      "Organizational Structure & Reporting"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "CO-F-004 — Quarterly Compliance Report"
    ],
    "relatedWorkflows": [
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-5A",
    "requiredItem": "Job description for the Administrator.",
    "ibmPolicyIds": [
      "GV-GB-003",
      "GV-OG-001",
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001",
      "GV-EA-001"
    ],
    "ibmPolicyTitles": [
      "Conflict of Interest Disclosure",
      "Organizational Structure & Reporting",
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation",
      "Interagency Agreements & Contracts"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 6 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-5A.01",
    "requiredItem": "Annual evaluation of the Administrator.",
    "ibmPolicyIds": [
      "GV-GB-001",
      "GV-GB-003",
      "GV-OG-001",
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001"
    ],
    "ibmPolicyTitles": [
      "Governing Body Authority & Responsibilities",
      "Conflict of Interest Disclosure",
      "Organizational Structure & Reporting",
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "GV-F-001 — Governing Body Agenda",
      "GV-F-002 — Governing Body Minutes"
    ],
    "relatedWorkflows": [
      "CL-WF-01 — INTAKE & REFERRAL QUALIFICATION",
      "CO-WF-01 — ANNUAL COMPLIANCE PROGRAM ATTESTATION",
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "CO-WF-22 — COMPLIANCE METRICS & QUARTERLY REPORT TO GOVERNING BODY",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "EN-WF-10 — ENTERPRISE KPI / METRICS REPORTING",
      "EN-WF-13 — ANNUAL COMPLIANCE ATTESTATION & MANAGEMENT CERTIFICATION",
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT",
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-02 — ANNUAL GOVERNING BODY SELF-ASSESSMENT",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-05 — ANNUAL INSTITUTIONAL PLAN & BUDGET APPROVAL",
      "GV-WF-06 — ANNUAL ACCEPTANCE-TO-SERVICE POLICY REVIEW",
      "GV-WF-07 — ANNUAL PUBLIC SERVICE INFORMATION REVIEW",
      "GV-WF-08 — CONFLICT OF INTEREST DISCLOSURE (ONBOARDING & ANNUAL)",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-12 — STAKEHOLDER / EXTERNAL COMMUNICATION & MEDIA REQUESTS",
      "GV-WF-13 — GOVERNING BODY TRAINING & ORIENTATION",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-08 — NON-ADMIT / REFERRAL REJECTION MANAGEMENT",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "RM-WF-01 — ENTERPRISE RISK REGISTER & QUARTERLY RISK REVIEW",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 6 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-6A",
    "requiredItem": "Organizational chart.",
    "ibmPolicyIds": [
      "GV-OG-004"
    ],
    "ibmPolicyTitles": [
      "Strategic Planning & Annual Goals"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-6B",
    "requiredItem": "Job description for the clinical manager(s).",
    "ibmPolicyIds": [
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001",
      "GV-OG-004"
    ],
    "ibmPolicyTitles": [
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation",
      "Strategic Planning & Annual Goals"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 4 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-6C",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-EA-001"
    ],
    "ibmPolicyTitles": [
      "Interagency Agreements & Contracts"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-7A",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-8A",
    "requiredItem": "Previous four months final OASIS Validation reports.",
    "ibmPolicyIds": [
      "CL-OA-001"
    ],
    "ibmPolicyTitles": [
      "OASIS Completion Timeliness & Accountability"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-8B",
    "requiredItem": "Previous four months final OASIS Validation reports.",
    "ibmPolicyIds": [
      "CL-OA-001"
    ],
    "ibmPolicyTitles": [
      "OASIS Completion Timeliness & Accountability"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH1-9A.01",
    "requiredItem": "Governing body and confidentiality documentation supporting governance oversight.",
    "ibmPolicyIds": [
      "GV-OG-002",
      "GV-OG-003",
      "CO-RA-001"
    ],
    "ibmPolicyTitles": [
      "Administrator Qualifications & Responsibilities",
      "Scope of Services Definition",
      "Regulatory Change Monitoring & Implementation"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION",
      "EN-WF-09 — ENTERPRISE MANDATORY EVENTS CALENDAR",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-09 — AGENCY LICENSURE & CERTIFICATION RENEWAL MANAGEMENT",
      "GV-WF-10 — CHANGE OF OWNERSHIP / AGENCY CLOSURE",
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-10A.01",
    "requiredItem": "On-call calendar.",
    "ibmPolicyIds": [
      "OP-PA-001"
    ],
    "ibmPolicyTitles": [
      "Patient Complaint & Grievance Resolution"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [
      "OP-F-010 — On-Call Coverage Calendar"
    ],
    "relatedWorkflows": [
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-11A.01",
    "requiredItem": "On-call calendar.",
    "ibmPolicyIds": [
      "OP-PA-001"
    ],
    "ibmPolicyTitles": [
      "Patient Complaint & Grievance Resolution"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [
      "OP-F-010 — On-Call Coverage Calendar"
    ],
    "relatedWorkflows": [
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-12A.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-1A.01",
    "requiredItem": "Marketing materials.",
    "ibmPolicyIds": [
      "GV-GB-003",
      "GV-OG-001",
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Conflict of Interest Disclosure",
      "Organizational Structure & Reporting",
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "GV-WF-03 — ADMINISTRATOR APPOINTMENT / REPLACEMENT / DELEGATION",
      "GV-WF-04 — CLINICAL MANAGER APPOINTMENT / REPLACEMENT",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-2A",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "EN-CM-001",
      "EN-LC-001",
      "GV-PM-001",
      "FN-BC-001",
      "FN-BC-003",
      "FN-BC-004"
    ],
    "ibmPolicyTitles": [
      "Enterprise Compliance Metrics Program",
      "Policy Lifecycle Control & Version Management",
      "Policy Development & Approval Process",
      "Medicare Billing & Claims Submission",
      "Patient Billing & Financial Responsibility",
      "Overpayment Identification & Refund"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "FN-F-002 — Billing Hold Register",
      "FN-F-001 — Pre-Billing Verification Checklist",
      "FN-F-003 — Claims Batch Log",
      "FN-F-004 — Aged Unsigned POC Report"
    ],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "EN-WF-01 — POLICY LIFECYCLE",
      "EN-WF-04 — MASTER POLICY INDEX / TAXONOMY REGISTER",
      "EN-WF-05 — REGULATORY CHANGE MANAGEMENT",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "QA-WF-13 — KPI DATA AGGREGATION",
      "QA-WF-18 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-07 — LUPA PREVENTION & VISIT UTILIZATION MONITORING",
      "QA-WF-11 — POLICY EFFECTIVENESS MONITORING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 6 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-4A",
    "requiredItem": "Grievance/complaint log.",
    "ibmPolicyIds": [
      "OP-IM-002",
      "CL-PR-003"
    ],
    "ibmPolicyTitles": [
      "Patient Acceptance & Admission Criteria",
      "Informed Consent"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "CL-F-010 — Grievance and Complaint Log"
    ],
    "relatedWorkflows": [
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 2 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-5A",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "EN-CM-001",
      "EN-LC-001",
      "GV-PM-001"
    ],
    "ibmPolicyTitles": [
      "Enterprise Compliance Metrics Program",
      "Policy Lifecycle Control & Version Management",
      "Policy Development & Approval Process"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "EN-WF-01 — POLICY LIFECYCLE",
      "EN-WF-04 — MASTER POLICY INDEX / TAXONOMY REGISTER",
      "EN-WF-05 — REGULATORY CHANGE MANAGEMENT",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT",
      "QA-WF-13 — KPI DATA AGGREGATION",
      "QA-WF-18 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-11 — POLICY EFFECTIVENESS MONITORING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-5C.01",
    "requiredItem": "Business Associate Agreements (BAAs).",
    "ibmPolicyIds": [
      "CO-HP-001",
      "CO-HP-004",
      "IT-SC-001"
    ],
    "ibmPolicyTitles": [
      "HIPAA Privacy Program",
      "Minimum Necessary Standard",
      "Information Security Program"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "CO-F-010 — Business Associate Agreement (BAA) Register"
    ],
    "relatedWorkflows": [
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-7A.01",
    "requiredItem": "Evidence of how ethical issues are identified, evaluated, and discussed.",
    "ibmPolicyIds": [
      "CL-PR-003",
      "OP-IM-002"
    ],
    "ibmPolicyTitles": [
      "Informed Consent",
      "Patient Acceptance & Admission Criteria"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "CL-F-010 — Grievance and Complaint Log"
    ],
    "relatedWorkflows": [
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 2 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-8A",
    "requiredItem": "Evidence of communication assistance for language barriers.",
    "ibmPolicyIds": [
      "CL-PR-001",
      "OP-IM-002"
    ],
    "ibmPolicyTitles": [
      "Patient Rights & Responsibilities",
      "Patient Acceptance & Admission Criteria"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "CL-F-010 — Grievance and Complaint Log"
    ],
    "relatedWorkflows": [
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 2 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH2-9A.01",
    "requiredItem": "Evidence of a Compliance Program.",
    "ibmPolicyIds": [
      "CO-CP-001",
      "CO-CP-002"
    ],
    "ibmPolicyTitles": [
      "Corporate Compliance Program",
      "Compliance Officer Designation & Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "CO-F-004 — Quarterly Compliance Report"
    ],
    "relatedWorkflows": [
      "CO-WF-01 — ANNUAL COMPLIANCE PROGRAM ATTESTATION",
      "CO-WF-06 — REGULATORY CHANGE MANAGEMENT",
      "CO-WF-19 — MEDICARE CoP COMPLIANCE VERIFICATION"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 2 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH3-1A",
    "requiredItem": "Most recent annual operating budget.",
    "ibmPolicyIds": [
      "FN-BC-001"
    ],
    "ibmPolicyTitles": [
      "Medicare Billing & Claims Submission"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "FN-F-001 — Pre-Billing Verification Checklist",
      "FN-F-002 — Billing Hold Register",
      "FN-F-003 — Claims Batch Log"
    ],
    "relatedWorkflows": [
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH3-1B",
    "requiredItem": "Most recent capital expenditure plan (if applicable).",
    "ibmPolicyIds": [
      "FN-BC-001"
    ],
    "ibmPolicyTitles": [
      "Medicare Billing & Claims Submission"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "FN-F-001 — Pre-Billing Verification Checklist",
      "FN-F-002 — Billing Hold Register",
      "FN-F-003 — Claims Batch Log"
    ],
    "relatedWorkflows": [
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH3-1C",
    "requiredItem": "Evidence of the review of the budget.",
    "ibmPolicyIds": [
      "FN-BC-001"
    ],
    "ibmPolicyTitles": [
      "Medicare Billing & Claims Submission"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "FN-F-001 — Pre-Billing Verification Checklist",
      "FN-F-002 — Billing Hold Register",
      "FN-F-003 — Claims Batch Log"
    ],
    "relatedWorkflows": [
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH3-3B.02",
    "requiredItem": "Recent Medicare cost report (N/A for initial Medicare certification).",
    "ibmPolicyIds": [
      "FN-BC-001"
    ],
    "ibmPolicyTitles": [
      "Medicare Billing & Claims Submission"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "FN-F-001 — Pre-Billing Verification Checklist",
      "FN-F-002 — Billing Hold Register",
      "FN-F-003 — Claims Batch Log"
    ],
    "relatedWorkflows": [
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH3-4A.01",
    "requiredItem": "Listing of patient care charges.",
    "ibmPolicyIds": [
      "FN-BC-001"
    ],
    "ibmPolicyTitles": [
      "Medicare Billing & Claims Submission"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "FN-F-001 — Pre-Billing Verification Checklist",
      "FN-F-002 — Billing Hold Register",
      "FN-F-003 — Claims Batch Log"
    ],
    "relatedWorkflows": [
      "FN-WF-01 — ANNUAL OPERATING BUDGET & INSTITUTIONAL PLAN",
      "FN-WF-02 — MONTHLY FINANCIAL CLOSE & VARIANCE REPORTING",
      "FN-WF-13 — EXTERNAL FINANCIAL AUDIT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-12A",
    "requiredItem": "Home Health Aide competency evaluation and/or training materials.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-12B",
    "requiredItem": "Home Health Aide competency evaluation and/or training materials.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-12C",
    "requiredItem": "Home Health Aide competency evaluation and/or training materials.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-12F",
    "requiredItem": "Home Health Aide competency evaluation and/or training materials.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-1B.01",
    "requiredItem": "Personnel records for required disciplines with required evidence items.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-2E.01",
    "requiredItem": "Job descriptions for identified staff.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-2I.01",
    "requiredItem": "Employee handbook or access to personnel policies.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-8A",
    "requiredItem": "Evidence of ongoing education and/or written education plan.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH4-8A.01",
    "requiredItem": "Evidence of ongoing education and/or written education plan.",
    "ibmPolicyIds": [
      "HR-TA-001",
      "HR-TD-001",
      "HR-ER-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards",
      "Annual Mandatory Training Requirements",
      "Performance Evaluation & Review"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 3 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-11A",
    "requiredItem": "Evidence skilled services are provided by or under supervision of qualified professionals.",
    "ibmPolicyIds": [
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-11F",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-12A.01",
    "requiredItem": "Patient education materials.",
    "ibmPolicyIds": [
      "CL-PR-001"
    ],
    "ibmPolicyTitles": [
      "Patient Rights & Responsibilities"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-13A.01",
    "requiredItem": "Referral log.",
    "ibmPolicyIds": [
      "OP-IM-001"
    ],
    "ibmPolicyTitles": [
      "Referral & Intake Management"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-16A.01",
    "requiredItem": "Verification of physician or allowed practitioner licensure.",
    "ibmPolicyIds": [
      "HR-TA-001"
    ],
    "ibmPolicyTitles": [
      "Recruitment & Hiring Standards"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "HR-WF-04 — PRIMARY SOURCE VERIFICATION & LICENSE TRACKING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-2C.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH5-2C.02",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-OG-005"
    ],
    "ibmPolicyTitles": [
      "Delegation of Authority"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-1A",
    "requiredItem": "Quality Assessment and Performance Improvement (QAPI) Program.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-1B.01",
    "requiredItem": "Job description for person responsible for QAPI Program.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-1C",
    "requiredItem": "Governing body minutes showing involvement in QAPI.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-1D.01",
    "requiredItem": "Evidence of personnel involvement in QAPI.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-3A.01",
    "requiredItem": "QAPI annual report.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-4A.02",
    "requiredItem": "Evidence of monitoring risk processes including infections and communicable diseases.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-4A.04",
    "requiredItem": "Evidence of monitoring administrative function aspect of agency.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-4A.05",
    "requiredItem": "Satisfaction surveys utilized in QAPI.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-4A.06",
    "requiredItem": "Evidence of grievance/complaint monitoring and corrective actions.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-4A.07",
    "requiredItem": "Evidence of quarterly record reviews used in QAPI.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-5A",
    "requiredItem": "Evidence QAPI focuses on high-risk, high-volume, or problem-prone areas.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-6A",
    "requiredItem": "Evidence of monitoring all patient-related variances.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH6-7A.01",
    "requiredItem": "Recent OASIS reports and evidence of ongoing monitoring.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "QA-F-020 — Quarterly QAPI Report"
    ],
    "relatedWorkflows": [
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)"
    ],
    "gapStatus": "MAPPED",
    "notes": "QAPI standards mapped through QAPI governance and meeting evidence chain. (Mapped to 2 IBM policy ID(s).)",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-10A.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "GV-EA-001"
    ],
    "ibmPolicyTitles": [
      "Interagency Agreements & Contracts"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [],
    "relatedWorkflows": [
      "GV-WF-11 — INTERAGENCY / THIRD-PARTY CONTRACT REVIEW",
      "GV-WF-14 — EXECUTIVE SESSION MANAGEMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-1A",
    "requiredItem": "Evidence of infection control program and related annual plans.",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001",
      "QA-AE-001",
      "RM-OS-002",
      "RM-ER-001",
      "RM-ER-002",
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management",
      "Adverse Event Identification & Reporting",
      "Airborne Transmissible Disease (ATD) Exposure Control Plan",
      "Enterprise Risk Management Program",
      "Incident Reporting & Investigation",
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "QA-WF-13 — KPI DATA AGGREGATION",
      "QA-WF-14 — PERFORMANCE INDICATOR TRACKING",
      "QA-WF-15 — TREND ANALYSIS",
      "QA-WF-16 — QAPI DATA VALIDATION",
      "QA-WF-18 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-05 — ADVERSE EVENT REPORTING, RCA & CORRECTIVE ACTION",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)",
      "QA-WF-07 — LUPA PREVENTION & VISIT UTILIZATION MONITORING",
      "QA-WF-10 — QAPI SELF-ASSESSMENT (ANNUAL)",
      "QA-WF-11 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-12 — PATIENT SAFETY EVENT COMMUNICATION",
      "RM-WF-16 — INCIDENT TREND ANALYSIS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-20 — INCIDENT RESPONSE COMPLIANCE AUDIT",
      "RM-WF-10 — WORKPLACE INJURY & OSHA RECORDKEEPING",
      "RM-WF-13 — HIGH-RISK MEDICATION DOUBLE-CHECK",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 10 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-1D",
    "requiredItem": "Infection control logs for patients/personnel and QAPI monitoring evidence.",
    "ibmPolicyIds": [
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 4 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-1D.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "RM-ER-005"
    ],
    "ibmPolicyTitles": [
      "Risk Trending & Pattern Analysis"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-2A.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "RM-ER-002",
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001",
      "RM-OS-004"
    ],
    "ibmPolicyTitles": [
      "Incident Reporting & Investigation",
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)",
      "Heat Illness Prevention Program"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 6 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-2B.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "RM-ER-002",
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001",
      "RM-OS-004"
    ],
    "ibmPolicyTitles": [
      "Incident Reporting & Investigation",
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)",
      "Heat Illness Prevention Program"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 6 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-3A",
    "requiredItem": "Emergency Preparedness Plan including all-hazards risk assessment.",
    "ibmPolicyIds": [
      "RM-EP-001"
    ],
    "ibmPolicyTitles": [
      "Emergency Preparedness Program — Governing Policy"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "OP-F-001 — Emergency Preparedness Exercise Record"
    ],
    "relatedWorkflows": [
      "RM-WF-03 — BIENNIAL EMERGENCY PREPAREDNESS PROGRAM REVIEW/UPDATE",
      "RM-WF-04 — BIENNIAL EMERGENCY PREPAREDNESS STAFF TRAINING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-3B",
    "requiredItem": "Emergency Preparedness Plan/Policies.",
    "ibmPolicyIds": [
      "RM-EP-001"
    ],
    "ibmPolicyTitles": [
      "Emergency Preparedness Program — Governing Policy"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "OP-F-001 — Emergency Preparedness Exercise Record"
    ],
    "relatedWorkflows": [
      "RM-WF-03 — BIENNIAL EMERGENCY PREPAREDNESS PROGRAM REVIEW/UPDATE",
      "RM-WF-04 — BIENNIAL EMERGENCY PREPAREDNESS STAFF TRAINING"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-3C",
    "requiredItem": "Communication Plan.",
    "ibmPolicyIds": [
      "RM-EP-001"
    ],
    "ibmPolicyTitles": [
      "Emergency Preparedness Program — Governing Policy"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "OP-F-001 — Emergency Preparedness Exercise Record"
    ],
    "relatedWorkflows": [
      "RM-WF-05 — ANNUAL EMERGENCY EXERCISE"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-3D",
    "requiredItem": "Evidence of annual emergency preparedness training and drills.",
    "ibmPolicyIds": [
      "RM-EP-001"
    ],
    "ibmPolicyTitles": [
      "Emergency Preparedness Program — Governing Policy"
    ],
    "evidenceCodes": [
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "OP-F-001 — Emergency Preparedness Exercise Record"
    ],
    "relatedWorkflows": [
      "RM-WF-06 — PANDEMIC / INFECTIOUS-DISEASE SURGE READINESS"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-3E",
    "requiredItem": "Integrated healthcare system emergency plan evidence (if applicable).",
    "ibmPolicyIds": [
      "RM-EP-001"
    ],
    "ibmPolicyTitles": [
      "Emergency Preparedness Program — Governing Policy"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "relatedForms": [
      "OP-F-001 — Emergency Preparedness Exercise Record"
    ],
    "relatedWorkflows": [
      "RM-WF-03 — BIENNIAL EMERGENCY PREPAREDNESS PROGRAM REVIEW/UPDATE"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-5A.01",
    "requiredItem": "Annual fire drill report and emergency power system testing results.",
    "ibmPolicyIds": [
      "RM-OS-001",
      "RM-OS-004"
    ],
    "ibmPolicyTitles": [
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)",
      "Heat Illness Prevention Program"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 2 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-6A.01",
    "requiredItem": "Required item not explicitly parsed; see source attachment.",
    "ibmPolicyIds": [
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 4 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-6B.01",
    "requiredItem": "Access to Safety Data Sheets (SDS).",
    "ibmPolicyIds": [
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 4 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-7A.01",
    "requiredItem": "OSHA forms 300, 300A, and/or 301 (if applicable).",
    "ibmPolicyIds": [
      "QA-PG-001",
      "QA-PI-001",
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "QAPI Program Establishment & Governance",
      "Performance Improvement Project Management",
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "relatedForms": [
      "QA-F-010 — QAPI Meeting Agenda",
      "QA-F-011 — QAPI Attendance Log",
      "QA-F-012 — QAPI Minutes Template",
      "QA-F-013 — QAPI Action Item Tracker",
      "QA-F-014 — QAPI Data Dashboard",
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "GV-WF-01 — GOVERNING BODY QUARTERLY MEETING & MINUTES",
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "QA-WF-13 — KPI DATA AGGREGATION",
      "QA-WF-14 — PERFORMANCE INDICATOR TRACKING",
      "QA-WF-15 — TREND ANALYSIS",
      "QA-WF-16 — QAPI DATA VALIDATION",
      "QA-WF-18 — POLICY EFFECTIVENESS MONITORING",
      "QA-WF-01 — QAPI PROGRAM CHARTER & ANNUAL REVIEW",
      "QA-WF-02 — MONTHLY QUALITY INDICATOR DASHBOARD PRODUCTION",
      "QA-WF-03 — QUARTERLY QAPI COMMITTEE REVIEW",
      "QA-WF-04 — ANNUAL PERFORMANCE IMPROVEMENT PROJECT (PIP) LIFECYCLE",
      "QA-WF-06 — INFECTION CONTROL SURVEILLANCE (QAPI-INTEGRATED)",
      "QA-WF-07 — LUPA PREVENTION & VISIT UTILIZATION MONITORING",
      "QA-WF-10 — QAPI SELF-ASSESSMENT (ANNUAL)",
      "QA-WF-11 — POLICY EFFECTIVENESS MONITORING",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 6 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-8A.01",
    "requiredItem": "Quality control logs for equipment used in provision of care.",
    "ibmPolicyIds": [
      "RM-OS-004"
    ],
    "ibmPolicyTitles": [
      "Heat Illness Prevention Program"
    ],
    "evidenceCodes": [
      "D",
      "I",
      "O"
    ],
    "relatedForms": [],
    "relatedWorkflows": [],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 1 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  },
  {
    "achcStandard": "HH7-9A.01",
    "requiredItem": "Quality control logs for equipment used in provision of care.",
    "ibmPolicyIds": [
      "RM-ER-005",
      "RM-ER-006",
      "OP-FM-001",
      "RM-OS-001"
    ],
    "ibmPolicyTitles": [
      "Risk Trending & Pattern Analysis",
      "Claims Management & Litigation Support",
      "Office Operations & Facility Management",
      "Cal/OSHA Injury & Illness Prevention Program (IIPP)"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "relatedForms": [
      "RM-F-010 — Quarterly Risk Report",
      "RM-F-011 — Risk Mitigation Plan"
    ],
    "relatedWorkflows": [
      "OP-WF-01 — BRANCH REGISTRATION & QUARTERLY OPERATIONS REVIEW",
      "OP-WF-02 — FACILITY / BRANCH INSPECTION (QUARTERLY)",
      "OP-WF-13 — AFTER-HOURS ON-CALL OPERATIONS",
      "RM-WF-17 — SAFETY MONITORING",
      "RM-WF-15 — ANNUAL ENTERPRISE RISK REASSESSMENT"
    ],
    "gapStatus": "MAPPED",
    "notes": "Mapped to 4 IBM policy ID(s) via print crosswalk rows.",
    "sourcePage": 756
  }
];
