/* Auto-generated by scripts/resetAchcMappings.ts */
/* RESET STATE — overlay cleared. */
/*
 * The survey-tag overlay was previously derived from the print +
 * attachment crosswalks. None of those derivations were manually
 * verified, so the entire overlay has been cleared as part of the
 * automated-mapping reset. Re-populate manually, one policy at a
 * time, after the corridorAlignment manual tagging pass.
 */

export interface AchcSurveyTag {
  policyId: string;
  primarySection: 'HH1' | 'HH2' | 'HH3' | 'HH4' | 'HH5' | 'HH6' | 'HH7';
  standards: string[];
  evidenceCodes: Array<'P' | 'D' | 'I' | 'O' | 'S'>;
  sourceCorridorPolicyNos: string[];
}

export const achcSurveyTags: AchcSurveyTag[] = [];
