/* Auto-generated by scripts/generateAchcCrosswalks.ts */
/* Source: print crosswalk pages 7-31 (primary) */

export interface AchcPrintCrosswalkRow {
  corridorSection: string;
  corridorPolicyNo: string;
  corridorTitle: string;
  ibmPolicyId: string | "UNMAPPED";
  ibmPolicyTitle?: string;
  evidenceCodes: Array<"P" | "D" | "I" | "O" | "S">;
  title22: string[];
  achcStandards: string[];
  medicareCop: string[];
  mappingConfidence: "HIGH" | "MEDIUM" | "LOW" | "UNMAPPED";
  mappingNotes: string;
  sourcePage: number;
}

export const achcPrintCrosswalk: AchcPrintCrosswalkRow[] = [
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-001",
    "corridorTitle": "Mission Statement",
    "ibmPolicyId": "EN-CM-001",
    "ibmPolicyTitle": "Enterprise Compliance Metrics Program",
    "evidenceCodes": [],
    "title22": [],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number; evidence blank in source (NEEDS_REVIEW).",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-002",
    "corridorTitle": "Governing Body",
    "ibmPolicyId": "GV-GB-001",
    "ibmPolicyTitle": "Governing Body Authority & Responsibilities",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74717",
      "22 CCR §74721",
      "22 CCR §74742",
      "SB 188"
    ],
    "achcStandards": [
      "HH1-1A",
      "HH1-1B",
      "HH1-2A",
      "HH1-2A.03",
      "HH1-5A.01"
    ],
    "medicareCop": [
      "42 CFR §484.105(a)",
      "42 CFR §484.105(h)",
      "42 CFR §484.65(e)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-003",
    "corridorTitle": "Conflict of Interest",
    "ibmPolicyId": "GV-GB-002",
    "ibmPolicyTitle": "Board Meeting & Minutes Requirements",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74665"
    ],
    "achcStandards": [
      "HH1-4A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-004",
    "corridorTitle": "Referral Disclosure and Care Decisions",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P"
    ],
    "title22": [],
    "achcStandards": [
      "HH1-4A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-005",
    "corridorTitle": "Public Disclosure Statement",
    "ibmPolicyId": "GV-GB-003",
    "ibmPolicyTitle": "Conflict of Interest Disclosure",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74665",
      "22 CCR §74718"
    ],
    "achcStandards": [
      "HH1-1A",
      "HH1-1B",
      "HH1-4A.01",
      "HH2-1A.01",
      "HH1-5A",
      "HH1-5A.01"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.105(b)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-006",
    "corridorTitle": "Administrative Qualifications and Responsibilities",
    "ibmPolicyId": "GV-OG-001",
    "ibmPolicyTitle": "Organizational Structure & Reporting",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74665",
      "22 CCR §74718"
    ],
    "achcStandards": [
      "HH1-1A",
      "HH1-1B",
      "HH1-4A.01",
      "HH2-1A.01",
      "HH1-5A",
      "HH1-5A.01"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.105(b)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-007",
    "corridorTitle": "Appointment of Executive Director/Administrator",
    "ibmPolicyId": "GV-OG-002",
    "ibmPolicyTitle": "Administrator Qualifications & Responsibilities",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [
      "22 CCR §74717",
      "22 CCR §74718",
      "22 CCR §74613",
      "22 CCR §74703",
      "22 CCR §74659",
      "22 CCR §74661",
      "22 CCR §74663",
      "22 CCR §74664",
      "22 CCR §74665",
      "22 CCR §74667",
      "22 CCR §74677",
      "22 CCR §74679",
      "22 CCR §74681",
      "22 CCR §74683",
      "HSC 1725",
      "HSC 1726",
      "HSC 1727.5(e",
      "HSC 1728.1"
    ],
    "achcStandards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "medicareCop": [
      "42 CFR §484.105(b)",
      "42 CFR §484.100",
      "42 CFR §484.105(f)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-008",
    "corridorTitle": "Designation of Individual in Absence of Executive Director/Administrator",
    "ibmPolicyId": "GV-OG-002",
    "ibmPolicyTitle": "Administrator Qualifications & Responsibilities",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [
      "22 CCR §74717",
      "22 CCR §74718",
      "22 CCR §74613",
      "22 CCR §74703",
      "22 CCR §74659",
      "22 CCR §74661",
      "22 CCR §74663",
      "22 CCR §74664",
      "22 CCR §74665",
      "22 CCR §74667",
      "22 CCR §74677",
      "22 CCR §74679",
      "22 CCR §74681",
      "22 CCR §74683",
      "HSC 1725",
      "HSC 1726",
      "HSC 1727.5(e",
      "HSC 1728.1"
    ],
    "achcStandards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "medicareCop": [
      "42 CFR §484.105(b)",
      "42 CFR §484.100",
      "42 CFR §484.105(f)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-009",
    "corridorTitle": "Home Health Administrator",
    "ibmPolicyId": "GV-OG-003",
    "ibmPolicyTitle": "Scope of Services Definition",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [
      "22 CCR §74717",
      "22 CCR §74718",
      "22 CCR §74613",
      "22 CCR §74703",
      "22 CCR §74659",
      "22 CCR §74661",
      "22 CCR §74663",
      "22 CCR §74664",
      "22 CCR §74665",
      "22 CCR §74667",
      "22 CCR §74677",
      "22 CCR §74679",
      "22 CCR §74681",
      "22 CCR §74683",
      "HSC 1725",
      "HSC 1726",
      "HSC 1727.5(e",
      "HSC 1728.1"
    ],
    "achcStandards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "medicareCop": [
      "42 CFR §484.105(b)",
      "42 CFR §484.100",
      "42 CFR §484.105(f)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-010",
    "corridorTitle": "Regulatory Compliance",
    "ibmPolicyId": "CO-RA-001",
    "ibmPolicyTitle": "Regulatory Change Monitoring & Implementation",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [
      "22 CCR §74717",
      "22 CCR §74718",
      "22 CCR §74613",
      "22 CCR §74703",
      "22 CCR §74659",
      "22 CCR §74661",
      "22 CCR §74663",
      "22 CCR §74664",
      "22 CCR §74665",
      "22 CCR §74667",
      "22 CCR §74677",
      "22 CCR §74679",
      "22 CCR §74681",
      "22 CCR §74683",
      "HSC 1725",
      "HSC 1726",
      "HSC 1727.5(e",
      "HSC 1728.1"
    ],
    "achcStandards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "medicareCop": [
      "42 CFR §484.105(b)",
      "42 CFR §484.100",
      "42 CFR §484.105(f)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-011",
    "corridorTitle": "Professional Advisory Committee",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [],
    "title22": [
      "22 CCR §74742"
    ],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping; evidence blank in print source (NEEDS_REVIEW).",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-012",
    "corridorTitle": "Policy Decisions",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "D"
    ],
    "title22": [
      "22 CCR §74721",
      "22 CCR §74742"
    ],
    "achcStandards": [
      "HH1-1A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 7
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-013",
    "corridorTitle": "Development of Policies and Procedures",
    "ibmPolicyId": "EN-CM-001",
    "ibmPolicyTitle": "Enterprise Compliance Metrics Program",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74701",
      "22 CCR §74721",
      "22 CCR §74731",
      "22 CCR §74742",
      "22 CCR §74743",
      "HSC 1727.5(d",
      "HSC 1727.5(f"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH2-2A",
      "HH2-5A"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-013",
    "corridorTitle": "Development of Policies and Procedures",
    "ibmPolicyId": "EN-LC-001",
    "ibmPolicyTitle": "Policy Lifecycle Control & Version Management",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74701",
      "22 CCR §74721",
      "22 CCR §74731",
      "22 CCR §74742",
      "22 CCR §74743",
      "HSC 1727.5(d",
      "HSC 1727.5(f"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH2-2A",
      "HH2-5A"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-013",
    "corridorTitle": "Development of Policies and Procedures",
    "ibmPolicyId": "GV-PM-001",
    "ibmPolicyTitle": "Policy Development & Approval Process",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74701",
      "22 CCR §74721",
      "22 CCR §74731",
      "22 CCR §74742",
      "22 CCR §74743",
      "HSC 1727.5(d",
      "HSC 1727.5(f"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH2-2A",
      "HH2-5A"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-014",
    "corridorTitle": "Clinical Policies and Procedures",
    "ibmPolicyId": "CO-CA-001",
    "ibmPolicyTitle": "California Confidentiality of Medical Information Act (CMIA) Compliance",
    "evidenceCodes": [],
    "title22": [
      "22 CCR §74693",
      "22 CCR §74701",
      "22 CCR §74721"
    ],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number; evidence blank in source (NEEDS_REVIEW).",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-014",
    "corridorTitle": "Clinical Policies and Procedures",
    "ibmPolicyId": "CO-CP-001",
    "ibmPolicyTitle": "Corporate Compliance Program",
    "evidenceCodes": [],
    "title22": [
      "22 CCR §74693",
      "22 CCR §74701",
      "22 CCR §74721"
    ],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number; evidence blank in source (NEEDS_REVIEW).",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-014",
    "corridorTitle": "Clinical Policies and Procedures",
    "ibmPolicyId": "CO-FA-001",
    "ibmPolicyTitle": "Anti-Kickback & Stark Law Compliance",
    "evidenceCodes": [],
    "title22": [
      "22 CCR §74693",
      "22 CCR §74701",
      "22 CCR §74721"
    ],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number; evidence blank in source (NEEDS_REVIEW).",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-015",
    "corridorTitle": "Use of Organizational Chart",
    "ibmPolicyId": "GV-OG-004",
    "ibmPolicyTitle": "Strategic Planning & Annual Goals",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74661"
    ],
    "achcStandards": [
      "HH1-6A",
      "HH1-6B"
    ],
    "medicareCop": [
      "42 CFR §484.105"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-016",
    "corridorTitle": "Uniform Quality of Care",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [],
    "achcStandards": [
      "HH1-1A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-017",
    "corridorTitle": "Experimental Research and Investigational Studies",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-018",
    "corridorTitle": "Organizational Planning",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-019",
    "corridorTitle": "Contingency Planning",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-020",
    "corridorTitle": "Contingency Plan If Organization Closes",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-021",
    "corridorTitle": "Branch Control",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-022",
    "corridorTitle": "Contracted Service Providers",
    "ibmPolicyId": "GV-EA-001",
    "ibmPolicyTitle": "Interagency Agreements & Contracts",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-023",
    "corridorTitle": "Home Health Contracted Services",
    "ibmPolicyId": "GV-EA-001",
    "ibmPolicyTitle": "Interagency Agreements & Contracts",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74667",
      "22 CCR §74609",
      "22 CCR §74669",
      "22 CCR §74675",
      "22 CCR §74719",
      "22 CCR §74652",
      "22 CCR §74709"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.100(a)",
      "42 CFR §484.110(c)",
      "42 CFR §484.100(b)",
      "42 CFR §484.105(d)",
      "42 CFR §484.105(e)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-024",
    "corridorTitle": "Written Agreements for Contracted Services",
    "ibmPolicyId": "GV-EA-002",
    "ibmPolicyTitle": "Community Liaison & Public Relations",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74652",
      "22 CCR §74719",
      "22 CCR §74721"
    ],
    "achcStandards": [
      "HH1-10A"
    ],
    "medicareCop": [
      "42 CFR §484.105(e)",
      "42 CFR §484.80(h)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-025",
    "corridorTitle": "Scope of Services",
    "ibmPolicyId": "GV-OG-005",
    "ibmPolicyTitle": "Delegation of Authority",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74693",
      "22 CCR §74695",
      "HSC 1727.1"
    ],
    "achcStandards": [
      "HH2-1A.01",
      "HH2-12A.01",
      "HH5-11A",
      "HH5-11F",
      "HH5-2C.01",
      "HH5-2C.02"
    ],
    "medicareCop": [
      "42 CFR §484.75",
      "42 CFR §484.105",
      "42 CFR §484.105(f)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-026",
    "corridorTitle": "Listing of Services Provided",
    "ibmPolicyId": "GV-OG-005",
    "ibmPolicyTitle": "Delegation of Authority",
    "evidenceCodes": [
      "D",
      "I"
    ],
    "title22": [
      "22 CCR §74693",
      "HSC 1727.1"
    ],
    "achcStandards": [
      "HH1-7A",
      "HH5-11A"
    ],
    "medicareCop": [
      "42 CFR §484.75",
      "42 CFR §484.105",
      "42 CFR §484.105(f)",
      "42 CFR §484.105(i)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-027",
    "corridorTitle": "Scope of the Behavioral Health Program",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "D"
    ],
    "title22": [],
    "achcStandards": [
      "HH5-2C.02"
    ],
    "medicareCop": [
      "42 CFR §484.105"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-028",
    "corridorTitle": "Financial Responsibility and Medicare Written Notices",
    "ibmPolicyId": "FN-BC-001",
    "ibmPolicyTitle": "Medicare Billing & Claims Submission",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74743"
    ],
    "achcStandards": [
      "HH2-2A"
    ],
    "medicareCop": [
      "42 CFR §484.50(c)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-028",
    "corridorTitle": "Financial Responsibility and Medicare Written Notices",
    "ibmPolicyId": "FN-BC-003",
    "ibmPolicyTitle": "Patient Billing & Financial Responsibility",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74743"
    ],
    "achcStandards": [
      "HH2-2A"
    ],
    "medicareCop": [
      "42 CFR §484.50(c)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-028",
    "corridorTitle": "Financial Responsibility and Medicare Written Notices",
    "ibmPolicyId": "FN-BC-004",
    "ibmPolicyTitle": "Overpayment Identification & Refund",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74743"
    ],
    "achcStandards": [
      "HH2-2A"
    ],
    "medicareCop": [
      "42 CFR §484.50(c)"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 8
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-029",
    "corridorTitle": "Program Planning",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [],
    "title22": [],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping; evidence blank in print source (NEEDS_REVIEW).",
    "sourcePage": 10
  },
  {
    "corridorSection": "Section 1",
    "corridorPolicyNo": "1-030",
    "corridorTitle": "Marketing Plan",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [],
    "title22": [],
    "achcStandards": [],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping; evidence blank in print source (NEEDS_REVIEW).",
    "sourcePage": 10
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-001",
    "corridorTitle": "Management of Exposures in Personnel",
    "ibmPolicyId": "QA-PG-001",
    "ibmPolicyTitle": "QAPI Program Establishment & Governance",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "title22": [
      "22 CCR §74721",
      "22 CCR §74723",
      "22 CCR §74742"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-7A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "1910.134",
      "1910.1030"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-001",
    "corridorTitle": "Management of Exposures in Personnel",
    "ibmPolicyId": "QA-PI-001",
    "ibmPolicyTitle": "Performance Improvement Project Management",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "title22": [
      "22 CCR §74721",
      "22 CCR §74723",
      "22 CCR §74742"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-7A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "1910.134",
      "1910.1030"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-002",
    "corridorTitle": "Record Keeping",
    "ibmPolicyId": "QA-AE-001",
    "ibmPolicyTitle": "Adverse Event Identification & Reporting",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "S"
    ],
    "title22": [
      "22 CCR §74721",
      "22 CCR §74723",
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "1904.1(a)",
      "1904.4",
      "1904.5",
      "1904.6",
      "1904.7",
      "1904.8",
      "1904.9",
      "1904.10",
      "1904.11",
      "1904.29",
      "1904.32",
      "1904.33",
      "1904.35",
      "1904.36",
      "1904.39",
      "1910.1030"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-002",
    "corridorTitle": "Record Keeping",
    "ibmPolicyId": "RM-OS-002",
    "ibmPolicyTitle": "Airborne Transmissible Disease (ATD) Exposure Control Plan",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "S"
    ],
    "title22": [
      "22 CCR §74721",
      "22 CCR §74723",
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "1904.1(a)",
      "1904.4",
      "1904.5",
      "1904.6",
      "1904.7",
      "1904.8",
      "1904.9",
      "1904.10",
      "1904.11",
      "1904.29",
      "1904.32",
      "1904.33",
      "1904.35",
      "1904.36",
      "1904.39",
      "1910.1030"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-003",
    "corridorTitle": "Occupational Exposure Information and Training",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74721",
      "22 CCR §74723",
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "1904.1(a)",
      "1904.4",
      "1904.5",
      "1904.6",
      "1904.7",
      "1904.8",
      "1904.9",
      "1904.10",
      "1904.11",
      "1904.29",
      "1904.32",
      "1904.33",
      "1904.35",
      "1904.36",
      "1904.39",
      "1910.1030"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-004",
    "corridorTitle": "Standard Precautions",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "O"
    ],
    "title22": [
      "22 CCR §74721"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "1910.1030"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-005",
    "corridorTitle": "Personal Protective Equipment",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "O"
    ],
    "title22": [
      "22 CCR §74693",
      "22 CCR §74671",
      "22 CCR §74721"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "USP 800.7",
      "1910.133",
      "1910.1030"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-006",
    "corridorTitle": "Hand Hygiene",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "O"
    ],
    "title22": [
      "22 CCR §74721"
    ],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-007",
    "corridorTitle": "Clean vs. Aseptic Technique",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-1A"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-008",
    "corridorTitle": "Infection Control/Expanded Precautions",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-1A"
    ],
    "medicareCop": [
      "42 CFR §484.70"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-009",
    "corridorTitle": "Contaminated Materials Disposition",
    "ibmPolicyId": "RM-ER-001",
    "ibmPolicyTitle": "Enterprise Risk Management Program",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-1A"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-010",
    "corridorTitle": "Contaminated Waste Disposal",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-2A.01",
      "HH7-2B.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-011",
    "corridorTitle": "Hazardous Waste Handling",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "title22": [],
    "achcStandards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-6A.01"
    ],
    "medicareCop": [
      "USP 800.11.4"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 26
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-012",
    "corridorTitle": "Accidental Exposure to Blood",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-1A",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-6A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-013",
    "corridorTitle": "Bag Technique",
    "ibmPolicyId": "RM-ER-002",
    "ibmPolicyTitle": "Incident Reporting & Investigation",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-1A",
      "HH7-2A.01",
      "HH7-2B.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-014",
    "corridorTitle": "Evaluating and Maintaining Records of Infections Among Patients",
    "ibmPolicyId": "RM-ER-005",
    "ibmPolicyTitle": "Risk Trending & Pattern Analysis",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-1A",
      "HH7-1D.01",
      "HH7-2A.01",
      "HH7-2B.01"
    ],
    "medicareCop": [
      "42 CFR §484.70"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-015",
    "corridorTitle": "Evaluating and Maintaining Records of Infections Among Personnel",
    "ibmPolicyId": "RM-ER-005",
    "ibmPolicyTitle": "Risk Trending & Pattern Analysis",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "USP 800.8",
      "USP 800.5",
      "USP 800.9",
      "USP 800.13"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-016",
    "corridorTitle": "Reporting of Communicable Diseases",
    "ibmPolicyId": "RM-ER-006",
    "ibmPolicyTitle": "Claims Management & Litigation Support",
    "evidenceCodes": [
      "P",
      "D"
    ],
    "title22": [
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "USP 800.8",
      "USP 800.5",
      "USP 800.9",
      "USP 800.13"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-017",
    "corridorTitle": "Communication of Hazards to Personnel",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "O"
    ],
    "title22": [
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "USP 800.8",
      "USP 800.5",
      "USP 800.9",
      "USP 800.13"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-018",
    "corridorTitle": "Environmental Safety Program",
    "ibmPolicyId": "OP-FM-001",
    "ibmPolicyTitle": "Office Operations & Facility Management",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "USP 800.8",
      "USP 800.5",
      "USP 800.9",
      "USP 800.13"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-018",
    "corridorTitle": "Environmental Safety Program",
    "ibmPolicyId": "RM-OS-001",
    "ibmPolicyTitle": "Cal/OSHA Injury & Illness Prevention Program (IIPP)",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [
      "22 CCR §74725"
    ],
    "achcStandards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "medicareCop": [
      "42 CFR §484.70",
      "USP 800.8",
      "USP 800.5",
      "USP 800.9",
      "USP 800.13"
    ],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-019",
    "corridorTitle": "Environmental Safety—Office",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-6A.01"
    ],
    "medicareCop": [
      "USP 800.5",
      "USP 800.9",
      "USP 800.13"
    ],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-020",
    "corridorTitle": "Fire Safety—Office",
    "ibmPolicyId": "RM-OS-001",
    "ibmPolicyTitle": "Cal/OSHA Injury & Illness Prevention Program (IIPP)",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-5A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-021",
    "corridorTitle": "Utilities Management—Office",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-5A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-022",
    "corridorTitle": "Equipment Management—Office",
    "ibmPolicyId": "RM-OS-004",
    "ibmPolicyTitle": "Heat Illness Prevention Program",
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-5A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "HIGH",
    "mappingNotes": "Mapped by Corridor policy number from print source.",
    "sourcePage": 27
  },
  {
    "corridorSection": "Section 6",
    "corridorPolicyNo": "6-023",
    "corridorTitle": "Environmental Safety—Patient",
    "ibmPolicyId": "UNMAPPED",
    "evidenceCodes": [
      "P",
      "I",
      "O"
    ],
    "title22": [],
    "achcStandards": [
      "HH5-2C.01",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-3B",
      "HH7-5A.01"
    ],
    "medicareCop": [],
    "mappingConfidence": "UNMAPPED",
    "mappingNotes": "No IBM mapping found for this Corridor print row.",
    "sourcePage": 27
  }
];
