/* Auto-generated by ACHC 8-gap closure */
/* Generated: 2026-07-09T18:18:44Z */

export interface AchcSurveyTag {
  policyId: string;
  primarySection: 'HH1' | 'HH2' | 'HH3' | 'HH4' | 'HH5' | 'HH6' | 'HH7';
  standards: string[];
  evidenceCodes: Array<'P' | 'D' | 'I' | 'O' | 'S'>;
  sourceCorridorPolicyNos: string[];
}

export const achcSurveyTags: AchcSurveyTag[] = [
  {
    "policyId": "CL-SD-016",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH1-1A.01",
      "HH7-2A.01",
      "HH7-2B.01"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": []
  },
  {
    "policyId": "CL-SD-022",
    "primarySection": "HH5",
    "standards": [
      "HH5-2C.02"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": []
  },
  {
    "policyId": "CO-RA-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "1-010"
    ]
  },
  {
    "policyId": "EN-CM-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH2-2A",
      "HH2-5A"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-013"
    ]
  },
  {
    "policyId": "EN-LC-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH2-2A",
      "HH2-5A"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-013"
    ]
  },
  {
    "policyId": "FN-BC-001",
    "primarySection": "HH2",
    "standards": [
      "HH2-2A"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": [
      "1-028"
    ]
  },
  {
    "policyId": "FN-BC-003",
    "primarySection": "HH2",
    "standards": [
      "HH2-2A"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": [
      "1-028"
    ]
  },
  {
    "policyId": "FN-BC-004",
    "primarySection": "HH2",
    "standards": [
      "HH2-2A"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": [
      "1-028"
    ]
  },
  {
    "policyId": "GV-EA-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH7-10A.01",
      "HH1-5A",
      "HH1-1A",
      "HH1-6C",
      "HH1-12A.01",
      "HH1-10A"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-022",
      "1-023"
    ]
  },
  {
    "policyId": "GV-EA-002",
    "primarySection": "HH1",
    "standards": [
      "HH1-10A"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-024"
    ]
  },
  {
    "policyId": "GV-GB-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A",
      "HH1-1B",
      "HH1-2A",
      "HH1-2A.03",
      "HH1-5A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-002"
    ]
  },
  {
    "policyId": "GV-GB-002",
    "primarySection": "HH1",
    "standards": [
      "HH1-4A.01"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": [
      "1-003"
    ]
  },
  {
    "policyId": "GV-GB-003",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A",
      "HH1-1B",
      "HH1-4A.01",
      "HH2-1A.01",
      "HH1-5A",
      "HH1-5A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-005"
    ]
  },
  {
    "policyId": "GV-OG-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A",
      "HH1-1B",
      "HH1-4A.01",
      "HH2-1A.01",
      "HH1-5A",
      "HH1-5A.01"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-006"
    ]
  },
  {
    "policyId": "GV-OG-002",
    "primarySection": "HH1",
    "standards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "1-007",
      "1-008"
    ]
  },
  {
    "policyId": "GV-OG-003",
    "primarySection": "HH1",
    "standards": [
      "HH1-5A",
      "HH1-5A.01",
      "HH1-6B",
      "HH1-1A",
      "HH1-1A.01",
      "HH1-1C",
      "HH1-9A.01",
      "HH1-12A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "1-009"
    ]
  },
  {
    "policyId": "GV-OG-004",
    "primarySection": "HH1",
    "standards": [
      "HH1-6A",
      "HH1-6B"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-015"
    ]
  },
  {
    "policyId": "GV-OG-005",
    "primarySection": "HH2",
    "standards": [
      "HH2-1A.01",
      "HH2-12A.01",
      "HH5-11A",
      "HH5-11F",
      "HH5-2C.01",
      "HH5-2C.02",
      "HH1-7A"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-025",
      "1-026"
    ]
  },
  {
    "policyId": "GV-PM-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH2-2A",
      "HH2-5A"
    ],
    "evidenceCodes": [
      "D",
      "I"
    ],
    "sourceCorridorPolicyNos": [
      "1-013"
    ]
  },
  {
    "policyId": "HR-EH-101",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH1-1A.01",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-6A.01"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": []
  },
  {
    "policyId": "OP-FM-001",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "6-018"
    ]
  },
  {
    "policyId": "QA-AE-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH7-1A"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "S"
    ],
    "sourceCorridorPolicyNos": [
      "6-002"
    ]
  },
  {
    "policyId": "QA-PG-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-7A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "sourceCorridorPolicyNos": [
      "6-001"
    ]
  },
  {
    "policyId": "QA-PI-001",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH7-1A",
      "HH7-7A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O",
      "S"
    ],
    "sourceCorridorPolicyNos": [
      "6-001"
    ]
  },
  {
    "policyId": "RM-ER-001",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "6-009"
    ]
  },
  {
    "policyId": "RM-ER-002",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH7-2A.01",
      "HH7-2B.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "6-013"
    ]
  },
  {
    "policyId": "RM-ER-005",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH7-1D.01",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-1D",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": [
      "6-014",
      "6-015"
    ]
  },
  {
    "policyId": "RM-ER-006",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": [
      "6-016"
    ]
  },
  {
    "policyId": "RM-OS-001",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH7-1D",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH1-1A.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01",
      "HH7-5A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "6-018",
      "6-020"
    ]
  },
  {
    "policyId": "RM-OS-002",
    "primarySection": "HH1",
    "standards": [
      "HH1-1A.01",
      "HH7-1A"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "S"
    ],
    "sourceCorridorPolicyNos": [
      "6-002"
    ]
  },
  {
    "policyId": "RM-OS-004",
    "primarySection": "HH7",
    "standards": [
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-5A.01"
    ],
    "evidenceCodes": [
      "P",
      "D",
      "I",
      "O"
    ],
    "sourceCorridorPolicyNos": [
      "6-022"
    ]
  },
  {
    "policyId": "RM-OS-101",
    "primarySection": "HH7",
    "standards": [
      "HH7-1A",
      "HH7-1D",
      "HH1-1A.01",
      "HH7-2A.01",
      "HH7-2B.01",
      "HH7-6A.01",
      "HH7-6B.01",
      "HH7-7A.01",
      "HH7-9A.01"
    ],
    "evidenceCodes": [
      "P",
      "D"
    ],
    "sourceCorridorPolicyNos": []
  }
];
