/* AUTO-GENERATED by scripts/compileWorkflows.ts. */
import type { WorkflowTemplate } from '@/policy/types/workflow';

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    "workflowId": "CL-WF-01",
    "templateKey": "CL-WF-01::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves acceptance decisions and all non-admits. Insurance Verifier certifies benefits.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-006",
      "CL-FM-009",
      "CL-FM-025",
      "CL-FM-027",
      "CL-FM-029",
      "CL-FM-050",
      "GV-FM-016",
      "OP-FM-014",
      "OP-FM-015",
      "OP-FM-018"
    ],
    "stepCount": 9,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.60(a)"
    ]
  },
  {
    "workflowId": "CL-WF-02",
    "templateKey": "CL-WF-02::per_event",
    "cadence": {
      "kind": "time_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinician attests; Clinical Manager audits.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-009",
      "CO-FM-021"
    ],
    "stepCount": 5,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 409.42",
      "SSA § 1835(a)(2)("
    ]
  },
  {
    "workflowId": "CL-WF-03",
    "templateKey": "CL-WF-03::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager attests completeness before billing release.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-010",
      "CO-FM-021"
    ],
    "stepCount": 5,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 424.22(a)(1)(v)",
      "SSA § 1814(a)(2)("
    ]
  },
  {
    "workflowId": "CL-WF-04",
    "templateKey": "CL-WF-04::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews; QA reviewer signs OASIS QA; Physician signs POC.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-001",
      "CL-FM-002",
      "CL-FM-005",
      "CL-FM-009",
      "CL-FM-019",
      "CL-FM-020",
      "CL-FM-026",
      "CL-FM-027",
      "CL-FM-029",
      "CL-FM-031",
      "CL-FM-038",
      "CL-FM-039",
      "CL-FM-041",
      "CL-FM-047"
    ],
    "stepCount": 8,
    "declaredRisk": "high",
    "regulatoryAnchors": [
      "42 CFR § 484.55"
    ]
  },
  {
    "workflowId": "CL-WF-05",
    "templateKey": "CL-WF-05::per_event",
    "cadence": {
      "kind": "time_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "QA Reviewer signs pre-submission; Clinical Manager signs competency annually.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-002",
      "CL-FM-031",
      "CL-FM-032",
      "CL-FM-045",
      "CL-FM-050",
      "CL-FM-051"
    ],
    "stepCount": 9,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.45"
    ]
  },
  {
    "workflowId": "CL-WF-06",
    "templateKey": "CL-WF-06::per_event",
    "cadence": {
      "kind": "time_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Physician signature required; Clinical Manager reviews POC completeness.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-005",
      "CL-FM-008",
      "CL-FM-035",
      "CL-FM-044",
      "CL-FM-057"
    ],
    "stepCount": 7,
    "declaredRisk": "high",
    "regulatoryAnchors": [
      "42 CFR § 484.60"
    ]
  },
  {
    "workflowId": "CL-WF-07",
    "templateKey": "CL-WF-07::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Physician signature required for each order. Clinical Manager enforces signature tracking.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-006",
      "CL-FM-007",
      "CL-FM-008"
    ],
    "stepCount": 6,
    "declaredRisk": "high",
    "regulatoryAnchors": [
      "42 CFR § 484.60(b)"
    ]
  },
  {
    "workflowId": "CL-WF-08",
    "templateKey": "CL-WF-08::weekly",
    "cadence": {
      "kind": "event_based",
      "interval": "weekly"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews complex-case conferences; approves deviations from POC.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-035",
      "CL-FM-053",
      "CL-FM-054"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.60(d)"
    ]
  },
  {
    "workflowId": "CL-WF-09",
    "templateKey": "CL-WF-09::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinician signs; Clinical Manager audits; physician signs orders/POC related to findings.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-013",
      "CL-FM-014",
      "CL-FM-017",
      "CL-FM-023",
      "CL-FM-024",
      "CL-FM-026",
      "CL-FM-033",
      "CL-FM-034",
      "CL-FM-039",
      "CL-FM-040",
      "CL-FM-041"
    ],
    "stepCount": 6,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.60(b)"
    ]
  },
  {
    "workflowId": "CL-WF-10",
    "templateKey": "CL-WF-10::semiannual",
    "cadence": {
      "kind": "event_based",
      "interval": "semiannual"
    },
    "approvals": [
      {
        "description": "RN signs each supervisory visit; Clinical Manager signs annual direct observations.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-015",
      "CL-FM-016",
      "CL-FM-042",
      "HR-FM-017",
      "HR-FM-031",
      "HR-FM-038"
    ],
    "stepCount": 9,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.75"
    ]
  },
  {
    "workflowId": "CL-WF-11",
    "templateKey": "CL-WF-11::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Staff Dev RN signs each module; Clinical Manager reviews completion.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-016",
      "HR-FM-017",
      "HR-FM-024"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.80(d)"
    ]
  },
  {
    "workflowId": "CL-WF-12",
    "templateKey": "CL-WF-12::on_demand",
    "cadence": {
      "kind": "time_based",
      "interval": "on_demand"
    },
    "approvals": [
      {
        "description": "Clinical Manager audits reconciliation completeness monthly.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-006",
      "CL-FM-007",
      "CL-FM-018",
      "CL-FM-019",
      "CL-FM-022",
      "RM-FM-012"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.60(b)"
    ]
  },
  {
    "workflowId": "CL-WF-13",
    "templateKey": "CL-WF-13::episodic",
    "cadence": {
      "kind": "event_based",
      "interval": "episodic"
    },
    "approvals": [
      {
        "description": "Physician orders all wound care; Clinical Manager audits; wound expert for complex.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-017",
      "CL-FM-023",
      "CL-FM-024",
      "CL-FM-026",
      "CL-FM-029",
      "CL-FM-037",
      "CL-FM-040"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.60"
    ]
  },
  {
    "workflowId": "CL-WF-14",
    "templateKey": "CL-WF-14::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Infection Preventionist signs surveillance; Clinical Manager audits.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-021",
      "HR-FM-014",
      "HR-FM-017",
      "HR-FM-021",
      "QA-FM-006"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.70"
    ]
  },
  {
    "workflowId": "CL-WF-15",
    "templateKey": "CL-WF-15::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Physician orders; Clinical Manager operational oversight; Compliance for platform.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-005",
      "CL-FM-006",
      "CL-FM-011",
      "CL-FM-025",
      "CO-FM-016",
      "IT-FM-020"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 409.46",
      "45 CFR § 164.312"
    ]
  },
  {
    "workflowId": "CL-WF-16",
    "templateKey": "CL-WF-16::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Admitting RN attests; Clinical Manager audits.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-017",
      "CL-FM-027",
      "CL-FM-028",
      "CL-FM-029",
      "CL-FM-052",
      "CO-FM-019",
      "OP-FM-017"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.50"
    ]
  },
  {
    "workflowId": "CL-WF-17",
    "templateKey": "CL-WF-17::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinician signs; Clinical Manager audits.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-022",
      "CL-FM-046",
      "OP-FM-018"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.60(c)"
    ]
  },
  {
    "workflowId": "CL-WF-18",
    "templateKey": "CL-WF-18::per_event",
    "cadence": {
      "kind": "time_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews; physician signs recert and new orders.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-002",
      "CL-FM-003",
      "CL-FM-005",
      "CL-FM-044",
      "CL-FM-045",
      "CL-FM-057"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.55"
    ]
  },
  {
    "workflowId": "CL-WF-19",
    "templateKey": "CL-WF-19::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs DC; physician concurrence for appropriate transitions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-002",
      "CL-FM-004",
      "CL-FM-036",
      "CL-FM-045"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.50(d)"
    ]
  },
  {
    "workflowId": "CL-WF-20",
    "templateKey": "CL-WF-20::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews patterns; physician involved in clinical decisions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-011",
      "CL-FM-012",
      "CL-FM-048",
      "CL-FM-053"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.60"
    ]
  },
  {
    "workflowId": "CL-WF-21",
    "templateKey": "CL-WF-21::per_event",
    "cadence": {
      "kind": "time_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves; Records certifies closure.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-013",
      "CL-FM-033",
      "CL-FM-034",
      "CL-FM-050",
      "CO-FM-038"
    ],
    "stepCount": 6,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.110"
    ]
  },
  {
    "workflowId": "CL-WF-22",
    "templateKey": "CL-WF-22::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager / MSW coordinate; Administrator briefed for material cases; Legal if complex.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-030",
      "CL-FM-053",
      "HR-FM-033",
      "QA-FM-004"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.50(e)"
    ]
  },
  {
    "workflowId": "CL-WF-23",
    "templateKey": "CL-WF-23::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves resolution; Compliance Officer reviews for systemic/regulatory issues.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-049",
      "CO-FM-024",
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-001",
      "QA-FM-003",
      "QA-FM-005"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.50(e)"
    ]
  },
  {
    "workflowId": "CL-WF-24",
    "templateKey": "CL-WF-24::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs specialty POC; physician orders; specialty consultant (if involved).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-005",
      "CL-FM-037",
      "CL-FM-039",
      "CL-FM-046",
      "CL-FM-047",
      "CL-FM-053",
      "CL-FM-054",
      "CL-FM-055"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CL-WF-25",
    "templateKey": "CL-WF-25::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs competency; HR files.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-016",
      "CL-FM-034",
      "CL-FM-051",
      "CL-FM-056",
      "HR-FM-007",
      "HR-FM-016",
      "HR-FM-038"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.115"
    ]
  },
  {
    "workflowId": "CO-WF-01",
    "templateKey": "CO-WF-01::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer signs; Governing Body accepts by formal vote. Retention ≥10 years (OIG best practice).",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-001",
      "CO-FM-005",
      "CO-FM-024",
      "CO-FM-032",
      "EN-FM-022",
      "GV-FM-005",
      "GV-FM-023"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.100"
    ]
  },
  {
    "workflowId": "CO-WF-02",
    "templateKey": "CO-WF-02::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer certifies enterprise completion quarterly; HR ensures individual file presence.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-002",
      "CO-FM-024",
      "EN-FM-001",
      "EN-FM-014",
      "HR-FM-009"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-03",
    "templateKey": "CO-WF-03::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Compliance Officer approves findings/closure; Legal concurs on reportability decisions; Governing Body informed of material matters.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-003",
      "CO-FM-004",
      "CO-FM-024",
      "EN-FM-019",
      "HR-FM-009",
      "HR-FM-010",
      "QA-FM-005"
    ],
    "stepCount": 11,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-04",
    "templateKey": "CO-WF-04::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Annual plan: Compliance Committee → Governing Body. Each audit report: Compliance Officer signs; department head acknowledges CAP.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-005",
      "CO-FM-022",
      "CO-FM-024",
      "CO-FM-032",
      "CO-FM-038",
      "EN-FM-019",
      "FN-FM-006",
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-005"
    ],
    "stepCount": 10,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-05",
    "templateKey": "CO-WF-05::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "PoC: Administrator signs; Governing Body approves Condition-Level PoCs. Legal reviews for CoP-level or enforcement-risk findings.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-006",
      "CO-FM-007",
      "CO-FM-008",
      "CO-FM-034",
      "EN-FM-019",
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-005"
    ],
    "stepCount": 14,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 488"
    ]
  },
  {
    "workflowId": "CO-WF-06",
    "templateKey": "CO-WF-06::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Compliance Officer for routine changes; Governing Body for material/CoP-impacting changes. Legal review for ambiguous/high-stakes.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-009",
      "CO-FM-024",
      "CO-FM-028",
      "EN-FM-005",
      "EN-FM-006",
      "EN-FM-007",
      "EN-FM-008",
      "EN-FM-009",
      "GV-FM-005",
      "HR-FM-017"
    ],
    "stepCount": 9,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-07",
    "templateKey": "CO-WF-07::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer before execution; Legal for novel; Governing Body for material arrangements or those above contract threshold.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-010",
      "CO-FM-011",
      "CO-FM-037",
      "GV-FM-018"
    ],
    "stepCount": 10,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 411"
    ]
  },
  {
    "workflowId": "CO-WF-08",
    "templateKey": "CO-WF-08::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Compliance Committee approves curriculum; Compliance Officer signs off on completion rates.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-004",
      "CO-FM-012",
      "CO-FM-024",
      "CO-FM-037",
      "FN-FM-011",
      "HR-FM-007"
    ],
    "stepCount": 6,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 422.503(b)(4)(vi)"
    ]
  },
  {
    "workflowId": "CO-WF-09",
    "templateKey": "CO-WF-09::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer certifies; HR enforces completion.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-013",
      "CO-FM-024",
      "EN-FM-001",
      "HR-FM-007",
      "IT-FM-026",
      "IT-FM-027"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.530"
    ]
  },
  {
    "workflowId": "CO-WF-10",
    "templateKey": "CO-WF-10::annual",
    "cadence": {
      "kind": "event_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Breach determination: Compliance Officer (with Legal for close calls). Notifications: Administrator sign-off. 500+ reports: Governing Body informed and Legal.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-004",
      "CO-FM-014",
      "CO-FM-015",
      "CO-FM-024",
      "CO-FM-028",
      "EN-FM-019",
      "GV-FM-005",
      "IT-FM-009",
      "IT-FM-011"
    ],
    "stepCount": 15,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-11",
    "templateKey": "CO-WF-11::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer executes BAAs; Legal reviews non-standard language; Administrator notified of any termination.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-014",
      "CO-FM-016",
      "CO-FM-017",
      "CO-FM-027",
      "GV-FM-018"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "CO-WF-12",
    "templateKey": "CO-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Records Clerk for routine; Compliance Officer for denials, sensitive categories, amendments.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-018",
      "CO-FM-019",
      "CO-FM-029",
      "HR-FM-037",
      "IT-FM-022"
    ],
    "stepCount": 11,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.508"
    ]
  },
  {
    "workflowId": "CO-WF-13",
    "templateKey": "CO-WF-13::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Compliance Officer approves each destruction batch. Legal confirms no hold.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-020",
      "IT-FM-003",
      "IT-FM-024"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.110",
      "45 CFR § 164.316"
    ]
  },
  {
    "workflowId": "CO-WF-14",
    "templateKey": "CO-WF-14::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Compliance Officer approves findings; Clinical Manager concurs on corrective actions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-033",
      "CL-FM-034",
      "CO-FM-021",
      "CO-FM-023",
      "CO-FM-024",
      "CO-FM-038",
      "FN-FM-006",
      "HR-FM-017"
    ],
    "stepCount": 8,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-15",
    "templateKey": "CO-WF-15::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Compliance Officer signs each monthly screening completion; Administrator on terminations.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-001",
      "CO-FM-025",
      "CO-FM-030",
      "FN-FM-006",
      "HR-FM-005"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 1001.1901"
    ]
  },
  {
    "workflowId": "CO-WF-16",
    "templateKey": "CO-WF-16::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Governing Body authorizes disclosure; Legal signs submission; Administrator signs settlement.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-030",
      "CO-FM-033",
      "EN-FM-019",
      "FN-FM-006",
      "GV-FM-005"
    ],
    "stepCount": 10,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 401.305"
    ]
  },
  {
    "workflowId": "CO-WF-17",
    "templateKey": "CO-WF-17::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "IT + Compliance Officer jointly sign SRA; Governing Body approves material risk acceptances.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-026",
      "EN-FM-019",
      "GV-FM-005",
      "GV-FM-023",
      "IT-FM-010",
      "IT-FM-011"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "CO-WF-18",
    "templateKey": "CO-WF-18::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Committee; Governing Body for material/clinical-decision-support AI.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-016",
      "CO-FM-024",
      "CO-FM-027",
      "CO-FM-031",
      "CO-FM-039",
      "GV-FM-005",
      "IT-FM-010"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-19",
    "templateKey": "CO-WF-19::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Compliance Officer signs; Governing Body receives quarterly summary and annual attestation.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-034",
      "CO-FM-036",
      "EN-FM-019",
      "GV-FM-023"
    ],
    "stepCount": 4,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-20",
    "templateKey": "CO-WF-20::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Committee consensus; minutes approved at next meeting.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-009",
      "CO-FM-024",
      "EN-FM-022",
      "GV-FM-023",
      "QA-FM-005"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-21",
    "templateKey": "CO-WF-21::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Compliance Officer for all sensitive-category exceptions and CMIA violation classifications.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-004",
      "CO-FM-014",
      "CO-FM-018",
      "CO-FM-019"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "CO-WF-22",
    "templateKey": "CO-WF-22::annual",
    "cadence": {
      "kind": "event_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Governing Body accepts; direction on material issues documented in minutes.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-017",
      "EN-FM-022",
      "GV-FM-005",
      "GV-FM-023"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-01",
    "templateKey": "EN-WF-01::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Tier 1 (REQUIRED): Governing Body. Tier 2 (RECOMMENDED): Administrator + Compliance Officer. Tier 3 (OPTIONAL): Department Director + Compliance Officer.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-024",
      "EN-FM-001",
      "EN-FM-002",
      "EN-FM-003",
      "EN-FM-004",
      "EN-FM-005",
      "EN-FM-006",
      "EN-FM-007",
      "EN-FM-008",
      "EN-FM-009",
      "EN-FM-020",
      "GV-FM-005",
      "QA-FM-001"
    ],
    "stepCount": 10,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "HIPAA § 164.316"
    ]
  },
  {
    "workflowId": "EN-WF-02",
    "templateKey": "EN-WF-02::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Owners sign reaffirmations; Governing Body accepts annual review report.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-002",
      "EN-FM-003",
      "EN-FM-008",
      "EN-FM-009",
      "EN-FM-010",
      "GV-FM-023"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105"
    ]
  },
  {
    "workflowId": "EN-WF-03",
    "templateKey": "EN-WF-03::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer certifies matrix; HR tracks completion.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-001",
      "EN-FM-011",
      "EN-FM-012",
      "GV-FM-023",
      "HR-FM-026"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "HIPAA § 164.530"
    ]
  },
  {
    "workflowId": "EN-WF-04",
    "templateKey": "EN-WF-04::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Compliance Officer certifies accuracy monthly.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-002",
      "EN-FM-013",
      "GV-FM-023"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-05",
    "templateKey": "EN-WF-05::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator approves plan; Governing Body acknowledges material changes.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-003",
      "EN-FM-014",
      "EN-FM-015",
      "EN-FM-016",
      "GV-FM-023"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-06",
    "templateKey": "EN-WF-06::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Compliance Officer audits quarterly.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-002",
      "EN-FM-017",
      "EN-FM-018"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "HIPAA § 164.316"
    ]
  },
  {
    "workflowId": "EN-WF-07",
    "templateKey": "EN-WF-07::quarterly",
    "cadence": {
      "kind": "event_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Compliance Officer approves new/revised forms.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-019",
      "EN-FM-020",
      "EN-FM-021"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-08",
    "templateKey": "EN-WF-08::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Compliance Officer approves destruction lists; Administrator signs annual.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-024",
      "EN-FM-022",
      "EN-FM-030",
      "EN-FM-031",
      "IT-FM-024",
      "IT-FM-036",
      "IT-FM-044"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.110",
      "HIPAA § 164.316"
    ]
  },
  {
    "workflowId": "EN-WF-09",
    "templateKey": "EN-WF-09::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Administrator approves annual calendar; Governing Body accepts.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-032",
      "EN-FM-033",
      "GV-FM-023"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-10",
    "templateKey": "EN-WF-10::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Administrator signs monthly; Governing Body accepts quarterly.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-018",
      "EN-FM-034",
      "GV-FM-023"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-11",
    "templateKey": "EN-WF-11::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator + Audit Committee of the Board.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-018",
      "CO-FM-019",
      "CO-FM-020",
      "EN-FM-028",
      "EN-FM-035",
      "GV-FM-023"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-12",
    "templateKey": "EN-WF-12::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator approves prioritization; Governing Body accepts risk appetite.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-022",
      "CO-FM-024",
      "GV-FM-005",
      "GV-FM-023",
      "IT-FM-003",
      "RM-FM-015",
      "RM-FM-017"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "EN-WF-13",
    "templateKey": "EN-WF-13::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator + CFO certify; Governing Body accepts.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-029",
      "EN-FM-036",
      "EN-FM-037",
      "GV-FM-005"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-01",
    "templateKey": "FN-WF-01::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Finance Committee recommends; Governing Body approves.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "FN-FM-001",
      "FN-FM-002",
      "FN-FM-014",
      "GV-FM-005",
      "GV-FM-011",
      "GV-FM-023"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(h)(4)"
    ]
  },
  {
    "workflowId": "FN-WF-02",
    "templateKey": "FN-WF-02::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "CFO approves monthly package.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-003",
      "FN-FM-004",
      "FN-FM-005",
      "GV-FM-005",
      "GV-FM-023"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-03",
    "templateKey": "FN-WF-03::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator certifies cost report.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-003",
      "FN-FM-006",
      "FN-FM-007",
      "FN-FM-008"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 413.20"
    ]
  },
  {
    "workflowId": "FN-WF-04",
    "templateKey": "FN-WF-04::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Billing Manager certifies clean claim; CFO reviews exceptions; Administrator signs cert statements (Provider Enrollment).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-009",
      "FN-FM-010",
      "FN-FM-011",
      "FN-FM-012"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.205"
    ]
  },
  {
    "workflowId": "FN-WF-05",
    "templateKey": "FN-WF-05::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "CFO approves appeal strategy; Legal engaged at ALJ.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-013",
      "FN-FM-014",
      "FN-FM-015",
      "QA-FM-006"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 405.940"
    ]
  },
  {
    "workflowId": "FN-WF-06",
    "templateKey": "FN-WF-06::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs off on clinical accuracy; CFO monitors response timing.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-013",
      "FN-FM-016",
      "FN-FM-017"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-07",
    "templateKey": "FN-WF-07::on_demand",
    "cadence": {
      "kind": "time_based",
      "interval": "on_demand"
    },
    "approvals": [
      {
        "description": "Administrator certifies CMS-838.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-018",
      "FN-FM-019"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 401.605"
    ]
  },
  {
    "workflowId": "FN-WF-08",
    "templateKey": "FN-WF-08::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator + Compliance Officer + CFO + Legal before any disclosure; Governing Body briefed (briefing recorded in **GV-FM-005 Governing Body Meeting Minutes**).",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-022",
      "CO-FM-024",
      "CO-FM-030",
      "CO-FM-033",
      "FN-FM-019",
      "FN-FM-020",
      "FN-FM-021",
      "FN-FM-022",
      "FN-FM-023",
      "FN-FM-024",
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-005"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 401.305"
    ]
  },
  {
    "workflowId": "FN-WF-09",
    "templateKey": "FN-WF-09::monthly",
    "cadence": {
      "kind": "event_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "CFO approves write-offs > threshold; large bundles require Board notice captured in **GV-FM-005 Governing Body Meeting Minutes**.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "FN-FM-004",
      "FN-FM-011",
      "FN-FM-014",
      "FN-FM-025",
      "FN-FM-026",
      "GV-FM-011"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-10",
    "templateKey": "FN-WF-10::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "CFO approves within threshold; Administrator for exceptions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-004",
      "FN-FM-026",
      "FN-FM-027",
      "FN-FM-028"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-11",
    "templateKey": "FN-WF-11::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Dept Mgr approves; CFO signs large; Controller reconciles.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-011",
      "HR-FM-005",
      "OP-FM-005"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-12",
    "templateKey": "FN-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "CFO signs payroll register.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "FN-FM-011",
      "HR-FM-024"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-13",
    "templateKey": "FN-WF-13::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Audit Committee accepts (minutes); Governing Body ratifies (minutes in GV-FM-005).",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "FN-FM-015",
      "GV-FM-005",
      "QA-FM-005"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-14",
    "templateKey": "FN-WF-14::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator approves; Governing Body on major adjustments.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "FN-FM-004"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "FN-WF-15",
    "templateKey": "FN-WF-15::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Compliance Officer + CFO approve sampling plan and final reports.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-018",
      "CO-FM-019",
      "CO-FM-022",
      "CO-FM-024",
      "CO-FM-032",
      "CO-FM-033",
      "FN-FM-008",
      "FN-FM-010",
      "FN-FM-014",
      "FN-FM-016",
      "FN-FM-020"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "GV-WF-01",
    "templateKey": "GV-WF-01::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "**Minutes approval:** Voting members at next scheduled meeting (motion, second, vote recorded).",
        "requiresGoverningBody": false
      },
      {
        "description": "**Policy approvals:** Majority vote of quorum; dissenting votes recorded by name.",
        "requiresGoverningBody": false
      },
      {
        "description": "**Delay consequence:** Minutes unapproved beyond 2 meetings trigger escalation to Compliance Committee and Governing Body Chair; treated as control failure reported in next CO-FM-024.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-024",
      "EN-FM-008",
      "EN-FM-021",
      "FN-FM-011",
      "GV-FM-004",
      "GV-FM-005",
      "GV-FM-006",
      "GV-FM-011",
      "GV-FM-021",
      "GV-FM-022",
      "GV-FM-023",
      "QA-FM-003",
      "RM-FM-008"
    ],
    "stepCount": 15,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "GV-WF-02",
    "templateKey": "GV-WF-02::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Improvement plan approved by full Governing Body vote.",
        "requiresGoverningBody": true
      },
      {
        "description": "Confidential individual assessments retained only by Compliance Officer / Chair.",
        "requiresGoverningBody": false
      },
      {
        "description": "Delay consequence: Missing annual self-assessment = governance control failure; tracked on Compliance Scorecard (EN-FM-022).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-008",
      "GV-FM-012",
      "GV-FM-021",
      "GV-FM-022",
      "GV-FM-024"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "GV-WF-03",
    "templateKey": "GV-WF-03::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Governing Body vote required for permanent appointment; Chair may designate interim unilaterally via written delegation.",
        "requiresGoverningBody": true
      },
      {
        "description": "CMS Form 855A required for change in Administrator (change in key personnel).",
        "requiresGoverningBody": false
      },
      {
        "description": "Delay consequence: Vacancy unfilled >30 days = CoP violation and immediate survey risk under § 484.105(b).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-003",
      "GV-FM-005",
      "GV-FM-006",
      "GV-FM-007",
      "GV-FM-013",
      "GV-FM-014",
      "GV-FM-017",
      "GV-FM-019",
      "HR-FM-005",
      "HR-FM-006",
      "HR-FM-007",
      "HR-FM-018"
    ],
    "stepCount": 12,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "GV-WF-04",
    "templateKey": "GV-WF-04::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator appoints; Governing Body confirms at next meeting. Delay beyond 30 days = escalation.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-003",
      "GV-FM-005",
      "GV-FM-006",
      "GV-FM-015",
      "GV-FM-017",
      "GV-FM-019",
      "HR-FM-003",
      "HR-FM-004",
      "HR-FM-005",
      "HR-FM-006",
      "HR-FM-007",
      "HR-FM-018",
      "HR-FM-031"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(c)"
    ]
  },
  {
    "workflowId": "GV-WF-05",
    "templateKey": "GV-WF-05::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Governing Body approval required before fiscal year start. Amendments >10% to any line require formal approval.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "FN-FM-011",
      "GV-FM-004",
      "GV-FM-005",
      "GV-FM-009",
      "HR-FM-019",
      "QA-FM-007"
    ],
    "stepCount": 9,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.105(h)"
    ]
  },
  {
    "workflowId": "GV-WF-06",
    "templateKey": "GV-WF-06::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Governing Body vote annually. Version increment on any material change.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-016",
      "HR-FM-017",
      "OP-FM-015"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(i)(1)"
    ]
  },
  {
    "workflowId": "GV-WF-07",
    "templateKey": "GV-WF-07::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Governing Body approves annually and on any material change.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-016",
      "GV-FM-020"
    ],
    "stepCount": 6,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.105(i)(2)(ii)"
    ]
  },
  {
    "workflowId": "GV-WF-08",
    "templateKey": "GV-WF-08::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Chair approves Administrator's COI; Governing Body approves Chair's COI and material exceptions.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-011",
      "GV-FM-005",
      "GV-FM-006",
      "GV-FM-023"
    ],
    "stepCount": 6,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 411.354"
    ]
  },
  {
    "workflowId": "GV-WF-09",
    "templateKey": "GV-WF-09::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator signs renewals; Governing Body reviews status quarterly; approves remediation plans for any denial.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-035",
      "GV-FM-002",
      "GV-FM-005",
      "GV-FM-019",
      "GV-FM-023"
    ],
    "stepCount": 8,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 489"
    ]
  },
  {
    "workflowId": "GV-WF-10",
    "templateKey": "GV-WF-10::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Governing Body formal resolution required; Legal Counsel concurrence; Administrator sign-offs per step.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CL-FM-036",
      "CO-FM-020",
      "GV-FM-001",
      "GV-FM-005",
      "GV-FM-022"
    ],
    "stepCount": 10,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 489.18"
    ]
  },
  {
    "workflowId": "GV-WF-11",
    "templateKey": "GV-WF-11::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator for contracts below threshold; Governing Body for contracts above threshold, referral-source contracts, or management agreements. BAA mandatory before any PHI exchange.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-010",
      "CO-FM-011",
      "CO-FM-016",
      "CO-FM-017",
      "GV-FM-005",
      "GV-FM-018",
      "HR-FM-005",
      "IT-FM-028",
      "OP-FM-003",
      "OP-FM-004",
      "OP-FM-005",
      "OP-FM-006",
      "OP-FM-007",
      "OP-FM-008"
    ],
    "stepCount": 11,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.105(f)"
    ]
  },
  {
    "workflowId": "GV-WF-12",
    "templateKey": "GV-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Routine by Administrator; high-risk/legal-sensitive by Chair with Legal Counsel.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-033",
      "GV-FM-020",
      "GV-FM-025"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.110"
    ]
  },
  {
    "workflowId": "GV-WF-13",
    "templateKey": "GV-WF-13::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Chair signs off annual completion; included in annual report to Governing Body.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-001",
      "GV-FM-008",
      "GV-FM-024"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(a)"
    ]
  },
  {
    "workflowId": "GV-WF-14",
    "templateKey": "GV-WF-14::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Chair convenes; majority must concur with motion; Legal Counsel concurrence recommended for privilege-sensitive topics.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-012",
      "GV-FM-022"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-01",
    "templateKey": "HR-WF-01::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator/CFO approves requisition; Hiring Mgr recommends finalist.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-001",
      "HR-FM-002",
      "HR-FM-003",
      "HR-FM-004"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-02",
    "templateKey": "HR-WF-02::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director clears hire; Compliance clears exclusion; Administrator for exceptions (individualized assessment).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-005",
      "HR-FM-006",
      "HR-FM-007",
      "HR-FM-008",
      "HR-FM-009"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-03",
    "templateKey": "HR-WF-03::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Hiring Mgr confirms competency at end of orientation.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-009",
      "EN-FM-001",
      "HR-FM-010",
      "HR-FM-011",
      "HR-FM-012",
      "HR-FM-013",
      "HR-FM-014",
      "IT-FM-001"
    ],
    "stepCount": 10,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-04",
    "templateKey": "HR-WF-04::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director signs renewal verification; Administrator on exceptions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-019",
      "GV-FM-023",
      "HR-FM-006",
      "HR-FM-015",
      "HR-FM-016"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.115"
    ]
  },
  {
    "workflowId": "HR-WF-05",
    "templateKey": "HR-WF-05::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs competency outcomes; RN Instructor conducts.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-014",
      "HR-FM-006",
      "HR-FM-017",
      "HR-FM-018",
      "HR-FM-019"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.80"
    ]
  },
  {
    "workflowId": "HR-WF-06",
    "templateKey": "HR-WF-06::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs competency outcomes.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-019",
      "HR-FM-020",
      "HR-FM-021",
      "HR-FM-022"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.75"
    ]
  },
  {
    "workflowId": "HR-WF-07",
    "templateKey": "HR-WF-07::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Compliance Officer certifies curriculum; Administrator accepts completion report.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-008",
      "CO-FM-009",
      "CO-FM-024",
      "GV-FM-005",
      "GV-FM-023",
      "HR-FM-017",
      "HR-FM-025",
      "HR-FM-026"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "HIPAA § 164.530"
    ]
  },
  {
    "workflowId": "HR-WF-08",
    "templateKey": "HR-WF-08::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Supervisor → HR Director; Administrator for exec.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-027",
      "HR-FM-028",
      "HR-FM-029",
      "HR-FM-030"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-09",
    "templateKey": "HR-WF-09::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director reviews all actions; Administrator approves terminations; Legal reviews high-risk terminations.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-031",
      "HR-FM-032",
      "HR-FM-033",
      "HR-FM-034",
      "HR-FM-035"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-10",
    "templateKey": "HR-WF-10::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director approves leave; Legal consulted for complex cases.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-036",
      "HR-FM-037",
      "HR-FM-038",
      "HR-FM-039",
      "HR-FM-040",
      "HR-FM-041",
      "HR-FM-042"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-11",
    "templateKey": "HR-WF-11::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director approves; Legal for denials or undue hardship assertions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-042",
      "HR-FM-043",
      "HR-FM-044",
      "HR-FM-045"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-12",
    "templateKey": "HR-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director; Administrator for findings/actions; Legal for sensitive cases.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-033",
      "HR-FM-035",
      "HR-FM-046",
      "HR-FM-047",
      "HR-FM-048",
      "HR-FM-049",
      "HR-FM-050",
      "HR-FM-051"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-13",
    "templateKey": "HR-WF-13::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Risk Manager + HR Director + Administrator on serious incidents.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-023",
      "HR-FM-041",
      "HR-FM-052",
      "HR-FM-053",
      "HR-FM-054",
      "RM-FM-009",
      "RM-FM-014"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-14",
    "templateKey": "HR-WF-14::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director approves; Administrator for involuntary; Legal for complex.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-055",
      "HR-FM-056",
      "HR-FM-057",
      "HR-FM-058",
      "IT-FM-002"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-15",
    "templateKey": "HR-WF-15::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Administrator signs monthly attestation.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-022",
      "CO-FM-024",
      "CO-FM-033",
      "FN-FM-020",
      "GV-FM-005",
      "GV-FM-023",
      "HR-FM-005",
      "HR-FM-015",
      "HR-FM-016",
      "OP-FM-008"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-16",
    "templateKey": "HR-WF-16::annual",
    "cadence": {
      "kind": "event_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "HR Director + Legal + CFO; Administrator signs.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-040",
      "HR-FM-041",
      "HR-FM-042",
      "HR-FM-059",
      "HR-FM-060"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "HR-WF-17",
    "templateKey": "HR-WF-17::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Supervisor approves time; CFO approves payroll.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-024",
      "HR-FM-040",
      "HR-FM-041",
      "HR-FM-042",
      "HR-FM-061",
      "HR-FM-062",
      "HR-FM-063"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "IT-WF-01",
    "templateKey": "IT-WF-01::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator approves; Governing Body accepts plan.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "IT-FM-001",
      "IT-FM-002",
      "IT-FM-003"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-02",
    "templateKey": "IT-WF-02::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Department Manager; Security Officer for privileged.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-004",
      "IT-FM-005",
      "IT-FM-006",
      "IT-FM-007",
      "IT-FM-008",
      "IT-FM-009"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-03",
    "templateKey": "IT-WF-03::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "HR Director signs; Security Officer monitors.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-056",
      "IT-FM-010",
      "IT-FM-011",
      "IT-FM-012",
      "IT-FM-013"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-04",
    "templateKey": "IT-WF-04::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Managers attest; Security Officer signs summary.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "IT-FM-014",
      "IT-FM-015",
      "IT-FM-016"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-05",
    "templateKey": "IT-WF-05::annual",
    "cadence": {
      "kind": "event_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Security Officer policy; Admin receives annual attestation.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-009",
      "IT-FM-017",
      "IT-FM-018",
      "IT-FM-019"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-06",
    "templateKey": "IT-WF-06::monthly",
    "cadence": {
      "kind": "event_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Security Officer certifies monthly review; Admin briefed quarterly.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-020",
      "IT-FM-021",
      "IT-FM-022"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.312"
    ]
  },
  {
    "workflowId": "IT-WF-07",
    "templateKey": "IT-WF-07::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Security Officer signs test results; Admin accepts.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-003",
      "IT-FM-023",
      "IT-FM-024",
      "IT-FM-025"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-08",
    "templateKey": "IT-WF-08::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator approves plan; Governing Body acknowledges.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "IT-FM-026",
      "IT-FM-027",
      "IT-FM-028",
      "RM-FM-002",
      "RM-FM-003"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308",
      "42 CFR § 484.102"
    ]
  },
  {
    "workflowId": "IT-WF-09",
    "templateKey": "IT-WF-09::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer/CISO manages; Administrator approves disclosures; Legal approves regulator notifications.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-024",
      "CO-FM-029",
      "GV-FM-005",
      "GV-FM-023",
      "IT-FM-029",
      "IT-FM-030",
      "IT-FM-031",
      "IT-FM-032"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-10",
    "templateKey": "IT-WF-10::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer approves exception; HR confirms device return on separation.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-029",
      "IT-FM-001",
      "IT-FM-020",
      "IT-FM-024",
      "IT-FM-029",
      "IT-FM-036"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "IT-WF-11",
    "templateKey": "IT-WF-11::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer approves exceptions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-011",
      "IT-FM-029",
      "IT-FM-033"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.310"
    ]
  },
  {
    "workflowId": "IT-WF-12",
    "templateKey": "IT-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer approves exceptions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-021",
      "IT-FM-034",
      "IT-FM-036"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.310"
    ]
  },
  {
    "workflowId": "IT-WF-13",
    "templateKey": "IT-WF-13::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer approves exceptions & prioritization.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-023",
      "IT-FM-029",
      "IT-FM-032",
      "IT-FM-035",
      "IT-FM-036"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.308"
    ]
  },
  {
    "workflowId": "IT-WF-14",
    "templateKey": "IT-WF-14::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "CAB for normal; Security Officer + Admin for emergency.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-037",
      "IT-FM-038",
      "IT-FM-039"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "IT-WF-15",
    "templateKey": "IT-WF-15::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Security Officer approves posture; Administrator signs contract; Compliance on BAA.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-016",
      "CO-FM-029",
      "IT-FM-040",
      "IT-FM-041"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "IT-WF-16",
    "templateKey": "IT-WF-16::quarterly",
    "cadence": {
      "kind": "event_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Security Officer certifies configs; HR approves training results.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-029",
      "IT-FM-029",
      "IT-FM-042",
      "IT-FM-043"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.312"
    ]
  },
  {
    "workflowId": "IT-WF-17",
    "templateKey": "IT-WF-17::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer signs annual inventory reconciliation.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-001",
      "IT-FM-036",
      "IT-FM-044"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.310"
    ]
  },
  {
    "workflowId": "IT-WF-18",
    "templateKey": "IT-WF-18::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Security Officer signs exceptions (split tunnel, legacy client).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "IT-FM-004",
      "IT-FM-009",
      "IT-FM-010",
      "IT-FM-011",
      "IT-FM-017",
      "IT-FM-022"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.312"
    ]
  },
  {
    "workflowId": "IT-WF-19",
    "templateKey": "IT-WF-19::quarterly",
    "cadence": {
      "kind": "event_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator approves zones; Security Officer reviews quarterly.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-016",
      "HR-FM-056",
      "IT-FM-045",
      "IT-FM-046"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.310"
    ]
  },
  {
    "workflowId": "IT-WF-20",
    "templateKey": "IT-WF-20::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Privacy Officer signs; Legal for complex CCPA deletion.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-048",
      "IT-FM-047",
      "IT-FM-048",
      "IT-FM-049"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.524"
    ]
  },
  {
    "workflowId": "OP-WF-01",
    "templateKey": "OP-WF-01::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator approves quarterly review; Governing Body accepts.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-018",
      "EN-FM-022",
      "GV-FM-001",
      "GV-FM-005",
      "GV-FM-023",
      "OP-FM-001"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105"
    ]
  },
  {
    "workflowId": "OP-WF-02",
    "templateKey": "OP-WF-02::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator signs quarterly.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "OP-FM-002",
      "RM-FM-013",
      "RM-FM-014"
    ],
    "stepCount": 6,
    "declaredRisk": "high",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-03",
    "templateKey": "OP-WF-03::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Procurement / Administrator for standard; Governing Body for material; Compliance for BAA/Stark/AKS overlap.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-016",
      "CO-FM-017",
      "CO-FM-027",
      "GV-FM-018",
      "HR-FM-005",
      "IT-FM-028",
      "OP-FM-003",
      "OP-FM-004",
      "OP-FM-005",
      "OP-FM-006",
      "OP-FM-007",
      "OP-FM-008"
    ],
    "stepCount": 9,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(f)"
    ]
  },
  {
    "workflowId": "OP-WF-04",
    "templateKey": "OP-WF-04::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator signs list quarterly; exceptions approved in writing.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-018",
      "HR-FM-005",
      "OP-FM-005",
      "OP-FM-007"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-05",
    "templateKey": "OP-WF-05::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator authorizes; Governing Body ratifies.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-016",
      "GV-FM-005",
      "HR-FM-005",
      "OP-FM-004",
      "OP-FM-009"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-06",
    "templateKey": "OP-WF-06::daily",
    "cadence": {
      "kind": "event_based",
      "interval": "daily"
    },
    "approvals": [
      {
        "description": "Office Administrator responsible; Compliance for breach.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CO-FM-028",
      "OP-FM-010",
      "OP-FM-011",
      "OP-FM-012",
      "OP-FM-013"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "45 CFR § 164.530"
    ]
  },
  {
    "workflowId": "OP-WF-07",
    "templateKey": "OP-WF-07::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves clinical acceptance; Insurance Verifier certifies coverage.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-027",
      "CL-FM-029",
      "CL-FM-055",
      "CO-FM-019",
      "FN-FM-004",
      "OP-FM-014",
      "OP-FM-018"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-08",
    "templateKey": "OP-WF-08::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves each non-admit.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-016",
      "OP-FM-015"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(i)(1)"
    ]
  },
  {
    "workflowId": "OP-WF-09",
    "templateKey": "OP-WF-09::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "HR verifies; Administrator signs on incidents.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-006",
      "HR-FM-023",
      "HR-FM-027",
      "OP-FM-016",
      "RM-FM-009"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-10",
    "templateKey": "OP-WF-10::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves custody exceptions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "OP-FM-017",
      "RM-FM-015"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-11",
    "templateKey": "OP-WF-11::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager ensures availability; Administrator approves vendor list.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "OP-FM-014",
      "OP-FM-018"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.50(a)"
    ]
  },
  {
    "workflowId": "OP-WF-12",
    "templateKey": "OP-WF-12::daily",
    "cadence": {
      "kind": "event_based",
      "interval": "daily"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews staffing; Administrator approves overtime/contract clinician usage.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-019",
      "OP-FM-019",
      "QA-FM-007"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "OP-WF-13",
    "templateKey": "OP-WF-13::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews daily; Administrator briefed on severe events.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "OP-FM-020"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.105(f)"
    ]
  },
  {
    "workflowId": "QA-WF-01",
    "templateKey": "QA-WF-01::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Governing Body approves annually. Committee approves in-year amendments; Governing Body ratifies material changes.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-007",
      "EN-FM-008",
      "GV-FM-005",
      "HR-FM-017",
      "QA-FM-001",
      "QA-FM-010"
    ],
    "stepCount": 7,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.65(a)"
    ]
  },
  {
    "workflowId": "QA-WF-02",
    "templateKey": "QA-WF-02::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "QAPI Lead signs monthly dashboard; Committee reviews quarterly (QA-WF-03).",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-045",
      "QA-FM-003",
      "QA-FM-004",
      "QA-FM-006",
      "QA-FM-007"
    ],
    "stepCount": 7,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.65(b)"
    ]
  },
  {
    "workflowId": "QA-WF-03",
    "templateKey": "QA-WF-03::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Committee majority; Governing Body reviews at next quarterly meeting (GV-WF-01).",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-023",
      "QA-FM-001",
      "QA-FM-002",
      "QA-FM-003",
      "QA-FM-004",
      "QA-FM-005",
      "QA-FM-006"
    ],
    "stepCount": 8,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.65(b)(3)"
    ]
  },
  {
    "workflowId": "QA-WF-04",
    "templateKey": "QA-WF-04::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Committee approves charter and closure; Governing Body signs off on closure and sustainment.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-001",
      "QA-FM-002",
      "QA-FM-003",
      "QA-FM-004",
      "QA-FM-005"
    ],
    "stepCount": 12,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.65(d)"
    ]
  },
  {
    "workflowId": "QA-WF-05",
    "templateKey": "QA-WF-05::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Committee approves RCA and CAP; Governing Body reviews sentinel events.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CL-FM-030",
      "CL-FM-049",
      "GV-FM-005",
      "QA-FM-001",
      "QA-FM-004",
      "QA-FM-005",
      "QA-FM-012",
      "QA-FM-013"
    ],
    "stepCount": 11,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.65(b)(1)(ii)"
    ]
  },
  {
    "workflowId": "QA-WF-06",
    "templateKey": "QA-WF-06::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "IP leads; Committee reviews trends and PIP decisions.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-021",
      "CL-FM-047",
      "GV-FM-023",
      "QA-FM-001",
      "QA-FM-002",
      "QA-FM-003",
      "QA-FM-006",
      "RM-FM-006"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.70"
    ]
  },
  {
    "workflowId": "QA-WF-07",
    "templateKey": "QA-WF-07::daily",
    "cadence": {
      "kind": "event_based",
      "interval": "daily"
    },
    "approvals": [
      {
        "description": "Clinical Manager for clinical frequency changes; Finance for financial impact sign-off.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-011",
      "CL-FM-012",
      "CO-FM-004",
      "FN-FM-009",
      "FN-FM-010",
      "QA-FM-003",
      "QA-FM-007"
    ],
    "stepCount": 7,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.215"
    ]
  },
  {
    "workflowId": "QA-WF-08",
    "templateKey": "QA-WF-08::monthly",
    "cadence": {
      "kind": "time_based",
      "interval": "monthly"
    },
    "approvals": [
      {
        "description": "Administrator approves exemption decision; Governing Body informed.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "QA-FM-002",
      "QA-FM-003",
      "QA-FM-008"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.245(b)(1)(iii)"
    ]
  },
  {
    "workflowId": "QA-WF-09",
    "templateKey": "QA-WF-09::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "QAPI Committee approves action plan; Governing Body briefed.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-023",
      "QA-FM-001",
      "QA-FM-002",
      "QA-FM-009",
      "QA-FM-011"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.245"
    ]
  },
  {
    "workflowId": "QA-WF-10",
    "templateKey": "QA-WF-10::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Committee and Governing Body annually.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-007",
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-001",
      "QA-FM-010"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.65(e)"
    ]
  },
  {
    "workflowId": "QA-WF-11",
    "templateKey": "QA-WF-11::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Committee approves closure or reopening.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "QA-FM-001",
      "QA-FM-005",
      "QA-FM-012"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "QA-WF-12",
    "templateKey": "QA-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator + Legal before disclosure; Board informed.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-049",
      "CL-FM-053",
      "GV-FM-005",
      "QA-FM-013"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.50"
    ]
  },
  {
    "workflowId": "RM-WF-01",
    "templateKey": "RM-WF-01::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Administrator approves register quarterly; Governing Body accepts annual reassessment.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-001",
      "RM-FM-008",
      "RM-FM-016",
      "RM-FM-017"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "RM-WF-02",
    "templateKey": "RM-WF-02::biennial",
    "cadence": {
      "kind": "time_based",
      "interval": "biennial"
    },
    "approvals": [
      {
        "description": "Administrator approves; Governing Body reviews.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "RM-FM-001",
      "RM-FM-008"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.102(a)"
    ]
  },
  {
    "workflowId": "RM-WF-03",
    "templateKey": "RM-WF-03::biennial",
    "cadence": {
      "kind": "time_based",
      "interval": "biennial"
    },
    "approvals": [
      {
        "description": "Administrator signs; Governing Body approves versioned plan.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "EN-FM-007",
      "EN-FM-008",
      "EN-FM-009",
      "GV-FM-005",
      "RM-FM-001",
      "RM-FM-002",
      "RM-FM-003"
    ],
    "stepCount": 8,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.102(a)"
    ]
  },
  {
    "workflowId": "RM-WF-04",
    "templateKey": "RM-WF-04::biennial",
    "cadence": {
      "kind": "event_based",
      "interval": "biennial"
    },
    "approvals": [
      {
        "description": "EP Coord certifies completion; HR enforces discipline for non-completion.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "HR-FM-017",
      "HR-FM-030"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.102(d)(1)"
    ]
  },
  {
    "workflowId": "RM-WF-05",
    "templateKey": "RM-WF-05::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "EP Coord signs AAR; Administrator reviews; Board briefed.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-007",
      "EN-FM-008",
      "GV-FM-005",
      "GV-FM-023",
      "QA-FM-005",
      "RM-FM-004",
      "RM-FM-005"
    ],
    "stepCount": 10,
    "declaredRisk": "immediate_jeopardy",
    "regulatoryAnchors": [
      "42 CFR § 484.102(d)(2)"
    ]
  },
  {
    "workflowId": "RM-WF-06",
    "templateKey": "RM-WF-06::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator approves activation; Governing Body briefed on activation.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "OP-FM-005",
      "RM-FM-006"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.102"
    ]
  },
  {
    "workflowId": "RM-WF-07",
    "templateKey": "RM-WF-07::episodic",
    "cadence": {
      "kind": "event_based",
      "interval": "episodic"
    },
    "approvals": [
      {
        "description": "Clinical Manager signs classifications periodically; EP Coord approves activation procedures.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-001",
      "CL-FM-048",
      "RM-FM-002",
      "RM-FM-005",
      "RM-FM-007"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.102(b)"
    ]
  },
  {
    "workflowId": "RM-WF-08",
    "templateKey": "RM-WF-08::quarterly",
    "cadence": {
      "kind": "time_based",
      "interval": "quarterly"
    },
    "approvals": [
      {
        "description": "Risk Manager signs; Administrator approves annual review; Governing Body briefed.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "HR-FM-014",
      "HR-FM-017",
      "HR-FM-022",
      "HR-FM-023",
      "RM-FM-013",
      "RM-FM-014",
      "RM-FM-018"
    ],
    "stepCount": 7,
    "declaredRisk": "high",
    "regulatoryAnchors": [
      "CCR § 3203"
    ]
  },
  {
    "workflowId": "RM-WF-09",
    "templateKey": "RM-WF-09::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator approves WVPP; Risk Manager signs investigations and annual review.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-019",
      "HR-FM-017",
      "HR-FM-036",
      "RM-FM-009",
      "RM-FM-018"
    ],
    "stepCount": 9,
    "declaredRisk": "high",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "RM-WF-10",
    "templateKey": "RM-WF-10::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator signs annual 300A; Risk Manager responsible for entries.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "EN-FM-019",
      "HR-FM-013",
      "HR-FM-014",
      "HR-FM-021",
      "HR-FM-022",
      "HR-FM-023"
    ],
    "stepCount": 8,
    "declaredRisk": "high",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "RM-WF-11",
    "templateKey": "RM-WF-11::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Administrator approves inventory annually; Risk Manager signs spill response closeouts.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "HR-FM-017",
      "OP-FM-005",
      "RM-FM-010"
    ],
    "stepCount": 5,
    "declaredRisk": "high",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "RM-WF-12",
    "templateKey": "RM-WF-12::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager approves replacement protocol; Administrator signs MDR reports.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "QA-FM-001",
      "RM-FM-011"
    ],
    "stepCount": 6,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "RM-WF-13",
    "templateKey": "RM-WF-13::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Clinical Manager reviews high-alert protocol annually; Pharmacy consultant concurs.",
        "requiresGoverningBody": false
      }
    ],
    "requiredForms": [
      "CL-FM-018",
      "CL-FM-019",
      "QA-FM-004",
      "RM-FM-012"
    ],
    "stepCount": 4,
    "declaredRisk": "moderate",
    "regulatoryAnchors": [
      "42 CFR § 484.60"
    ]
  },
  {
    "workflowId": "RM-WF-14",
    "templateKey": "RM-WF-14::per_event",
    "cadence": {
      "kind": "event_based",
      "interval": "per_event"
    },
    "approvals": [
      {
        "description": "Administrator + Legal for strategy; Governing Body for settlements above threshold.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "CO-FM-033",
      "GV-FM-005",
      "QA-FM-001",
      "RM-FM-015"
    ],
    "stepCount": 8,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  },
  {
    "workflowId": "RM-WF-15",
    "templateKey": "RM-WF-15::annual",
    "cadence": {
      "kind": "time_based",
      "interval": "annual"
    },
    "approvals": [
      {
        "description": "Governing Body approves risk appetite, top risks, and resource allocation.",
        "requiresGoverningBody": true
      }
    ],
    "requiredForms": [
      "GV-FM-005",
      "GV-FM-023",
      "RM-FM-008",
      "RM-FM-016"
    ],
    "stepCount": 5,
    "declaredRisk": "moderate",
    "regulatoryAnchors": []
  }
] as unknown as WorkflowTemplate[];

export const WORKFLOW_TEMPLATE_BY_ID: Record<string, WorkflowTemplate> = Object.fromEntries(
  WORKFLOW_TEMPLATES.map((t) => [t.workflowId, t]),
);
