/* AUTO-GENERATED by scripts/compileWorkflows.ts. */
import type { WorkflowGraph } from '@/policy/types/workflow';

export const WORKFLOW_GRAPH: WorkflowGraph = {
  "workflowIds": [
    "CL-WF-26",
    "CL-WF-27",
    "CL-WF-28",
    "CL-WF-29",
    "CL-WF-30",
    "CL-WF-31",
    "CL-WF-32",
    "CL-WF-33",
    "CL-WF-34",
    "CL-WF-35",
    "CL-WF-36",
    "CL-WF-37",
    "CL-WF-01",
    "CL-WF-02",
    "CL-WF-03",
    "CL-WF-04",
    "CL-WF-05",
    "CL-WF-06",
    "CL-WF-07",
    "CL-WF-08",
    "CL-WF-09",
    "CL-WF-10",
    "CL-WF-11",
    "CL-WF-12",
    "CL-WF-13",
    "CL-WF-14",
    "CL-WF-15",
    "CL-WF-16",
    "CL-WF-17",
    "CL-WF-18",
    "CL-WF-19",
    "CL-WF-20",
    "CL-WF-21",
    "CL-WF-22",
    "CL-WF-23",
    "CL-WF-24",
    "CL-WF-25",
    "CO-WF-23",
    "CO-WF-24",
    "CO-WF-25",
    "CO-WF-26",
    "CO-WF-27",
    "CO-WF-28",
    "CO-WF-29",
    "CO-WF-30",
    "CO-WF-01",
    "CO-WF-02",
    "CO-WF-03",
    "CO-WF-04",
    "CO-WF-05",
    "CO-WF-06",
    "CO-WF-07",
    "CO-WF-08",
    "CO-WF-09",
    "CO-WF-10",
    "CO-WF-11",
    "CO-WF-12",
    "CO-WF-13",
    "CO-WF-14",
    "CO-WF-15",
    "CO-WF-16",
    "CO-WF-17",
    "CO-WF-18",
    "CO-WF-19",
    "CO-WF-20",
    "CO-WF-21",
    "CO-WF-22",
    "EN-WF-01",
    "EN-WF-02",
    "EN-WF-03",
    "EN-WF-04",
    "EN-WF-05",
    "EN-WF-06",
    "EN-WF-07",
    "EN-WF-08",
    "EN-WF-09",
    "EN-WF-10",
    "EN-WF-11",
    "EN-WF-12",
    "EN-WF-13",
    "FN-WF-01",
    "FN-WF-02",
    "FN-WF-03",
    "FN-WF-04",
    "FN-WF-05",
    "FN-WF-06",
    "FN-WF-07",
    "FN-WF-08",
    "FN-WF-09",
    "FN-WF-10",
    "FN-WF-11",
    "FN-WF-12",
    "FN-WF-13",
    "FN-WF-14",
    "FN-WF-15",
    "GV-WF-01",
    "GV-WF-02",
    "GV-WF-03",
    "GV-WF-04",
    "GV-WF-05",
    "GV-WF-06",
    "GV-WF-07",
    "GV-WF-08",
    "GV-WF-09",
    "GV-WF-10",
    "GV-WF-11",
    "GV-WF-12",
    "GV-WF-13",
    "GV-WF-14",
    "HR-WF-18",
    "HR-WF-19",
    "HR-WF-20",
    "HR-WF-21",
    "HR-WF-01",
    "HR-WF-02",
    "HR-WF-03",
    "HR-WF-04",
    "HR-WF-05",
    "HR-WF-06",
    "HR-WF-07",
    "HR-WF-08",
    "HR-WF-09",
    "HR-WF-10",
    "HR-WF-11",
    "HR-WF-12",
    "HR-WF-13",
    "HR-WF-14",
    "HR-WF-15",
    "HR-WF-16",
    "HR-WF-17",
    "IT-WF-21",
    "IT-WF-22",
    "IT-WF-23",
    "IT-WF-24",
    "IT-WF-25",
    "IT-WF-01",
    "IT-WF-02",
    "IT-WF-03",
    "IT-WF-04",
    "IT-WF-05",
    "IT-WF-06",
    "IT-WF-07",
    "IT-WF-08",
    "IT-WF-09",
    "IT-WF-10",
    "IT-WF-11",
    "IT-WF-12",
    "IT-WF-13",
    "IT-WF-14",
    "IT-WF-15",
    "IT-WF-16",
    "IT-WF-17",
    "IT-WF-18",
    "IT-WF-19",
    "IT-WF-20",
    "OP-WF-01",
    "OP-WF-02",
    "OP-WF-03",
    "OP-WF-04",
    "OP-WF-05",
    "OP-WF-06",
    "OP-WF-07",
    "OP-WF-08",
    "OP-WF-09",
    "OP-WF-10",
    "OP-WF-11",
    "OP-WF-12",
    "OP-WF-13",
    "QA-WF-13",
    "QA-WF-14",
    "QA-WF-15",
    "QA-WF-16",
    "QA-WF-17",
    "QA-WF-18",
    "QA-WF-01",
    "QA-WF-02",
    "QA-WF-03",
    "QA-WF-04",
    "QA-WF-05",
    "QA-WF-06",
    "QA-WF-07",
    "QA-WF-08",
    "QA-WF-09",
    "QA-WF-10",
    "QA-WF-11",
    "QA-WF-12",
    "RM-WF-16",
    "RM-WF-17",
    "RM-WF-18",
    "RM-WF-19",
    "RM-WF-20",
    "RM-WF-01",
    "RM-WF-02",
    "RM-WF-03",
    "RM-WF-04",
    "RM-WF-05",
    "RM-WF-06",
    "RM-WF-07",
    "RM-WF-08",
    "RM-WF-09",
    "RM-WF-10",
    "RM-WF-11",
    "RM-WF-12",
    "RM-WF-13",
    "RM-WF-14",
    "RM-WF-15"
  ],
  "byForm": {
    "CL-FM-005": [
      "CL-WF-26",
      "CL-WF-30",
      "CL-WF-33",
      "CL-WF-04",
      "CL-WF-06",
      "CL-WF-15",
      "CL-WF-18",
      "CL-WF-24",
      "CO-WF-23"
    ],
    "CO-FM-021": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-37",
      "CL-WF-02",
      "CL-WF-03",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-28",
      "CO-WF-29",
      "CO-WF-14",
      "QA-WF-16",
      "QA-WF-17"
    ],
    "CO-FM-022": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-31",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-35",
      "CL-WF-36",
      "CL-WF-37",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-28",
      "CO-WF-29",
      "CO-WF-04",
      "EN-WF-12",
      "FN-WF-08",
      "FN-WF-15",
      "HR-WF-21",
      "HR-WF-15",
      "IT-WF-21",
      "IT-WF-22",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-20"
    ],
    "CO-FM-024": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-35",
      "CL-WF-36",
      "CL-WF-37",
      "CL-WF-23",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-27",
      "CO-WF-28",
      "CO-WF-29",
      "CO-WF-30",
      "CO-WF-01",
      "CO-WF-02",
      "CO-WF-03",
      "CO-WF-04",
      "CO-WF-06",
      "CO-WF-08",
      "CO-WF-09",
      "CO-WF-10",
      "CO-WF-14",
      "CO-WF-18",
      "CO-WF-20",
      "EN-WF-01",
      "EN-WF-08",
      "EN-WF-12",
      "FN-WF-08",
      "FN-WF-15",
      "GV-WF-01",
      "HR-WF-18",
      "HR-WF-19",
      "HR-WF-20",
      "HR-WF-21",
      "HR-WF-07",
      "HR-WF-15",
      "IT-WF-21",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25",
      "IT-WF-09",
      "QA-WF-16",
      "QA-WF-17",
      "QA-WF-18",
      "QA-WF-03",
      "RM-WF-16",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-20"
    ],
    "QA-FM-005": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-33",
      "CL-WF-36",
      "CL-WF-37",
      "CL-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-27",
      "CO-WF-29",
      "CO-WF-30",
      "CO-WF-03",
      "CO-WF-04",
      "CO-WF-05",
      "CO-WF-20",
      "FN-WF-08",
      "FN-WF-13",
      "HR-WF-21",
      "IT-WF-24",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-05",
      "QA-WF-11",
      "RM-WF-16",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-20",
      "RM-WF-05"
    ],
    "QA-FM-025": [
      "CL-WF-26"
    ],
    "CL-FM-002": [
      "CL-WF-27",
      "CL-WF-04",
      "CL-WF-05",
      "CL-WF-18",
      "CL-WF-19",
      "CO-WF-23",
      "CO-WF-24"
    ],
    "CL-FM-031": [
      "CL-WF-27",
      "CL-WF-04",
      "CL-WF-05"
    ],
    "FN-FM-006": [
      "CL-WF-27",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-29",
      "CO-WF-04",
      "CO-WF-14",
      "CO-WF-15",
      "CO-WF-16",
      "FN-WF-03"
    ],
    "HR-FM-016": [
      "CL-WF-27",
      "CL-WF-25",
      "CO-WF-26",
      "HR-WF-19",
      "HR-WF-04",
      "HR-WF-15"
    ],
    "CL-FM-015": [
      "CL-WF-28",
      "CL-WF-10"
    ],
    "CL-FM-029": [
      "CL-WF-29",
      "CL-WF-01",
      "CL-WF-04",
      "CL-WF-13",
      "CL-WF-16",
      "OP-WF-07"
    ],
    "CL-FM-036": [
      "CL-WF-29",
      "CL-WF-19",
      "GV-WF-10"
    ],
    "CL-FM-009": [
      "CL-WF-30",
      "CL-WF-01",
      "CL-WF-02",
      "CL-WF-04"
    ],
    "CL-FM-018": [
      "CL-WF-31",
      "CL-WF-12",
      "RM-WF-13"
    ],
    "CL-FM-022": [
      "CL-WF-31",
      "CL-WF-12",
      "CL-WF-17"
    ],
    "RM-FM-012": [
      "CL-WF-31",
      "CL-WF-12",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-13"
    ],
    "CL-FM-021": [
      "CL-WF-32",
      "CL-WF-14",
      "QA-WF-06",
      "RM-WF-17"
    ],
    "HR-FM-014": [
      "CL-WF-32",
      "CL-WF-14",
      "HR-WF-03",
      "RM-WF-08",
      "RM-WF-10"
    ],
    "QA-FM-027": [
      "CL-WF-32"
    ],
    "CL-FM-053": [
      "CL-WF-33",
      "CL-WF-36",
      "CL-WF-08",
      "CL-WF-20",
      "CL-WF-22",
      "CL-WF-24",
      "QA-WF-12"
    ],
    "CL-FM-054": [
      "CL-WF-33",
      "CL-WF-08",
      "CL-WF-24"
    ],
    "EN-FM-034": [
      "CL-WF-34",
      "CL-WF-35",
      "CL-WF-36",
      "CO-WF-27",
      "EN-WF-10",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "RM-WF-16"
    ],
    "QA-FM-021": [
      "CL-WF-34",
      "CL-WF-35",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-17",
      "QA-WF-03"
    ],
    "QA-FM-026": [
      "CL-WF-34",
      "RM-WF-16",
      "RM-WF-20"
    ],
    "QA-FM-020": [
      "CL-WF-35",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-17"
    ],
    "CL-FM-048": [
      "CL-WF-36",
      "CL-WF-20",
      "IT-WF-20",
      "RM-WF-07"
    ],
    "CL-FM-006": [
      "CL-WF-37",
      "CL-WF-01",
      "CL-WF-07",
      "CL-WF-12",
      "CL-WF-15"
    ],
    "CL-FM-007": [
      "CL-WF-37",
      "CL-WF-07",
      "CL-WF-12"
    ],
    "CL-FM-025": [
      "CL-WF-01",
      "CL-WF-15"
    ],
    "CL-FM-027": [
      "CL-WF-01",
      "CL-WF-04",
      "CL-WF-16",
      "OP-WF-07"
    ],
    "CL-FM-050": [
      "CL-WF-01",
      "CL-WF-05",
      "CL-WF-21"
    ],
    "GV-FM-016": [
      "CL-WF-01",
      "GV-WF-06",
      "GV-WF-07",
      "OP-WF-08"
    ],
    "OP-FM-014": [
      "CL-WF-01",
      "CO-WF-28",
      "OP-WF-07",
      "OP-WF-11"
    ],
    "OP-FM-015": [
      "CL-WF-01",
      "GV-WF-06",
      "OP-WF-08"
    ],
    "OP-FM-018": [
      "CL-WF-01",
      "CL-WF-17",
      "OP-WF-07",
      "OP-WF-11",
      "RM-WF-17"
    ],
    "CL-FM-010": [
      "CL-WF-03",
      "CO-WF-23"
    ],
    "CL-FM-001": [
      "CL-WF-04",
      "RM-WF-07"
    ],
    "CL-FM-019": [
      "CL-WF-04",
      "CL-WF-12",
      "RM-WF-13"
    ],
    "CL-FM-020": [
      "CL-WF-04"
    ],
    "CL-FM-026": [
      "CL-WF-04",
      "CL-WF-09",
      "CL-WF-13"
    ],
    "CL-FM-038": [
      "CL-WF-04"
    ],
    "CL-FM-039": [
      "CL-WF-04",
      "CL-WF-09",
      "CL-WF-24"
    ],
    "CL-FM-041": [
      "CL-WF-04",
      "CL-WF-09"
    ],
    "CL-FM-047": [
      "CL-WF-04",
      "CL-WF-24",
      "QA-WF-06"
    ],
    "CL-FM-032": [
      "CL-WF-05"
    ],
    "CL-FM-045": [
      "CL-WF-05",
      "CL-WF-18",
      "CL-WF-19",
      "QA-WF-02"
    ],
    "CL-FM-051": [
      "CL-WF-05",
      "CL-WF-25",
      "HR-WF-19"
    ],
    "CL-FM-008": [
      "CL-WF-06",
      "CL-WF-07"
    ],
    "CL-FM-035": [
      "CL-WF-06",
      "CL-WF-08"
    ],
    "CL-FM-044": [
      "CL-WF-06",
      "CL-WF-18"
    ],
    "CL-FM-057": [
      "CL-WF-06",
      "CL-WF-18"
    ],
    "CL-FM-013": [
      "CL-WF-09",
      "CL-WF-21"
    ],
    "CL-FM-014": [
      "CL-WF-09",
      "HR-WF-05"
    ],
    "CL-FM-017": [
      "CL-WF-09",
      "CL-WF-13",
      "CL-WF-16"
    ],
    "CL-FM-023": [
      "CL-WF-09",
      "CL-WF-13"
    ],
    "CL-FM-024": [
      "CL-WF-09",
      "CL-WF-13"
    ],
    "CL-FM-033": [
      "CL-WF-09",
      "CL-WF-21",
      "CO-WF-14"
    ],
    "CL-FM-034": [
      "CL-WF-09",
      "CL-WF-21",
      "CL-WF-25",
      "CO-WF-14"
    ],
    "CL-FM-040": [
      "CL-WF-09",
      "CL-WF-13"
    ],
    "CL-FM-016": [
      "CL-WF-10",
      "CL-WF-11",
      "CL-WF-25"
    ],
    "CL-FM-042": [
      "CL-WF-10"
    ],
    "HR-FM-017": [
      "CL-WF-10",
      "CL-WF-11",
      "CL-WF-14",
      "CO-WF-06",
      "CO-WF-14",
      "GV-WF-06",
      "HR-WF-18",
      "HR-WF-05",
      "HR-WF-07",
      "QA-WF-01",
      "RM-WF-19",
      "RM-WF-04",
      "RM-WF-08",
      "RM-WF-09",
      "RM-WF-11"
    ],
    "HR-FM-031": [
      "CL-WF-10",
      "GV-WF-04",
      "HR-WF-09"
    ],
    "HR-FM-038": [
      "CL-WF-10",
      "CL-WF-25",
      "HR-WF-10"
    ],
    "HR-FM-024": [
      "CL-WF-11",
      "FN-WF-12",
      "HR-WF-17"
    ],
    "CL-FM-037": [
      "CL-WF-13",
      "CL-WF-24"
    ],
    "HR-FM-021": [
      "CL-WF-14",
      "HR-WF-06",
      "RM-WF-10"
    ],
    "QA-FM-006": [
      "CL-WF-14",
      "FN-WF-05",
      "QA-WF-02",
      "QA-WF-03",
      "QA-WF-06"
    ],
    "CL-FM-011": [
      "CL-WF-15",
      "CL-WF-20",
      "QA-WF-07"
    ],
    "CO-FM-016": [
      "CL-WF-15",
      "CO-WF-11",
      "CO-WF-18",
      "GV-WF-11",
      "IT-WF-15",
      "IT-WF-19",
      "OP-WF-03",
      "OP-WF-05"
    ],
    "IT-FM-020": [
      "CL-WF-15",
      "IT-WF-06",
      "IT-WF-10"
    ],
    "CL-FM-028": [
      "CL-WF-16"
    ],
    "CL-FM-052": [
      "CL-WF-16"
    ],
    "CO-FM-019": [
      "CL-WF-16",
      "CO-WF-12",
      "CO-WF-21",
      "EN-WF-11",
      "FN-WF-15",
      "OP-WF-07"
    ],
    "OP-FM-017": [
      "CL-WF-16",
      "OP-WF-10"
    ],
    "CL-FM-046": [
      "CL-WF-17",
      "CL-WF-24"
    ],
    "CL-FM-003": [
      "CL-WF-18"
    ],
    "CL-FM-004": [
      "CL-WF-19"
    ],
    "CL-FM-012": [
      "CL-WF-20",
      "QA-WF-07"
    ],
    "CO-FM-038": [
      "CL-WF-21",
      "CO-WF-04",
      "CO-WF-14"
    ],
    "CL-FM-030": [
      "CL-WF-22",
      "QA-WF-05"
    ],
    "HR-FM-033": [
      "CL-WF-22",
      "HR-WF-09",
      "HR-WF-12"
    ],
    "QA-FM-004": [
      "CL-WF-22",
      "QA-WF-02",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-05",
      "RM-WF-13"
    ],
    "CL-FM-049": [
      "CL-WF-23",
      "QA-WF-05",
      "QA-WF-12"
    ],
    "GV-FM-005": [
      "CL-WF-23",
      "CO-WF-01",
      "CO-WF-04",
      "CO-WF-05",
      "CO-WF-06",
      "CO-WF-10",
      "CO-WF-16",
      "CO-WF-17",
      "CO-WF-18",
      "CO-WF-22",
      "EN-WF-01",
      "EN-WF-12",
      "EN-WF-13",
      "FN-WF-01",
      "FN-WF-02",
      "FN-WF-08",
      "FN-WF-13",
      "GV-WF-01",
      "GV-WF-02",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-05",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-08",
      "GV-WF-09",
      "GV-WF-10",
      "GV-WF-11",
      "GV-WF-14",
      "HR-WF-04",
      "HR-WF-07",
      "HR-WF-15",
      "IT-WF-01",
      "IT-WF-04",
      "IT-WF-09",
      "OP-WF-01",
      "OP-WF-05",
      "QA-WF-01",
      "QA-WF-04",
      "QA-WF-05",
      "QA-WF-08",
      "QA-WF-10",
      "QA-WF-12",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-06",
      "RM-WF-08",
      "RM-WF-14",
      "RM-WF-15"
    ],
    "GV-FM-023": [
      "CL-WF-23",
      "CO-WF-27",
      "CO-WF-01",
      "CO-WF-04",
      "CO-WF-05",
      "CO-WF-17",
      "CO-WF-19",
      "CO-WF-20",
      "CO-WF-22",
      "EN-WF-02",
      "EN-WF-03",
      "EN-WF-04",
      "EN-WF-05",
      "EN-WF-09",
      "EN-WF-10",
      "EN-WF-11",
      "EN-WF-12",
      "FN-WF-01",
      "FN-WF-02",
      "FN-WF-08",
      "GV-WF-01",
      "GV-WF-08",
      "GV-WF-09",
      "HR-WF-04",
      "HR-WF-07",
      "HR-WF-15",
      "IT-WF-01",
      "IT-WF-04",
      "IT-WF-09",
      "IT-WF-13",
      "OP-WF-01",
      "QA-WF-17",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-06",
      "QA-WF-09",
      "QA-WF-10",
      "RM-WF-19",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-08",
      "RM-WF-15"
    ],
    "QA-FM-001": [
      "CL-WF-23",
      "EN-WF-01",
      "QA-WF-01",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-05",
      "QA-WF-06",
      "QA-WF-09",
      "QA-WF-10",
      "QA-WF-11",
      "RM-WF-01",
      "RM-WF-12",
      "RM-WF-14"
    ],
    "QA-FM-003": [
      "CL-WF-23",
      "GV-WF-01",
      "QA-WF-02",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-06",
      "QA-WF-07",
      "QA-WF-08"
    ],
    "CL-FM-055": [
      "CL-WF-24",
      "OP-WF-07"
    ],
    "CL-FM-056": [
      "CL-WF-25"
    ],
    "HR-FM-007": [
      "CL-WF-25",
      "CO-WF-08",
      "CO-WF-09",
      "GV-WF-03",
      "GV-WF-04",
      "HR-WF-02"
    ],
    "CO-FM-003": [
      "CO-WF-27",
      "CO-WF-03"
    ],
    "CO-FM-004": [
      "CO-WF-27",
      "CO-WF-03",
      "CO-WF-08",
      "CO-WF-10",
      "CO-WF-21",
      "QA-WF-07"
    ],
    "HR-FM-005": [
      "CO-WF-27",
      "CO-WF-15",
      "FN-WF-11",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-11",
      "HR-WF-20",
      "HR-WF-02",
      "HR-WF-15",
      "OP-WF-03",
      "OP-WF-04",
      "OP-WF-05"
    ],
    "EN-FM-019": [
      "CO-WF-30",
      "CO-WF-03",
      "CO-WF-04",
      "CO-WF-05",
      "CO-WF-10",
      "CO-WF-16",
      "CO-WF-17",
      "CO-WF-19",
      "EN-WF-07",
      "QA-WF-18",
      "RM-WF-09",
      "RM-WF-10"
    ],
    "QA-FM-022": [
      "CO-WF-30"
    ],
    "CO-FM-001": [
      "CO-WF-01",
      "CO-WF-15"
    ],
    "CO-FM-005": [
      "CO-WF-01",
      "CO-WF-04"
    ],
    "CO-FM-032": [
      "CO-WF-01",
      "CO-WF-04",
      "FN-WF-15"
    ],
    "EN-FM-022": [
      "CO-WF-01",
      "CO-WF-20",
      "CO-WF-22",
      "EN-WF-08",
      "HR-WF-18",
      "HR-WF-19",
      "OP-WF-01",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-18",
      "QA-WF-03"
    ],
    "CO-FM-002": [
      "CO-WF-02"
    ],
    "EN-FM-001": [
      "CO-WF-02",
      "CO-WF-09",
      "EN-WF-01",
      "EN-WF-03",
      "GV-WF-13",
      "HR-WF-03"
    ],
    "EN-FM-014": [
      "CO-WF-02",
      "EN-WF-05"
    ],
    "HR-FM-009": [
      "CO-WF-02",
      "CO-WF-03",
      "HR-WF-18",
      "HR-WF-20",
      "HR-WF-02",
      "IT-WF-23"
    ],
    "HR-FM-010": [
      "CO-WF-03",
      "HR-WF-03"
    ],
    "CO-FM-006": [
      "CO-WF-05"
    ],
    "CO-FM-007": [
      "CO-WF-05"
    ],
    "CO-FM-008": [
      "CO-WF-05",
      "HR-WF-07"
    ],
    "CO-FM-034": [
      "CO-WF-05",
      "CO-WF-19"
    ],
    "CO-FM-009": [
      "CO-WF-06",
      "CO-WF-20",
      "HR-WF-03",
      "HR-WF-07"
    ],
    "CO-FM-028": [
      "CO-WF-06",
      "CO-WF-10",
      "OP-WF-06"
    ],
    "EN-FM-005": [
      "CO-WF-06",
      "EN-WF-01"
    ],
    "EN-FM-006": [
      "CO-WF-06",
      "EN-WF-01"
    ],
    "EN-FM-007": [
      "CO-WF-06",
      "EN-WF-01",
      "QA-WF-18",
      "QA-WF-01",
      "QA-WF-10",
      "RM-WF-03",
      "RM-WF-05"
    ],
    "EN-FM-008": [
      "CO-WF-06",
      "EN-WF-01",
      "EN-WF-02",
      "GV-WF-01",
      "QA-WF-01",
      "RM-WF-03",
      "RM-WF-05"
    ],
    "EN-FM-009": [
      "CO-WF-06",
      "EN-WF-01",
      "EN-WF-02",
      "RM-WF-03"
    ],
    "CO-FM-010": [
      "CO-WF-07",
      "GV-WF-11"
    ],
    "CO-FM-011": [
      "CO-WF-07",
      "GV-WF-08",
      "GV-WF-11"
    ],
    "CO-FM-037": [
      "CO-WF-07",
      "CO-WF-08"
    ],
    "GV-FM-018": [
      "CO-WF-07",
      "CO-WF-11",
      "GV-WF-11",
      "OP-WF-03",
      "OP-WF-04"
    ],
    "CO-FM-012": [
      "CO-WF-08"
    ],
    "FN-FM-011": [
      "CO-WF-08",
      "FN-WF-04",
      "FN-WF-09",
      "FN-WF-11",
      "FN-WF-12",
      "GV-WF-01",
      "GV-WF-05"
    ],
    "CO-FM-013": [
      "CO-WF-09"
    ],
    "IT-FM-026": [
      "CO-WF-09",
      "IT-WF-08"
    ],
    "IT-FM-027": [
      "CO-WF-09",
      "IT-WF-08"
    ],
    "CO-FM-014": [
      "CO-WF-10",
      "CO-WF-11",
      "CO-WF-21"
    ],
    "CO-FM-015": [
      "CO-WF-10"
    ],
    "IT-FM-009": [
      "CO-WF-10",
      "IT-WF-21",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25",
      "IT-WF-02",
      "IT-WF-05",
      "IT-WF-18"
    ],
    "IT-FM-011": [
      "CO-WF-10",
      "CO-WF-17",
      "IT-WF-03",
      "IT-WF-11",
      "IT-WF-18"
    ],
    "CO-FM-017": [
      "CO-WF-11",
      "GV-WF-11",
      "OP-WF-03"
    ],
    "CO-FM-027": [
      "CO-WF-11",
      "CO-WF-18",
      "OP-WF-03"
    ],
    "CO-FM-018": [
      "CO-WF-12",
      "CO-WF-21",
      "EN-WF-11",
      "FN-WF-15"
    ],
    "CO-FM-029": [
      "CO-WF-12",
      "IT-WF-09",
      "IT-WF-10",
      "IT-WF-15",
      "IT-WF-16"
    ],
    "HR-FM-037": [
      "CO-WF-12",
      "HR-WF-10"
    ],
    "IT-FM-022": [
      "CO-WF-12",
      "IT-WF-06",
      "IT-WF-18"
    ],
    "CO-FM-020": [
      "CO-WF-13",
      "EN-WF-11",
      "GV-WF-10"
    ],
    "IT-FM-003": [
      "CO-WF-13",
      "EN-WF-12",
      "IT-WF-01",
      "IT-WF-07"
    ],
    "IT-FM-024": [
      "CO-WF-13",
      "EN-WF-08",
      "IT-WF-07",
      "IT-WF-10"
    ],
    "CO-FM-023": [
      "CO-WF-14"
    ],
    "CO-FM-025": [
      "CO-WF-15"
    ],
    "CO-FM-030": [
      "CO-WF-15",
      "CO-WF-16",
      "FN-WF-08"
    ],
    "CO-FM-033": [
      "CO-WF-16",
      "FN-WF-08",
      "FN-WF-15",
      "GV-WF-12",
      "HR-WF-15",
      "RM-WF-14"
    ],
    "CO-FM-026": [
      "CO-WF-17"
    ],
    "IT-FM-010": [
      "CO-WF-17",
      "CO-WF-18",
      "IT-WF-03",
      "IT-WF-18"
    ],
    "CO-FM-031": [
      "CO-WF-18"
    ],
    "CO-FM-039": [
      "CO-WF-18"
    ],
    "CO-FM-036": [
      "CO-WF-19"
    ],
    "EN-FM-017": [
      "CO-WF-22",
      "EN-WF-06"
    ],
    "EN-FM-002": [
      "EN-WF-01",
      "EN-WF-02",
      "EN-WF-04",
      "EN-WF-06"
    ],
    "EN-FM-003": [
      "EN-WF-01",
      "EN-WF-02",
      "EN-WF-05"
    ],
    "EN-FM-004": [
      "EN-WF-01"
    ],
    "EN-FM-020": [
      "EN-WF-01",
      "EN-WF-07"
    ],
    "EN-FM-010": [
      "EN-WF-02"
    ],
    "EN-FM-011": [
      "EN-WF-03"
    ],
    "EN-FM-012": [
      "EN-WF-03"
    ],
    "HR-FM-026": [
      "EN-WF-03",
      "HR-WF-07"
    ],
    "EN-FM-013": [
      "EN-WF-04"
    ],
    "EN-FM-015": [
      "EN-WF-05"
    ],
    "EN-FM-016": [
      "EN-WF-05"
    ],
    "EN-FM-018": [
      "EN-WF-06",
      "EN-WF-10",
      "OP-WF-01"
    ],
    "EN-FM-021": [
      "EN-WF-07",
      "GV-WF-01"
    ],
    "EN-FM-030": [
      "EN-WF-08"
    ],
    "EN-FM-031": [
      "EN-WF-08"
    ],
    "IT-FM-036": [
      "EN-WF-08",
      "IT-WF-10",
      "IT-WF-12",
      "IT-WF-13",
      "IT-WF-17"
    ],
    "IT-FM-044": [
      "EN-WF-08",
      "IT-WF-17"
    ],
    "EN-FM-032": [
      "EN-WF-09"
    ],
    "EN-FM-033": [
      "EN-WF-09"
    ],
    "EN-FM-028": [
      "EN-WF-11"
    ],
    "EN-FM-035": [
      "EN-WF-11"
    ],
    "RM-FM-015": [
      "EN-WF-12",
      "OP-WF-10",
      "RM-WF-14"
    ],
    "RM-FM-017": [
      "EN-WF-12",
      "RM-WF-01"
    ],
    "EN-FM-029": [
      "EN-WF-13"
    ],
    "EN-FM-036": [
      "EN-WF-13"
    ],
    "EN-FM-037": [
      "EN-WF-13"
    ],
    "FN-FM-001": [
      "FN-WF-01"
    ],
    "FN-FM-002": [
      "FN-WF-01"
    ],
    "FN-FM-014": [
      "FN-WF-01",
      "FN-WF-05",
      "FN-WF-09",
      "FN-WF-15"
    ],
    "GV-FM-011": [
      "FN-WF-01",
      "FN-WF-09",
      "GV-WF-01"
    ],
    "FN-FM-003": [
      "FN-WF-02",
      "FN-WF-03"
    ],
    "FN-FM-004": [
      "FN-WF-02",
      "FN-WF-09",
      "FN-WF-10",
      "FN-WF-14",
      "OP-WF-07"
    ],
    "FN-FM-005": [
      "FN-WF-02"
    ],
    "FN-FM-007": [
      "FN-WF-03"
    ],
    "FN-FM-008": [
      "FN-WF-03",
      "FN-WF-15"
    ],
    "FN-FM-009": [
      "FN-WF-04",
      "QA-WF-07"
    ],
    "FN-FM-010": [
      "FN-WF-04",
      "FN-WF-15",
      "QA-WF-07"
    ],
    "FN-FM-012": [
      "FN-WF-04"
    ],
    "FN-FM-013": [
      "FN-WF-05",
      "FN-WF-06"
    ],
    "FN-FM-015": [
      "FN-WF-05",
      "FN-WF-13"
    ],
    "FN-FM-016": [
      "FN-WF-06",
      "FN-WF-15"
    ],
    "FN-FM-017": [
      "FN-WF-06"
    ],
    "FN-FM-018": [
      "FN-WF-07"
    ],
    "FN-FM-019": [
      "FN-WF-07",
      "FN-WF-08"
    ],
    "FN-FM-020": [
      "FN-WF-08",
      "FN-WF-15",
      "HR-WF-15"
    ],
    "FN-FM-021": [
      "FN-WF-08"
    ],
    "FN-FM-022": [
      "FN-WF-08"
    ],
    "FN-FM-023": [
      "FN-WF-08"
    ],
    "FN-FM-024": [
      "FN-WF-08"
    ],
    "FN-FM-025": [
      "FN-WF-09"
    ],
    "FN-FM-026": [
      "FN-WF-09",
      "FN-WF-10"
    ],
    "FN-FM-027": [
      "FN-WF-10"
    ],
    "FN-FM-028": [
      "FN-WF-10"
    ],
    "OP-FM-005": [
      "FN-WF-11",
      "GV-WF-11",
      "OP-WF-03",
      "OP-WF-04",
      "RM-WF-06",
      "RM-WF-11"
    ],
    "GV-FM-004": [
      "GV-WF-01",
      "GV-WF-05"
    ],
    "GV-FM-006": [
      "GV-WF-01",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-08"
    ],
    "GV-FM-021": [
      "GV-WF-01",
      "GV-WF-02"
    ],
    "GV-FM-022": [
      "GV-WF-01",
      "GV-WF-02",
      "GV-WF-10",
      "GV-WF-14"
    ],
    "RM-FM-008": [
      "GV-WF-01",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-15"
    ],
    "GV-FM-008": [
      "GV-WF-02",
      "GV-WF-13"
    ],
    "GV-FM-012": [
      "GV-WF-02",
      "GV-WF-14"
    ],
    "GV-FM-024": [
      "GV-WF-02",
      "GV-WF-13"
    ],
    "GV-FM-003": [
      "GV-WF-03",
      "GV-WF-04"
    ],
    "GV-FM-007": [
      "GV-WF-03"
    ],
    "GV-FM-013": [
      "GV-WF-03"
    ],
    "GV-FM-014": [
      "GV-WF-03"
    ],
    "GV-FM-017": [
      "GV-WF-03",
      "GV-WF-04"
    ],
    "GV-FM-019": [
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-09",
      "HR-WF-04"
    ],
    "HR-FM-006": [
      "GV-WF-03",
      "GV-WF-04",
      "HR-WF-20",
      "HR-WF-02",
      "HR-WF-04",
      "HR-WF-05",
      "OP-WF-09"
    ],
    "HR-FM-018": [
      "GV-WF-03",
      "GV-WF-04",
      "HR-WF-05"
    ],
    "GV-FM-015": [
      "GV-WF-04"
    ],
    "HR-FM-003": [
      "GV-WF-04",
      "HR-WF-01"
    ],
    "HR-FM-004": [
      "GV-WF-04",
      "HR-WF-01"
    ],
    "GV-FM-009": [
      "GV-WF-05"
    ],
    "HR-FM-019": [
      "GV-WF-05",
      "HR-WF-05",
      "HR-WF-06",
      "OP-WF-12"
    ],
    "QA-FM-007": [
      "GV-WF-05",
      "OP-WF-12",
      "QA-WF-02",
      "QA-WF-07"
    ],
    "GV-FM-020": [
      "GV-WF-07",
      "GV-WF-12"
    ],
    "CO-FM-035": [
      "GV-WF-09"
    ],
    "GV-FM-002": [
      "GV-WF-09"
    ],
    "GV-FM-001": [
      "GV-WF-10",
      "OP-WF-01"
    ],
    "IT-FM-028": [
      "GV-WF-11",
      "IT-WF-08",
      "OP-WF-03"
    ],
    "OP-FM-003": [
      "GV-WF-11",
      "OP-WF-03"
    ],
    "OP-FM-004": [
      "GV-WF-11",
      "OP-WF-03",
      "OP-WF-05"
    ],
    "OP-FM-006": [
      "GV-WF-11",
      "OP-WF-03"
    ],
    "OP-FM-007": [
      "GV-WF-11",
      "OP-WF-03",
      "OP-WF-04"
    ],
    "OP-FM-008": [
      "GV-WF-11",
      "HR-WF-15",
      "OP-WF-03"
    ],
    "GV-FM-025": [
      "GV-WF-12"
    ],
    "HR-FM-012": [
      "HR-WF-21",
      "HR-WF-03"
    ],
    "HR-FM-015": [
      "HR-WF-21",
      "HR-WF-04",
      "HR-WF-15"
    ],
    "HR-FM-001": [
      "HR-WF-01"
    ],
    "HR-FM-002": [
      "HR-WF-01"
    ],
    "HR-FM-008": [
      "HR-WF-02"
    ],
    "HR-FM-011": [
      "HR-WF-03"
    ],
    "HR-FM-013": [
      "HR-WF-03",
      "RM-WF-10"
    ],
    "IT-FM-001": [
      "HR-WF-03",
      "IT-WF-01",
      "IT-WF-10",
      "IT-WF-17"
    ],
    "HR-FM-020": [
      "HR-WF-06"
    ],
    "HR-FM-022": [
      "HR-WF-06",
      "RM-WF-08",
      "RM-WF-10"
    ],
    "HR-FM-025": [
      "HR-WF-07"
    ],
    "HR-FM-027": [
      "HR-WF-08",
      "OP-WF-09"
    ],
    "HR-FM-028": [
      "HR-WF-08"
    ],
    "HR-FM-029": [
      "HR-WF-08"
    ],
    "HR-FM-030": [
      "HR-WF-08",
      "RM-WF-04"
    ],
    "HR-FM-032": [
      "HR-WF-09"
    ],
    "HR-FM-034": [
      "HR-WF-09"
    ],
    "HR-FM-035": [
      "HR-WF-09",
      "HR-WF-12"
    ],
    "HR-FM-036": [
      "HR-WF-10",
      "RM-WF-09"
    ],
    "HR-FM-039": [
      "HR-WF-10"
    ],
    "HR-FM-040": [
      "HR-WF-10",
      "HR-WF-16",
      "HR-WF-17"
    ],
    "HR-FM-041": [
      "HR-WF-10",
      "HR-WF-13",
      "HR-WF-16",
      "HR-WF-17"
    ],
    "HR-FM-042": [
      "HR-WF-10",
      "HR-WF-11",
      "HR-WF-16",
      "HR-WF-17"
    ],
    "HR-FM-043": [
      "HR-WF-11"
    ],
    "HR-FM-044": [
      "HR-WF-11"
    ],
    "HR-FM-045": [
      "HR-WF-11"
    ],
    "HR-FM-046": [
      "HR-WF-12"
    ],
    "HR-FM-047": [
      "HR-WF-12"
    ],
    "HR-FM-048": [
      "HR-WF-12"
    ],
    "HR-FM-049": [
      "HR-WF-12"
    ],
    "HR-FM-050": [
      "HR-WF-12"
    ],
    "HR-FM-051": [
      "HR-WF-12"
    ],
    "HR-FM-023": [
      "HR-WF-13",
      "OP-WF-09",
      "RM-WF-08",
      "RM-WF-10"
    ],
    "HR-FM-052": [
      "HR-WF-13"
    ],
    "HR-FM-053": [
      "HR-WF-13"
    ],
    "HR-FM-054": [
      "HR-WF-13"
    ],
    "RM-FM-009": [
      "HR-WF-13",
      "OP-WF-09",
      "RM-WF-09"
    ],
    "RM-FM-014": [
      "HR-WF-13",
      "OP-WF-02",
      "RM-WF-08"
    ],
    "HR-FM-055": [
      "HR-WF-14"
    ],
    "HR-FM-056": [
      "HR-WF-14",
      "IT-WF-03",
      "IT-WF-19"
    ],
    "HR-FM-057": [
      "HR-WF-14"
    ],
    "HR-FM-058": [
      "HR-WF-14"
    ],
    "IT-FM-002": [
      "HR-WF-14",
      "IT-WF-01"
    ],
    "HR-FM-059": [
      "HR-WF-16"
    ],
    "HR-FM-060": [
      "HR-WF-16"
    ],
    "HR-FM-061": [
      "HR-WF-17"
    ],
    "HR-FM-062": [
      "HR-WF-17"
    ],
    "HR-FM-063": [
      "HR-WF-17"
    ],
    "IT-FM-004": [
      "IT-WF-02",
      "IT-WF-18"
    ],
    "IT-FM-005": [
      "IT-WF-02"
    ],
    "IT-FM-006": [
      "IT-WF-02"
    ],
    "IT-FM-007": [
      "IT-WF-02"
    ],
    "IT-FM-008": [
      "IT-WF-02"
    ],
    "IT-FM-012": [
      "IT-WF-03"
    ],
    "IT-FM-013": [
      "IT-WF-03"
    ],
    "IT-FM-014": [
      "IT-WF-04"
    ],
    "IT-FM-015": [
      "IT-WF-04"
    ],
    "IT-FM-016": [
      "IT-WF-04"
    ],
    "IT-FM-017": [
      "IT-WF-05",
      "IT-WF-18"
    ],
    "IT-FM-018": [
      "IT-WF-05"
    ],
    "IT-FM-019": [
      "IT-WF-05"
    ],
    "IT-FM-021": [
      "IT-WF-06",
      "IT-WF-12"
    ],
    "IT-FM-023": [
      "IT-WF-07"
    ],
    "IT-FM-025": [
      "IT-WF-07"
    ],
    "RM-FM-002": [
      "IT-WF-08",
      "RM-WF-03",
      "RM-WF-07"
    ],
    "RM-FM-003": [
      "IT-WF-08",
      "RM-WF-03"
    ],
    "IT-FM-029": [
      "IT-WF-09",
      "IT-WF-10",
      "IT-WF-11",
      "IT-WF-13",
      "IT-WF-16"
    ],
    "IT-FM-030": [
      "IT-WF-09"
    ],
    "IT-FM-031": [
      "IT-WF-09"
    ],
    "IT-FM-032": [
      "IT-WF-09",
      "IT-WF-13"
    ],
    "IT-FM-033": [
      "IT-WF-11"
    ],
    "IT-FM-034": [
      "IT-WF-12"
    ],
    "IT-FM-035": [
      "IT-WF-13"
    ],
    "IT-FM-037": [
      "IT-WF-14"
    ],
    "IT-FM-038": [
      "IT-WF-14"
    ],
    "IT-FM-039": [
      "IT-WF-14"
    ],
    "IT-FM-040": [
      "IT-WF-15"
    ],
    "IT-FM-041": [
      "IT-WF-15"
    ],
    "IT-FM-042": [
      "IT-WF-16"
    ],
    "IT-FM-043": [
      "IT-WF-16"
    ],
    "IT-FM-045": [
      "IT-WF-19"
    ],
    "IT-FM-046": [
      "IT-WF-19"
    ],
    "IT-FM-047": [
      "IT-WF-20"
    ],
    "IT-FM-048": [
      "IT-WF-20"
    ],
    "IT-FM-049": [
      "IT-WF-20"
    ],
    "OP-FM-001": [
      "OP-WF-01"
    ],
    "OP-FM-002": [
      "OP-WF-02"
    ],
    "RM-FM-013": [
      "OP-WF-02",
      "RM-WF-08"
    ],
    "OP-FM-009": [
      "OP-WF-05"
    ],
    "OP-FM-010": [
      "OP-WF-06"
    ],
    "OP-FM-011": [
      "OP-WF-06"
    ],
    "OP-FM-012": [
      "OP-WF-06"
    ],
    "OP-FM-013": [
      "OP-WF-06"
    ],
    "OP-FM-016": [
      "OP-WF-09"
    ],
    "OP-FM-019": [
      "OP-WF-12"
    ],
    "OP-FM-020": [
      "OP-WF-13"
    ],
    "QA-FM-010": [
      "QA-WF-01",
      "QA-WF-10"
    ],
    "QA-FM-002": [
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-06",
      "QA-WF-08",
      "QA-WF-09"
    ],
    "QA-FM-012": [
      "QA-WF-05",
      "QA-WF-11"
    ],
    "QA-FM-013": [
      "QA-WF-05",
      "QA-WF-12"
    ],
    "RM-FM-006": [
      "QA-WF-06",
      "RM-WF-06"
    ],
    "QA-FM-008": [
      "QA-WF-08"
    ],
    "QA-FM-009": [
      "QA-WF-09"
    ],
    "QA-FM-011": [
      "QA-WF-09"
    ],
    "RM-FM-016": [
      "RM-WF-01",
      "RM-WF-15"
    ],
    "RM-FM-001": [
      "RM-WF-02",
      "RM-WF-03"
    ],
    "RM-FM-004": [
      "RM-WF-05"
    ],
    "RM-FM-005": [
      "RM-WF-05",
      "RM-WF-07"
    ],
    "RM-FM-007": [
      "RM-WF-07"
    ],
    "RM-FM-018": [
      "RM-WF-08",
      "RM-WF-09"
    ],
    "RM-FM-010": [
      "RM-WF-11"
    ],
    "RM-FM-011": [
      "RM-WF-12"
    ]
  },
  "byPolicy": {
    "CL-PA-005": [
      "CL-WF-26",
      "CL-WF-30",
      "CL-WF-35",
      "CL-WF-37",
      "CL-WF-03"
    ],
    "CL-PA-007": [
      "CL-WF-26",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-24"
    ],
    "CL-PA-003": [
      "CL-WF-27",
      "RM-WF-07"
    ],
    "CL-PA-008": [
      "CL-WF-28"
    ],
    "CL-PA-010": [
      "CL-WF-29"
    ],
    "CL-PA-002": [
      "CL-WF-30",
      "CL-WF-02"
    ],
    "CL-PA-012": [
      "CL-WF-31"
    ],
    "CL-PA-014": [
      "CL-WF-32"
    ],
    "CL-PA-009": [
      "CL-WF-36"
    ],
    "CL-PA-001": [
      "CL-WF-01",
      "CL-WF-04",
      "GV-WF-06",
      "OP-WF-07",
      "OP-WF-08"
    ],
    "OP-IN-001": [
      "CL-WF-01",
      "OP-WF-07"
    ],
    "GV-GB-001": [
      "CL-WF-01",
      "CO-WF-01",
      "CO-WF-19",
      "CO-WF-22",
      "EN-WF-09",
      "EN-WF-10",
      "EN-WF-13",
      "FN-WF-01",
      "FN-WF-02",
      "FN-WF-13",
      "GV-WF-01",
      "GV-WF-02",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-05",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-08",
      "GV-WF-09",
      "GV-WF-10",
      "GV-WF-11",
      "GV-WF-12",
      "GV-WF-13",
      "GV-WF-14",
      "OP-WF-01",
      "OP-WF-08",
      "QA-WF-01",
      "QA-WF-03",
      "RM-WF-01",
      "RM-WF-15"
    ],
    "CL-OA-001": [
      "CL-WF-04",
      "CL-WF-05",
      "CL-WF-18",
      "CL-WF-25",
      "QA-WF-02"
    ],
    "CL-OA-006": [
      "CL-WF-05",
      "CL-WF-21",
      "CO-WF-14"
    ],
    "CL-CP-001": [
      "CL-WF-06",
      "FN-WF-04",
      "OP-WF-12"
    ],
    "CL-CP-002": [
      "CL-WF-06",
      "CL-WF-08"
    ],
    "CL-CP-003": [
      "CL-WF-07"
    ],
    "CL-SD-001": [
      "CL-WF-09",
      "QA-WF-07"
    ],
    "CL-SD-002": [
      "CL-WF-09"
    ],
    "CL-SD-003": [
      "CL-WF-10",
      "CL-WF-11"
    ],
    "HR-TD-001": [
      "CL-WF-11",
      "CO-WF-02"
    ],
    "CL-SD-007": [
      "CL-WF-12",
      "HR-WF-19",
      "RM-WF-13"
    ],
    "CL-SD-004": [
      "CL-WF-13"
    ],
    "CL-SD-005": [
      "CL-WF-13",
      "CL-WF-24",
      "HR-WF-05"
    ],
    "CL-IC-001": [
      "CL-WF-14",
      "QA-WF-06",
      "RM-WF-06"
    ],
    "CL-SD-006": [
      "CL-WF-15"
    ],
    "CL-PA-004": [
      "CL-WF-16",
      "CL-WF-17",
      "CL-WF-22",
      "CL-WF-23",
      "OP-WF-10",
      "OP-WF-13",
      "QA-WF-12"
    ],
    "CL-SD-008": [
      "CL-WF-17"
    ],
    "CL-DC-001": [
      "CL-WF-19"
    ],
    "CL-SD-009": [
      "CL-WF-20"
    ],
    "CO-DC-001": [
      "CL-WF-21",
      "CO-WF-13",
      "CO-WF-14"
    ],
    "HR-FM-033": [
      "CL-WF-22"
    ],
    "HR-TA-001": [
      "CL-WF-25",
      "GV-WF-03",
      "GV-WF-04",
      "HR-WF-01"
    ],
    "CO-CB-001": [
      "CO-WF-23"
    ],
    "FN-RC-002": [
      "CO-WF-23"
    ],
    "CO-CB-002": [
      "CO-WF-24"
    ],
    "CO-CB-003": [
      "CO-WF-25"
    ],
    "CO-CB-004": [
      "CO-WF-26"
    ],
    "CO-CP-005": [
      "CO-WF-27",
      "CO-WF-07",
      "CO-WF-15",
      "GV-WF-08",
      "OP-WF-04"
    ],
    "FN-RC-001": [
      "CO-WF-28"
    ],
    "FN-RC-005": [
      "CO-WF-29"
    ],
    "CO-CP-002": [
      "CO-WF-30",
      "CO-WF-01",
      "CO-WF-02",
      "EN-WF-03",
      "GV-WF-08",
      "HR-WF-07"
    ],
    "CO-CP-001": [
      "CO-WF-01",
      "CO-WF-02",
      "CO-WF-04",
      "CO-WF-20",
      "CO-WF-22",
      "EN-WF-05",
      "EN-WF-09",
      "GV-WF-01",
      "GV-WF-03",
      "GV-WF-10",
      "GV-WF-11",
      "QA-WF-01",
      "QA-WF-10"
    ],
    "CO-CP-003": [
      "CO-WF-03",
      "HR-WF-02",
      "HR-WF-15"
    ],
    "CO-CP-007": [
      "CO-WF-03",
      "HR-WF-09",
      "RM-WF-14"
    ],
    "CO-CP-006": [
      "CO-WF-04",
      "EN-WF-11",
      "EN-WF-12",
      "FN-WF-15"
    ],
    "CO-CP-010": [
      "CO-WF-05"
    ],
    "CO-RA-001": [
      "CO-WF-06",
      "CO-WF-19",
      "EN-WF-09",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-09",
      "GV-WF-10",
      "HR-WF-04"
    ],
    "EN-LC-001": [
      "CO-WF-06",
      "QA-WF-11"
    ],
    "GV-PM-001": [
      "CO-WF-06",
      "EN-WF-01",
      "EN-WF-04"
    ],
    "CO-FA-001": [
      "CO-WF-07",
      "CO-WF-08"
    ],
    "CO-FA-002": [
      "CO-WF-07"
    ],
    "CO-CP-004": [
      "CO-WF-08"
    ],
    "CO-HP-001": [
      "CO-WF-09",
      "CO-WF-12",
      "GV-WF-12",
      "GV-WF-14",
      "OP-WF-06"
    ],
    "CO-HP-004": [
      "CO-WF-09",
      "GV-WF-12"
    ],
    "CO-HP-003": [
      "CO-WF-10",
      "HR-WF-07"
    ],
    "CO-HP-005": [
      "CO-WF-10",
      "IT-WF-20"
    ],
    "CO-CA-001": [
      "CO-WF-10",
      "CO-WF-12",
      "CO-WF-21",
      "IT-WF-20",
      "OP-WF-06"
    ],
    "CO-HP-002": [
      "CO-WF-11",
      "GV-WF-11"
    ],
    "CO-HP-006": [
      "CO-WF-12",
      "IT-WF-15"
    ],
    "CO-CP-008": [
      "CO-WF-16"
    ],
    "CO-HP-008": [
      "CO-WF-17"
    ],
    "IT-SP-001": [
      "CO-WF-17",
      "CO-WF-18",
      "IT-WF-01",
      "OP-WF-03"
    ],
    "CO-AI-001": [
      "CO-WF-18"
    ],
    "EN-AI-001": [
      "CO-WF-18"
    ],
    "EN-PM-001": [
      "EN-WF-01"
    ],
    "EN-PM-002": [
      "EN-WF-02"
    ],
    "EN-AK-001": [
      "EN-WF-03"
    ],
    "EN-TG-001": [
      "EN-WF-04",
      "GV-WF-02",
      "HR-WF-03"
    ],
    "EN-CM-001": [
      "EN-WF-05",
      "QA-WF-13",
      "QA-WF-18"
    ],
    "EN-CM-002": [
      "EN-WF-06"
    ],
    "EN-PM-003": [
      "EN-WF-07"
    ],
    "EN-RM-001": [
      "EN-WF-08"
    ],
    "EN-MT-001": [
      "EN-WF-09"
    ],
    "EN-MT-002": [
      "EN-WF-10"
    ],
    "EN-AU-001": [
      "EN-WF-11"
    ],
    "EN-AU-002": [
      "EN-WF-12"
    ],
    "RM-RI-001": [
      "EN-WF-12"
    ],
    "EN-AU-003": [
      "EN-WF-13"
    ],
    "FN-FP-001": [
      "FN-WF-01"
    ],
    "FN-FP-002": [
      "FN-WF-02"
    ],
    "FN-AU-001": [
      "FN-WF-03"
    ],
    "FN-BL-001": [
      "FN-WF-04"
    ],
    "CL-SD-011": [
      "FN-WF-04"
    ],
    "FN-BL-002": [
      "FN-WF-05"
    ],
    "FN-BL-003": [
      "FN-WF-06"
    ],
    "FN-AR-001": [
      "FN-WF-07"
    ],
    "FN-AR-002": [
      "FN-WF-08"
    ],
    "CO-FW-002": [
      "FN-WF-08"
    ],
    "FN-AR-003": [
      "FN-WF-09"
    ],
    "FN-AR-004": [
      "FN-WF-09"
    ],
    "FN-BL-004": [
      "FN-WF-10"
    ],
    "FN-BL-005": [
      "FN-WF-10"
    ],
    "FN-AP-001": [
      "FN-WF-11"
    ],
    "CO-FW-001": [
      "FN-WF-11"
    ],
    "FN-PR-001": [
      "FN-WF-12",
      "HR-WF-14"
    ],
    "HR-TA-004": [
      "FN-WF-12",
      "HR-WF-20",
      "HR-WF-03",
      "HR-WF-17"
    ],
    "FN-AU-002": [
      "FN-WF-13"
    ],
    "FN-BL-006": [
      "FN-WF-14"
    ],
    "FN-BL-007": [
      "FN-WF-14"
    ],
    "FN-BL-008": [
      "FN-WF-15"
    ],
    "GV-GB-002": [
      "GV-WF-01",
      "GV-WF-14"
    ],
    "GV-GB-003": [
      "GV-WF-01"
    ],
    "QA-PG-001": [
      "GV-WF-01",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-18",
      "QA-WF-01",
      "QA-WF-02",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-06",
      "QA-WF-07",
      "QA-WF-10",
      "QA-WF-11"
    ],
    "GV-GB-004": [
      "GV-WF-02",
      "GV-WF-13"
    ],
    "GV-OG-001": [
      "GV-WF-03",
      "GV-WF-04"
    ],
    "FN-FP-005": [
      "GV-WF-05"
    ],
    "OP-FM-005": [
      "GV-WF-06"
    ],
    "GV-EA-004": [
      "GV-WF-07",
      "GV-WF-09",
      "HR-WF-04"
    ],
    "GV-EA-001": [
      "GV-WF-11"
    ],
    "GV-EA-002": [
      "GV-WF-12"
    ],
    "HR-TR-001": [
      "HR-WF-18",
      "HR-WF-05"
    ],
    "HR-TR-101": [
      "HR-WF-18"
    ],
    "HR-TD-003": [
      "HR-WF-19"
    ],
    "HR-TA-003": [
      "HR-WF-20",
      "HR-WF-02",
      "HR-WF-15"
    ],
    "HR-WM-007": [
      "HR-WF-21"
    ],
    "HR-TA-002": [
      "HR-WF-01"
    ],
    "CO-TR-001": [
      "HR-WF-03"
    ],
    "HR-TA-005": [
      "HR-WF-04"
    ],
    "HR-TR-002": [
      "HR-WF-06"
    ],
    "HR-TR-003": [
      "HR-WF-07"
    ],
    "RM-OS-101": [
      "HR-WF-07",
      "HR-WF-13",
      "OP-WF-02",
      "RM-WF-08"
    ],
    "HR-PM-001": [
      "HR-WF-08"
    ],
    "HR-ER-001": [
      "HR-WF-09"
    ],
    "HR-ER-002": [
      "HR-WF-10"
    ],
    "HR-ER-003": [
      "HR-WF-11"
    ],
    "HR-ER-004": [
      "HR-WF-12"
    ],
    "HR-HS-001": [
      "HR-WF-13"
    ],
    "HR-ER-005": [
      "HR-WF-14",
      "IT-WF-03"
    ],
    "IT-SP-004": [
      "HR-WF-14",
      "IT-WF-19"
    ],
    "HR-CO-001": [
      "HR-WF-16"
    ],
    "IT-AC-001": [
      "IT-WF-21",
      "IT-WF-02"
    ],
    "IT-AC-002": [
      "IT-WF-21",
      "IT-WF-03"
    ],
    "IT-IS-001": [
      "IT-WF-22",
      "IT-WF-25"
    ],
    "IT-AU-001": [
      "IT-WF-23",
      "IT-WF-24"
    ],
    "IT-VM-001": [
      "IT-WF-25"
    ],
    "IT-AC-003": [
      "IT-WF-04"
    ],
    "IT-AC-004": [
      "IT-WF-05"
    ],
    "IT-SP-002": [
      "IT-WF-06"
    ],
    "IT-BC-001": [
      "IT-WF-07"
    ],
    "IT-BC-002": [
      "IT-WF-08"
    ],
    "IT-IR-001": [
      "IT-WF-09"
    ],
    "IT-AM-001": [
      "IT-WF-10"
    ],
    "IT-AM-002": [
      "IT-WF-11"
    ],
    "IT-AM-003": [
      "IT-WF-12"
    ],
    "IT-NE-001": [
      "IT-WF-13"
    ],
    "IT-NE-002": [
      "IT-WF-14"
    ],
    "IT-SP-003": [
      "IT-WF-15"
    ],
    "IT-NE-003": [
      "IT-WF-16"
    ],
    "IT-DM-001": [
      "IT-WF-17"
    ],
    "IT-NE-004": [
      "IT-WF-18"
    ],
    "OP-BR-001": [
      "OP-WF-01"
    ],
    "OP-FM-001": [
      "OP-WF-02"
    ],
    "OP-SM-001": [
      "OP-WF-03",
      "OP-WF-04"
    ],
    "CO-FM-027": [
      "OP-WF-03"
    ],
    "OP-SM-003": [
      "OP-WF-05"
    ],
    "RM-EP-001": [
      "OP-WF-05",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-07"
    ],
    "OP-RC-002": [
      "OP-WF-06"
    ],
    "OP-FM-002": [
      "OP-WF-09",
      "OP-WF-10"
    ],
    "OP-SM-005": [
      "OP-WF-11"
    ],
    "OP-IN-002": [
      "OP-WF-12"
    ],
    "CL-SD-010": [
      "OP-WF-13"
    ],
    "QA-PI-001": [
      "QA-WF-14",
      "QA-WF-04"
    ],
    "QA-PIP-001": [
      "QA-WF-17"
    ],
    "QA-PG-002": [
      "QA-WF-01",
      "QA-WF-03"
    ],
    "QA-SM-001": [
      "QA-WF-02"
    ],
    "QA-AE-001": [
      "QA-WF-05",
      "QA-WF-12",
      "RM-WF-16",
      "RM-WF-20",
      "RM-WF-13"
    ],
    "QA-AE-003": [
      "QA-WF-05"
    ],
    "FN-BC-001": [
      "QA-WF-07"
    ],
    "QA-SM-002": [
      "QA-WF-08"
    ],
    "QA-SM-004": [
      "QA-WF-09"
    ],
    "RM-RM-001": [
      "RM-WF-16",
      "RM-WF-18"
    ],
    "RM-OS-001": [
      "RM-WF-17"
    ],
    "HR-WM-004": [
      "RM-WF-17"
    ],
    "RM-RM-002": [
      "RM-WF-20"
    ],
    "RM-RA-001": [
      "RM-WF-01",
      "RM-WF-15"
    ],
    "RM-EP-002": [
      "RM-WF-06"
    ],
    "HR-EH-101": [
      "RM-WF-08"
    ],
    "RM-SS-001": [
      "RM-WF-09"
    ],
    "RM-OS-002": [
      "RM-WF-10"
    ],
    "RM-OS-003": [
      "RM-WF-11"
    ],
    "RM-PS-001": [
      "RM-WF-12"
    ],
    "RM-LI-001": [
      "RM-WF-14"
    ]
  },
  "byRegulation": {
    "42 CFR § 484.60": [
      "CL-WF-26",
      "CL-WF-29",
      "CL-WF-06",
      "CL-WF-13",
      "CL-WF-20",
      "RM-WF-13"
    ],
    "42 CFR § 484.55": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-04",
      "CL-WF-18"
    ],
    "42 CFR § 484.45": [
      "CL-WF-27",
      "CL-WF-05"
    ],
    "42 CFR § 484.110": [
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-21",
      "CO-WF-25",
      "CO-WF-13",
      "EN-WF-08",
      "GV-WF-12"
    ],
    "42 CFR § 484.60(b)": [
      "CL-WF-28",
      "CL-WF-31",
      "CL-WF-37",
      "CL-WF-07",
      "CL-WF-09",
      "CL-WF-12"
    ],
    "42 CFR § 409.42": [
      "CL-WF-30",
      "CL-WF-02"
    ],
    "42 CFR § 409.44": [
      "CL-WF-30"
    ],
    "42 CFR § 484.70": [
      "CL-WF-32",
      "CL-WF-14",
      "QA-WF-06"
    ],
    "42 CFR § 484.60(d)": [
      "CL-WF-33",
      "CL-WF-08"
    ],
    "42 CFR § 484.65": [
      "CL-WF-34",
      "CL-WF-35",
      "CO-WF-26",
      "CO-WF-30",
      "QA-WF-18"
    ],
    "42 CFR § 484.60(c)": [
      "CL-WF-36",
      "CL-WF-17"
    ],
    "42 CFR § 409.43": [
      "CL-WF-37"
    ],
    "42 CFR § 484.60(a)": [
      "CL-WF-01"
    ],
    "SSA § 1835(a)(2)(": [
      "CL-WF-02"
    ],
    "42 CFR § 424.22(a)(1)(v)": [
      "CL-WF-03"
    ],
    "SSA § 1814(a)(2)(": [
      "CL-WF-03"
    ],
    "42 CFR § 484.75": [
      "CL-WF-10",
      "HR-WF-06"
    ],
    "42 CFR § 484.80(d)": [
      "CL-WF-11",
      "HR-WF-19"
    ],
    "42 CFR § 409.46": [
      "CL-WF-15"
    ],
    "45 CFR § 164.312": [
      "CL-WF-15",
      "IT-WF-21",
      "IT-WF-06",
      "IT-WF-16",
      "IT-WF-18"
    ],
    "42 CFR § 484.50": [
      "CL-WF-16",
      "QA-WF-12"
    ],
    "42 CFR § 484.50(d)": [
      "CL-WF-19"
    ],
    "42 CFR § 484.50(e)": [
      "CL-WF-22",
      "CL-WF-23"
    ],
    "42 CFR § 484.115": [
      "CL-WF-25",
      "HR-WF-18",
      "HR-WF-19",
      "HR-WF-21",
      "HR-WF-04"
    ],
    "42 CFR § 484.205": [
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-29",
      "FN-WF-04"
    ],
    "SSA § 1862(a)(1)(": [
      "CO-WF-23"
    ],
    "42 CFR § 422.503(b)(4)(vi)": [
      "CO-WF-27",
      "CO-WF-08"
    ],
    "SSA § 1128": [
      "CO-WF-27"
    ],
    "42 CFR § 424.22": [
      "CO-WF-28"
    ],
    "42 CFR § 484.100": [
      "CO-WF-01"
    ],
    "42 CFR § 488": [
      "CO-WF-05"
    ],
    "42 CFR § 411": [
      "CO-WF-07"
    ],
    "45 CFR § 164.530": [
      "CO-WF-09",
      "IT-WF-23",
      "OP-WF-06"
    ],
    "45 CFR § 164.308": [
      "CO-WF-11",
      "CO-WF-17",
      "IT-WF-22",
      "IT-WF-01",
      "IT-WF-02",
      "IT-WF-03",
      "IT-WF-04",
      "IT-WF-05",
      "IT-WF-07",
      "IT-WF-08",
      "IT-WF-09",
      "IT-WF-13"
    ],
    "45 CFR § 164.508": [
      "CO-WF-12"
    ],
    "45 CFR § 164.316": [
      "CO-WF-13"
    ],
    "42 CFR § 1001.1901": [
      "CO-WF-15"
    ],
    "42 CFR § 401.305": [
      "CO-WF-16",
      "FN-WF-08"
    ],
    "HIPAA § 164.316": [
      "EN-WF-01",
      "EN-WF-06",
      "EN-WF-08"
    ],
    "42 CFR § 484.105": [
      "EN-WF-02",
      "OP-WF-01"
    ],
    "HIPAA § 164.530": [
      "EN-WF-03",
      "HR-WF-07"
    ],
    "42 CFR § 484.105(h)(4)": [
      "FN-WF-01"
    ],
    "42 CFR § 413.20": [
      "FN-WF-03"
    ],
    "42 CFR § 405.940": [
      "FN-WF-05"
    ],
    "42 CFR § 401.605": [
      "FN-WF-07"
    ],
    "42 CFR § 484.105(c)": [
      "GV-WF-04"
    ],
    "42 CFR § 484.105(h)": [
      "GV-WF-05"
    ],
    "42 CFR § 484.105(i)(1)": [
      "GV-WF-06",
      "OP-WF-08"
    ],
    "42 CFR § 484.105(i)(2)(ii)": [
      "GV-WF-07"
    ],
    "42 CFR § 411.354": [
      "GV-WF-08"
    ],
    "42 CFR § 489": [
      "GV-WF-09"
    ],
    "42 CFR § 489.18": [
      "GV-WF-10"
    ],
    "42 CFR § 484.105(f)": [
      "GV-WF-11",
      "OP-WF-03",
      "OP-WF-13"
    ],
    "42 CFR § 484.105(a)": [
      "GV-WF-13"
    ],
    "42 CFR § 484.80": [
      "HR-WF-18",
      "HR-WF-05"
    ],
    "HIPAA § 164.308": [
      "IT-WF-21",
      "IT-WF-25"
    ],
    "HIPAA § 164.312": [
      "IT-WF-23",
      "IT-WF-24"
    ],
    "42 CFR § 484.102": [
      "IT-WF-08",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-06"
    ],
    "45 CFR § 164.310": [
      "IT-WF-11",
      "IT-WF-12",
      "IT-WF-17",
      "IT-WF-19"
    ],
    "45 CFR § 164.524": [
      "IT-WF-20"
    ],
    "42 CFR § 484.50(a)": [
      "OP-WF-11"
    ],
    "42 CFR § 484.65(b)": [
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-02",
      "RM-WF-16",
      "RM-WF-20"
    ],
    "42 CFR § 484.65(c)": [
      "QA-WF-17"
    ],
    "42 CFR § 484.65(a)": [
      "QA-WF-01"
    ],
    "42 CFR § 484.65(b)(3)": [
      "QA-WF-03"
    ],
    "42 CFR § 484.65(d)": [
      "QA-WF-04"
    ],
    "42 CFR § 484.65(b)(1)(ii)": [
      "QA-WF-05"
    ],
    "42 CFR § 484.215": [
      "QA-WF-07"
    ],
    "42 CFR § 484.245(b)(1)(iii)": [
      "QA-WF-08"
    ],
    "42 CFR § 484.245": [
      "QA-WF-09"
    ],
    "42 CFR § 484.65(e)": [
      "QA-WF-10"
    ],
    "42 CFR § 484.102(a)": [
      "RM-WF-02",
      "RM-WF-03"
    ],
    "42 CFR § 484.102(d)(1)": [
      "RM-WF-04"
    ],
    "42 CFR § 484.102(d)(2)": [
      "RM-WF-05"
    ],
    "42 CFR § 484.102(b)": [
      "RM-WF-07"
    ],
    "CCR § 3203": [
      "RM-WF-08"
    ]
  },
  "byRole": {
    "QA Reviewer (RN)": [
      "CL-WF-26"
    ],
    "Clinical Manager": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-30",
      "CL-WF-31",
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-32",
      "CL-WF-33",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-34",
      "CL-WF-35",
      "CL-WF-35",
      "CL-WF-36",
      "CL-WF-36",
      "CL-WF-37",
      "CL-WF-37",
      "CL-WF-01",
      "CL-WF-04",
      "CL-WF-05",
      "CL-WF-07",
      "CL-WF-08",
      "CL-WF-10",
      "CL-WF-12",
      "CL-WF-17",
      "CL-WF-19",
      "CL-WF-20",
      "CL-WF-21",
      "CL-WF-24",
      "CL-WF-25",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-04",
      "CO-WF-05",
      "CO-WF-06",
      "CO-WF-08",
      "CO-WF-14",
      "CO-WF-19",
      "CO-WF-20",
      "FN-WF-06",
      "FN-WF-15",
      "GV-WF-01",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-10",
      "GV-WF-13",
      "HR-WF-19",
      "HR-WF-19",
      "HR-WF-05",
      "IT-WF-08",
      "OP-WF-01",
      "OP-WF-08",
      "OP-WF-08",
      "OP-WF-10",
      "OP-WF-10",
      "OP-WF-12",
      "QA-WF-14",
      "QA-WF-02",
      "QA-WF-03",
      "QA-WF-05",
      "QA-WF-09",
      "QA-WF-10",
      "RM-WF-19",
      "RM-WF-20",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-07",
      "RM-WF-07",
      "RM-WF-13",
      "RM-WF-13"
    ],
    "Medical Records": [
      "CL-WF-26",
      "CL-WF-37",
      "CO-WF-12",
      "FN-WF-06"
    ],
    "Clinical Manager (audit report)": [
      "CL-WF-26"
    ],
    "Compliance Officer (CAP if systemic)": [
      "CL-WF-26"
    ],
    "OASIS QA Specialist": [
      "CL-WF-27"
    ],
    "Coder": [
      "CL-WF-27",
      "CL-WF-30",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-14",
      "FN-WF-04",
      "FN-WF-06"
    ],
    "Compliance Officer for systemic": [
      "CL-WF-27",
      "CL-WF-29",
      "CO-WF-26",
      "HR-WF-18"
    ],
    "QA Reviewer": [
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-36",
      "CL-WF-37"
    ],
    "Medical Records Auditor": [
      "CL-WF-29"
    ],
    "UR Nurse": [
      "CL-WF-30"
    ],
    "Compliance Officer for billing-impactful patterns": [
      "CL-WF-30"
    ],
    "Pharmacist Reviewer / RN auditor": [
      "CL-WF-31"
    ],
    "Medical Director for systemic": [
      "CL-WF-31"
    ],
    "Infection Preventionist": [
      "CL-WF-32",
      "CL-WF-14",
      "QA-WF-01",
      "QA-WF-03",
      "RM-WF-06"
    ],
    "Medical Director for cluster events": [
      "CL-WF-32"
    ],
    "Medical Director if pattern": [
      "CL-WF-34"
    ],
    "QA Analyst": [
      "CL-WF-35",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-17"
    ],
    "QAPI Lead": [
      "CL-WF-35",
      "CO-WF-05",
      "CO-WF-19",
      "GV-WF-01",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-17",
      "QA-WF-02",
      "QA-WF-04",
      "QA-WF-05",
      "QA-WF-06",
      "QA-WF-08",
      "QA-WF-09",
      "QA-WF-10",
      "QA-WF-11",
      "RM-WF-16"
    ],
    "Scheduler": [
      "CL-WF-36",
      "CL-WF-20",
      "OP-WF-12"
    ],
    "Intake Coordinator / Admissions Nurse": [
      "CL-WF-01"
    ],
    "Insurance Verifier": [
      "CL-WF-01",
      "OP-WF-07"
    ],
    "Physician liaison": [
      "CL-WF-01"
    ],
    "Clinical Manager (acceptance decisions": [
      "CL-WF-01"
    ],
    "non-admits)": [
      "CL-WF-01"
    ],
    "Admitting RN": [
      "CL-WF-02",
      "CL-WF-16",
      "OP-WF-07"
    ],
    "Case Manager": [
      "CL-WF-02",
      "CL-WF-18",
      "CL-WF-19",
      "CL-WF-20",
      "CL-WF-24",
      "OP-WF-12",
      "RM-WF-07"
    ],
    "Physician": [
      "CL-WF-02",
      "CL-WF-03",
      "CL-WF-06",
      "CL-WF-07",
      "CL-WF-12",
      "CL-WF-13"
    ],
    "Clinical Mgr": [
      "CL-WF-02",
      "CL-WF-03",
      "CL-WF-06",
      "CL-WF-10",
      "CL-WF-11",
      "CL-WF-13",
      "CL-WF-14",
      "CL-WF-18",
      "CL-WF-18",
      "CL-WF-19",
      "CL-WF-20",
      "CL-WF-22",
      "CL-WF-24",
      "FN-WF-14",
      "OP-WF-11",
      "OP-WF-12",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-06",
      "RM-WF-08",
      "RM-WF-09",
      "RM-WF-10"
    ],
    "Clinical Manager (quarterly spot-audit)": [
      "CL-WF-02"
    ],
    "Intake/Clinical Liaison": [
      "CL-WF-03"
    ],
    "Billing": [
      "CL-WF-03",
      "CO-WF-14",
      "FN-WF-07",
      "FN-WF-08",
      "FN-WF-09",
      "FN-WF-10",
      "FN-WF-14",
      "FN-WF-15"
    ],
    "Admitting RN (or PT for therapy-only case under state scope)": [
      "CL-WF-04"
    ],
    "Disciplines for specialty components": [
      "CL-WF-04"
    ],
    "Assessing clinician": [
      "CL-WF-05"
    ],
    "OASIS QA Reviewer": [
      "CL-WF-05"
    ],
    "OASIS Coordinator": [
      "CL-WF-05"
    ],
    "Assessing clinician (RN / PT)": [
      "CL-WF-06"
    ],
    "All disciplines (for discipline-specific orders)": [
      "CL-WF-06"
    ],
    "Physician signature": [
      "CL-WF-06",
      "CL-WF-07"
    ],
    "Clinician receiving order": [
      "CL-WF-07"
    ],
    "Office": [
      "CL-WF-07"
    ],
    "Case Manager (RN)": [
      "CL-WF-08"
    ],
    "All disciplines": [
      "CL-WF-08",
      "CL-WF-19"
    ],
    "Visiting clinician": [
      "CL-WF-09",
      "CL-WF-14",
      "CL-WF-20"
    ],
    "Clinical Manager (QA)": [
      "CL-WF-09",
      "CL-WF-21"
    ],
    "Clinical Manager (periodic QA)": [
      "CL-WF-09"
    ],
    "RN Supervisor": [
      "CL-WF-10"
    ],
    "HHA": [
      "CL-WF-10"
    ],
    "Staff Development RN": [
      "CL-WF-11",
      "HR-WF-19"
    ],
    "HR": [
      "CL-WF-11",
      "CL-WF-25",
      "CO-WF-01",
      "CO-WF-03",
      "CO-WF-06",
      "CO-WF-08",
      "CO-WF-09",
      "CO-WF-21",
      "EN-WF-08",
      "GV-WF-10",
      "HR-WF-19",
      "HR-WF-08",
      "HR-WF-11",
      "HR-WF-13",
      "HR-WF-14",
      "HR-WF-17",
      "IT-WF-21",
      "IT-WF-03",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-06",
      "RM-WF-16",
      "RM-WF-03",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-06",
      "RM-WF-08",
      "RM-WF-09"
    ],
    "Staff Dev RN": [
      "CL-WF-11"
    ],
    "RN": [
      "CL-WF-12"
    ],
    "Pharmacy consultant": [
      "CL-WF-12",
      "RM-WF-13"
    ],
    "Visiting RN (wound certified preferred)": [
      "CL-WF-13"
    ],
    "PT/OT for functional": [
      "CL-WF-13"
    ],
    "wound consultant": [
      "CL-WF-13"
    ],
    "Clinical Manager / Wound Expert": [
      "CL-WF-13"
    ],
    "Clinician": [
      "CL-WF-15"
    ],
    "Patient/caregiver": [
      "CL-WF-15"
    ],
    "IT": [
      "CL-WF-15",
      "CO-WF-04",
      "CO-WF-06",
      "CO-WF-11",
      "EN-WF-08",
      "HR-WF-03",
      "HR-WF-14",
      "IT-WF-04",
      "IT-WF-15",
      "IT-WF-19",
      "QA-WF-02",
      "QA-WF-04",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-05"
    ],
    "Physician (order)": [
      "CL-WF-15"
    ],
    "Clinical Mgr (operations)": [
      "CL-WF-15"
    ],
    "Intake": [
      "CL-WF-16",
      "FN-WF-04"
    ],
    "Social Work": [
      "CL-WF-16"
    ],
    "Admitting RN attests": [
      "CL-WF-16"
    ],
    "Clinician (discipline-appropriate)": [
      "CL-WF-17"
    ],
    "MSW": [
      "CL-WF-17",
      "CL-WF-19",
      "CL-WF-22",
      "CL-WF-23",
      "CL-WF-24"
    ],
    "Staff Dev": [
      "CL-WF-17"
    ],
    "Recert clinician": [
      "CL-WF-18"
    ],
    "physician": [
      "CL-WF-18",
      "CL-WF-19",
      "CL-WF-19",
      "CL-WF-24"
    ],
    "Physician (new orders)": [
      "CL-WF-18"
    ],
    "Clinician (author)": [
      "CL-WF-21"
    ],
    "Records": [
      "CL-WF-21"
    ],
    "Any clinician (mandatory reporter)": [
      "CL-WF-22"
    ],
    "Compliance": [
      "CL-WF-22",
      "FN-WF-05",
      "HR-WF-14",
      "IT-WF-01",
      "IT-WF-15",
      "OP-WF-03",
      "OP-WF-04",
      "OP-WF-05",
      "OP-WF-06",
      "QA-WF-06",
      "RM-WF-03"
    ],
    "Legal": [
      "CL-WF-22",
      "CO-WF-27",
      "CO-WF-01",
      "CO-WF-03",
      "CO-WF-05",
      "CO-WF-06",
      "CO-WF-07",
      "CO-WF-10",
      "CO-WF-11",
      "CO-WF-18",
      "EN-WF-05",
      "EN-WF-08",
      "FN-WF-08",
      "FN-WF-14",
      "HR-WF-10",
      "HR-WF-12",
      "HR-WF-16",
      "HR-WF-17",
      "IT-WF-09",
      "OP-WF-03",
      "QA-WF-12"
    ],
    "Administrator briefed": [
      "CL-WF-22"
    ],
    "Clinical Manager / Designated Grievance Officer": [
      "CL-WF-23"
    ],
    "Clinicians": [
      "CL-WF-23"
    ],
    "Compliance Officer": [
      "CL-WF-23",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-27",
      "CO-WF-28",
      "CO-WF-29",
      "CO-WF-30",
      "CO-WF-01",
      "CO-WF-02",
      "CO-WF-02",
      "CO-WF-03",
      "CO-WF-05",
      "CO-WF-06",
      "CO-WF-07",
      "CO-WF-07",
      "CO-WF-08",
      "CO-WF-09",
      "CO-WF-11",
      "CO-WF-11",
      "CO-WF-13",
      "CO-WF-14",
      "CO-WF-15",
      "CO-WF-15",
      "CO-WF-19",
      "CO-WF-21",
      "CO-WF-21",
      "CO-WF-22",
      "EN-WF-01",
      "EN-WF-03",
      "EN-WF-04",
      "EN-WF-04",
      "EN-WF-05",
      "EN-WF-06",
      "EN-WF-07",
      "EN-WF-08",
      "EN-WF-13",
      "GV-WF-01",
      "GV-WF-02",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-05",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-09",
      "GV-WF-10",
      "GV-WF-12",
      "GV-WF-13",
      "HR-WF-20",
      "HR-WF-20",
      "HR-WF-03",
      "HR-WF-04",
      "IT-WF-22",
      "IT-WF-23",
      "OP-WF-01",
      "QA-WF-18",
      "QA-WF-01",
      "QA-WF-03",
      "QA-WF-08",
      "QA-WF-10",
      "RM-WF-16",
      "RM-WF-20",
      "RM-WF-20",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-10",
      "RM-WF-14",
      "RM-WF-15"
    ],
    "Specialty-trained clinician": [
      "CL-WF-24"
    ],
    "specialty consultant": [
      "CL-WF-24"
    ],
    "Staff Development RN / Clinical Manager": [
      "CL-WF-25"
    ],
    "discipline leaders": [
      "CL-WF-25"
    ],
    "Billing Auditor": [
      "CO-WF-23",
      "CO-WF-25",
      "CO-WF-29"
    ],
    "Administrator for systemic holds": [
      "CO-WF-23"
    ],
    "Compliance Auditor": [
      "CO-WF-24",
      "CO-WF-27"
    ],
    "Governing Body informed for material findings": [
      "CO-WF-24"
    ],
    "Coder Auditor (HCS-D / BCHH-C)": [
      "CO-WF-26"
    ],
    "Governing Body for material": [
      "CO-WF-27"
    ],
    "Compliance Officer for routine": [
      "CO-WF-27"
    ],
    "Insurance Verifier / Billing Auditor": [
      "CO-WF-28"
    ],
    "Intake Coord": [
      "CO-WF-28",
      "OP-WF-11"
    ],
    "Revenue Integrity Lead": [
      "CO-WF-29"
    ],
    "CFO/Controller": [
      "CO-WF-29"
    ],
    "Domain Owners (CAP owners)": [
      "CO-WF-30"
    ],
    "Compliance Officer (closure attestation)": [
      "CO-WF-30"
    ],
    "Administrator for >30-day overdue": [
      "CO-WF-30"
    ],
    "Administrator": [
      "CO-WF-01",
      "CO-WF-05",
      "CO-WF-06",
      "CO-WF-07",
      "CO-WF-10",
      "CO-WF-16",
      "CO-WF-19",
      "CO-WF-20",
      "EN-WF-05",
      "EN-WF-10",
      "EN-WF-11",
      "EN-WF-12",
      "FN-WF-01",
      "FN-WF-02",
      "FN-WF-03",
      "FN-WF-06",
      "FN-WF-08",
      "FN-WF-14",
      "GV-WF-02",
      "GV-WF-04",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-09",
      "GV-WF-10",
      "GV-WF-11",
      "GV-WF-13",
      "HR-WF-01",
      "HR-WF-03",
      "HR-WF-04",
      "HR-WF-07",
      "HR-WF-12",
      "HR-WF-13",
      "HR-WF-15",
      "HR-WF-16",
      "IT-WF-01",
      "IT-WF-04",
      "IT-WF-07",
      "IT-WF-08",
      "IT-WF-09",
      "IT-WF-15",
      "IT-WF-19",
      "OP-WF-01",
      "OP-WF-02",
      "OP-WF-03",
      "OP-WF-04",
      "OP-WF-05",
      "OP-WF-05",
      "OP-WF-09",
      "OP-WF-11",
      "QA-WF-14",
      "QA-WF-01",
      "QA-WF-03",
      "QA-WF-08",
      "QA-WF-08",
      "QA-WF-10",
      "QA-WF-12",
      "QA-WF-12",
      "RM-WF-16",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-03",
      "RM-WF-05",
      "RM-WF-05",
      "RM-WF-06",
      "RM-WF-08",
      "RM-WF-09",
      "RM-WF-10",
      "RM-WF-11",
      "RM-WF-12",
      "RM-WF-15"
    ],
    "Governing Body": [
      "CO-WF-01",
      "CO-WF-16",
      "EN-WF-02",
      "EN-WF-09",
      "EN-WF-12",
      "FN-WF-01",
      "FN-WF-13",
      "GV-WF-05",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-10",
      "GV-WF-10",
      "IT-WF-08",
      "OP-WF-01",
      "QA-WF-01",
      "QA-WF-04",
      "QA-WF-10",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-15"
    ],
    "HR Director": [
      "CO-WF-02",
      "CO-WF-20",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-08",
      "HR-WF-02",
      "HR-WF-08",
      "HR-WF-09",
      "HR-WF-09",
      "HR-WF-10",
      "HR-WF-11",
      "HR-WF-14"
    ],
    "Department Head": [
      "CO-WF-03"
    ],
    "Clinical Manager (if clinical)": [
      "CO-WF-03",
      "CO-WF-18"
    ],
    "Compliance Committee for complex investigations": [
      "CO-WF-03"
    ],
    "Governing Body for findings with material exposure.": [
      "CO-WF-03"
    ],
    "Compliance Officer / Internal Auditor": [
      "CO-WF-04",
      "CO-WF-14"
    ],
    "Department heads": [
      "CO-WF-04",
      "FN-WF-01",
      "RM-WF-01"
    ],
    "Finance": [
      "CO-WF-04",
      "CO-WF-06",
      "CO-WF-07",
      "CO-WF-08",
      "CO-WF-11",
      "CO-WF-16",
      "CO-WF-20",
      "CO-WF-22",
      "EN-WF-08",
      "GV-WF-10",
      "GV-WF-11",
      "OP-WF-05",
      "QA-WF-02",
      "QA-WF-07",
      "RM-WF-01"
    ],
    "Compliance Committee": [
      "CO-WF-04",
      "CO-WF-08",
      "CO-WF-18"
    ],
    "Governing Body (annual plan)": [
      "CO-WF-04"
    ],
    "all department heads": [
      "CO-WF-05"
    ],
    "Administrator (PoC)": [
      "CO-WF-05"
    ],
    "Governing Body (for Condition-Level)": [
      "CO-WF-05"
    ],
    "Governing Body (material changes)": [
      "CO-WF-06"
    ],
    "Legal Counsel for novel arrangements": [
      "CO-WF-07"
    ],
    "Governing Body for material arrangements": [
      "CO-WF-07"
    ],
    "Compliance Officer (Privacy)": [
      "CO-WF-09"
    ],
    "IT Administrator (Security)": [
      "CO-WF-09"
    ],
    "Compliance Officer (Privacy Officer)": [
      "CO-WF-10"
    ],
    "IT Administrator (Security Officer)": [
      "CO-WF-10"
    ],
    "Compliance Officer for low-probability-of-compromise determinations": [
      "CO-WF-10"
    ],
    "Legal + Administrator for notifications": [
      "CO-WF-10"
    ],
    "Governing Body for 500+ breaches": [
      "CO-WF-10"
    ],
    "contracting parties": [
      "CO-WF-11"
    ],
    "Compliance Officer / Privacy Officer": [
      "CO-WF-12",
      "IT-WF-21"
    ],
    "Clinical Records Clerk": [
      "CO-WF-12"
    ],
    "Clinical/Intake Staff": [
      "CO-WF-12"
    ],
    "IT (for EHR access reports)": [
      "CO-WF-12"
    ],
    "Compliance Officer for non-routine/sensitive requests": [
      "CO-WF-12"
    ],
    "Records Custodian (under Compliance Officer)": [
      "CO-WF-13"
    ],
    "IT (electronic)": [
      "CO-WF-13"
    ],
    "Legal (holds)": [
      "CO-WF-13"
    ],
    "department owners": [
      "CO-WF-13"
    ],
    "HR (maintains roster)": [
      "CO-WF-15"
    ],
    "Compliance Officer + Legal Counsel": [
      "CO-WF-16"
    ],
    "IT Administrator (Security Officer) + Compliance Officer (Privacy)": [
      "CO-WF-17"
    ],
    "IT team": [
      "CO-WF-17",
      "IT-WF-01"
    ],
    "Clinical": [
      "CO-WF-17",
      "CO-WF-22",
      "QA-WF-04",
      "RM-WF-01",
      "RM-WF-11"
    ],
    "Ops": [
      "CO-WF-17",
      "RM-WF-11",
      "RM-WF-12"
    ],
    "Governing Body (material risks)": [
      "CO-WF-17"
    ],
    "Compliance Officer + IT Administrator": [
      "CO-WF-18"
    ],
    "Governing Body (material/high-risk)": [
      "CO-WF-18"
    ],
    "Governing Body annually": [
      "CO-WF-19"
    ],
    "Compliance Officer (Chair)": [
      "CO-WF-20"
    ],
    "IT Administrator": [
      "CO-WF-20"
    ],
    "Legal (as needed)": [
      "CO-WF-20",
      "EN-WF-01"
    ],
    "Compliance Committee by quorum": [
      "CO-WF-20"
    ],
    "Clinical Records": [
      "CO-WF-21"
    ],
    "IT (data)": [
      "CO-WF-22"
    ],
    "Governing Body review": [
      "CO-WF-22"
    ],
    "Policy Owner (domain SME)": [
      "EN-WF-01"
    ],
    "subject committees": [
      "EN-WF-01"
    ],
    "Governing Body for REQUIRED (Tier 1) policies": [
      "EN-WF-01"
    ],
    "Administrator + Compliance for others per matrix": [
      "EN-WF-01"
    ],
    "Compliance Officer / Policy Committee": [
      "EN-WF-02"
    ],
    "All Policy Owners": [
      "EN-WF-02"
    ],
    "HR + Compliance": [
      "EN-WF-03"
    ],
    "Supervisors": [
      "EN-WF-03"
    ],
    "IT/LMS": [
      "EN-WF-03"
    ],
    "Policy Administrator": [
      "EN-WF-04",
      "EN-WF-06"
    ],
    "Policy Owners": [
      "EN-WF-04",
      "EN-WF-05",
      "EN-WF-07",
      "QA-WF-11"
    ],
    "Governing Body for material changes": [
      "EN-WF-05"
    ],
    "IT (portal)": [
      "EN-WF-06"
    ],
    "Forms Library Administrator": [
      "EN-WF-07"
    ],
    "QAPI (feedback)": [
      "EN-WF-07"
    ],
    "Records Manager / Compliance": [
      "EN-WF-08"
    ],
    "Administrator for destruction cycles": [
      "EN-WF-08"
    ],
    "Compliance Officer + Administrator": [
      "EN-WF-09"
    ],
    "Domain owners": [
      "EN-WF-09"
    ],
    "CFO + Compliance Officer": [
      "EN-WF-10",
      "FN-WF-15"
    ],
    "Department owners": [
      "EN-WF-10"
    ],
    "Governing Body acceptance": [
      "EN-WF-10"
    ],
    "Compliance Officer (internal audit)": [
      "EN-WF-11"
    ],
    "Functional owners": [
      "EN-WF-11"
    ],
    "Governing Body (audit committee)": [
      "EN-WF-11"
    ],
    "Risk Manager + Compliance Officer": [
      "EN-WF-12"
    ],
    "All domain owners": [
      "EN-WF-12"
    ],
    "All Dept Heads": [
      "EN-WF-13"
    ],
    "Administrator + CFO": [
      "EN-WF-13"
    ],
    "Governing Body accepts": [
      "EN-WF-13"
    ],
    "CFO / Finance Director": [
      "FN-WF-01"
    ],
    "Controller": [
      "FN-WF-02",
      "FN-WF-03",
      "FN-WF-11",
      "FN-WF-13"
    ],
    "Finance team": [
      "FN-WF-02"
    ],
    "CFO": [
      "FN-WF-02",
      "FN-WF-03",
      "FN-WF-05",
      "FN-WF-06",
      "FN-WF-07",
      "FN-WF-12",
      "FN-WF-13",
      "FN-WF-14",
      "HR-WF-17"
    ],
    "external cost-report preparer": [
      "FN-WF-03"
    ],
    "Governing Body briefed": [
      "FN-WF-03",
      "FN-WF-08",
      "HR-WF-12",
      "HR-WF-13",
      "IT-WF-01",
      "QA-WF-09"
    ],
    "Billing Manager": [
      "FN-WF-04"
    ],
    "Clinical Manager (docs)": [
      "FN-WF-04"
    ],
    "CFO (reviews exception claims)": [
      "FN-WF-04"
    ],
    "Denial Management Specialist": [
      "FN-WF-05"
    ],
    "Clinical Manager (medical review)": [
      "FN-WF-05"
    ],
    "ADR Coordinator (Billing/Compliance)": [
      "FN-WF-06"
    ],
    "AR Supervisor": [
      "FN-WF-07",
      "FN-WF-09"
    ],
    "Administrator (certifies)": [
      "FN-WF-07"
    ],
    "Compliance Officer + CFO": [
      "FN-WF-08"
    ],
    "Coders": [
      "FN-WF-08",
      "FN-WF-15"
    ],
    "Patient Financial Counselor": [
      "FN-WF-09",
      "FN-WF-10"
    ],
    "CFO (write-offs over threshold)": [
      "FN-WF-09"
    ],
    "Administrator (large bundles)": [
      "FN-WF-09"
    ],
    "Social Worker": [
      "FN-WF-10"
    ],
    "CFO for charity approvals per threshold": [
      "FN-WF-10"
    ],
    "AP Clerk": [
      "FN-WF-11"
    ],
    "Dept Mgr (approval)": [
      "FN-WF-11"
    ],
    "CFO for payments over threshold": [
      "FN-WF-11"
    ],
    "Payroll Specialist / Manager": [
      "FN-WF-12"
    ],
    "HR (rates": [
      "FN-WF-12"
    ],
    "changes)": [
      "FN-WF-12"
    ],
    "IT (system)": [
      "FN-WF-12"
    ],
    "Audit Committee (Board)": [
      "FN-WF-13"
    ],
    "external auditor": [
      "FN-WF-13"
    ],
    "Governing Body (major changes)": [
      "FN-WF-14"
    ],
    "Revenue Integrity Analyst / Compliance Auditor": [
      "FN-WF-15"
    ],
    "Governing Body Chair": [
      "GV-WF-01",
      "GV-WF-02",
      "GV-WF-03"
    ],
    "Administrator (prepares agenda & packet)": [
      "GV-WF-01"
    ],
    "Secretary (minutes drafting)": [
      "GV-WF-01"
    ],
    "Governing Body (quorum vote)": [
      "GV-WF-01"
    ],
    "minutes approved at next meeting": [
      "GV-WF-01"
    ],
    "external governance consultant (optional)": [
      "GV-WF-02"
    ],
    "Governing Body full vote": [
      "GV-WF-02"
    ],
    "Legal Counsel": [
      "GV-WF-03",
      "GV-WF-09",
      "GV-WF-10",
      "GV-WF-11",
      "GV-WF-12",
      "GV-WF-14"
    ],
    "Governing Body (appointment)": [
      "GV-WF-03"
    ],
    "Administrator (delegation of daily authority)": [
      "GV-WF-03"
    ],
    "Governing Body (confirmation)": [
      "GV-WF-04"
    ],
    "Administrator (preparer)": [
      "GV-WF-05"
    ],
    "CFO/Finance": [
      "GV-WF-05"
    ],
    "Clinical Manager (staffing & case-mix input)": [
      "GV-WF-05"
    ],
    "Marketing/External Affairs": [
      "GV-WF-07"
    ],
    "Compliance Officer (administrator of process)": [
      "GV-WF-08"
    ],
    "Governing Body Chair reviews Administrator": [
      "GV-WF-08"
    ],
    "Governing Body reviews Chair's disclosures.": [
      "GV-WF-08"
    ],
    "Finance (fees)": [
      "GV-WF-09"
    ],
    "Governing Body (annual review)": [
      "GV-WF-09"
    ],
    "Compliance Officer (Stark/AKS & BAA review)": [
      "GV-WF-11"
    ],
    "Clinical Manager (clinical services)": [
      "GV-WF-11"
    ],
    "Governing Body for all contracts >$50": [
      "GV-WF-11"
    ],
    "000/year OR with referral sources OR management service agreements": [
      "GV-WF-11"
    ],
    "Administrator / External Affairs": [
      "GV-WF-12"
    ],
    "Clinical Manager (for clinical matters)": [
      "GV-WF-12"
    ],
    "Administrator (routine)": [
      "GV-WF-12"
    ],
    "Governing Body Chair (high-risk)": [
      "GV-WF-12"
    ],
    "Chair": [
      "GV-WF-13",
      "GV-WF-14"
    ],
    "Secretary": [
      "GV-WF-14"
    ],
    "Compliance Officer (as invited)": [
      "GV-WF-14"
    ],
    "Training Coordinator": [
      "HR-WF-18"
    ],
    "HR Manager": [
      "HR-WF-18",
      "HR-WF-18",
      "HR-WF-21",
      "HR-WF-21"
    ],
    "Department Heads": [
      "HR-WF-18",
      "QA-WF-11"
    ],
    "Director of Nursing for specialty competencies": [
      "HR-WF-19"
    ],
    "HR Compliance Specialist": [
      "HR-WF-20",
      "HR-WF-21"
    ],
    "Administrator for any hit": [
      "HR-WF-20"
    ],
    "Compliance Officer for systemic gaps": [
      "HR-WF-21"
    ],
    "HR Director / Recruiter": [
      "HR-WF-01"
    ],
    "Hiring Manager": [
      "HR-WF-01",
      "HR-WF-03"
    ],
    "Finance (budget)": [
      "HR-WF-01"
    ],
    "Compliance (JD review for excluded roles)": [
      "HR-WF-01"
    ],
    "HR Specialist": [
      "HR-WF-02",
      "HR-WF-04"
    ],
    "Compliance (exclusion review)": [
      "HR-WF-02"
    ],
    "Legal (adverse action)": [
      "HR-WF-02"
    ],
    "Administrator for exceptions": [
      "HR-WF-02"
    ],
    "HR Onboarding Specialist": [
      "HR-WF-03"
    ],
    "RN Instructor / Clinical Mgr": [
      "HR-WF-05"
    ],
    "HR Training Coordinator": [
      "HR-WF-05",
      "HR-WF-06"
    ],
    "Clinical Manager / Discipline lead": [
      "HR-WF-06"
    ],
    "Clinical Manager / Administrator": [
      "HR-WF-06"
    ],
    "HR Training Coordinator + Compliance Officer": [
      "HR-WF-07"
    ],
    "Clinical Educator": [
      "HR-WF-07"
    ],
    "Risk Manager": [
      "HR-WF-07",
      "OP-WF-09",
      "QA-WF-05",
      "QA-WF-12",
      "RM-WF-16",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-20",
      "RM-WF-01",
      "RM-WF-11",
      "RM-WF-14",
      "RM-WF-15"
    ],
    "Governing Body reviews completion": [
      "HR-WF-07"
    ],
    "Supervisor": [
      "HR-WF-08",
      "HR-WF-09",
      "HR-WF-10",
      "HR-WF-11",
      "HR-WF-13",
      "HR-WF-14"
    ],
    "Clinical Manager (clinical)": [
      "HR-WF-08"
    ],
    "Administrator (executives)": [
      "HR-WF-08"
    ],
    "Legal (termination)": [
      "HR-WF-09"
    ],
    "Administrator for termination": [
      "HR-WF-09",
      "HR-WF-14"
    ],
    "HR Leave Administrator": [
      "HR-WF-10"
    ],
    "Occ Health": [
      "HR-WF-11",
      "HR-WF-13"
    ],
    "HR Director / outside investigator for exec complaints": [
      "HR-WF-12"
    ],
    "Compliance (if overlap with retaliation)": [
      "HR-WF-12"
    ],
    "Risk Manager / Safety Officer": [
      "HR-WF-13"
    ],
    "Payroll": [
      "HR-WF-14"
    ],
    "Compliance Officer / HR": [
      "HR-WF-15"
    ],
    "HR Director + CFO": [
      "HR-WF-16"
    ],
    "Payroll + Supervisors": [
      "HR-WF-17"
    ],
    "IT Security Officer": [
      "IT-WF-21",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25",
      "RM-WF-20"
    ],
    "Application Owners": [
      "IT-WF-21",
      "IT-WF-24"
    ],
    "Privacy Officer": [
      "IT-WF-22",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-24",
      "IT-WF-25",
      "IT-WF-09",
      "IT-WF-20"
    ],
    "Administrator for material findings": [
      "IT-WF-22",
      "IT-WF-25"
    ],
    "Compliance Officer for breach determination": [
      "IT-WF-23"
    ],
    "IT Operations": [
      "IT-WF-25"
    ],
    "IT Director": [
      "IT-WF-25"
    ],
    "Security Officer (may coincide with Privacy Officer)": [
      "IT-WF-01"
    ],
    "external assessor (optional)": [
      "IT-WF-01"
    ],
    "IT Access Admin": [
      "IT-WF-02",
      "IT-WF-03"
    ],
    "HR (role)": [
      "IT-WF-02"
    ],
    "Security Officer": [
      "IT-WF-02",
      "IT-WF-03",
      "IT-WF-04",
      "IT-WF-04",
      "IT-WF-05",
      "IT-WF-07",
      "IT-WF-10",
      "IT-WF-11",
      "IT-WF-11",
      "IT-WF-12",
      "IT-WF-13",
      "IT-WF-14",
      "IT-WF-15",
      "IT-WF-16",
      "IT-WF-16",
      "IT-WF-17",
      "IT-WF-17",
      "IT-WF-18",
      "IT-WF-19"
    ],
    "Department Manager": [
      "IT-WF-02"
    ],
    "Security Officer for elevated access": [
      "IT-WF-02"
    ],
    "HR Director / Security Officer": [
      "IT-WF-03"
    ],
    "Dept Managers (attestation)": [
      "IT-WF-04"
    ],
    "IT Security": [
      "IT-WF-05",
      "IT-WF-12"
    ],
    "Users": [
      "IT-WF-05"
    ],
    "Security Officer / IT SecOps": [
      "IT-WF-06"
    ],
    "System owners": [
      "IT-WF-06"
    ],
    "Administrator (periodic review)": [
      "IT-WF-06"
    ],
    "IT Infrastructure Lead": [
      "IT-WF-07"
    ],
    "Security Officer / IT Lead": [
      "IT-WF-08"
    ],
    "EP Coordinator": [
      "IT-WF-08",
      "RM-WF-03",
      "RM-WF-04",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-05",
      "RM-WF-06"
    ],
    "Security Officer / CISO (or equivalent)": [
      "IT-WF-09"
    ],
    "IT SecOps": [
      "IT-WF-09",
      "IT-WF-16"
    ],
    "External DFIR": [
      "IT-WF-09"
    ],
    "Governing Body (material incidents)": [
      "IT-WF-09"
    ],
    "IT Endpoint Admin": [
      "IT-WF-10"
    ],
    "Security Officer for exceptions": [
      "IT-WF-10"
    ],
    "IT Mobile Admin": [
      "IT-WF-11"
    ],
    "IT Security / SysAdmin": [
      "IT-WF-13"
    ],
    "IT Change Manager": [
      "IT-WF-14"
    ],
    "Dev/Ops teams": [
      "IT-WF-14"
    ],
    "Change Advisory Board (CAB)": [
      "IT-WF-14"
    ],
    "Procurement (OP-WF-03)": [
      "IT-WF-15"
    ],
    "HR (training)": [
      "IT-WF-16"
    ],
    "IT Asset Mgmt": [
      "IT-WF-17"
    ],
    "certified destruction vendor": [
      "IT-WF-17"
    ],
    "IT NetOps / Security Officer": [
      "IT-WF-18"
    ],
    "Facilities Mgr": [
      "IT-WF-19"
    ],
    "Privacy Officer / Medical Records": [
      "IT-WF-20"
    ],
    "IT (data extraction)": [
      "IT-WF-20"
    ],
    "Branch Manager": [
      "OP-WF-01"
    ],
    "Facilities Manager / Office Administrator": [
      "OP-WF-02"
    ],
    "Risk Manager (IIPP overlap)": [
      "OP-WF-02"
    ],
    "IT (server room)": [
      "OP-WF-02"
    ],
    "Procurement / Administrator": [
      "OP-WF-03"
    ],
    "Requesting department": [
      "OP-WF-03"
    ],
    "IT (if data)": [
      "OP-WF-03"
    ],
    "Governing Body for material contracts": [
      "OP-WF-03"
    ],
    "Procurement": [
      "OP-WF-04"
    ],
    "Procurement / EP Coord": [
      "OP-WF-05"
    ],
    "Office Administrator / Records Clerk": [
      "OP-WF-06"
    ],
    "IT (for secure fax)": [
      "OP-WF-06"
    ],
    "Intake Coordinator": [
      "OP-WF-07",
      "OP-WF-08"
    ],
    "Clinical Manager (for clinical acceptance": [
      "OP-WF-07"
    ],
    "CL-WF-01)": [
      "OP-WF-07"
    ],
    "HR (driver verification)": [
      "OP-WF-09"
    ],
    "Fleet/Facilities Mgr (vehicles)": [
      "OP-WF-09"
    ],
    "Clinician in custody": [
      "OP-WF-10"
    ],
    "Contracted interpreter vendor": [
      "OP-WF-11"
    ],
    "On-call RN": [
      "OP-WF-13"
    ],
    "On-call Supervisor": [
      "OP-WF-13"
    ],
    "Clinical Manager next day": [
      "OP-WF-13"
    ],
    "Clinical Manager (next-day review)": [
      "OP-WF-13"
    ],
    "IT Data Owner": [
      "QA-WF-13"
    ],
    "Domain KPI Owners": [
      "QA-WF-13"
    ],
    "QAPI Committee Chair": [
      "QA-WF-15",
      "QA-WF-17"
    ],
    "Data Steward (IT)": [
      "QA-WF-16"
    ],
    "Domain Owners": [
      "QA-WF-16"
    ],
    "IT Director for material data issues": [
      "QA-WF-16"
    ],
    "PIP Owner": [
      "QA-WF-17",
      "QA-WF-04"
    ],
    "Governing Body for material PIPs": [
      "QA-WF-17"
    ],
    "Domain Policy Owners": [
      "QA-WF-18"
    ],
    "QAPI Committee": [
      "QA-WF-18",
      "QA-WF-04",
      "QA-WF-05",
      "QA-WF-06",
      "QA-WF-09",
      "QA-WF-10",
      "QA-WF-11"
    ],
    "Governing Body for material policy revisions": [
      "QA-WF-18"
    ],
    "QAPI Lead / Clinical Manager": [
      "QA-WF-01"
    ],
    "Data Analyst": [
      "QA-WF-01",
      "QA-WF-09"
    ],
    "QAPI Data Analyst / QAPI Lead": [
      "QA-WF-02"
    ],
    "QAPI Lead (Chair)": [
      "QA-WF-03"
    ],
    "Committee": [
      "QA-WF-03",
      "QA-WF-07"
    ],
    "reported to Governing Body": [
      "QA-WF-03"
    ],
    "Operations": [
      "QA-WF-04"
    ],
    "discipline-specific clinicians": [
      "QA-WF-05"
    ],
    "Governing Body for sentinel": [
      "QA-WF-05"
    ],
    "Infection Preventionist (IP) / Clinical Manager": [
      "QA-WF-06"
    ],
    "QAPI Lead + Clinical Manager": [
      "QA-WF-07",
      "QA-WF-12"
    ],
    "Schedulers": [
      "QA-WF-07"
    ],
    "Case Managers": [
      "QA-WF-07"
    ],
    "HHCAHPS Coordinator": [
      "QA-WF-08"
    ],
    "Governing Body (exemption decision)": [
      "QA-WF-08"
    ],
    "HHCAHPS Coord": [
      "QA-WF-09"
    ],
    "Legal concurrence": [
      "QA-WF-12"
    ],
    "IP": [
      "RM-WF-16",
      "RM-WF-17"
    ],
    "Governing Body for sentinel patterns": [
      "RM-WF-16"
    ],
    "Safety Officer": [
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19"
    ],
    "Operations Manager": [
      "RM-WF-17",
      "RM-WF-18"
    ],
    "Emergency Preparedness Coordinator": [
      "RM-WF-19",
      "RM-WF-02"
    ],
    "Governing Body informed via GV-WF-01": [
      "RM-WF-19"
    ],
    "Governing Body for material gaps": [
      "RM-WF-20"
    ],
    "Governing Body quarterly": [
      "RM-WF-01"
    ],
    "Risk Mgr": [
      "RM-WF-02"
    ],
    "selected staff": [
      "RM-WF-05"
    ],
    "Admitting clinician (RN)": [
      "RM-WF-07"
    ],
    "EP Coord": [
      "RM-WF-07",
      "RM-WF-08",
      "RM-WF-09"
    ],
    "Risk Manager (IIPP Administrator)": [
      "RM-WF-08"
    ],
    "Risk Manager / Safety Coordinator": [
      "RM-WF-09"
    ],
    "Risk Manager / HR": [
      "RM-WF-10"
    ],
    "Clinical Manager + Risk Manager": [
      "RM-WF-12"
    ],
    "Biomedical vendor": [
      "RM-WF-12"
    ],
    "Administering clinician": [
      "RM-WF-13"
    ],
    "Second clinician reviewer": [
      "RM-WF-13"
    ],
    "Administrator + Legal Counsel": [
      "RM-WF-14"
    ],
    "insurance broker": [
      "RM-WF-14"
    ],
    "Governing Body for material matters": [
      "RM-WF-14"
    ],
    "All department heads": [
      "RM-WF-15"
    ]
  },
  "byDomain": {
    "CL": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-35",
      "CL-WF-36",
      "CL-WF-37",
      "CL-WF-01",
      "CL-WF-02",
      "CL-WF-03",
      "CL-WF-04",
      "CL-WF-05",
      "CL-WF-06",
      "CL-WF-07",
      "CL-WF-08",
      "CL-WF-09",
      "CL-WF-10",
      "CL-WF-11",
      "CL-WF-12",
      "CL-WF-13",
      "CL-WF-14",
      "CL-WF-15",
      "CL-WF-16",
      "CL-WF-17",
      "CL-WF-18",
      "CL-WF-19",
      "CL-WF-20",
      "CL-WF-21",
      "CL-WF-22",
      "CL-WF-23",
      "CL-WF-24",
      "CL-WF-25"
    ],
    "CO": [
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-27",
      "CO-WF-28",
      "CO-WF-29",
      "CO-WF-30",
      "CO-WF-01",
      "CO-WF-02",
      "CO-WF-03",
      "CO-WF-04",
      "CO-WF-05",
      "CO-WF-06",
      "CO-WF-07",
      "CO-WF-08",
      "CO-WF-09",
      "CO-WF-10",
      "CO-WF-11",
      "CO-WF-12",
      "CO-WF-13",
      "CO-WF-14",
      "CO-WF-15",
      "CO-WF-16",
      "CO-WF-17",
      "CO-WF-18",
      "CO-WF-19",
      "CO-WF-20",
      "CO-WF-21",
      "CO-WF-22"
    ],
    "EN": [
      "EN-WF-01",
      "EN-WF-02",
      "EN-WF-03",
      "EN-WF-04",
      "EN-WF-05",
      "EN-WF-06",
      "EN-WF-07",
      "EN-WF-08",
      "EN-WF-09",
      "EN-WF-10",
      "EN-WF-11",
      "EN-WF-12",
      "EN-WF-13"
    ],
    "FN": [
      "FN-WF-01",
      "FN-WF-02",
      "FN-WF-03",
      "FN-WF-04",
      "FN-WF-05",
      "FN-WF-06",
      "FN-WF-07",
      "FN-WF-08",
      "FN-WF-09",
      "FN-WF-10",
      "FN-WF-11",
      "FN-WF-12",
      "FN-WF-13",
      "FN-WF-14",
      "FN-WF-15"
    ],
    "GV": [
      "GV-WF-01",
      "GV-WF-02",
      "GV-WF-03",
      "GV-WF-04",
      "GV-WF-05",
      "GV-WF-06",
      "GV-WF-07",
      "GV-WF-08",
      "GV-WF-09",
      "GV-WF-10",
      "GV-WF-11",
      "GV-WF-12",
      "GV-WF-13",
      "GV-WF-14"
    ],
    "HR": [
      "HR-WF-18",
      "HR-WF-19",
      "HR-WF-20",
      "HR-WF-21",
      "HR-WF-01",
      "HR-WF-02",
      "HR-WF-03",
      "HR-WF-04",
      "HR-WF-05",
      "HR-WF-06",
      "HR-WF-07",
      "HR-WF-08",
      "HR-WF-09",
      "HR-WF-10",
      "HR-WF-11",
      "HR-WF-12",
      "HR-WF-13",
      "HR-WF-14",
      "HR-WF-15",
      "HR-WF-16",
      "HR-WF-17"
    ],
    "IT": [
      "IT-WF-21",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25",
      "IT-WF-01",
      "IT-WF-02",
      "IT-WF-03",
      "IT-WF-04",
      "IT-WF-05",
      "IT-WF-06",
      "IT-WF-07",
      "IT-WF-08",
      "IT-WF-09",
      "IT-WF-10",
      "IT-WF-11",
      "IT-WF-12",
      "IT-WF-13",
      "IT-WF-14",
      "IT-WF-15",
      "IT-WF-16",
      "IT-WF-17",
      "IT-WF-18",
      "IT-WF-19",
      "IT-WF-20"
    ],
    "OP": [
      "OP-WF-01",
      "OP-WF-02",
      "OP-WF-03",
      "OP-WF-04",
      "OP-WF-05",
      "OP-WF-06",
      "OP-WF-07",
      "OP-WF-08",
      "OP-WF-09",
      "OP-WF-10",
      "OP-WF-11",
      "OP-WF-12",
      "OP-WF-13"
    ],
    "QA": [
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-17",
      "QA-WF-18",
      "QA-WF-01",
      "QA-WF-02",
      "QA-WF-03",
      "QA-WF-04",
      "QA-WF-05",
      "QA-WF-06",
      "QA-WF-07",
      "QA-WF-08",
      "QA-WF-09",
      "QA-WF-10",
      "QA-WF-11",
      "QA-WF-12"
    ],
    "RM": [
      "RM-WF-16",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-20",
      "RM-WF-01",
      "RM-WF-02",
      "RM-WF-03",
      "RM-WF-04",
      "RM-WF-05",
      "RM-WF-06",
      "RM-WF-07",
      "RM-WF-08",
      "RM-WF-09",
      "RM-WF-10",
      "RM-WF-11",
      "RM-WF-12",
      "RM-WF-13",
      "RM-WF-14",
      "RM-WF-15"
    ]
  },
  "downstream": {
    "CL-WF-04": [
      "CL-WF-26",
      "CL-WF-29",
      "CL-WF-30"
    ],
    "CL-WF-06": [
      "CL-WF-26",
      "CL-WF-37",
      "CL-WF-04",
      "CO-WF-23"
    ],
    "CL-WF-07": [
      "CL-WF-26",
      "CL-WF-37",
      "CO-WF-23"
    ],
    "CL-WF-18": [
      "CL-WF-26"
    ],
    "QA-WF-03": [
      "CL-WF-26",
      "CL-WF-27",
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-35",
      "CL-WF-36",
      "CL-WF-37",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-27",
      "CO-WF-28",
      "CO-WF-29",
      "CO-WF-30",
      "HR-WF-18",
      "HR-WF-19",
      "HR-WF-20",
      "HR-WF-21",
      "IT-WF-21",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-17",
      "QA-WF-18",
      "RM-WF-16",
      "RM-WF-17",
      "RM-WF-18",
      "RM-WF-19",
      "RM-WF-20"
    ],
    "CO-WF-04": [
      "CL-WF-26",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-30",
      "HR-WF-18",
      "HR-WF-21",
      "IT-WF-21",
      "IT-WF-24",
      "RM-WF-20"
    ],
    "HR-WF-09": [
      "CL-WF-26",
      "CL-WF-28",
      "CL-WF-36",
      "CO-WF-23",
      "CO-WF-27",
      "CO-WF-30",
      "HR-WF-18",
      "HR-WF-19",
      "HR-WF-20",
      "HR-WF-08",
      "IT-WF-23"
    ],
    "CO-WF-22": [
      "CL-WF-26",
      "CO-WF-27",
      "CO-WF-29",
      "CO-WF-30",
      "HR-WF-18",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-25",
      "RM-WF-16",
      "RM-WF-20"
    ],
    "CL-WF-05": [
      "CL-WF-27",
      "CL-WF-35",
      "CL-WF-04",
      "CL-WF-18",
      "CO-WF-23",
      "CO-WF-26"
    ],
    "CL-WF-25": [
      "CL-WF-27",
      "CL-WF-28",
      "CO-WF-23",
      "HR-WF-19"
    ],
    "FN-WF-15": [
      "CL-WF-27",
      "CL-WF-29",
      "CL-WF-30",
      "CL-WF-36",
      "CL-WF-37",
      "CO-WF-23",
      "CO-WF-26",
      "CO-WF-28",
      "CO-WF-29"
    ],
    "CO-WF-08": [
      "CL-WF-27",
      "CL-WF-30",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-26",
      "CO-WF-27",
      "EN-WF-13",
      "HR-WF-18"
    ],
    "CL-WF-09": [
      "CL-WF-28",
      "CL-WF-30",
      "CL-WF-33",
      "CL-WF-34",
      "CL-WF-37",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25"
    ],
    "CO-WF-14": [
      "CL-WF-28",
      "CL-WF-29",
      "CL-WF-37",
      "CO-WF-25"
    ],
    "CL-WF-10": [
      "CL-WF-28"
    ],
    "CL-WF-21": [
      "CL-WF-28",
      "CL-WF-29",
      "CO-WF-25",
      "FN-WF-10"
    ],
    "CL-WF-01": [
      "CL-WF-29",
      "CO-WF-28",
      "OP-WF-07"
    ],
    "CL-WF-19": [
      "CL-WF-29",
      "CL-WF-34"
    ],
    "CL-WF-16": [
      "CL-WF-29",
      "CL-WF-04"
    ],
    "CL-WF-02": [
      "CL-WF-30",
      "CL-WF-04"
    ],
    "FN-WF-04": [
      "CL-WF-30",
      "CO-WF-23",
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-28"
    ],
    "CL-WF-12": [
      "CL-WF-31",
      "CL-WF-34",
      "CL-WF-04"
    ],
    "RM-WF-13": [
      "CL-WF-31",
      "CL-WF-12"
    ],
    "QA-WF-05": [
      "CL-WF-31",
      "CL-WF-32",
      "CL-WF-12",
      "CL-WF-13",
      "RM-WF-16",
      "RM-WF-20",
      "RM-WF-13"
    ],
    "EN-WF-01": [
      "CL-WF-31",
      "CL-WF-33",
      "CL-WF-34",
      "QA-WF-18"
    ],
    "CL-WF-14": [
      "CL-WF-32",
      "RM-WF-17"
    ],
    "QA-WF-06": [
      "CL-WF-32"
    ],
    "RM-WF-06": [
      "CL-WF-32",
      "CL-WF-14",
      "RM-WF-19"
    ],
    "HR-WF-07": [
      "CL-WF-32",
      "CO-WF-26",
      "HR-WF-18",
      "HR-WF-19"
    ],
    "CL-WF-08": [
      "CL-WF-33",
      "CL-WF-34"
    ],
    "CL-WF-22": [
      "CL-WF-33",
      "CL-WF-23",
      "RM-WF-20"
    ],
    "QA-WF-04": [
      "CL-WF-34",
      "CL-WF-35",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-17",
      "QA-WF-03",
      "RM-WF-16"
    ],
    "QA-WF-08": [
      "CL-WF-34"
    ],
    "QA-WF-02": [
      "CL-WF-35",
      "QA-WF-13",
      "QA-WF-14",
      "QA-WF-16"
    ],
    "QA-WF-09": [
      "CL-WF-35",
      "QA-WF-14"
    ],
    "CL-WF-27": [
      "CL-WF-35",
      "QA-WF-16"
    ],
    "CL-WF-20": [
      "CL-WF-36",
      "OP-WF-12"
    ],
    "QA-WF-07": [
      "CL-WF-36"
    ],
    "CL-WF-11": [
      "CL-WF-10",
      "HR-WF-18"
    ],
    "CO-WF-12": [
      "CL-WF-16"
    ],
    "CO-WF-10": [
      "CL-WF-23",
      "CO-WF-11",
      "CO-WF-12",
      "CO-WF-13",
      "CO-WF-21",
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-09",
      "IT-WF-10",
      "IT-WF-15",
      "IT-WF-16",
      "IT-WF-17",
      "OP-WF-06",
      "RM-WF-20"
    ],
    "CO-WF-05": [
      "CL-WF-23",
      "CO-WF-30",
      "EN-WF-08"
    ],
    "CL-WF-03": [
      "CO-WF-23"
    ],
    "FN-WF-08": [
      "CO-WF-24",
      "CO-WF-25",
      "CO-WF-29",
      "EN-WF-13",
      "FN-WF-07",
      "FN-WF-15",
      "HR-WF-02",
      "HR-WF-15"
    ],
    "CO-WF-16": [
      "CO-WF-24",
      "CO-WF-27",
      "CO-WF-29",
      "CO-WF-04",
      "CO-WF-07",
      "CO-WF-15",
      "HR-WF-20",
      "RM-WF-20"
    ],
    "CO-WF-23": [
      "CO-WF-24",
      "CO-WF-26",
      "CO-WF-30",
      "QA-WF-16",
      "QA-WF-18",
      "QA-WF-03"
    ],
    "GV-WF-01": [
      "CO-WF-24",
      "CO-WF-27",
      "CO-WF-30",
      "GV-WF-05",
      "IT-WF-22",
      "IT-WF-24",
      "IT-WF-25",
      "QA-WF-17",
      "QA-WF-18",
      "QA-WF-03",
      "RM-WF-18",
      "RM-WF-19"
    ],
    "CO-WF-03": [
      "CO-WF-27",
      "CO-WF-07",
      "CO-WF-08",
      "QA-WF-07",
      "RM-WF-16"
    ],
    "CO-WF-15": [
      "CO-WF-27",
      "HR-WF-20"
    ],
    "HR-WF-15": [
      "CO-WF-27",
      "HR-WF-20",
      "IT-WF-21"
    ],
    "FN-WF-05": [
      "CO-WF-29",
      "FN-WF-15"
    ],
    "FN-WF-06": [
      "CO-WF-29"
    ],
    "FN-WF-07": [
      "CO-WF-29",
      "FN-WF-11"
    ],
    "CL-WF-26": [
      "CO-WF-30",
      "QA-WF-18",
      "QA-WF-03"
    ],
    "QA-WF-13": [
      "CO-WF-30",
      "QA-WF-14",
      "QA-WF-15",
      "QA-WF-16",
      "QA-WF-17",
      "QA-WF-03"
    ],
    "HR-WF-18": [
      "CO-WF-30",
      "HR-WF-21",
      "QA-WF-18",
      "QA-WF-03"
    ],
    "RM-WF-16": [
      "CO-WF-30",
      "QA-WF-18",
      "QA-WF-03",
      "RM-WF-17"
    ],
    "IT-WF-21": [
      "CO-WF-30",
      "IT-WF-23",
      "QA-WF-18",
      "QA-WF-03"
    ],
    "EN-WF-03": [
      "EN-WF-01"
    ],
    "IT-WF-04": [
      "EN-WF-03",
      "IT-WF-21"
    ],
    "IT-WF-17": [
      "EN-WF-08",
      "IT-WF-10"
    ],
    "EN-WF-05": [
      "EN-WF-13"
    ],
    "GV-WF-06": [
      "FN-WF-01",
      "OP-WF-08"
    ],
    "QA-WF-01": [
      "FN-WF-05"
    ],
    "GV-WF-07": [
      "GV-WF-06"
    ],
    "GV-WF-02": [
      "GV-WF-13"
    ],
    "HR-WF-03": [
      "HR-WF-18",
      "HR-WF-21"
    ],
    "HR-WF-05": [
      "HR-WF-18",
      "HR-WF-19"
    ],
    "CO-WF-09": [
      "HR-WF-18",
      "IT-WF-22",
      "IT-WF-15"
    ],
    "HR-WF-19": [
      "HR-WF-18",
      "HR-WF-21",
      "QA-WF-13"
    ],
    "HR-WF-06": [
      "HR-WF-19"
    ],
    "HR-WF-04": [
      "HR-WF-20",
      "HR-WF-21"
    ],
    "CO-WF-27": [
      "HR-WF-20"
    ],
    "HR-WF-02": [
      "HR-WF-20",
      "HR-WF-21"
    ],
    "HR-WF-08": [
      "HR-WF-21",
      "IT-WF-21",
      "IT-WF-23"
    ],
    "HR-WF-20": [
      "HR-WF-21"
    ],
    "CO-WF-06": [
      "HR-WF-02"
    ],
    "IT-WF-02": [
      "HR-WF-03",
      "IT-WF-21"
    ],
    "HR-WF-14": [
      "HR-WF-03"
    ],
    "CO-WF-07": [
      "HR-WF-09",
      "HR-WF-12"
    ],
    "HR-WF-12": [
      "HR-WF-09",
      "HR-WF-17"
    ],
    "IT-WF-03": [
      "IT-WF-21"
    ],
    "IT-WF-22": [
      "IT-WF-21",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25"
    ],
    "IT-WF-01": [
      "IT-WF-22",
      "IT-WF-24"
    ],
    "IT-WF-05": [
      "IT-WF-22"
    ],
    "IT-WF-07": [
      "IT-WF-22"
    ],
    "IT-WF-08": [
      "IT-WF-22",
      "IT-WF-25"
    ],
    "EN-WF-12": [
      "IT-WF-22",
      "IT-WF-23",
      "IT-WF-24",
      "IT-WF-25",
      "QA-WF-15",
      "QA-WF-18",
      "QA-WF-03",
      "RM-WF-16",
      "RM-WF-18",
      "RM-WF-19"
    ],
    "IT-WF-09": [
      "IT-WF-22",
      "IT-WF-24",
      "IT-WF-25",
      "IT-WF-03",
      "IT-WF-06",
      "IT-WF-08",
      "IT-WF-14",
      "IT-WF-16",
      "IT-WF-17",
      "IT-WF-18",
      "IT-WF-19",
      "RM-WF-20"
    ],
    "IT-WF-06": [
      "IT-WF-23",
      "IT-WF-24"
    ],
    "IT-WF-23": [
      "IT-WF-24",
      "QA-WF-13"
    ],
    "IT-WF-10": [
      "IT-WF-25"
    ],
    "IT-WF-11": [
      "IT-WF-25"
    ],
    "RM-WF-02": [
      "IT-WF-08",
      "RM-WF-18",
      "RM-WF-03"
    ],
    "GV-WF-11": [
      "IT-WF-15",
      "OP-WF-03"
    ],
    "GV-WF-10": [
      "OP-WF-01"
    ],
    "OP-WF-04": [
      "OP-WF-03"
    ],
    "RM-WF-10": [
      "OP-WF-09",
      "RM-WF-16"
    ],
    "RM-WF-14": [
      "OP-WF-10"
    ],
    "CL-WF-35": [
      "QA-WF-13"
    ],
    "CL-WF-34": [
      "QA-WF-13"
    ],
    "CO-WF-29": [
      "QA-WF-13"
    ],
    "RM-WF-17": [
      "QA-WF-13"
    ],
    "IT-WF-14": [
      "QA-WF-13",
      "QA-WF-16"
    ],
    "QA-WF-16": [
      "QA-WF-13",
      "QA-WF-03"
    ],
    "QA-WF-14": [
      "QA-WF-15",
      "QA-WF-03"
    ],
    "CO-WF-25": [
      "QA-WF-16"
    ],
    "QA-WF-15": [
      "QA-WF-17",
      "QA-WF-03"
    ],
    "QA-WF-11": [
      "QA-WF-18"
    ],
    "QA-WF-17": [
      "QA-WF-03"
    ],
    "QA-WF-18": [
      "QA-WF-03"
    ],
    "HR-WF-13": [
      "RM-WF-16",
      "RM-WF-20"
    ],
    "IT-WF-25": [
      "RM-WF-16"
    ],
    "RM-WF-08": [
      "RM-WF-17"
    ],
    "RM-WF-09": [
      "RM-WF-17"
    ],
    "OP-WF-09": [
      "RM-WF-17"
    ],
    "OP-WF-02": [
      "RM-WF-18"
    ],
    "RM-WF-01": [
      "RM-WF-18"
    ],
    "RM-WF-03": [
      "RM-WF-19",
      "RM-WF-02"
    ],
    "RM-WF-04": [
      "RM-WF-19",
      "RM-WF-03"
    ],
    "RM-WF-05": [
      "RM-WF-19"
    ],
    "RM-WF-07": [
      "RM-WF-19"
    ],
    "CL-WF-23": [
      "RM-WF-20"
    ],
    "CO-WF-30": [
      "RM-WF-20"
    ]
  },
  "kpis": {
    "total": 206,
    "byDomain": {
      "CL": 37,
      "CO": 30,
      "EN": 13,
      "FN": 15,
      "GV": 14,
      "HR": 21,
      "IT": 25,
      "OP": 13,
      "QA": 18,
      "RM": 20
    },
    "byCadence": {
      "time_based": 112,
      "event_based": 90,
      "continuous": 4
    },
    "requiresGoverningBody": 62,
    "highRisk": 63
  }
} as unknown as WorkflowGraph;

export function workflowsByForm(formId: string): string[] {
  return WORKFLOW_GRAPH.byForm[formId] ?? [];
}
export function workflowsByPolicy(policyId: string): string[] {
  return WORKFLOW_GRAPH.byPolicy[policyId] ?? [];
}
export function workflowsByRegulation(anchor: string): string[] {
  return WORKFLOW_GRAPH.byRegulation[anchor] ?? [];
}
export function workflowsByRole(role: string): string[] {
  return WORKFLOW_GRAPH.byRole[role] ?? [];
}
