import type { ExecutiveCaseModule } from './academyTypes';

export const additionalCases: ExecutiveCaseModule[] = [
  {
    id: 'GB-006', sequence: 6, title: 'Compliance Independence & Escalation', shortTitle: 'Compliance',
    domain: 'Integrity oversight', duration: '46–62 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Policy validation', available: true,
    lede: 'Protect independent investigation and patient interests when revenue, reputation, and executive influence converge.',
    sources: ['42 CFR 484.105(a)', '42 CFR 484.65(e)', 'CO-CP-001', 'CO-CP-002', 'CO-CP-004', 'CO-CP-005', 'CO-CP-006', 'CO-CP-007', 'CO-CP-008', 'CO-FA-001', 'CO-FA-002', 'CO-FA-003'], achc: ['HH2-9A.01', 'HH2-7A.01'],
    caseTitle: 'The protected producer', caseDate: 'November 13, 2026 · Privileged special session',
    caseContext: 'A hotline report links the highest-producing branch leader, a major referral source, and a senior executive to altered eligibility documentation and retaliation.',
    decisiveDuty: 'The Governing Body protects independence, evidence, patients, and due process before it protects revenue or reputation.',
    doctrine: [
      { number: '01', title: 'Preserve independence', body: 'Subjects of an allegation cannot control scope, evidence, investigators, or reporting.' },
      { number: '02', title: 'Protect first', body: 'Stop retaliation and patient/billing exposure without declaring guilt before facts are tested.' },
      { number: '03', title: 'Escalate by risk', body: 'Credibility, scope, seniority, recurrence, and ongoing exposure determine Governing Body attention.' },
      { number: '04', title: 'Record restraint', body: 'Document decisions, safeguards, owners, and thresholds without contaminating the investigation.' },
    ],
    evidence: [
      { id: 'hotline', code: 'I-01', title: 'Hotline allegation', kind: 'Restricted', status: 'restricted', essential: true, relevant: true, summary: 'The report supplies dates, record IDs, and an alleged retaliatory schedule change.', details: ['Five patient records are identified.', 'The reporter names an executive instruction.', 'A schedule reduction followed the first internal complaint.'], source: 'Synthetic confidential report' },
      { id: 'access', code: 'I-02', title: 'Record-access log', kind: 'System log', status: 'attention', essential: true, relevant: true, summary: 'Eligibility fields changed after billing review and before claim submission.', details: ['The branch leader edited four records.', 'Two edits occurred using delegated credentials.', 'Original values remain in audit history.'], source: 'Synthetic audit trail' },
      { id: 'referrals', code: 'I-03', title: 'Referral concentration report', kind: 'Analytics', status: 'attention', essential: true, relevant: true, summary: 'The implicated source supplies 31% of branch admissions.', details: ['Volume rose after a marketing agreement.', 'No finding of wrongdoing is established by concentration alone.', 'Abrupt termination could affect current patient transitions.'], source: 'Synthetic referral analysis' },
      { id: 'email', code: 'I-04', title: 'Senior executive email', kind: 'Communication', status: 'restricted', essential: true, relevant: true, summary: 'The executive asks Compliance to route all interviews through Operations.', details: ['The executive is named in the allegation.', 'The email cites “message consistency.”', 'It also asks IT to defer a mailbox hold.'], source: 'Synthetic privileged training record' },
      { id: 'retaliation', code: 'I-05', title: 'Staffing chronology', kind: 'Workforce', status: 'attention', essential: true, relevant: true, summary: 'The reporter lost visits after speaking with a manager.', details: ['Performance ratings were previously satisfactory.', 'The branch cites census changes affecting several staff.', 'Causation is unresolved but protective review is warranted.'], source: 'Synthetic chronology' },
      { id: 'awards', code: 'I-06', title: 'Leadership awards profile', kind: 'Recognition', status: 'clean', relevant: false, summary: 'The branch leader has won three internal awards.', details: ['Awards cover census growth, staff retention, and patient-satisfaction improvement.', 'The most recent award predates the hotline report by five months.', 'Selection materials contain no record-level compliance review.'], source: 'Synthetic recognition profile' },
      { id: 'plan', code: 'I-07', title: 'Compliance investigation plan', kind: 'Compliance', status: 'clean', essential: true, relevant: true, summary: 'The Compliance Officer proposes independent reporting, evidence preservation, and interim controls.', details: ['External counsel supports privilege structure.', 'Patient/claim review is prioritized.', 'Weekly Chair updates and trigger-based full Board escalation are defined.'], source: 'Synthetic investigation plan' },
    ],
    findings: [
      { id: 'independence', type: 'authority', statement: 'A named subject is attempting to control interviews and evidence preservation.', correct: true, critical: true },
      { id: 'proof', type: 'authority', statement: 'The 31% referral concentration is sufficient to treat the referral arrangement as substantiated before interviews and contract review are completed.', correct: false },
      { id: 'board', type: 'authority', statement: 'The Board must authorize safeguards and independent reporting without directing witness answers.', correct: true },
      { id: 'retaliation-risk', type: 'risk', statement: 'The chronology creates a credible retaliation risk requiring immediate protection.', correct: true },
      { id: 'patient-claim', type: 'risk', statement: 'Record changes may create patient, billing, and repayment exposure that cannot wait for final discipline.', correct: true, critical: true },
      { id: 'award', type: 'risk', statement: 'Documented awards and prior satisfactory performance materially reduce the urgency of the proposed evidence hold.', correct: false },
    ],
    decisions: [
      { id: 'operations', label: 'Critical', title: 'Use the established Operations channel', body: 'Let the named executive coordinate interview sequencing, document access, and updates while Compliance independently evaluates the conclusions.', critical: true },
      { id: 'terminate', label: 'Overbroad', title: 'Remove all implicated leaders pending review', body: 'Suspend every named person, terminate the referral arrangement, and announce corrective action before testing allegations and individual responsibility.' },
      { id: 'independent', label: 'Defensible', title: 'Protect and investigate independently', body: 'Preserve evidence, prevent retaliation, protect patients/claims, define independent reporting, and reserve final findings and discipline.', correct: true },
      { id: 'wait', label: 'Critical', title: 'Preserve records and await external direction', body: 'Issue a general hold but defer interviews, patient/claim review, and retaliation safeguards until a regulator or payer defines the investigation scope.', critical: true },
    ],
    recordPrompt: 'Select the five safeguards that preserve independence and due process.',
    clauses: [
      { id: 'hold', text: 'Issue and verify an evidence-preservation hold across relevant systems and custodians.', correct: true },
      { id: 'reporting', text: 'Compliance reports independently to the designated Governing Body channel for this matter.', correct: true },
      { id: 'protect', text: 'Implement non-retaliation monitoring and an alternate reporting route for affected staff.', correct: true },
      { id: 'patients', text: 'Conduct immediate patient-safety and claim-exposure triage while the investigation proceeds.', correct: true },
      { id: 'scope', text: 'Record scope, investigators, privilege posture, update cadence, and escalation triggers.', correct: true },
      { id: 'guilt', text: 'Record that every named individual committed fraud before interviews occur.', correct: false, critical: true },
      { id: 'delete', text: 'Permit routine mailbox deletion until the allegation is substantiated.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why bypass the ordinary Operations channel?', answers: ['Operational leaders have material incentives, so Compliance should exclude Operations from all factual and patient-continuity input', 'A named subject cannot control the investigation affecting that subject', 'Potential billing exposure makes external counsel the only permissible investigation owner, regardless of internal conflict controls'], correct: 1 },
      { id: 'd2', prompt: 'What can occur before a final finding?', answers: ['Only evidence preservation; employment, patient, and claim safeguards would improperly presume the allegation is true', 'Neutral safeguards for evidence, patients, claims, and retaliation risk', 'Temporary discipline and payer disclosure, provided the Board labels both actions provisional pending investigation'], correct: 1 },
      { id: 'd3', prompt: 'What is the Board’s role?', answers: ['Approve the interview plan, individual questions, credibility findings, and device-collection steps to demonstrate active oversight', 'Ensure independence, resources, safeguards, escalation, and accountable resolution', 'Delegate the matter to counsel and receive a final privileged conclusion without interim reporting or separate patient-risk review'], correct: 1 },
    ],
    remediation: { duty: 'Independence is an operational condition, not an org-chart label.', trap: 'Revenue importance and executive seniority made interference sound like coordination.', repair: 'Separate safeguarding, investigation, adjudication, disclosure, and discipline; assign a conflict-free owner to each.', transferRule: 'Protective action may be immediate without converting allegation into guilt.' },
    transfer: { prompt: 'The external review later clears the referral arrangement but confirms retaliation by a different manager. What must the Board do?', answers: ['Close the referral matter and address retaliation through the routine HR process without revising the investigation record because it was outside the original theory', 'Resolve and document each supported and unsupported issue separately, including corrective action for retaliation', 'Amend the originating allegation to substitute the responsible manager, then retain one consolidated substantiated finding for reporting and remediation'], correct: 1, rationale: 'An investigation can disprove one theory and substantiate another. The record must preserve both results accurately.' },
  },
  {
    id: 'GB-007', sequence: 7, title: 'Fiscal Stewardship Under Regulatory Risk', shortTitle: 'Fiscal stewardship',
    domain: 'Budget and viability', duration: '44–60 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Policy validation', available: true,
    lede: 'Make financially viable choices without starving mandatory quality, compliance, or patient-safety controls.',
    sources: ['42 CFR 484.105(a)', '42 CFR 484.105(h)', '42 CFR 484.65(e)', 'FN-FP-005', 'FN-FP-007', 'QA-PG-001', 'QA-PG-002', 'CO-CP-002', 'CO-CP-007'], achc: ['HH3-1A', 'HH3-1B', 'HH3-1C'],
    caseTitle: 'The savings plan', caseDate: 'December 8, 2026 · Annual budget adoption',
    caseContext: 'Cash is tightening. Three budget packages all balance on paper, but each handles denials, compliance, QAPI, and staffing risk differently.',
    decisiveDuty: 'A balanced spreadsheet is not a defensible budget if it disables the controls needed to deliver lawful, safe care.',
    doctrine: [
      { number: '01', title: 'Fund the duty', body: 'Budget approval must preserve resources needed for operations, QAPI, compliance, and patient safety.' },
      { number: '02', title: 'Read the driver', body: 'Separate timing pressure from structural loss, denial exposure, and referral concentration.' },
      { number: '03', title: 'Model the consequence', body: 'Every reduction needs service, control, patient, and regulatory impact analysis.' },
      { number: '04', title: 'Monitor the remedy', body: 'Define triggers and return dates before financial pressure becomes emergency governance.' },
    ],
    evidence: [
      { id: 'forecast', code: 'F-01', title: '13-week cash forecast', kind: 'Finance', status: 'attention', essential: true, relevant: true, summary: 'Liquidity drops below the Board floor in week nine under the base case.', details: ['Collections slowed 11 days.', 'Payroll and patient-service obligations remain funded through week eight.', 'No downside sensitivity is shown.'], source: 'Synthetic forecast' },
      { id: 'denials', code: 'F-02', title: 'Denial root-cause report', kind: 'Revenue cycle', status: 'restricted', essential: true, relevant: true, summary: 'Most denials originate in two correctable documentation workflows.', details: ['61% involve incomplete face-to-face or plan-of-care evidence.', 'Appeal success is high when complete evidence exists.', 'Proposed package A removes the denial analyst.'], source: 'Synthetic analysis' },
      { id: 'qapi', code: 'F-03', title: 'QAPI resource request', kind: 'Quality', status: 'attention', essential: true, relevant: true, summary: 'Weekend escalation and subgroup analysis require temporary protected resources.', details: ['Request is tied to an open high-risk PIP.', 'Effectiveness review is due next quarter.', 'Package B defers all requested resources.'], source: 'Synthetic QAPI request' },
      { id: 'compliance', code: 'F-04', title: 'Compliance staffing map', kind: 'Compliance', status: 'attention', essential: true, relevant: true, summary: 'Package A combines investigation ownership with a revenue executive.', details: ['Independence conflict is identified.', 'Hotline volume is rising.', 'Package C preserves conflict-free reporting.'], source: 'Synthetic control map' },
      { id: 'options', code: 'F-05', title: 'Budget option book', kind: 'Board packet', status: 'restricted', essential: true, relevant: true, summary: 'Only package C addresses denial workflow and stages noncritical spending.', details: ['A cuts QAPI/compliance and the denial analyst.', 'B delays patient-safety resources and assumes collections improve.', 'C pauses expansion, fixes denial workflows, preserves core controls, and sets cash triggers.'], source: 'Synthetic budget packet' },
      { id: 'referral', code: 'F-06', title: 'Payer and referral concentration', kind: 'Risk', status: 'attention', relevant: true, summary: 'One source and one payer create material concentration.', details: ['Loss of either worsens the downside case.', 'No illegality is inferred.', 'Diversification plan is unfunded in A and B.'], source: 'Synthetic risk analysis' },
      { id: 'office', code: 'F-07', title: 'Office redesign proposal', kind: 'Capital', status: 'clean', relevant: false, summary: 'A workspace redesign is included in the discretionary capital queue.', details: ['Estimated cost is $164,000 over two phases.', 'The lease does not require the work.', 'Vendor mobilization has not begun and the deposit is refundable.'], source: 'Synthetic capital proposal' },
    ],
    findings: [
      { id: 'cash', type: 'risk', statement: 'The base plan breaches the approved liquidity floor without a trigger response.', correct: true },
      { id: 'controls', type: 'authority', statement: 'Package A creates a compliance-independence problem and removes a denial-control resource.', correct: true, critical: true },
      { id: 'qapi-cut', type: 'risk', statement: 'Package B delays resources linked to an active patient-safety priority without impact analysis.', correct: true, critical: true },
      { id: 'illegal', type: 'authority', statement: 'Because federal rules set no fixed compliance or QAPI budget, package A creates no governance issue if the total operating budget balances.', correct: false },
      { id: 'driver', type: 'risk', statement: 'The denial report identifies a correctable operational driver rather than only a volume problem.', correct: true },
      { id: 'renovation', type: 'risk', statement: 'The refundable office project should proceed because delaying approved capital work would itself create a service-continuity risk.', correct: false },
    ],
    decisions: [
      { id: 'a', label: 'Critical', title: 'Choose package A with monthly monitoring', body: 'Retain expansion, remove the denial analyst, combine investigation ownership with Revenue, and monitor denials and hotline volume monthly.', critical: true },
      { id: 'b', label: 'Critical', title: 'Choose package B with a contingency reserve', body: 'Defer active QAPI resources, assume collections improve, and reserve funds for later intervention if the safety indicator worsens further.', critical: true },
      { id: 'c', label: 'Defensible', title: 'Adopt package C with controls', body: 'Protect essential oversight, fix denial workflows, stage discretionary spending, and require trigger-based reporting.', correct: true },
      { id: 'none', label: 'Incomplete', title: 'Extend the prior budget temporarily', body: 'Continue existing spending for 60 days while management develops a consensus package, without setting liquidity, denial, or safety triggers.' },
    ],
    recordPrompt: 'Select five clauses for the budget resolution.',
    clauses: [
      { id: 'adopt', text: 'Approve package C and its defined operating and capital components.', correct: true },
      { id: 'protect', text: 'Preserve conflict-free compliance, QAPI, and patient-safety resources tied to active risk.', correct: true },
      { id: 'denial', text: 'Fund the targeted denial-workflow correction and report recovery against defined measures.', correct: true },
      { id: 'trigger', text: 'Require weekly liquidity reporting and escalation at the approved thresholds.', correct: true },
      { id: 'return', text: 'Return for Board review if collections, census, denials, or control-resource assumptions vary materially.', correct: true },
      { id: 'guarantee', text: 'State that package C guarantees financial viability.', correct: false },
      { id: 'hide', text: 'Remove the downside case from the retained packet to avoid unnecessary concern.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why was package C defensible?', answers: ['It produced the most immediate cash preservation while assigning management discretion to restore controls if conditions improved', 'It addressed cash drivers while preserving essential controls and defining triggers', 'It balanced reductions across departments so no single oversight function absorbed a disproportionate share of the savings'], correct: 1 },
      { id: 'd2', prompt: 'What must accompany a reduction affecting compliance or QAPI?', answers: ['A quantified savings estimate, department-owner concurrence, and a quarterly review of whether the reduced function met its service levels', 'A documented impact assessment and a viable control alternative', 'A temporary reduction period, executive exception authority, and evidence that the affected department stayed within its total budget'], correct: 1 },
      { id: 'd3', prompt: 'What evidence proves ongoing fiscal oversight?', answers: ['Annual approval, monthly cash reporting, and management certification that spending remained within the adopted total', 'Budget, capital plan, monitoring, variance analysis, and recorded corrective decisions', 'Current bank balances, accounts-receivable aging, and a forecast showing that payroll remains funded through the next quarter'], correct: 1 },
    ],
    remediation: { duty: 'Fiscal stewardship includes control adequacy.', trap: 'The deepest cut appeared decisive but quietly increased denial, compliance, and patient-safety exposure.', repair: 'Trace each dollar decision to the operational driver, duty affected, mitigation, metric, trigger, and owner.', transferRule: 'Savings are not real when they merely move cost into denials, harm, repayment, or enforcement.' },
    transfer: { prompt: 'Collections improve sooner than expected, but denial root causes remain. Should the Board immediately restore the deferred expansion?', answers: ['Restore the first expansion phase because the liquidity condition is met, while leaving the remaining phases contingent on denial improvement', 'Only after testing whether the improvement is sustainable and whether denial/control milestones are met', 'Restore expansion if management funds a temporary denial team from the improved collections and reports both workstreams monthly'], correct: 1, rationale: 'Liquidity improvement does not automatically resolve the structural driver or the Board’s staged conditions.' },
  },
  {
    id: 'GB-008', sequence: 8, title: 'Strategy, Scope & Policy Authority', shortTitle: 'Strategy & policy',
    domain: 'Controlled direction', duration: '42–58 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Policy validation', available: true,
    lede: 'Distinguish editorial change from substantive governance and prevent mixed-version approval from becoming policy fiction.',
    sources: ['42 CFR 484.105(a)', '42 CFR 484.105(i)', 'CMS QSO-26-13-HHA (July 15, 2026) · G990/G992', 'GV-PM-001', 'EN-LC-001', 'GV-OG-005 · scope-policy identity reconciliation required'], achc: ['HH1-1A.01'],
    caseTitle: 'The “minor” revision', caseDate: 'January 19, 2027 · Consent calendar',
    caseContext: 'A 63-page policy packet is presented as editorial. Redlines alter service scope, escalation time, approval authority, and one patient-rights workflow across three conflicting versions.',
    decisiveDuty: 'Substance is determined by operational effect—not by the label placed on a revision.',
    doctrine: [
      { number: '01', title: 'Classify effect', body: 'A change is substantive when it alters rights, duties, scope, thresholds, accountability, or evidence.' },
      { number: '02', title: 'Control the version', body: 'The body that approves must know exactly which text and exhibits are being adopted.' },
      { number: '03', title: 'Test implementation', body: 'Training, forms, systems, workflows, acceptance-to-service criteria, public service/limitation information, and effective dates must align to the approved operating model and remain current when services change.' },
      { number: '04', title: 'Record the authority', body: 'Minutes identify the version, decision, conditions, effective date, and superseded instrument.' },
    ],
    evidence: [
      { id: 'clean', code: 'P-01', title: 'Clean policy packet', kind: 'Policy', status: 'attention', essential: true, relevant: true, summary: 'The clean PDF says version 7.1 but contains no change summary.', details: ['Effective date is blank.', 'Two exhibits are dated earlier.', 'Footer identifies a different owner than the registry.'], source: 'Synthetic controlled document' },
      { id: 'redline', code: 'P-02', title: 'Legal redline', kind: 'Redline', status: 'restricted', essential: true, relevant: true, summary: 'Changes reach far beyond grammar.', details: ['After-hours escalation moves from 30 to 90 minutes.', 'A new service line is added.', 'Patient-rights complaint routing changes.', 'Administrator approval becomes manager approval.'], source: 'Synthetic comparison' },
      { id: 'registry', code: 'P-03', title: 'Policy registry export', kind: 'Registry', status: 'attention', essential: true, relevant: true, summary: 'The registry labels the revision “non-substantive.”', details: ['Classification owner is the policy author.', 'No Compliance or clinical sign-off.', 'Version 7.0 remains marked active.'], source: 'Synthetic registry' },
      { id: 'workflow', code: 'P-04', title: 'Workflow impact map', kind: 'Operations', status: 'restricted', essential: true, relevant: true, summary: 'Six forms and two automations would execute the old rules.', details: ['After-hours timer remains 30 minutes.', 'Complaint form routes to the old owner.', 'New service line has no credential gate.'], source: 'Synthetic impact analysis' },
      { id: 'agenda', code: 'P-05', title: 'Consent-calendar agenda', kind: 'Governance', status: 'attention', essential: true, relevant: true, summary: 'The item requests approval without identifying version or substantive effects.', details: ['Five minutes allocated.', 'No presenter assigned.', 'Motion language says “all routine updates.”'], source: 'Synthetic agenda' },
      { id: 'email', code: 'P-06', title: 'Author reassurance email', kind: 'Communication', status: 'attention', relevant: false, summary: 'The author says “nothing meaningful changed.”', details: ['Sent before the legal redline and workflow map were circulated.', 'The author describes the revision as formatting and terminology cleanup.', 'No version hash, comparison, or affected-workflow list is attached.'], source: 'Synthetic author communication' },
      { id: 'scope', code: 'P-07', title: 'Approved service-scope record', kind: 'Authority', status: 'restricted', essential: true, relevant: true, summary: 'The proposed new service is outside the currently approved operational plan.', details: ['No staffing or competency analysis.', 'No budget allocation.', 'No regulatory readiness determination.'], source: 'Synthetic scope record' },
    ],
    findings: [
      { id: 'substantive', type: 'authority', statement: 'The changes are substantive because they alter scope, rights, timing, and decision authority.', correct: true, critical: true },
      { id: 'mixed', type: 'authority', statement: 'The packet does not establish one unambiguous version for approval.', correct: true, critical: true },
      { id: 'author', type: 'authority', statement: 'The author’s non-substantive classification may be accepted because no control owner formally challenged it before the consent calendar closed.', correct: false },
      { id: 'implementation', type: 'risk', statement: 'Forms and automations would conflict with the proposed policy at go-live.', correct: true },
      { id: 'scope-risk', type: 'risk', statement: 'The new service line lacks operational, competency, budget, and readiness evidence.', correct: true },
      { id: 'consent', type: 'risk', statement: 'Consent-calendar placement and the opportunity to request removal are sufficient review controls for this packet.', correct: false },
    ],
    decisions: [
      { id: 'approve', label: 'Critical', title: 'Approve the identified clean version', body: 'Adopt version 7.1 as the intended final policy and direct staff to reconcile effective dates, owners, forms, and workflow settings before rollout.', critical: true },
      { id: 'reject', label: 'Overbroad', title: 'Freeze the policy family', body: 'Keep version 7.0 active and prohibit changes to the policy, related forms, timers, routing, and service scope until the annual review cycle.' },
      { id: 'return', label: 'Defensible', title: 'Return for controlled substantive review', body: 'Lock one version, classify effects, complete readiness and cross-system impact review, then present explicit approval language.', correct: true },
      { id: 'author-decides', label: 'Incomplete', title: 'Accept the author’s classification', body: 'Return the packet for the author to select the canonical file and certify that the changes are non-substantive, then publish without renewed Board action.' },
    ],
    recordPrompt: 'Select five elements of the Board’s return directive.',
    clauses: [
      { id: 'no-approval', text: 'No policy version is approved at this meeting.', correct: true },
      { id: 'one-version', text: 'Return one checksum-identified clean version with a complete redline and change summary.', correct: true },
      { id: 'impact', text: 'Document legal, clinical, operational, workflow, form, system, training, and evidence impacts.', correct: true },
      { id: 'scope-clause', text: 'Separately validate the proposed service-scope expansion and required readiness evidence.', correct: true },
      { id: 'motion', text: 'Future motion must identify version, effective date, conditions, and superseded version.', correct: true },
      { id: 'silent', text: 'Permit staff to choose among versions after approval.', correct: false, critical: true },
      { id: 'retro', text: 'Make the eventual policy effective before training and system changes are complete.', correct: false },
    ],
    defense: [
      { id: 'd1', prompt: 'What makes a revision substantive?', answers: ['A new version number, multiple redlined pages, or changes that require staff communication before publication', 'Its effect on rights, duties, scope, thresholds, accountability, or evidence', 'The policy owner’s classification when Compliance and clinical leaders have not documented a contrary impact'], correct: 1 },
      { id: 'd2', prompt: 'What exactly did the Board approve today?', answers: ['Version 7.1, subject to administrative reconciliation of the effective date, owner, and related implementation materials', 'The common provisions appearing consistently across the clean PDF, redline, registry entry, and consent-calendar description', 'Nothing; the package was returned for controlled review'], correct: 2 },
      { id: 'd3', prompt: 'Why inspect workflows and forms?', answers: ['To verify that presentation, numbering, links, and document ownership match the controlled policy before release', 'Because implementation artifacts can contradict the approved rule', 'Because workflow and form review is the technical team’s substitute for a separate substantive-policy classification'], correct: 1 },
    ],
    remediation: { duty: 'The approval object must be exact.', trap: 'A clean PDF, a “minor” label, and a consent agenda concealed changes in legal and operational effect.', repair: 'Identify the canonical version, classify each effect, trace implementation dependencies, and state the approval object verbatim.', transferRule: 'Do not infer substance from file name, page count, author confidence, or agenda placement.' },
    transfer: { prompt: 'The revised packet changes only punctuation and fixes two broken links; no meaning, workflow, form, role, or evidence requirement changes. May it use the non-substantive route?', answers: ['Potentially yes, if the controlled classification and verification process confirms no substantive effect', 'Only if the Governing Body first approves the clean file, because link corrections can change the evidence available to staff', 'Yes after the policy owner records an editorial attestation and confirms that the page count and version history remain unchanged'], correct: 0, rationale: 'True editorial changes may follow the approved non-substantive route, but the classification still requires evidence.' },
  },
  {
    id: 'GB-009', sequence: 9, title: 'Enterprise Risk, Incidents & Emergency Governance', shortTitle: 'Enterprise risk',
    domain: 'Compound-event command', duration: '50–68 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Policy validation', available: true,
    lede: 'Govern patient safety, continuity, privacy, claims, and public communication as one compound event without collapsing their separate decision paths.',
    sources: ['42 CFR 484.65', '42 CFR 484.102', '42 CFR 484.110', 'RM-ER-001', 'RM-EP-001', 'QA-AE-001', 'QA-AE-002', 'QA-AE-003', 'QA-AE-004', 'CO-DC-003', 'CO-HP-101', 'CO-IR-101', 'GV-EA-002 · communications-policy identity validation required'], achc: ['HH2-4A', 'HH6-4A.02', 'HH6-4A.05', 'HH7-2A.01', 'HH7-2B.01', 'HH7-3A', 'HH7-3B', 'HH7-3C', 'HH7-3D', 'HH7-3E'],
    caseTitle: 'The forty-seven minutes', caseDate: 'February 3, 2027 · Emergency briefing',
    caseContext: 'A regional outage delays an urgent escalation, an employee posts about the event, a reporter calls, and the incident record remains incomplete.',
    decisiveDuty: 'One event can activate several governance duties; one improvised response cannot satisfy them all.',
    doctrine: [
      { number: '01', title: 'Stabilize care', body: 'Patient protection and continuity decisions lead the sequence.' },
      { number: '02', title: 'Preserve evidence', body: 'Logs, communications, records, and system state must be retained before narratives drift.' },
      { number: '03', title: 'Route each duty', body: 'Clinical, emergency, privacy, legal, payer, regulator, and communication paths have distinct owners and clocks.' },
      { number: '04', title: 'Govern recurrence', body: 'The Board directs system learning, resources, and effectiveness—not merely case closure.' },
    ],
    evidence: [
      { id: 'timeline', code: 'R-01', title: 'Unified event timeline', kind: 'Incident', status: 'restricted', essential: true, relevant: true, summary: 'Forty-seven minutes elapsed between urgent symptom report and successful clinician contact.', details: ['Primary telephony and EHR were unavailable.', 'Backup call tree began 19 minutes after the first failed attempt.', 'Patient was transported and stabilized.'], source: 'Synthetic incident timeline' },
      { id: 'plan', code: 'R-02', title: 'Emergency communication plan', kind: 'Continuity', status: 'attention', essential: true, relevant: true, summary: 'The plan requires backup activation after five minutes.', details: ['Printed call tree was outdated.', 'Two numbers belonged to former staff.', 'Last exercise did not test simultaneous EHR and telephony loss.'], source: 'Synthetic emergency plan' },
      { id: 'record', code: 'R-03', title: 'Clinical record comparison', kind: 'Clinical', status: 'restricted', essential: true, relevant: true, summary: 'A late entry describes the escalation but does not identify itself as late.', details: ['Original note ends before the outage.', 'Metadata shows later insertion.', 'Factual content is plausible but authentication is deficient.'], source: 'Synthetic record audit' },
      { id: 'social', code: 'R-04', title: 'Social-media capture', kind: 'Privacy', status: 'restricted', essential: true, relevant: true, summary: 'An employee post includes enough contextual detail to create identification risk.', details: ['No patient name is shown.', 'Location, time, condition, and photo background narrow identity.', 'The post was deleted after 23 minutes.'], source: 'Synthetic preserved capture' },
      { id: 'media', code: 'R-05', title: 'Reporter inquiry', kind: 'Communication', status: 'attention', relevant: true, summary: 'A reporter asks whether the agency concealed a preventable hospitalization.', details: ['Facts remain under review.', 'No authorized response has been issued.', 'Operations drafted a categorical denial.'], source: 'Synthetic inquiry' },
      { id: 'complaints', code: 'R-06', title: 'Prior complaint pattern', kind: 'Quality', status: 'attention', essential: true, relevant: true, summary: 'Two earlier complaints cite unreachable after-hours numbers.', details: ['Both were closed individually.', 'No aggregate pattern review is documented.', 'The same outdated number appears in the current call tree.'], source: 'Synthetic trend evidence' },
      { id: 'weather', code: 'R-07', title: 'Weather bulletin', kind: 'External', status: 'attention', relevant: false, summary: 'A routine weather advisory was active in the service region.', details: ['The advisory ran from 14:00 to 20:00 for wind and localized power interruption.', 'The telephony vendor’s preliminary log identifies scheduled network maintenance at 16:42.', 'No agency office-closure notice was issued.'], source: 'Synthetic external bulletin' },
    ],
    findings: [
      { id: 'delay', type: 'risk', statement: 'Backup activation materially exceeded the supplied five-minute control.', correct: true, critical: true },
      { id: 'record-gap', type: 'authority', statement: 'The clinical late entry requires accurate late-entry authentication rather than deletion or backdating.', correct: true },
      { id: 'privacy', type: 'risk', statement: 'The post requires privacy assessment even without a patient name.', correct: true },
      { id: 'pattern', type: 'risk', statement: 'Prior complaint evidence makes the current communication failure a potential recurring system issue.', correct: true, critical: true },
      { id: 'deny', type: 'authority', statement: 'The Board may authorize the drafted public denial because the patient stabilized and the preliminary vendor log identifies an external outage.', correct: false },
      { id: 'weather-cause', type: 'risk', statement: 'The weather advisory and incident timing are sufficient to classify the event as an external-cause failure.', correct: false },
    ],
    decisions: [
      { id: 'clinical-only', label: 'Critical', title: 'Manage through the clinical incident process', body: 'Stabilize the patient, complete the clinical review, and route the outage, late entry, privacy post, and prior complaints as separate departmental matters.', critical: true },
      { id: 'public', label: 'Critical', title: 'Issue a qualified public denial', body: 'State that no confirmed agency failure caused the hospitalization, while noting that technical and documentation reviews remain open.', critical: true },
      { id: 'command', label: 'Defensible', title: 'Activate compound-event governance', body: 'Stabilize, preserve, route each obligation, authorize factual communication, investigate recurrence, and set effectiveness review.', correct: true },
      { id: 'blame', label: 'Overbroad', title: 'Treat the outage as the controlling cause', body: 'Pursue vendor remedies and technology replacement while closing the agency call-tree, complaint-pattern, late-entry, and workforce-control reviews.' },
    ],
    recordPrompt: 'Select five executive directives for the compound event.',
    clauses: [
      { id: 'protect', text: 'Confirm patient protection, follow-up, and current after-hours continuity measures.', correct: true },
      { id: 'preserve', text: 'Preserve system logs, communications, social capture, clinical audit history, and vendor evidence.', correct: true },
      { id: 'routes', text: 'Assign clinical, emergency, privacy, legal/regulatory, payer, and communications assessments with their deadlines.', correct: true },
      { id: 'pattern-clause', text: 'Open system-level analysis linking prior complaints, call-tree maintenance, and exercise design.', correct: true },
      { id: 'return', text: 'Require corrective actions, owners, resource needs, measures, and an effectiveness review date.', correct: true },
      { id: 'backdate', text: 'Backdate the clinical entry to the time of the outage.', correct: false, critical: true },
      { id: 'deny-clause', text: 'State publicly that no agency control failed before the investigation is complete.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why is this a compound event?', answers: ['Multiple departments handled related facts, so the Board should consolidate the matters under the highest-severity clinical classification', 'It activates patient, continuity, record, privacy, complaint-pattern, legal, and communication duties', 'The outage and hospitalization occurred in one time window, making the vendor incident record the primary governance evidence'], correct: 1 },
      { id: 'd2', prompt: 'What should public communication contain now?', answers: ['A preliminary denial of causation paired with a commitment to update the statement if the investigation identifies an agency control failure', 'Only authorized, verified facts and appropriately limited statements while review continues', 'A factual chronology of the patient event with direct identifiers removed, plus the agency’s current view of likely root cause'], correct: 1 },
      { id: 'd3', prompt: 'What turns correction into governance?', answers: ['Replacing the failed call-tree entries, counseling the employee, and documenting completion in the incident and privacy files', 'System analysis, resources, accountable actions, measures, and effectiveness evidence', 'Closing each departmental workstream after its assigned corrective task is completed and reporting a consolidated closure date'], correct: 1 },
    ],
    remediation: { duty: 'One event, multiple controlled responses.', trap: 'Patient stabilization made the event look complete while other obligations and recurrence signals remained open.', repair: 'Create one master timeline, then branch every triggered duty to its owner, clock, evidence, decision, and closure criterion.', transferRule: 'Do not let one successful outcome erase a failed process or a separate legal duty.' },
    transfer: { prompt: 'The patient experiences no lasting harm, but the backup-plan and privacy failures are substantiated. May the Board close without corrective action?', answers: ['Yes, if the clinical review documents no injury and department leaders attest that the isolated control failures have not recurred', 'No; process and privacy failures require corrective action and effectiveness review independent of harm severity', 'Yes, after documenting vendor service credits and completing individual counseling for the employee responsible for the post'], correct: 1, rationale: 'A favorable outcome does not neutralize substantiated control failures or recurrence risk.' },
  },
  {
    id: 'GB-010', sequence: 10, title: 'Contracts, Referrals & External Arrangements', shortTitle: 'External arrangements',
    domain: 'Third-party governance', duration: '46–64 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Policy validation', available: true,
    lede: 'Recognize when a small-dollar arrangement is materially large because it touches patients, PHI, clinical workflow, and referrals.',
    sources: ['42 CFR 484.105(e)', 'GV-EA-001', 'CO-FA-001', 'CO-HP-005', 'CO-BA-101'], achc: ['HH1-10A', 'HH1-4A.01', 'HH2-5C.01'],
    caseTitle: 'Under the threshold', caseDate: 'March 15, 2027 · Contract approval',
    caseContext: 'A $19,800 care-coordination vendor is presented as below the Board threshold. Its platform receives PHI, influences scheduling, and is owned partly by a major referral-source executive.',
    decisiveDuty: 'Under the supplied case rule, patient, PHI, clinical, and referral effects trigger review independently of price; the agency’s canonical below-threshold review rule remains provisional.',
    doctrine: [
      { number: '01', title: 'Map the arrangement', body: 'Identify money, services, patients, PHI, referrals, control, subcontractors, and exit dependencies.' },
      { number: '02', title: 'Test fair value and purpose', body: 'Compensation and selection must withstand a referral-independent rationale.' },
      { number: '03', title: 'Protect care and data', body: 'Clinical accountability, access limits, BAA terms, incident duties, and continuity must be explicit.' },
      { number: '04', title: 'Monitor after signature', body: 'Approval begins—not ends—the evidence obligation.' },
    ],
    evidence: [
      { id: 'proposal', code: 'V-01', title: 'Vendor proposal', kind: 'Commercial', status: 'attention', essential: true, relevant: true, summary: 'Price is below threshold but scope includes patient triage routing and record access.', details: ['Platform prioritizes visit rescheduling.', 'Vendor staff can view clinical notes.', 'Pricing is tied partly to “activated referrals.”'], source: 'Synthetic proposal' },
      { id: 'ownership', code: 'V-02', title: 'Ownership disclosure', kind: 'Conflict', status: 'restricted', essential: true, relevant: true, summary: 'A referral-source executive owns 18% of the vendor.', details: ['Relationship was disclosed after selection.', 'The referral source represents 24% of admissions.', 'No independent conflict review is attached.'], source: 'Synthetic disclosure' },
      { id: 'baa', code: 'V-03', title: 'Draft BAA and security exhibit', kind: 'Privacy', status: 'restricted', essential: true, relevant: true, summary: 'The BAA/security package requires separate testing of mandatory BAA elements and agency-negotiated risk controls.', details: ['Broad access is permitted.', 'Subcontractor transparency, incident timing, data return, and verified deletion require contract-level resolution.', 'No evidence-access right for audits.'], source: 'Synthetic agreement' },
      { id: 'clinical', code: 'V-04', title: 'Clinical accountability map', kind: 'Operations', status: 'attention', essential: true, relevant: true, summary: 'The vendor workflow can defer visits without Clinical Manager review.', details: ['No escalation threshold.', 'No after-hours clinical owner.', 'Patient communication templates imply vendor authority.'], source: 'Synthetic workflow map' },
      { id: 'pricing', code: 'V-05', title: 'Fair-value comparison', kind: 'Finance', status: 'attention', essential: true, relevant: true, summary: 'Base fee is within range; referral-activation compensation is not supported.', details: ['Two independent quotes use flat fees.', 'No valuation supports the variable component.', 'Sales forecast assumes referral growth.'], source: 'Synthetic pricing analysis' },
      { id: 'monitoring', code: 'V-06', title: 'Vendor monitoring plan', kind: 'Oversight', status: 'attention', essential: true, relevant: true, summary: 'The plan measures uptime but not patient, privacy, referral, or clinical-control risk.', details: ['No complaint linkage.', 'No access-log review.', 'No corrective threshold or termination trigger.'], source: 'Synthetic monitoring plan' },
      { id: 'demo', code: 'V-07', title: 'Product demonstration score', kind: 'Evaluation', status: 'clean', relevant: false, summary: 'Users rated the interface 4.8 out of 5.', details: ['Eight administrative users attended.', 'The demonstration used synthetic records and a scripted scheduling path.', 'No Clinical Manager, Privacy Officer, or referral-compliance reviewer scored the session.'], source: 'Synthetic evaluation summary' },
    ],
    findings: [
      { id: 'material', type: 'authority', statement: 'Under the supplied case rule, the arrangement requires review despite price because it affects PHI, patient workflow, and a referral relationship.', correct: true },
      { id: 'conflict', type: 'authority', statement: 'The ownership relationship requires conflict and referral-risk review.', correct: true, critical: true },
      { id: 'price-safe', type: 'authority', statement: 'Below the $25,000 threshold, Board review is unnecessary unless Compliance first substantiates unlawful referral conduct.', correct: false },
      { id: 'clinical-risk', type: 'risk', statement: 'The workflow permits a vendor to influence care timing without adequate clinical control.', correct: true, critical: true },
      { id: 'privacy-gap', type: 'risk', statement: 'Mandatory BAA elements and the separate subcontractor, access, incident, audit, and exit controls require completion and documented review.', correct: true },
      { id: 'demo-safe', type: 'risk', statement: 'The high usability score and synthetic-data demonstration support a limited pilot before the remaining privacy and clinical controls are finalized.', correct: false },
    ],
    decisions: [
      { id: 'sign', label: 'Critical', title: 'Approve the limited pilot', body: 'Rely on the low annual value and pilot term, then address referral compensation, clinical deferral, privacy, and exit terms during the first quarterly review.', critical: true },
      { id: 'ban', label: 'Overbroad', title: 'Exclude the vendor and related referral source', body: 'Terminate consideration of the vendor and suspend the referral relationship before testing whether independent terms and controls can remove the identified risks.' },
      { id: 'condition', label: 'Defensible', title: 'Return with material-risk conditions', body: 'Remove referral-linked pay, resolve conflict, preserve clinical authority, complete privacy/security terms, and define monitoring and exit.', correct: true },
      { id: 'it', label: 'Incomplete', title: 'Complete technical approval first', body: 'Authorize IT and Privacy to approve the platform and data exchange while Operations separately negotiates clinical workflow and referral provisions after launch.' },
    ],
    recordPrompt: 'Select five conditions required before reconsideration.',
    clauses: [
      { id: 'comp', text: 'Remove or independently validate compensation tied to referral activation.', correct: true },
      { id: 'coi', text: 'Complete conflict review and exclude affected persons from selection and approval as required.', correct: true },
      { id: 'clinical-clause', text: 'Preserve agency clinical authority with explicit escalation, review, and patient-communication controls.', correct: true },
      { id: 'privacy', text: 'Complete the mandatory BAA elements and separately negotiate the security, subcontractor, access, incident, audit, retention, return, and deletion controls required by the agency’s risk assessment.', correct: true },
      { id: 'monitor', text: 'Define patient, quality, privacy, referral, access, service, corrective, and termination monitoring.', correct: true },
      { id: 'threshold', text: 'State that price below $25,000 conclusively eliminates materiality.', correct: false, critical: true },
      { id: 'retro', text: 'Begin live-PHI use during contract repair and approve it retroactively.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why did the Board review a small contract in this case?', answers: ['The pilot falls below the spending threshold, but recurring payments and a future renewal option make the aggregate financial exposure material', 'The supplied case rule treats material patient, PHI, clinical, and referral effects as independent review triggers', 'The vendor touches clinical operations, so Board approval is required even if the arrangement uses no PHI or referral-linked compensation'], correct: 1 },
      { id: 'd2', prompt: 'What is the key clinical boundary?', answers: ['The vendor may defer visits within Board-approved parameters if an agency clinician reviews a daily exception report', 'Agency clinical leadership retains care decisions and escalation authority', 'The referral source may set scheduling priorities when the agency documents that patient choice and clinical escalation remain available'], correct: 1 },
      { id: 'd3', prompt: 'What proves post-signature oversight?', answers: ['A signed agreement, implementation checklist, annual vendor attestation, and documented renewal approval', 'Defined monitoring, evidence access, corrective thresholds, and exit rights', 'Quarterly vendor scorecards, invoice approval, user-satisfaction data, and a standing management review meeting'], correct: 1 },
    ],
    remediation: { duty: 'Assess total material effect.', trap: 'A low price and polished demo narrowed attention to procurement while referral, PHI, and clinical risks remained.', repair: 'Map every flow of money, data, patients, decisions, referrals, subcontracting, monitoring, and exit before classifying the arrangement.', transferRule: 'Dollar thresholds do not override independent material-risk triggers.' },
    transfer: { prompt: 'The vendor removes referral-linked compensation and the conflicted owner divests, but the workflow still permits unreviewed visit deferral. Is the arrangement ready?', answers: ['Yes, if the Board limits the pilot population and receives a weekly report of every deferred visit during implementation', 'No; clinical-control and patient-safety defects remain independently material', 'Yes, if the vendor accepts financial responsibility for adverse events associated with an automated deferral'], correct: 1, rationale: 'Correcting one risk domain does not cure a separate clinical-authority defect.' },
  },
  {
    id: 'GB-011', sequence: 11, title: 'Survey, Enforcement & Closure Decisions', shortTitle: 'Survey & enforcement',
    domain: 'Regulatory defense', duration: '52–72 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Crosswalk validation', available: true,
    lede: 'Answer precisely, produce contemporaneous evidence, correct inaccuracies, and control time-sensitive licensing or closure actions.',
    sources: ['CMS Appendix B', 'CO-RA-001–007', 'GV-EA-004', 'GV-EA-005', 'CDPH HHA board-change packet'], achc: ['HH1-1A', 'HH1-1A.01', 'HH1-1B', 'HH1-12A.01'],
    caseTitle: 'The answer that outran the record', caseDate: 'April 21, 2027 · Survey day two',
    caseContext: 'The Chair tells a surveyor every board change was timely reported. A packet draft, roster mismatch, branch approval gap, and prior minutes make that answer unsafe.',
    decisiveDuty: 'A defensible survey response is accurate, bounded, evidenced, and corrected when new facts change it.',
    doctrine: [
      { number: '01', title: 'Answer the question asked', body: 'State verified facts and limits; do not fill evidence gaps with confidence.' },
      { number: '02', title: 'Produce the chain', body: 'Authority, action, implementation, monitoring, and correction should reconcile.' },
      { number: '03', title: 'Correct promptly', body: 'A discovered inaccuracy should be corrected transparently with evidence and action.' },
      { number: '04', title: 'Control the clock', body: 'Board change, branch, sanction, ownership, and closure actions require coordinated deadlines and proof.' },
    ],
    evidence: [
      { id: 'transcript', code: 'S-01', title: 'Survey interview note', kind: 'Survey', status: 'attention', essential: true, relevant: true, summary: 'The Chair gives an unqualified assurance about all change reporting.', details: ['No documents were reviewed during the answer.', 'Surveyor requests the most recent package.', 'Chair promises same-day production.'], source: 'Synthetic interview record' },
      { id: 'roster', code: 'S-02', title: 'Controlled roster comparison', kind: 'Governance', status: 'restricted', essential: true, relevant: true, summary: 'Internal and submitted rosters differ by one director and one effective date.', details: ['Green appears internally but not externally.', 'Ortiz effective date differs by 17 days.', 'No reconciliation sign-off.'], source: 'Synthetic comparison' },
      { id: 'packet', code: 'S-03', title: 'CDPH packet workbench', kind: 'Regulatory', status: 'attention', essential: true, relevant: true, summary: 'The package remains in draft and lacks required supporting items.', details: ['HS 200 incomplete.', 'HS 215A missing for one individual.', 'Org chart omits ownership percentages.', 'Resolution and bylaws versions conflict.'], source: 'Synthetic packet modeled on current CDPH checklist' },
      { id: 'branch', code: 'S-04', title: 'Branch approval file', kind: 'Licensure', status: 'restricted', essential: true, relevant: true, summary: 'Marketing began before the supplied Medicare approval evidence.', details: ['No patient was served from the branch.', 'Public materials state the branch is “now open.”', 'Approval evidence is dated nine days later.'], source: 'Synthetic branch file · ACHC HH1-12A.01 context' },
      { id: 'minutes', code: 'S-05', title: 'Prior Board minutes', kind: 'Minutes', status: 'attention', essential: true, relevant: true, summary: 'The Board was told the package had been submitted, but no submission evidence is attached.', details: ['Action owner reports “filed.”', 'No tracking number or receipt.', 'Follow-up item is marked closed.'], source: 'Synthetic governance record' },
      { id: 'receipt', code: 'S-06', title: 'Submission receipt search', kind: 'Evidence', status: 'attention', essential: true, relevant: true, summary: 'No receipt is found in email, evidence storage, or regulatory log.', details: ['Draft cover letter exists.', 'No sent-message metadata.', 'Compliance cannot verify submission.'], source: 'Synthetic evidence search' },
      { id: 'script', code: 'S-07', title: 'Survey talking points', kind: 'Communication', status: 'attention', relevant: false, summary: 'A draft script says “all requirements fully satisfied.”', details: ['Prepared at 06:12 before the day-two evidence request was received.', 'The change-reporting assurance has no footnote or linked receipt.', 'The author is listed as Executive Communications.'], source: 'Synthetic communication draft' },
    ],
    findings: [
      { id: 'answer', type: 'authority', statement: 'The Chair’s categorical answer exceeds the verified record and requires correction.', correct: true, critical: true },
      { id: 'submission', type: 'authority', statement: 'Board minutes stating “filed” do not substitute for submission evidence.', correct: true },
      { id: 'script-safe', type: 'authority', statement: 'The talking points are reliable for the interview because Executive Communications approved them before the evidence request arrived.', correct: false },
      { id: 'packet-gap', type: 'risk', statement: 'The board-change package is incomplete and internally inconsistent.', correct: true, critical: true },
      { id: 'branch-risk', type: 'risk', statement: 'Premature branch marketing requires factual assessment and correction even though no patient was served there.', correct: true },
      { id: 'hide', type: 'risk', statement: 'The draft packet may be withheld as nonresponsive because it was never submitted, while only final controlled records are produced.', correct: false },
    ],
    decisions: [
      { id: 'defend', label: 'Critical', title: 'Maintain the answer pending formal verification', body: 'Repeat the Chair’s response as the agency position, produce the strongest supporting documents, and correct it only after the internal review reaches a final conclusion.', critical: true },
      { id: 'confess-all', label: 'Overbroad', title: 'Disclose the full suspected failure set', body: 'Tell the surveyor every potential filing, roster, minutes, and governance defect before distinguishing verified facts, unresolved discrepancies, and legal conclusions.' },
      { id: 'correct', label: 'Defensible', title: 'Correct, produce, and remediate', body: 'Correct the answer, explain verified limits, produce responsive evidence, open a controlled regulatory workstream, and preserve all records.', correct: true },
      { id: 'delay', label: 'Critical', title: 'Complete reconciliation before correcting', body: 'Wait until every form and appointment record is reconciled so the agency can provide one final correction instead of an interim factual update.', critical: true },
    ],
    recordPrompt: 'Select five actions for the survey and regulatory response record.',
    clauses: [
      { id: 'correct', text: 'Promptly correct the prior interview response with the verified facts and identified uncertainty.', correct: true },
      { id: 'produce', text: 'Produce the requested records accurately, including responsive drafts when required and appropriately handled.', correct: true },
      { id: 'packet', text: 'Assign completion and reconciliation of the applicable CDPH package, forms, governing documents, and submission evidence.', correct: true },
      { id: 'branch', text: 'Stop or correct premature branch representations and validate all approval evidence.', correct: true },
      { id: 'govern', text: 'Record owners, deadlines, legal/compliance review, Board updates, and effectiveness checks.', correct: true },
      { id: 'rewrite', text: 'Alter prior minutes to remove the statement that the package was filed.', correct: false, critical: true },
      { id: 'destroy', text: 'Delete incomplete drafts before producing the final package.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'What should the Chair say after finding the discrepancy?', answers: ['State that the earlier answer reflected the Board’s good-faith understanding and reserve correction until the full package review is complete', 'Correct the record promptly, state verified facts and limits, and explain the controlled response', 'Withdraw the answer and direct all remaining questions to counsel without identifying which facts are verified or disputed'], correct: 1 },
      { id: 'd2', prompt: 'What proves submission?', answers: ['Approved minutes, the signed resolution, and a dated cover letter placed in the regulatory correspondence file', 'A complete reconciled package plus reliable transmission/receipt evidence', 'A regulator-facing roster and organization chart that match the internal registry and show the intended effective date'], correct: 1 },
      { id: 'd3', prompt: 'Why preserve the inaccurate earlier record?', answers: ['To demonstrate that the statement was made before the discrepancy was known and therefore should not affect the current compliance assessment', 'To maintain an honest audit trail showing discovery, correction, and remediation', 'To preserve only the original wording that differs from the correction, while replacing supporting drafts to avoid duplicate records'], correct: 1 },
    ],
    remediation: { duty: 'Accuracy beats confidence.', trap: 'A categorical answer and polished talking points arrived before evidence reconciliation.', repair: 'For every survey answer, mark verified fact, source, limit, owner, and any correction duty before speaking.', transferRule: 'A corrected answer is stronger than a confidently repeated inaccuracy.' },
    transfer: { prompt: 'A receipt is later found proving timely submission, but the submitted roster still contains an incorrect effective date. What is the defensible response?', answers: ['Report that timely submission is now verified and treat the date variance as an internal clerical issue unless the regulator separately requests correction', 'Update the surveyor/regulator accurately: submission is verified, but the content discrepancy remains and is being corrected', 'Replace the roster in the retained submission set with a corrected copy and explain that the receipt confirms the package itself was timely'], correct: 1, rationale: 'One newly verified fact narrows the issue; it does not erase a separate content error.' },
  },
  {
    id: 'GB-012', sequence: 12, title: 'Conflicts, Ethics & Governance Improvement', shortTitle: 'Conflicts & ethics',
    domain: 'Board integrity', duration: '44–60 min', difficulty: 'Expert', posture: 'provisional', postureLabel: 'Policy validation', available: true,
    lede: 'Detect indirect conflicts, repair contaminated deliberation, and convert self-assessment into measurable governance improvement.',
    sources: ['GV-GB-003', 'GV-GB-005', 'CO-CP-004'], achc: ['HH1-4A.01', 'HH2-7A.01'],
    caseTitle: 'The conflict nobody owned', caseDate: 'May 18, 2027 · Annual self-assessment',
    caseContext: 'A director’s spouse advises a vendor owned by a referral partner. The director never receives vendor payments but shaped the selection criteria and attended deliberation.',
    decisiveDuty: 'A conflict can be indirect, noncash, and still contaminate information access, deliberation, and public trust.',
    doctrine: [
      { number: '01', title: 'Disclose broadly', body: 'Evaluate family, financial, professional, referral, gift, and loyalty interests—not only direct payment.' },
      { number: '02', title: 'Manage the process', body: 'Disclosure, access restriction, recusal, departure, quorum, minutes, and follow-up are separate controls.' },
      { number: '03', title: 'Repair contamination', body: 'Determine what information and decisions were affected; do not merely collect a late form.' },
      { number: '04', title: 'Improve the Board', body: 'Self-assessment produces owners, measures, deadlines, and verification.' },
    ],
    evidence: [
      { id: 'annual', code: 'E-01', title: 'Annual disclosure', kind: 'Conflict', status: 'attention', essential: true, relevant: true, summary: 'The director checked “no conflicts” six months earlier.', details: ['Form asks about spouse relationships.', 'Director later says the advisory role was “informal.”', 'No amendment was filed before vendor selection.'], source: 'Synthetic disclosure · ACHC HH1-4A.01 context' },
      { id: 'spouse', code: 'E-02', title: 'Advisory engagement', kind: 'Restricted', status: 'restricted', essential: true, relevant: true, summary: 'The spouse receives a monthly fee from the selected vendor.', details: ['Engagement began before RFP drafting.', 'Fee does not vary by award.', 'Spouse advised on market positioning.'], source: 'Synthetic agreement' },
      { id: 'referral', code: 'E-03', title: 'Ownership and referral map', kind: 'Relationship', status: 'restricted', essential: true, relevant: true, summary: 'The vendor is 35% owned by an executive of a material referral source.', details: ['Relationship was not shown in the selection packet.', 'No claim of illegality is established by ownership alone.', 'The relationship increases conflict and compliance scrutiny.'], source: 'Synthetic relationship map' },
      { id: 'criteria', code: 'E-04', title: 'RFP edit history', kind: 'System log', status: 'attention', essential: true, relevant: true, summary: 'The director added criteria uniquely favorable to the vendor.', details: ['Two criteria mirror the spouse’s advisory deck.', 'Other members were not told of the connection.', 'Changes materially affected scoring.'], source: 'Synthetic audit history' },
      { id: 'minutes', code: 'E-05', title: 'Selection minutes', kind: 'Minutes', status: 'attention', essential: true, relevant: true, summary: 'The minutes say no conflicts were disclosed and record a unanimous vote.', details: ['Director presented comparative scoring.', 'No departure from the room.', 'Quorum would have remained without the director.'], source: 'Synthetic meeting record' },
      { id: 'assessment', code: 'E-06', title: 'Governance self-assessment', kind: 'Improvement', status: 'attention', essential: true, relevant: true, summary: 'Members rate conflict management highly but evidence review shows gaps.', details: ['No event-specific disclosure prompt.', 'Annual forms are not cross-checked against vendor/referral files.', 'Prior action item “improve disclosure” has no owner or due date.'], source: 'Synthetic assessment' },
      { id: 'bio', code: 'E-07', title: 'Director biography', kind: 'Profile', status: 'clean', relevant: false, summary: 'The director is widely respected and serves on nonprofit boards.', details: ['The profile lists healthcare strategy and procurement experience.', 'It identifies three community-board appointments.', 'It contains no family, vendor, advisory, or referral-relationship fields.'], source: 'Synthetic director profile' },
    ],
    findings: [
      { id: 'indirect', type: 'authority', statement: 'The spouse and referral/vendor relationships create an indirect conflict requiring management.', correct: true, critical: true },
      { id: 'process', type: 'authority', statement: 'The director influenced criteria, accessed information, deliberated, and voted without conflict controls.', correct: true, critical: true },
      { id: 'no-direct', type: 'authority', statement: 'Because no payment reached the director, an amended annual disclosure fully resolves the relationship without reassessing prior participation.', correct: false },
      { id: 'minutes', type: 'risk', statement: 'The minutes are inaccurate when they state that no conflicts were disclosed or present.', correct: true },
      { id: 'system', type: 'risk', statement: 'The annual-only disclosure process and unowned improvement action are weak governance controls.', correct: true },
      { id: 'respect', type: 'risk', statement: 'The director’s record and an unchanged vendor outcome permit the repair to end with a late disclosure and minutes addendum.', correct: false },
    ],
    decisions: [
      { id: 'late-form', label: 'Critical', title: 'Complete disclosure and preserve the award', body: 'Obtain an amended conflict form, document that the director received no direct payment, and leave the scoring and award intact unless price is shown unreasonable.', critical: true },
      { id: 'permanent', label: 'Overbroad', title: 'Remove the director and cancel the award', body: 'End the director’s service and vendor relationship immediately without first assessing the policy, neutral scoring, fair value, patient impact, or available process repair.' },
      { id: 'repair', label: 'Defensible', title: 'Isolate, reassess, and improve', body: 'Restrict the conflicted director, independently reassess the procurement and prior action, correct the record, and strengthen disclosure controls.', correct: true },
      { id: 'ignore', label: 'Critical', title: 'Treat the relationship as nonfinancial', body: 'Record the spouse’s fixed advisory fee as outside the director’s personal interest and require future disclosure only if compensation depends on the award.', critical: true },
    ],
    recordPrompt: 'Select five clauses for a defensible conflict-management action.',
    clauses: [
      { id: 'restrict', text: 'The affected director will not receive further nonpublic materials, deliberate, or vote on the matter pending resolution.', correct: true },
      { id: 'independent', text: 'A conflict-free group will reassess criteria, scoring, alternatives, fair value, and referral implications.', correct: true },
      { id: 'record', text: 'Correct the official record prospectively through an accurate addendum or subsequent minutes without rewriting history.', correct: true },
      { id: 'decision', text: 'Determine the validity and remedy of the procurement using the supplied governing and policy rules.', correct: true },
      { id: 'improve', text: 'Implement event-specific disclosure prompts, relationship cross-checks, owners, deadlines, and effectiveness review.', correct: true },
      { id: 'sanitize', text: 'Delete the director’s participation from the original minutes.', correct: false, critical: true },
      { id: 'cash-only', text: 'Limit future disclosure questions to direct payments received by Board members.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why is this a conflict without direct payment to the director?', answers: ['The spouse’s compensated role is imputed automatically to the director, making the vendor ineligible regardless of influence or process controls', 'Family, professional, referral, and loyalty interests can impair or appear to impair independent judgment', 'The vendor’s selection creates a conflict retrospectively even if the director did not know of the spouse’s engagement during deliberation'], correct: 1 },
      { id: 'd2', prompt: 'What must be repaired beyond the form?', answers: ['The annual disclosure, minutes, and procurement file, provided an independent reviewer confirms the selected vendor remained the highest scorer', 'Information access, criteria influence, deliberation, vote, record, procurement validity, and future controls', 'The director’s disclosure and recusal record plus a prospective policy amendment covering spouse and referral-source relationships'], correct: 1 },
      { id: 'd3', prompt: 'What makes self-assessment effective?', answers: ['Documented member ratings, narrative comments, and annual Board acceptance of the completed assessment', 'Specific improvement actions with owners, deadlines, measures, and verification', 'Comparison with the prior year’s scores and evidence that every low-rated domain received an educational response'], correct: 1 },
    ],
    remediation: { duty: 'Manage influence, not just money.', trap: 'An indirect relationship and a respected member made the conflict easy to rationalize as immaterial.', repair: 'Map interest, information, influence, deliberation, vote, record, underlying action, and control improvement separately.', transferRule: 'A late disclosure reveals a problem; it does not retroactively cure contaminated process.' },
    transfer: { prompt: 'Independent reassessment shows the same vendor remains clearly superior under neutral criteria and fair-value terms. What follows?', answers: ['The Board may ratify the original award because neutral rescoring proves the conflict did not change the economic outcome', 'The Board may make a new conflict-free decision with an accurate record after completing required reviews; the old process remains historically defective', 'The Board should select the next-ranked vendor because a new award to the same vendor would leave an appearance concern that process controls cannot address'], correct: 1, rationale: 'A sound new decision can follow independent reassessment, but it does not rewrite the earlier contaminated process.' },
  },
  {
    id: 'GB-CAPSTONE', sequence: 13, title: 'The Governance Record Under Pressure', shortTitle: 'Capstone',
    domain: 'Integrated command', duration: '75–95 min', difficulty: 'Capstone', posture: 'gated', postureLabel: 'Certification gated', available: true,
    lede: 'Defend two interlocked cases where authority, QAPI, fiscal pressure, conflict, survey evidence, and patient risk collide.',
    sources: ['42 CFR 484.65', '42 CFR 484.105', 'CMS Appendix B', 'GB policy set · canonical identity reconciliation required for certification'], achc: ['HH1-1A', 'HH1-2A', 'HH1-4A.01', 'HH1-5A.01', 'HH1-10A', 'HH1-12A.01', 'HH2-5C.01', 'HH2-7A.01', 'HH2-9A.01', 'HH3-1A', 'HH3-1B', 'HH3-1C', 'HH6-1A', 'HH6-1C', 'HH6-1D.01', 'HH6-3A.01', 'HH6-4A.02', 'HH6-4A.04', 'HH6-4A.05', 'HH6-4A.06', 'HH6-4A.07', 'HH6-5A', 'HH6-7A.01'],
    caseTitle: 'The clean packet', caseDate: 'June 24, 2027 · Annual governance review',
    caseContext: 'The annual packet is immaculate. Underneath it, a conflicted vendor decision, a masked QAPI subgroup, an unreported board change, and a budget condition all depend on the same inaccurate minutes.',
    decisiveDuty: 'Executive governance is the ability to reconstruct truth across systems, then make a lawful, patient-protective, evidence-backed decision under pressure.',
    doctrine: [
      { number: '01', title: 'Reconstruct authority', body: 'Establish who could act, under which rule, with what conflict and quorum conditions.' },
      { number: '02', title: 'Interrogate performance', body: 'Test aggregate claims against subgroup, complaint, incident, and source evidence.' },
      { number: '03', title: 'Protect the record', body: 'Do not make the official record cleaner than the underlying facts.' },
      { number: '04', title: 'Direct the enterprise', body: 'Resolve immediate risk while assigning durable corrective systems and effectiveness review.' },
    ],
    evidence: [
      { id: 'minutes', code: 'X-01', title: 'Annual governance minutes', kind: 'Minutes', status: 'attention', essential: true, relevant: true, summary: 'Minutes record unanimous approvals, full disclosure, and timely reporting.', details: ['Attendance log shows one disconnected remote member.', 'Conflict trail shows a director participated.', 'No submission receipt supports the board-change statement.'], source: 'Synthetic capstone record' },
      { id: 'qapi', code: 'X-02', title: 'Annual QAPI report', kind: 'Quality', status: 'restricted', essential: true, relevant: true, summary: 'Aggregate goals are met; a fragile subgroup and linked complaints worsened.', details: ['PIP closure criteria require subgroup success.', 'Budget assumes the PIP closes.', 'Committee minutes do not show consensus.'], source: 'Synthetic capstone analysis' },
      { id: 'contract', code: 'X-03', title: 'Vendor agreement and ownership map', kind: 'Contract', status: 'restricted', essential: true, relevant: true, summary: 'The vendor handles PHI and care routing; an interested director influenced selection.', details: ['BAA exit terms are incomplete.', 'Referral-linked compensation remains.', 'Board motion treated the item as informational until the vote.'], source: 'Synthetic capstone contract' },
      { id: 'budget', code: 'X-04', title: 'Adopted budget conditions', kind: 'Finance', status: 'attention', essential: true, relevant: true, summary: 'Savings depend on vendor go-live and QAPI resource release.', details: ['Liquidity remains above floor for eight weeks.', 'Denial root causes are unresolved.', 'Compliance independence funding is preserved only in an unapproved appendix.'], source: 'Synthetic capstone budget' },
      { id: 'board', code: 'X-05', title: 'Board authority and CDPH file', kind: 'Governance', status: 'restricted', essential: true, relevant: true, summary: 'One voting participant was never validly appointed and the external packet remains draft.', details: ['Quorum may still exist without the nominee.', 'Vote margins differ by item.', 'No CDPH transmission evidence.'], source: 'Synthetic capstone authority file' },
      { id: 'incident', code: 'X-06', title: 'Patient-safety escalation', kind: 'Risk', status: 'restricted', essential: true, relevant: true, summary: 'A delayed after-hours response involves the same vendor workflow and high-risk subgroup.', details: ['Patient stabilized.', 'Prior complaints identify similar delay.', 'The incident was excluded from the annual narrative as “post-period.”'], source: 'Synthetic capstone incident' },
      { id: 'script', code: 'X-07', title: 'Survey interview script', kind: 'Communication', status: 'attention', relevant: false, summary: 'The script describes all systems as effective and fully implemented.', details: ['Version metadata shows it was written before the annual packet was reconciled.', 'It uses “all,” “fully,” and “without exception” across six answers.', 'No source links, evidence owners, or qualification notes are embedded.'], source: 'Synthetic interview preparation draft' },
      { id: 'audit', code: 'X-08', title: 'Cross-system audit trail', kind: 'Evidence', status: 'restricted', essential: true, relevant: true, summary: 'Timestamps connect policy, minutes, QAPI, contract, and budget inconsistencies.', details: ['Several “approved” files predate the meeting.', 'One appendix changed afterward without addendum.', 'Access history identifies the editors.'], source: 'Synthetic capstone audit trail' },
    ],
    findings: [
      { id: 'authority', type: 'authority', statement: 'The decision record must be reconstructed item by item using valid membership, participation, notice, conflict, and voting facts.', correct: true, critical: true },
      { id: 'record', type: 'authority', statement: 'The clean minutes are materially unreliable across several decisions.', correct: true, critical: true },
      { id: 'all-void', type: 'authority', statement: 'The unappointed nominee’s participation makes every action presumptively invalid until the Board repeats the full agenda.', correct: false },
      { id: 'qapi', type: 'risk', statement: 'QAPI closure and related budget savings are unsupported by subgroup and complaint evidence.', correct: true, critical: true },
      { id: 'contract', type: 'risk', statement: 'The vendor arrangement combines conflict, referral, PHI, clinical-control, and monitoring risk.', correct: true },
      { id: 'post-period', type: 'risk', statement: 'Because the incident arose after the report period, it may be excluded from the current QAPI and budget decisions if it is managed in the next cycle.', correct: false },
    ],
    decisions: [
      { id: 'accept', label: 'Critical', title: 'Accept with a consolidated correction plan', body: 'Approve the annual packet and dependent actions, then require management to repair the minutes, filing, subgroup, contract, and budget evidence before the next quarter.', critical: true },
      { id: 'void', label: 'Overbroad', title: 'Suspend every dependent annual action', body: 'Treat each approval, budget line, contract step, QAPI decision, and filing as ineffective until the entire annual record is reconstructed and reapproved.' },
      { id: 'command', label: 'Defensible', title: 'Issue an integrated corrective command', body: 'Protect patients, preserve evidence, quarantine unsupported actions, reconstruct each decision, correct reporting, and require measured remediation.', correct: true },
      { id: 'rewrite', label: 'Critical', title: 'Issue corrected final versions', body: 'Replace the minutes, dashboard, filing packet, and approval appendix with reconciled versions before production, retaining only a general note that administrative corrections occurred.', critical: true },
    ],
    recordPrompt: 'Select five directives for the integrated governance action.',
    clauses: [
      { id: 'safety', text: 'Implement immediate patient and after-hours safeguards while preserving current service continuity.', correct: true },
      { id: 'preserve', text: 'Preserve all source records, versions, access logs, communications, and submission evidence.', correct: true },
      { id: 'quarantine', text: 'Do not rely on disputed approvals until each item is reconstructed under its actual authority and evidence.', correct: true },
      { id: 'workstreams', text: 'Assign conflict-free QAPI, contract, governance-record, regulatory, budget, and incident workstreams with one integrated executive timeline.', correct: true },
      { id: 'return', text: 'Require owners, deadlines, resources, thresholds, corrected records, external-reporting decisions, and effectiveness evidence.', correct: true },
      { id: 'clean', text: 'Replace source records with corrected versions that omit the original defects.', correct: false, critical: true },
      { id: 'guarantee', text: 'State that no citation or enforcement action can occur after these directives.', correct: false },
    ],
    defense: [
      { id: 'd1', prompt: 'Why not accept the polished packet?', answers: ['Its narrative omits several known qualifications, even though the underlying approvals can be preserved through a consolidated corrective-action plan', 'Its conclusions fail cross-source reconciliation across authority, QAPI, conflict, and reporting evidence', 'Its component reports use different reporting periods, so the Board should defer only the annual summary while leaving each component decision unchanged'], correct: 1 },
      { id: 'd2', prompt: 'Why not void every action immediately?', answers: ['The Board should first correct the annual minutes because a reliable master record will determine which dependent actions remain valid', 'Validity and remedy must be assessed item by item using the applicable facts and rules', 'The affected actions remain presumptively valid until a regulator, court, or contracting party formally challenges the underlying records'], correct: 1 },
      { id: 'd3', prompt: 'What is the strongest survey defense?', answers: ['A complete corrected packet, leadership attestations, and evidence that no patient experienced lasting harm from the identified deficiencies', 'An accurate evidence chain showing discovery, protection, correction, accountable remediation, and effectiveness', 'A privileged investigation report, Board resolution accepting remediation, and a commitment to provide effectiveness data at the next annual review'], correct: 1 },
    ],
    remediation: { duty: 'Integrate without collapsing distinctions.', trap: 'Every individual artifact looked plausible; only cross-system reconciliation exposed the shared defects.', repair: 'Build one timeline and decision ledger linking person, authority, evidence, risk, decision, record, implementation, monitoring, and correction.', transferRule: 'Resolve each defect on its own facts, then test how its remedy changes dependent decisions.' },
    transfer: { prompt: 'Independent reconstruction confirms the budget motion had valid quorum and no conflict, but it relied expressly on an invalid vendor approval and unsupported PIP closure. What is the best conclusion?', answers: ['Preserve the budget vote because its procedure was valid, but freeze only the vendor and QAPI savings lines until those assumptions are repaired', 'Its procedural vote may be valid, but the Board must reassess the dependent assumptions and take a new informed budget action', 'Treat the budget as ineffective from adoption because a material false premise contaminates every appropriation, including unrelated operating expenses'], correct: 1, rationale: 'Procedural validity does not make materially false dependencies safe. The Board must reassess and act on accurate information.' },
  },
];
