import type { AcademyModuleSummary, ExecutiveCaseModule } from './academyTypes';
import { additionalCases } from './academyDataMore';

const cases: ExecutiveCaseModule[] = [
  {
    id: 'GB-001', sequence: 1, title: 'The Authority That Cannot Disappear', shortTitle: 'Authority',
    domain: 'Legal accountability', duration: '38–52 min', difficulty: 'Expert', posture: 'gated',
    postureLabel: 'Attestation gated', available: true,
    lede: 'Separate retained accountability from work that may be assigned, contracted, or operationally directed.',
    sources: ['42 CFR 484.105(a)–(c)', '42 CFR 484.65(e)', 'CMS Appendix B', 'GV-GB-001 · canonical identity reconciliation required', 'GV-OG-002', 'GV-OG-003 · canonical identity reconciliation required'],
    achc: ['HH1-1A', 'HH1-5A', 'HH1-5A.01', 'HH1-6B'],
    caseTitle: 'The management agreement', caseDate: 'August 4, 2026 · Special session',
    caseContext: 'A proposed management-company agreement promises rapid stabilization, but its exhibits quietly relocate appointment, QAPI, budget, and clinical-control decisions.',
    decisiveDuty: 'The Governing Body may obtain help; it cannot contract away the accountability that defines it.',
    doctrine: [
      { number: '01', title: 'Retain accountability', body: 'Legal responsibility remains with the Governing Body even when competent people perform the work.' },
      { number: '02', title: 'Name the operator', body: 'The Administrator directs day-to-day operations and reports to the Governing Body.' },
      { number: '03', title: 'Test the boundary', body: 'Ask who decides, who monitors, who can correct, and what evidence reaches the Board.' },
      { number: '04', title: 'Do not confuse expertise with authority', body: 'A contractor may advise or execute within limits; expertise does not transfer statutory accountability.' },
    ],
    evidence: [
      { id: 'agreement', code: 'A-01', title: 'Management services agreement', kind: 'Contract', status: 'restricted', essential: true, relevant: true, summary: 'The vendor receives “exclusive authority” over four reserved functions.', details: ['Vendor appoints and removes the Administrator without further Board action.', 'Vendor approves the annual operating budget and may reallocate QAPI resources.', 'Vendor’s clinical director has final authority over standards of care.', 'The Board receives a quarterly one-page performance summary.'], source: 'Synthetic contract · compare with 42 CFR 484.105' },
      { id: 'matrix', code: 'A-02', title: 'Delegation matrix', kind: 'Governance', status: 'attention', essential: true, relevant: true, summary: 'The RACI chart leaves the Board merely “informed.”', details: ['QAPI priorities: vendor accountable; Board informed.', 'Administrator evaluation: vendor accountable.', 'Budget approval: vendor accountable.', 'Policy adoption: vendor accountable.'], source: 'Synthetic operating exhibit' },
      { id: 'minutes', code: 'A-03', title: 'Special-session draft minutes', kind: 'Minutes', status: 'attention', essential: true, relevant: true, summary: 'The motion adopts the agreement “as presented” without retained-duty findings.', details: ['No clause preserves Governing Body authority.', 'No monitoring cadence, escalation threshold, or termination trigger is recorded.', 'The Administrator was absent from the executive presentation.'], source: 'Synthetic meeting record' },
      { id: 'qapi', code: 'A-04', title: 'QAPI escalation memorandum', kind: 'Quality', status: 'restricted', essential: true, relevant: true, summary: 'Two high-risk indicators already require executive attention.', details: ['Hospitalization subgroup increased while aggregate rate improved.', 'The proposed budget removes the analyst assigned to validation.', 'The vendor calls both matters “operational.”'], source: 'Synthetic QAPI memorandum · 42 CFR 484.65(e)' },
      { id: 'org', code: 'A-05', title: 'Current organization chart', kind: 'Organization', status: 'clean', relevant: true, summary: 'The Administrator and Clinical Manager currently report through defined lines.', details: ['Administrator reports to the Governing Body.', 'Clinical Manager reports to the Administrator.', 'No management company appears in the approved chart.'], source: 'Synthetic controlled record' },
      { id: 'brochure', code: 'A-06', title: 'Vendor capability brochure', kind: 'Marketing', status: 'clean', relevant: false, summary: 'The vendor advertises national scale and an accreditation success rate.', details: ['The brochure reports support for 43 healthcare organizations.', 'It advertises a 98% accreditation-readiness rate.', 'Underlying client references and calculation methods are not included.'], source: 'Synthetic vendor marketing' },
      { id: 'legal', code: 'A-07', title: 'Counsel issue list', kind: 'Legal', status: 'attention', essential: true, relevant: true, summary: 'Counsel flags reserved powers but has not approved the agreement.', details: ['Appointment, budget, QAPI, and clinical oversight clauses require revision.', 'Operational support may remain if decision rights and reporting are repaired.', 'The memo is advisory; the Board must make and record the decision.'], source: 'Synthetic privileged training artifact' },
    ],
    findings: [
      { id: 'abdication', type: 'authority', statement: 'The agreement converts four retained Governing Body duties into vendor-exclusive powers.', correct: true, critical: true },
      { id: 'operator', type: 'authority', statement: 'The Administrator’s day-to-day role is displaced rather than supported.', correct: true },
      { id: 'contracting', type: 'authority', statement: 'Section 484.105 prevents a management contractor from holding substantial operating duties even when the Board retains documented decision and corrective rights.', correct: false },
      { id: 'qapi-risk', type: 'risk', statement: 'The proposed reporting and resource model weakens meaningful QAPI oversight.', correct: true, critical: true },
      { id: 'marketing', type: 'risk', statement: 'The vendor’s accreditation history and the current organization chart together provide sufficient assurance that retained controls will persist after transition.', correct: false },
      { id: 'record', type: 'risk', statement: 'The draft minutes do not show the Board tested retained authority or monitoring.', correct: true },
    ],
    decisions: [
      { id: 'approve', label: 'Critical', title: 'Approve with enhanced reporting', body: 'Accept the exclusive-authority clauses, add monthly dashboards, and rely on the Board’s termination right if performance deteriorates.', critical: true },
      { id: 'rejectall', label: 'Overbroad', title: 'Retain every operational function', body: 'Reject the agreement and require the Board to approve routine staffing, scheduling, purchasing, and clinical-operating decisions.' },
      { id: 'repair', label: 'Defensible', title: 'Return with reserved-power repairs', body: 'Preserve appointments, budget, QAPI, clinical authority, monitoring, escalation, and corrective control with the Board.', correct: true },
      { id: 'defer', label: 'Incomplete', title: 'Defer to counsel’s risk opinion', body: 'Pause execution, obtain counsel’s written risk ranking, and treat that opinion as the final decision without a recorded Board authority analysis.' },
    ],
    recordPrompt: 'Select the five clauses that create a defensible Board directive.',
    clauses: [
      { id: 'retain', text: 'The Governing Body retains full legal authority and responsibility notwithstanding contracted support.', correct: true },
      { id: 'appoint', text: 'Appointment and evaluation of the Administrator remain Governing Body actions.', correct: true },
      { id: 'monitor', text: 'Management must return with defined metrics, reporting cadence, escalation thresholds, and corrective rights.', correct: true },
      { id: 'qapi-clause', text: 'QAPI priorities and resource adequacy remain subject to Governing Body oversight.', correct: true },
      { id: 'conditional', text: 'Revised documents require legal/compliance review and a subsequent recorded Board decision.', correct: true },
      { id: 'expertise', text: 'Because the vendor has greater expertise, it assumes the Board’s regulatory accountability.', correct: false, critical: true },
      { id: 'retro', text: 'The agreement is effective immediately and may be ratified after implementation.', correct: false },
    ],
    defense: [
      { id: 'd1', prompt: 'What is the cleanest proof that the Board did not abdicate?', answers: ['A credentialed vendor, detailed work plan, and contractual indemnity for operational failures', 'Reserved powers plus active monitoring and corrective control', 'A termination clause, quarterly scorecard, and counsel’s opinion that delegation is customary'], correct: 1 },
      { id: 'd2', prompt: 'Who remains responsible for day-to-day operation?', answers: ['The Administrator, operating within Board-approved authority and oversight', 'The management company executive who controls the largest share of operational resources', 'The Board Chair acting through weekly executive instructions and exception approvals'], correct: 0 },
      { id: 'd3', prompt: 'Can outside experts perform substantial work?', answers: ['Only advisory work; substantial execution would necessarily transfer the Board’s accountability', 'Yes, if accountability, boundaries, monitoring, and correction remain clear', 'Yes, when the agreement includes measurable outcomes, indemnity, and a right to terminate for cause'], correct: 1 },
    ],
    remediation: { duty: 'Accountability survives delegation.', trap: 'The agreement used competent people and polished reporting to make abdication look efficient.', repair: 'Mark every decision right, oversight input, escalation trigger, and corrective power before approving the operating model.', transferRule: 'Change one contractual fact at a time; do not let expertise, price, or indemnity answer the authority question.' },
    transfer: { prompt: 'The revised agreement lets the vendor recommend an Administrator, but only the Governing Body may appoint, evaluate, or remove that person. The vendor operates under Board-approved metrics and immediate escalation duties. What remains required?', answers: ['Annual contract renewal supported by the vendor’s certification that every delegated activity met the approved metrics', 'Ongoing Board oversight, evidence review, and corrective action when performance fails', 'Chair-level approval of material staffing and scheduling exceptions, with the full Board reviewing only unresolved disputes'], correct: 1, rationale: 'The repaired authority boundary permits support, but retained accountability still requires active oversight and correction.' },
  },
  {
    id: 'GB-002', sequence: 2, title: 'Structure, Bylaws, Membership & Orientation', shortTitle: 'Structure',
    domain: 'Board constitution', duration: '42–58 min', difficulty: 'Expert', posture: 'provisional',
    postureLabel: 'Policy validation', available: true,
    lede: 'Prove that the people exercising authority were validly seated, oriented, and consistently reported across every controlling record.',
    sources: ['42 CFR 484.105(a)', 'CDPH HHA Change of Governing Board packet (current HS 200 and HS 215A required as applicable)', 'GV-GB-001 · canonical identity reconciliation required'],
    achc: ['HH1-1A', 'HH1-1A.01', 'HH1-1B', 'HH1-2A', 'HH1-2A.03'],
    caseTitle: 'The invisible board change', caseDate: 'September 10, 2026 · Organizational action',
    caseContext: 'Two directors begin voting immediately after a restructuring. Internally the Board appears complete; the appointment trail and regulatory package tell a different story.',
    decisiveDuty: 'A board roster is not self-authenticating. Authority must reconcile to bylaws, appointments, orientation, minutes, organization records, and required reporting.',
    doctrine: [
      { number: '01', title: 'Constitute authority', body: 'Verify the legal instrument, authorized seats, appointments, terms, and voting rights.' },
      { number: '02', title: 'Complete and evidence orientation', body: 'Complete and document governance orientation within the applicable post-appointment deadline; experience is not substitute evidence.' },
      { number: '03', title: 'Reconcile every record', body: 'Board, ownership, organization, enrollment, and licensing records must describe the same reality.' },
      { number: '04', title: 'Report the change', body: 'A resolution alone is not the complete CDPH board-change package.' },
    ],
    evidence: [
      { id: 'bylaws', code: 'B-01', title: 'Controlled bylaws', kind: 'Authority', status: 'restricted', essential: true, relevant: true, summary: 'Five voting seats require appointment by the sole corporate member.', details: ['Terms begin only after written member action.', 'Vacancies do not expand remaining members’ appointment authority.', 'Remote participation is permitted with real-time two-way communication.'], source: 'Synthetic bylaw excerpt' },
      { id: 'roster', code: 'B-02', title: 'Board roster', kind: 'Governance', status: 'attention', essential: true, relevant: true, summary: 'Two new directors appear with start dates but no appointment references.', details: ['Seven voting names are listed although bylaws authorize five seats.', 'Two former directors remain in the “active” distribution group.', 'Term fields are blank for the two new directors.'], source: 'Synthetic controlled record' },
      { id: 'member-action', code: 'B-03', title: 'Corporate-member action', kind: 'Appointment', status: 'restricted', essential: true, relevant: true, summary: 'One new director is appointed; the second is only nominated.', details: ['Signed action appoints L. Ortiz effective September 1.', 'M. Green is identified as a nominee pending background review.', 'No later written action is supplied.'], source: 'Synthetic corporate action' },
      { id: 'orientation', code: 'B-04', title: 'Orientation register', kind: 'Education', status: 'attention', essential: true, relevant: true, summary: 'Both individuals attended a briefing; only one completed the required orientation evidence.', details: ['Ortiz completed authority, QAPI, conflict, and survey-evidence topics.', 'Green signed a confidentiality form only.', 'No competency or policy acknowledgement is recorded for Green.'], source: 'Synthetic training record · ACHC HH1-2A.03 context' },
      { id: 'minutes', code: 'B-05', title: 'September draft minutes', kind: 'Minutes', status: 'attention', essential: true, relevant: true, summary: 'Both individuals are counted for quorum and vote on a budget amendment.', details: ['Opening record lists six voting members present.', 'Green seconds and votes on the budget motion.', 'The minutes state “all directors duly seated” without supporting reference.'], source: 'Synthetic meeting record' },
      { id: 'cdph', code: 'B-06', title: 'CDPH change packet index', kind: 'Regulatory', status: 'restricted', essential: true, relevant: true, summary: 'The packet includes a resolution but omits several reconciliation documents.', details: ['HS 200 is incomplete.', 'Organizational chart omits ownership percentages and the parent relationship.', 'HS 215A is prepared for Ortiz but not Green.', 'No reconciled director/officer list is attached.'], source: 'Synthetic packet modeled on current CDPH checklist' },
      { id: 'bio', code: 'B-07', title: 'Executive biographies', kind: 'Background', status: 'clean', relevant: false, summary: 'Both candidates have distinguished healthcare careers.', details: ['Ortiz lists 18 years of health-system finance leadership.', 'Green lists prior nonprofit board and compliance-committee service.', 'Neither biography identifies the appointing instrument, term, or governance-orientation date.'], source: 'Synthetic candidate profiles' },
    ],
    findings: [
      { id: 'seat', type: 'authority', statement: 'Green was nominated but not appointed under the supplied bylaws.', correct: true, critical: true },
      { id: 'size', type: 'authority', statement: 'The controlled roster exceeds the number of voting seats authorized by the bylaws.', correct: true },
      { id: 'experience', type: 'authority', statement: 'Green’s documented prior board service permits provisional participation while the corporate member completes the appointment instrument.', correct: false },
      { id: 'orientation-gap', type: 'risk', statement: 'The orientation record is incomplete for a person already treated as a voting member.', correct: true },
      { id: 'packet-gap', type: 'risk', statement: 'The CDPH package is not complete or reconciled to the internal authority records.', correct: true, critical: true },
      { id: 'resolution-only', type: 'risk', statement: 'The signed resolution and completed HS 215A for Ortiz are sufficient for the current filing; the roster and organization-chart discrepancies may be reconciled later.', correct: false },
    ],
    decisions: [
      { id: 'ratify', label: 'Critical', title: 'Ratify the prior participation', body: 'Approve a present-day appointment resolution that deems Green seated from the earlier meeting, then certify the existing minutes and filing package.', critical: true },
      { id: 'exclude-all', label: 'Overbroad', title: 'Reconstitute the full Board', body: 'Suspend every director and reopen all prior actions until each appointment, term, orientation record, and filing can be reverified.' },
      { id: 'repair', label: 'Defensible', title: 'Quarantine and reconcile', body: 'Stop relying on Green’s vote, validate affected actions, complete appointment/orientation, and submit a reconciled CDPH package.', correct: true },
      { id: 'hr', label: 'Incomplete', title: 'Complete orientation prospectively', body: 'Have HR finish Green’s orientation and update the roster, while leaving the appointment gap, affected votes, and external package unreconciled.' },
    ],
    recordPrompt: 'Select the five directives that repair authority and the external record.',
    clauses: [
      { id: 'quarantine', text: 'Do not count the nominee as a voting member until valid appointment evidence exists.', correct: true },
      { id: 'review-actions', text: 'Review each affected action using the valid membership, quorum, and voting facts applicable at the time.', correct: true },
      { id: 'orientation-clause', text: 'Complete and retain governance-specific orientation within 14 calendar days after appointment; impose a pre-participation condition only if the controlling bylaws or appointment instrument requires it.', correct: true },
      { id: 'reconcile', text: 'Reconcile bylaws, appointments, roster, minutes, organization chart, and regulatory forms to one controlled list.', correct: true },
      { id: 'submit', text: 'Complete the applicable CDPH board-change package and retain submission evidence.', correct: true },
      { id: 'retro', text: 'Backdate the nominee’s term to match the first meeting attended.', correct: false, critical: true },
      { id: 'bio-clause', text: 'Attach executive biographies as substitute evidence of appointment and orientation.', correct: false },
    ],
    defense: [
      { id: 'd1', prompt: 'What establishes that a person could vote?', answers: ['A current roster and approved minutes showing the individual participated without objection', 'The required appointment action reconciled to the governing instrument', 'A completed orientation record plus evidence that the individual met the Board’s competency criteria'], correct: 1 },
      { id: 'd2', prompt: 'What is the best CDPH package control?', answers: ['A signed resolution, current roster, and cover letter that describe the intended change consistently', 'Reconcile every person and entity across forms, chart, governing documents, and internal records', 'Submit the available forms promptly, then correct internal and external inconsistencies during the next annual review'], correct: 1 },
      { id: 'd3', prompt: 'Does orientation replace appointment?', answers: ['It can when the governing instrument permits participation pending formal ratification and the minutes disclose that status', 'It can for experienced executives when orientation verifies governance competency before the first vote', 'No; they prove different requirements'], correct: 2 },
    ],
    remediation: { duty: 'Prove the chain from legal instrument to person to action.', trap: 'The roster and polished biographies made an unappointed nominee look fully seated.', repair: 'Reconcile seat authority, appointment, term, orientation, participation, and external reporting as separate proofs.', transferRule: 'Do not allow one valid document to cure a different missing element.' },
    transfer: { prompt: 'Green is later validly appointed and completes orientation. The earlier budget vote would have passed by the same margin without Green. What should the Board do?', answers: ['Approve an addendum that records Green as a nonvoting observer at the earlier meeting because the outcome did not depend on Green’s vote', 'Evaluate and accurately document the earlier action using the valid participants and applicable decision rules; do not rewrite history', 'Ratify Green’s earlier participation prospectively because valid later appointment and an unchanged vote margin eliminate practical prejudice'], correct: 1, rationale: 'Later compliance does not rewrite earlier facts. The Board must assess the earlier action under the rules and valid participants that existed then.' },
  },
  {
    id: 'GB-004', sequence: 4, title: 'Appoint, Oversee, Replace', shortTitle: 'Leadership',
    domain: 'Executive continuity', duration: '40–55 min', difficulty: 'Expert', posture: 'provisional',
    postureLabel: 'Policy validation', available: true,
    lede: 'Protect continuous qualified leadership when the ordinary succession plan fails at the worst possible moment.',
    sources: ['42 CFR 484.105(b)–(c)', 'CMS Appendix B', 'GV-OG-002', 'GV-GB-004 · canonical identity reconciliation required'],
    achc: ['HH1-5A', 'HH1-5A.01', 'HH1-6B'],
    caseTitle: 'The empty chair', caseDate: 'October 6, 2026 · Survey entry conference',
    caseContext: 'The Administrator is unexpectedly hospitalized as surveyors arrive. The named alternate has an expired professional license and the Clinical Manager is covering a patient escalation.',
    decisiveDuty: 'Continuity requires a qualified, authorized person—not a familiar name on an obsolete plan.',
    doctrine: [
      { number: '01', title: 'Appoint deliberately', body: 'Appointment, authority, qualifications, and reporting must be independently evidenced.' },
      { number: '02', title: 'Keep the alternate current', body: 'A succession plan that is not monitored becomes a false control.' },
      { number: '03', title: 'Separate roles', body: 'Operational continuity must preserve Administrator and Clinical Manager functions.' },
      { number: '04', title: 'Correct in real time', body: 'During survey, state the facts, activate a lawful plan, and produce the evidence trail.' },
    ],
    evidence: [
      { id: 'appointment', code: 'C-01', title: 'Administrator appointment resolution', kind: 'Governance', status: 'clean', essential: true, relevant: true, summary: 'The current Administrator was properly appointed.', details: ['Appointment is current.', 'The resolution requires Board-approved alternate coverage.', 'Unexpected absence must be reported promptly to the Chair.'], source: 'Synthetic Board resolution' },
      { id: 'succession', code: 'C-02', title: 'Succession plan', kind: 'Continuity', status: 'attention', essential: true, relevant: true, summary: 'The designated alternate was last verified fourteen months ago.', details: ['R. Kim is named as first alternate.', 'Qualification check date is August 2025.', 'The plan lists no second qualified alternate.'], source: 'Synthetic controlled plan' },
      { id: 'license', code: 'C-03', title: 'License verification', kind: 'Credential', status: 'restricted', essential: true, relevant: true, summary: 'Kim’s required professional license expired six weeks earlier.', details: ['No renewal is shown.', 'HR flagged the expiration but the succession owner was not notified.', 'The personnel system still shows “eligible.”'], source: 'Synthetic credential evidence' },
      { id: 'cm-log', code: 'C-04', title: 'Clinical Manager escalation log', kind: 'Clinical', status: 'attention', essential: true, relevant: true, summary: 'The Clinical Manager is managing two urgent care issues and cannot absorb every executive function.', details: ['One medication discrepancy needs prescriber contact.', 'One missed-visit escalation is open.', 'No qualified clinical designee is activated.'], source: 'Synthetic operational record' },
      { id: 'candidate', code: 'C-05', title: 'Qualified interim candidate file', kind: 'Credential', status: 'clean', essential: true, relevant: true, summary: 'A regional leader meets the supplied qualification criteria and is immediately available.', details: ['Current credentials verified the same morning.', 'Experience and availability documented.', 'No appointment or delegated authority exists yet.'], source: 'Synthetic candidate record' },
      { id: 'email', code: 'C-06', title: 'Chair’s informal email', kind: 'Communication', status: 'attention', relevant: true, summary: 'The Chair tells Kim to “handle everything until further notice.”', details: ['No time limit or scope.', 'No qualification check.', 'No Board action or emergency authority citation.'], source: 'Synthetic email' },
      { id: 'survey', code: 'C-07', title: 'Surveyor request list', kind: 'Survey', status: 'clean', relevant: true, summary: 'Surveyors request leadership authority and continuity evidence.', details: ['Current Administrator appointment.', 'Alternate/designee qualifications.', 'Organization chart and availability evidence.'], source: 'Synthetic survey request modeled on CMS guidance' },
    ],
    findings: [
      { id: 'unqualified', type: 'authority', statement: 'The named alternate cannot be relied upon without current required qualifications.', correct: true, critical: true },
      { id: 'email-power', type: 'authority', statement: 'The Chair’s email may temporarily activate Kim under the controlled succession plan without a current qualification check.', correct: false },
      { id: 'candidate-gap', type: 'authority', statement: 'The qualified candidate still needs valid authorization before functioning as interim Administrator.', correct: true },
      { id: 'clinical-overload', type: 'risk', statement: 'Assigning all functions to the Clinical Manager would jeopardize separate clinical oversight and current escalations.', correct: true, critical: true },
      { id: 'plan-failure', type: 'risk', statement: 'The stale succession verification is a failed governance control.', correct: true },
      { id: 'survey-delay', type: 'risk', statement: 'Maintaining the named alternate through survey and documenting the credential correction afterward is the least disruptive continuity response.', correct: false },
    ],
    decisions: [
      { id: 'kim', label: 'Critical', title: 'Activate the documented alternate conditionally', body: 'Place Kim in the role under the existing succession plan while HR seeks same-day confirmation that the expired license is being renewed.', critical: true },
      { id: 'cm', label: 'Critical', title: 'Use temporary dual-role coverage', body: 'Authorize the Clinical Manager to hold both roles through survey exit while delegating the two open clinical escalations to available field supervisors.', critical: true },
      { id: 'appoint', label: 'Defensible', title: 'Authorize a qualified interim leader', body: 'Verify qualifications, take the required governance action, define scope and reporting, preserve clinical coverage, and disclose accurately to surveyors.', correct: true },
      { id: 'pause', label: 'Incomplete', title: 'Restrict operations pending appointment', body: 'Freeze new admissions and nonurgent visits until the next scheduled Board meeting can approve an interim leader, without testing emergency action options.' },
    ],
    recordPrompt: 'Select the five elements of a defensible emergency leadership action.',
    clauses: [
      { id: 'facts', text: 'Record the Administrator’s unplanned unavailability and the time the Governing Body was notified.', correct: true },
      { id: 'reject', text: 'Document why the stale named alternate was not activated.', correct: true },
      { id: 'verify', text: 'Identify the verified qualifications and availability of the interim appointee.', correct: true },
      { id: 'scope', text: 'Define interim authority, effective period, reporting, and reassessment cadence.', correct: true },
      { id: 'clinical', text: 'Preserve qualified Clinical Manager coverage and active patient escalation handling.', correct: true },
      { id: 'backdate', text: 'Backdate the interim appointment to the start of the Administrator’s hospitalization.', correct: false, critical: true },
      { id: 'omit', text: 'Omit the failed succession-plan verification to simplify the survey response.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why was the listed alternate not used?', answers: ['The Board selected a more experienced candidate after comparing leadership histories and survey-readiness records', 'Required current qualifications could not be verified', 'Survey staff requested a different contact before reviewing the succession plan and credential file'], correct: 1 },
      { id: 'd2', prompt: 'What makes the interim candidate operationally lawful?', answers: ['Relevant experience, immediate availability, and written acceptance of the succession plan’s assigned responsibilities', 'Verified qualifications plus valid appointment/authorization and defined accountability', 'A current HR eligibility status, favorable credentialing screen, and notice to department leaders'], correct: 1 },
      { id: 'd3', prompt: 'What should surveyors hear?', answers: ['That the Administrator remains operationally responsible during the absence because the appointment resolution has not been rescinded', 'Accurate facts, immediate protective action, and the evidence trail', 'That the succession plan was followed in substance because a qualified executive assumed the essential functions promptly'], correct: 1 },
    ],
    remediation: { duty: 'Continuity is a live governance control.', trap: 'A controlled document looked authoritative even though its qualification evidence had expired.', repair: 'Verify the person, authority, scope, duration, role separation, and patient-risk coverage at activation time.', transferRule: 'A current name, credential, or email alone is never the whole authority chain.' },
    transfer: { prompt: 'Kim renews the license the next day. May the agency alter the prior-day record to show Kim was qualified when the absence began?', answers: ['Yes, if the renewal is effective within the same reporting period and the record notes that verification was completed the following day', 'No; preserve the original facts and document only the later change prospectively', 'Yes, through a Chair-approved corrective addendum that treats the lapse as an administrative credentialing delay'], correct: 1, rationale: 'Later qualification does not change the historical facts. Governance records must remain accurate and prospective.' },
  },
  {
    id: 'GB-005', sequence: 5, title: 'QAPI as an Executive Duty', shortTitle: 'QAPI',
    domain: 'Quality governance', duration: '55–75 min', difficulty: 'Expert', posture: 'provisional',
    postureLabel: 'Crosswalk validation', available: true,
    lede: 'Interrogate apparently favorable data, protect high-risk subgroups, and demand proof before closing improvement work.',
    sources: ['42 CFR 484.65', 'CMS Appendix B', '22 CCR 74742 · validation required', 'QA-PG-001', 'QA-PG-002', 'QA-PI-001', 'QA-AE-001', 'QA-AE-002', 'QA-AE-003', 'QA-AE-004'],
    achc: ['HH6-1A', 'HH6-1C', 'HH6-1D.01', 'HH6-3A.01', 'HH6-4A.02', 'HH6-4A.04', 'HH6-4A.05', 'HH6-4A.06', 'HH6-4A.07', 'HH6-5A', 'HH6-7A.01'],
    caseTitle: 'The green dashboard', caseDate: 'Q2 2026 · Quarterly QAPI review',
    caseContext: 'The executive dashboard is green, leadership recommends closing a hospitalization PIP, and a stratified appendix shows that one fragile subgroup deteriorated.',
    decisiveDuty: 'Aggregate improvement cannot erase a known high-risk subgroup or replace the PIP’s approved effectiveness criteria.',
    doctrine: [
      { number: '01', title: 'Interrogate the denominator', body: 'Trend, sample, exclusions, risk adjustment, and subgroup behavior determine whether the headline is trustworthy.' },
      { number: '02', title: 'Use approved criteria', body: 'Closure follows the charter’s effectiveness and sustainability rules—not optimism or elapsed time.' },
      { number: '03', title: 'Resource the program', body: 'The Governing Body ensures QAPI has authority, information, participation, and resources.' },
      { number: '04', title: 'Keep federal and agency rules distinct', body: 'Two active PIPs may be an agency control; it is not the federal minimum stated in 42 CFR 484.65(d).' },
    ],
    evidence: [
      { id: 'dashboard', code: 'Q-01', title: 'Executive KPI dashboard', kind: 'Dashboard', status: 'clean', essential: true, relevant: true, summary: 'All-agency hospitalization improved from 18.4% to 15.1%.', details: ['Dashboard status is green.', 'No confidence interval or subgroup alert appears.', 'Narrative recommends PIP closure.'], source: 'Synthetic QAPI packet' },
      { id: 'stratified', code: 'Q-02', title: 'Stratified outcome table', kind: 'Analysis', status: 'restricted', essential: true, relevant: true, summary: 'The high-risk heart-failure subgroup worsened despite aggregate improvement.', details: ['Heart-failure subgroup: 22.0% to 27.8%.', 'Other diagnoses improved materially.', 'The subgroup represents 18% of the eligible population.'], source: 'Synthetic analysis · 42 CFR 484.65(c)' },
      { id: 'charter', code: 'Q-03', title: 'Approved PIP charter', kind: 'Charter', status: 'restricted', essential: true, relevant: true, summary: 'Closure requires two consecutive quarters below threshold in every monitored high-risk stratum.', details: ['Target: below 20% in each named stratum.', 'Sustainability: two consecutive quarters.', 'Escalation: any stratum above 25% triggers root-cause review.'], source: 'Synthetic PIP charter' },
      { id: 'complaints', code: 'Q-04', title: 'Complaint linkage extract', kind: 'Quality', status: 'attention', essential: true, relevant: true, summary: 'Three heart-failure complaints reference delayed symptom escalation.', details: ['Two complaints were substantiated.', 'One involves an after-hours handoff.', 'Complaint trend was excluded from the dashboard narrative.'], source: 'Synthetic complaint extract · ACHC HH2-4A / HH6-4A.05' },
      { id: 'minutes', code: 'Q-05', title: 'QAPI committee minutes', kind: 'Minutes', status: 'attention', essential: true, relevant: true, summary: 'The committee questioned closure but the draft recommendation says “consensus achieved.”', details: ['Two members requested subgroup analysis.', 'No vote is recorded.', 'The analyst’s caution is absent from the executive summary.'], source: 'Synthetic committee record' },
      { id: 'resources', code: 'Q-06', title: 'Resource decision memo', kind: 'Budget', status: 'attention', essential: true, relevant: true, summary: 'The proposed budget removes weekend analyst coverage and nurse coaching hours.', details: ['Savings begin immediately after closure.', 'No risk assessment accompanies the reduction.', 'The subgroup problem depends partly on weekend escalation.'], source: 'Synthetic resource memo' },
      { id: 'pips', code: 'Q-07', title: 'Active PIP register', kind: 'Registry', status: 'clean', relevant: true, summary: 'Two active PIPs are listed under the agency’s stricter internal control.', details: ['Hospitalization PIP is one of two.', 'The policy text labels two PIPs as a federal minimum.', 'CMS guidance instead describes at least one project annually in development, ongoing, or completed.'], source: 'Synthetic registry · policy attribution requires correction' },
      { id: 'celebration', code: 'Q-08', title: 'Leadership celebration email', kind: 'Communication', status: 'attention', relevant: false, summary: 'The email praises the green dashboard and announces closure before Board review.', details: ['Sent to branch leaders two days before the Board packet was finalized.', 'The message quotes the 15.1% aggregate rate.', 'No subgroup table, charter criterion, or approval reference is attached.'], source: 'Synthetic leadership communication' },
    ],
    findings: [
      { id: 'aggregate', type: 'risk', statement: 'Aggregate improvement masks deterioration in a defined high-risk subgroup.', correct: true, critical: true },
      { id: 'criteria', type: 'authority', statement: 'The proposed closure does not meet the approved PIP effectiveness and sustainability criteria.', correct: true, critical: true },
      { id: 'consensus', type: 'authority', statement: 'The draft committee minutes support closure because they record no formal dissenting vote and the aggregate target was met.', correct: false },
      { id: 'complaint-link', type: 'risk', statement: 'Complaint evidence materially reinforces the subgroup signal and requires analysis.', correct: true },
      { id: 'resource-risk', type: 'risk', statement: 'Removing relevant resources before demonstrating effectiveness creates additional risk.', correct: true },
      { id: 'two-federal', type: 'authority', statement: 'The agency may defend its two-active-PIP control as the federal minimum because it is more stringent than the annual-project language.', correct: false },
    ],
    decisions: [
      { id: 'close', label: 'Critical', title: 'Close with enhanced surveillance', body: 'Accept the aggregate improvement, release the temporary resources, and monitor the heart-failure subgroup through the routine dashboard.', critical: true },
      { id: 'restart', label: 'Overbroad', title: 'Revalidate the full QAPI portfolio', body: 'Suspend closure decisions across every project and rebuild all measures, baselines, interventions, and committee recommendations from source data.' },
      { id: 'continue', label: 'Defensible', title: 'Continue with targeted executive direction', body: 'Reject closure, require subgroup root-cause work, preserve resources, reconcile complaints, and return against the approved criteria.', correct: true },
      { id: 'delay', label: 'Incomplete', title: 'Defer closure for another quarter', body: 'Keep the project administratively open but approve no subgroup analysis, corrective owner, protected resources, or return threshold until the next routine report.' },
    ],
    recordPrompt: 'Select the five directions that create effective Governing Body oversight.',
    clauses: [
      { id: 'reject-close', text: 'The Governing Body does not authorize closure because approved stratum and sustainability criteria are unmet.', correct: true },
      { id: 'rca', text: 'QAPI leadership must complete a heart-failure subgroup root-cause analysis linked to complaints and after-hours processes.', correct: true },
      { id: 'resources-clause', text: 'Relevant analyst and coaching resources remain in place pending demonstrated effectiveness.', correct: true },
      { id: 'return', text: 'Management must return with stratified measures, exclusions, denominator, interventions, owner, and threshold results.', correct: true },
      { id: 'policy-fix', text: 'Compliance must correct the policy statement that attributes the two-active-PIP agency control to federal law.', correct: true },
      { id: 'green', text: 'The green aggregate dashboard is conclusive evidence that every patient group improved.', correct: false, critical: true },
      { id: 'minutes-fix', text: 'Revise committee minutes to state that unanimous closure consensus occurred.', correct: false, critical: true },
    ],
    defense: [
      { id: 'd1', prompt: 'Why did the Board reject closure?', answers: ['The internal policy required two active projects, so closing either project would necessarily violate the federal annual-project requirement', 'A high-risk stratum worsened and the approved effectiveness criteria were unmet', 'The aggregate result improved for only two months, so subgroup performance and complaint linkage were not material to the closure decision'], correct: 1 },
      { id: 'd2', prompt: 'What makes the next report decision-grade?', answers: ['A fuller narrative explaining why aggregate performance should remain the primary closure measure despite subgroup volatility', 'Stratified data, definitions, exclusions, linked complaints, interventions, owners, and thresholds', 'A reconciled executive summary with committee approval, a refreshed dashboard, and a recommendation from the QAPI Coordinator'], correct: 1 },
      { id: 'd3', prompt: 'What is the federal PIP principle reflected in CMS guidance?', answers: ['Maintain two active projects throughout each calendar year, adjusting their scope to the agency’s size and performance', 'Annual projects proportionate to scope, complexity, and past performance, with at least one in development, ongoing, or completed each calendar year', 'Open a project only after a measure exceeds its target for two consecutive reporting periods and the Board authorizes formal intervention'], correct: 1 },
    ],
    remediation: { duty: 'Govern the signal, not the color.', trap: 'The aggregate headline, premature celebration, and policy misstatement each offered a shortcut around the underlying evidence.', repair: 'Rebuild the chain from population and subgroup to intervention, threshold, sustainability, resources, and Board direction.', transferRule: 'A favorable aggregate never answers whether every monitored high-risk stratum met its approved criterion.' },
    transfer: { prompt: 'Next quarter the heart-failure subgroup improves to 19.2%, but the charter requires two consecutive quarters below 20%. What may the Board conclude?', answers: ['Approve conditional closure because the point threshold is met, while retaining one quarter of post-closure surveillance before releasing resources', 'Continue monitoring until the approved sustainability condition is met, unless the charter is prospectively and defensibly amended', 'Count the current quarter together with the agency-wide prior-quarter improvement because both measures address the same hospitalization outcome'], correct: 1, rationale: 'One favorable quarter meets the point threshold but not the approved sustainability rule.' },
  },
];

export const GB003_SUMMARY: AcademyModuleSummary = {
  id: 'GB-003', sequence: 3, title: 'Meetings That Prove Governance', shortTitle: 'Meetings',
  domain: 'Decision evidence', duration: '48–65 min', difficulty: 'Expert', posture: 'provisional',
  postureLabel: 'Policy validation', available: true,
  lede: 'Convene valid meetings, repair defective actions, and produce minutes that withstand evidence-level scrutiny.',
  sources: ['42 CFR 484.105', 'CMS Appendix B', 'GV-GB-002', 'GV-GB-003'],
  achc: ['HH1-2A', 'HH1-2A.03', 'HH1-4A.01'],
};

export const CASE_MODULES: Record<string, ExecutiveCaseModule> = Object.fromEntries(
  [...cases, ...additionalCases].map((module) => [module.id, module]),
);

export const MODULES: AcademyModuleSummary[] = [
  ...cases,
  GB003_SUMMARY,
  ...additionalCases,
].map(({ id, sequence, title, shortTitle, domain, duration, difficulty, posture, postureLabel, available, lede, sources, achc }) => ({
  id, sequence, title, shortTitle, domain, duration, difficulty, posture, postureLabel, available, lede, sources, achc,
})).sort((a, b) => a.sequence - b.sequence);

export { cases };
