/* ═══════════════════════════════════════════════════════════════
   AUTO-GENERATED — DO NOT EDIT
   File: policyQuizMap.generated.ts
   Generator: apps/employee-journey/scripts/generateJourneyMappings.ts
   Source branch: feature/governing-body-portal
   Schema version: 1.0.0
   Regenerate with: npm run journey:map:generate (from apps/employee-journey)
   68 course quiz bundles from Course_Catalog.aoa.json, cross-joined to Policy_Assignments.aoa.json by Course ID.
   passScore taken directly from Course_Catalog "Pass score" column (already 85 for the 5 OASIS-titled courses, 80 otherwise).
   bankStatus counts: {"DRAFT_REVIEW_REQUIRED":1,"MISSING":67}
   ═══════════════════════════════════════════════════════════════ */

export interface GeneratedQuizBundle {
  bundleId: string;
  courseId: string;
  pathway: string;
  title: string;
  policyIds: string[];
  passScore: number;
  maxAttempts: number;
  questionCount: number;
  bankStatus: 'APPROVED' | 'DRAFT_REVIEW_REQUIRED' | 'MISSING';
  draftQuestions?: { id: string; stem: string; options: string[]; correctIndex: number; policyId: string }[];
  note: string;
}

export const POLICY_QUIZ_MAP: GeneratedQuizBundle[] = [
  {
    "bundleId": "G-01",
    "courseId": "G-01",
    "pathway": "General",
    "title": "Agency Orientation, Scope & Policy Responsibilities",
    "policyIds": [
      "HR-TA-005",
      "HR-TR-101",
      "GV-OG-001",
      "GV-OG-003",
      "GV-PM-003",
      "GV-PM-004"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "DRAFT_REVIEW_REQUIRED",
    "draftQuestions": [
      {
        "id": "G-01-DRAFT-Q1",
        "stem": "DRAFT SAMPLE — Who is responsible for verifying an employee has read and attested to every policy assigned under General Orientation?",
        "options": [
          "The employee only",
          "The employee and their supervisor/HR per HR-TA-005",
          "No one — attestation is optional",
          "The Governing Body only"
        ],
        "correctIndex": 1,
        "policyId": "HR-TA-005"
      },
      {
        "id": "G-01-DRAFT-Q2",
        "stem": "DRAFT SAMPLE — General Orientation acknowledgments are due by:",
        "options": [
          "Day 90",
          "Day 5 for orientation / Day 14 for all acknowledgments",
          "End of first year",
          "There is no deadline"
        ],
        "correctIndex": 1,
        "policyId": "HR-TA-005"
      },
      {
        "id": "G-01-DRAFT-Q3",
        "stem": "DRAFT SAMPLE — What passing score is required for the General Orientation quiz?",
        "options": [
          "60%",
          "70%",
          "80%",
          "100%"
        ],
        "correctIndex": 2,
        "policyId": "HR-TA-005"
      }
    ],
    "note": "DRAFT sample bank only (3 of 10 required items) — pilot alignment with GAO-001. NOT an approved bank; quiz UI must still block completion until an approved 10-item bank ships."
  },
  {
    "bundleId": "G-02",
    "courseId": "G-02",
    "pathway": "General",
    "title": "Compliance, Ethics, FWA & Speaking Up",
    "policyIds": [
      "CO-CP-001",
      "CO-CP-004",
      "CO-CP-005",
      "CO-CP-006",
      "CO-CP-008",
      "CO-FW-101",
      "CO-FA-001",
      "CO-FA-002"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "G-03",
    "courseId": "G-03",
    "pathway": "General",
    "title": "Privacy, Confidentiality & Information Security",
    "policyIds": [
      "CO-HP-101",
      "CO-IR-101",
      "CO-DG-101",
      "IT-SC-001",
      "IT-SC-002",
      "IT-UP-002",
      "IT-UP-003",
      "IT-UP-004",
      "CO-AI-101",
      "IT-UP-001",
      "IT-SA-001"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "G-04",
    "courseId": "G-04",
    "pathway": "General",
    "title": "Patient Rights, Abuse Reporting & Grievances",
    "policyIds": [
      "CL-PR-001",
      "CL-PR-006",
      "HR-ER-009",
      "OP-PA-001",
      "GV-PM-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "G-05",
    "courseId": "G-05",
    "pathway": "General",
    "title": "IIPP, Workplace Violence, Safety & Incident Reporting",
    "policyIds": [
      "RM-OS-001",
      "HR-WM-004",
      "RM-SS-002",
      "RM-ER-002",
      "QA-AE-001"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "G-06",
    "courseId": "G-06",
    "pathway": "General",
    "title": "Emergency Preparedness & Service Continuity",
    "policyIds": [
      "OP-FM-005",
      "RM-EP-001",
      "RM-EP-002",
      "OP-SL-006"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "G-07",
    "courseId": "G-07",
    "pathway": "General",
    "title": "Respectful Workplace & Employment Conduct",
    "policyIds": [
      "HR-ER-002",
      "HR-ER-003",
      "HR-ER-004",
      "HR-ER-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "G-08",
    "courseId": "G-08",
    "pathway": "General",
    "title": "QAPI & Patient Safety Awareness",
    "policyIds": [
      "QA-PG-001",
      "QA-AE-004",
      "QA-PI-004",
      "QA-SM-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "LVN-01",
    "courseId": "LVN-01",
    "pathway": "LVN",
    "title": "LVN Role, Scope, Competency & Supervision",
    "policyIds": [
      "HR-JD-006",
      "HR-JD-000",
      "CL-SD-001",
      "CL-SD-008",
      "HR-TA-006",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "LVN-02",
    "courseId": "LVN-02",
    "pathway": "LVN",
    "title": "Clinical Documentation, Plans & Orders",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-004",
      "CL-CP-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "LVN-03",
    "courseId": "LVN-03",
    "pathway": "LVN",
    "title": "Patient-Facing Care, Coordination & Field Practice",
    "policyIds": [
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "CL-CC-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "LVN-04",
    "courseId": "LVN-04",
    "pathway": "LVN",
    "title": "Medication, Infection & High-Risk Clinical Care",
    "policyIds": [
      "CL-SD-012",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "RM-PS-005",
      "RM-OS-002",
      "RM-OS-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "LVN-05",
    "courseId": "LVN-05",
    "pathway": "LVN",
    "title": "Transitions, Specialty Services & Field Safety",
    "policyIds": [
      "CL-CP-006",
      "CL-CP-007",
      "CL-SD-009",
      "CL-SD-010",
      "CL-SD-011",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-002",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-01",
    "courseId": "RN-01",
    "pathway": "RN",
    "title": "RN Role, Scope, HHA Supervision & Competency",
    "policyIds": [
      "HR-JD-005",
      "HR-JD-000",
      "CL-SD-001",
      "CL-SD-006",
      "CL-SD-007",
      "CL-SD-008",
      "HR-TA-006",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-02",
    "courseId": "RN-02",
    "pathway": "RN",
    "title": "Documentation, Plan of Care & Order Lifecycle",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-001",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-004",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CP-008",
      "CL-CP-009",
      "CL-CC-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-03",
    "courseId": "RN-03",
    "pathway": "RN",
    "title": "Comprehensive Assessment & Medicare Eligibility",
    "policyIds": [
      "CL-CA-001",
      "CL-CA-004",
      "CL-CA-005",
      "CL-CA-006",
      "CL-CA-007"
    ],
    "passScore": 85,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-04",
    "courseId": "RN-04",
    "pathway": "RN",
    "title": "OASIS Authorization, Accuracy & Submission Integrity",
    "policyIds": [
      "CL-CA-002",
      "CL-CA-003",
      "CL-OA-001",
      "CL-OA-002",
      "CL-OA-003",
      "CL-OA-004",
      "CL-OA-005",
      "CL-OA-006",
      "CL-OA-007",
      "CL-OA-008",
      "CL-OA-009",
      "CL-OA-010",
      "CL-OA-011",
      "CL-OA-012",
      "CL-OA-013",
      "CL-OA-014",
      "CL-OA-015",
      "CL-OA-016",
      "CL-OA-017",
      "CL-OA-018",
      "CL-OA-019",
      "CL-OA-101"
    ],
    "passScore": 85,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-05",
    "courseId": "RN-05",
    "pathway": "RN",
    "title": "Medication, Infection & High-Risk Clinical Care",
    "policyIds": [
      "CL-SD-012",
      "CL-SD-013",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "RM-PS-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-06",
    "courseId": "RN-06",
    "pathway": "RN",
    "title": "Specialty Procedures, Telehealth, IV & Wound Care",
    "policyIds": [
      "CL-SD-009",
      "CL-SD-010",
      "CL-SD-011",
      "RM-PS-002",
      "RM-PS-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-07",
    "courseId": "RN-07",
    "pathway": "RN",
    "title": "Transitions, Special Populations & Patient Safeguards",
    "policyIds": [
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "RN-08",
    "courseId": "RN-08",
    "pathway": "RN",
    "title": "Clinical Quality, Documentation Audit & Field Safety",
    "policyIds": [
      "QA-PI-005",
      "QA-PI-006",
      "QA-PI-007",
      "QA-SM-002",
      "QA-SM-003",
      "CO-DC-002",
      "CO-DC-004",
      "FN-CM-003",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003",
      "OP-SL-007"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "HHA-01",
    "courseId": "HHA-01",
    "pathway": "HHA",
    "title": "HHA Job Duties, Scope & Care-Plan Compliance",
    "policyIds": [
      "HR-JD-007",
      "HR-JD-000",
      "CL-SD-006",
      "CL-CP-001",
      "HR-TA-006"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "HHA-02",
    "courseId": "HHA-02",
    "pathway": "HHA",
    "title": "HHA Competency Evaluation & Supervision",
    "policyIds": [
      "CL-SD-007",
      "CL-SD-008",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "HHA-03",
    "courseId": "HHA-03",
    "pathway": "HHA",
    "title": "Aide Documentation, Communication & Missed Visits",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CL-CP-005",
      "CL-SD-024",
      "CL-SD-025",
      "OP-SL-001",
      "CL-CC-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "HHA-04",
    "courseId": "HHA-04",
    "pathway": "HHA",
    "title": "Personal Care Safety, Med Reporting, IPC, Falls & Pain",
    "policyIds": [
      "CL-SD-012",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "HHA-05",
    "courseId": "HHA-05",
    "pathway": "HHA",
    "title": "Annual 12-Hour In-Service & Field Safety",
    "policyIds": [
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-002",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003",
      "OP-SL-004",
      "OP-SL-007"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "PT-01",
    "courseId": "PT-01",
    "pathway": "PT",
    "title": "PT Job Duties, Scope, Supervision & Competency",
    "policyIds": [
      "HR-JD-008",
      "HR-JD-000",
      "CL-SD-002",
      "CL-SD-008",
      "HR-TA-006",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "PT-02",
    "courseId": "PT-02",
    "pathway": "PT",
    "title": "Therapy Documentation, Coordination & Field Safety",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CC-101",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "PT-03",
    "courseId": "PT-03",
    "pathway": "PT",
    "title": "Therapy-Only OASIS & Specialty PT Services",
    "policyIds": [
      "CL-CA-001",
      "CL-CA-002",
      "CL-CA-004",
      "CL-CA-005",
      "CL-OA-001",
      "CL-OA-002",
      "CL-OA-003",
      "CL-OA-004",
      "CL-OA-005",
      "CL-OA-006",
      "CL-OA-007",
      "CL-OA-008",
      "CL-OA-009",
      "CL-OA-010",
      "CL-OA-011",
      "CL-OA-012",
      "CL-OA-013",
      "CL-OA-014",
      "CL-OA-015",
      "CL-OA-016",
      "CL-OA-017",
      "CL-OA-018",
      "CL-OA-019",
      "CL-OA-101",
      "CL-SD-009",
      "CL-SD-011",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-PS-005"
    ],
    "passScore": 85,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "PTA-01",
    "courseId": "PTA-01",
    "pathway": "PTA",
    "title": "PTA Scope Under PT Supervision & Competency",
    "policyIds": [
      "MISSING-PTA-JD",
      "HR-JD-000",
      "CL-SD-002",
      "CL-SD-008",
      "HR-TA-006",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "PTA-02",
    "courseId": "PTA-02",
    "pathway": "PTA",
    "title": "PTA Documentation, Care-Plan Compliance & Field Safety",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CC-101",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "PTA-03",
    "courseId": "PTA-03",
    "pathway": "PTA",
    "title": "PTA Specialty Safety & Transitions",
    "policyIds": [
      "CL-SD-009",
      "CL-SD-011",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-PS-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "OT-01",
    "courseId": "OT-01",
    "pathway": "OT",
    "title": "OT Job Duties, Scope, Supervision & Competency",
    "policyIds": [
      "HR-JD-009",
      "HR-JD-000",
      "CL-SD-003",
      "CL-SD-008",
      "HR-TA-006",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "OT-02",
    "courseId": "OT-02",
    "pathway": "OT",
    "title": "Therapy Documentation, Coordination & Field Safety",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CC-101",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "OT-03",
    "courseId": "OT-03",
    "pathway": "OT",
    "title": "Therapy-Only OASIS & Specialty OT Services",
    "policyIds": [
      "CL-CA-001",
      "CL-CA-002",
      "CL-CA-004",
      "CL-CA-005",
      "CL-OA-001",
      "CL-OA-002",
      "CL-OA-003",
      "CL-OA-004",
      "CL-OA-005",
      "CL-OA-006",
      "CL-OA-007",
      "CL-OA-008",
      "CL-OA-009",
      "CL-OA-010",
      "CL-OA-011",
      "CL-OA-012",
      "CL-OA-013",
      "CL-OA-014",
      "CL-OA-015",
      "CL-OA-016",
      "CL-OA-017",
      "CL-OA-018",
      "CL-OA-019",
      "CL-OA-101",
      "CL-SD-009",
      "CL-SD-011",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-PS-005"
    ],
    "passScore": 85,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "COTA-01",
    "courseId": "COTA-01",
    "pathway": "COTA",
    "title": "COTA Scope Under OT Supervision & Competency",
    "policyIds": [
      "MISSING-COTA-JD",
      "HR-JD-000",
      "CL-SD-003",
      "CL-SD-008",
      "HR-TA-006",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "COTA-02",
    "courseId": "COTA-02",
    "pathway": "COTA",
    "title": "COTA Documentation, Care-Plan Compliance & Field Safety",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CC-101",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "COTA-03",
    "courseId": "COTA-03",
    "pathway": "COTA",
    "title": "COTA Specialty Safety & Transitions",
    "policyIds": [
      "CL-SD-009",
      "CL-SD-011",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-PS-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "SLP-01",
    "courseId": "SLP-01",
    "pathway": "SLP",
    "title": "SLP Practice, Documentation, Field Safety & Conditional OASIS",
    "policyIds": [
      "HR-JD-010",
      "HR-JD-000",
      "CL-SD-004",
      "HR-TA-006",
      "HR-TD-003",
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CC-101",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003",
      "CL-CA-001",
      "CL-CA-002",
      "CL-CA-004",
      "CL-CA-005",
      "CL-OA-001",
      "CL-OA-002",
      "CL-OA-003",
      "CL-OA-004",
      "CL-OA-005",
      "CL-OA-006",
      "CL-OA-007",
      "CL-OA-008",
      "CL-OA-009",
      "CL-OA-010",
      "CL-OA-011",
      "CL-OA-012",
      "CL-OA-013",
      "CL-OA-014",
      "CL-OA-015",
      "CL-OA-016",
      "CL-OA-017",
      "CL-OA-018",
      "CL-OA-019",
      "CL-OA-101",
      "CL-SD-009",
      "CL-SD-011",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-PS-005"
    ],
    "passScore": 85,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "MSW-01",
    "courseId": "MSW-01",
    "pathway": "MSW",
    "title": "MSW Practice, Documentation, Coordination & Field Safety",
    "policyIds": [
      "HR-JD-011",
      "HR-JD-000",
      "CL-SD-005",
      "HR-TA-006",
      "HR-TD-003",
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-003",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CC-101",
      "CL-PR-002",
      "CL-PR-003",
      "CL-PR-004",
      "CL-PR-005",
      "OP-PA-002",
      "OP-PA-003",
      "OP-PA-004",
      "OP-PA-005",
      "OP-SL-001",
      "OP-SL-004",
      "OP-SL-007",
      "RM-OS-002",
      "RM-OS-003",
      "RM-OS-004",
      "RM-PS-001",
      "RM-PS-003",
      "RM-SS-001",
      "RM-SS-003",
      "OP-SL-003",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-01",
    "courseId": "ADM-01",
    "pathway": "ADM",
    "title": "Administrator Authority, Accountability & Delegation",
    "policyIds": [
      "HR-JD-001",
      "HR-JD-000",
      "GV-GB-001",
      "GV-OG-001",
      "GV-OG-002",
      "GV-OG-003",
      "GV-OG-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-02",
    "courseId": "ADM-02",
    "pathway": "ADM",
    "title": "Governance, Board Operations & Policy Lifecycle",
    "policyIds": [
      "GV-GB-002",
      "GV-GB-003",
      "GV-GB-004",
      "GV-GB-005",
      "GV-PM-001",
      "GV-PM-002",
      "GV-PM-003",
      "GV-PM-004",
      "GV-PM-005",
      "EN-LC-001",
      "EN-LC-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-03",
    "courseId": "ADM-03",
    "pathway": "ADM",
    "title": "Compliance Leadership & Survey Readiness",
    "policyIds": [
      "CO-CP-002",
      "CO-CP-003",
      "CO-CP-007",
      "CO-RA-001",
      "CO-RA-002",
      "CO-RA-003",
      "CO-RA-004",
      "CO-RA-005",
      "CO-RA-006",
      "CO-RA-007",
      "EN-CM-001",
      "EN-CM-002"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-04",
    "courseId": "ADM-04",
    "pathway": "ADM",
    "title": "QAPI Governance & Data-Driven Oversight",
    "policyIds": [
      "QA-PG-001",
      "QA-PG-002",
      "QA-PG-003",
      "QA-PI-001",
      "QA-PI-002",
      "QA-PI-003",
      "QA-PI-004",
      "QA-PI-005",
      "QA-AE-002",
      "QA-AE-003",
      "QA-AE-004",
      "QA-SM-001",
      "QA-SM-003",
      "QA-SM-004",
      "QA-SM-005",
      "QA-VBP-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-05",
    "courseId": "ADM-05",
    "pathway": "ADM",
    "title": "Enterprise Risk, Emergency & Claims Leadership",
    "policyIds": [
      "RM-EP-001",
      "RM-EP-002",
      "RM-EP-003",
      "RM-ER-001",
      "RM-ER-002",
      "RM-ER-003",
      "RM-ER-004",
      "RM-ER-005",
      "RM-ER-006"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-06",
    "courseId": "ADM-06",
    "pathway": "ADM",
    "title": "Workforce, Training, Competency & Employee Relations Leadership",
    "policyIds": [
      "HR-TA-005",
      "HR-TA-006",
      "HR-TD-001",
      "HR-TD-003",
      "HR-TD-005",
      "HR-TR-101",
      "HR-WM-001",
      "HR-WM-003",
      "HR-WM-004",
      "HR-WM-007",
      "HR-ER-001",
      "HR-ER-002",
      "HR-ER-004",
      "HR-ER-006"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "ADM-07",
    "courseId": "ADM-07",
    "pathway": "ADM",
    "title": "Financial Stewardship, Licensure & Agency Continuity",
    "policyIds": [
      "FN-FP-005",
      "FN-FP-007",
      "FN-BC-004",
      "GV-EA-001",
      "GV-EA-004",
      "GV-EA-005",
      "GV-OG-004"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-01",
    "courseId": "DON-01",
    "pathway": "DON",
    "title": "DON / Clinical Manager Authority, Delegation & Role",
    "policyIds": [
      "HR-JD-003",
      "HR-JD-004",
      "HR-JD-000",
      "GV-OG-002",
      "GV-OG-005",
      "HR-TA-006"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-02",
    "courseId": "DON-02",
    "pathway": "DON",
    "title": "Clinical Documentation, Orders & Care Coordination Oversight",
    "policyIds": [
      "CL-CD-001",
      "CL-CD-002",
      "CL-CD-003",
      "CL-CD-004",
      "CO-DC-001",
      "CO-DC-002",
      "CO-DC-003",
      "CO-DC-004",
      "CL-DC-101",
      "CL-CP-001",
      "CL-CP-002",
      "CL-CP-003",
      "CL-CP-004",
      "CL-CP-005",
      "CL-CP-006",
      "CL-CP-007",
      "CL-CP-008",
      "CL-CP-009",
      "CL-CC-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-03",
    "courseId": "DON-03",
    "pathway": "DON",
    "title": "Assessment & OASIS Governance",
    "policyIds": [
      "CL-CA-001",
      "CL-CA-002",
      "CL-CA-003",
      "CL-CA-004",
      "CL-CA-005",
      "CL-CA-006",
      "CL-CA-007",
      "CL-OA-001",
      "CL-OA-002",
      "CL-OA-003",
      "CL-OA-004",
      "CL-OA-005",
      "CL-OA-006",
      "CL-OA-007",
      "CL-OA-008",
      "CL-OA-009",
      "CL-OA-010",
      "CL-OA-011",
      "CL-OA-012",
      "CL-OA-013",
      "CL-OA-014",
      "CL-OA-015",
      "CL-OA-016",
      "CL-OA-017",
      "CL-OA-018",
      "CL-OA-019",
      "CL-OA-101"
    ],
    "passScore": 85,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-04",
    "courseId": "DON-04",
    "pathway": "DON",
    "title": "Discipline Services, HHA Supervision & Competency",
    "policyIds": [
      "CL-SD-001",
      "CL-SD-002",
      "CL-SD-003",
      "CL-SD-004",
      "CL-SD-005",
      "CL-SD-006",
      "CL-SD-007",
      "CL-SD-008",
      "HR-TD-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-05",
    "courseId": "DON-05",
    "pathway": "DON",
    "title": "Medication, Specialty & High-Risk Clinical Governance",
    "policyIds": [
      "CL-SD-009",
      "CL-SD-010",
      "CL-SD-011",
      "CL-SD-012",
      "CL-SD-013",
      "CL-SD-014",
      "CL-SD-015",
      "CL-SD-016",
      "CL-SD-017",
      "CL-SD-018",
      "CL-SD-019",
      "CL-SD-020",
      "CL-SD-021",
      "CL-SD-022",
      "CL-SD-023",
      "CL-SD-024",
      "CL-SD-025",
      "RM-PS-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-06",
    "courseId": "DON-06",
    "pathway": "DON",
    "title": "Clinical QAPI, Outcomes & Patient Safety",
    "policyIds": [
      "QA-PG-001",
      "QA-PG-002",
      "QA-PG-003",
      "QA-PI-001",
      "QA-PI-002",
      "QA-PI-003",
      "QA-PI-004",
      "QA-PI-005",
      "QA-PI-006",
      "QA-PI-007",
      "QA-SM-001",
      "QA-SM-002",
      "QA-SM-003",
      "QA-SM-004",
      "QA-SM-005",
      "QA-AE-002",
      "QA-AE-003",
      "QA-AE-004",
      "QA-VBP-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-07",
    "courseId": "DON-07",
    "pathway": "DON",
    "title": "Clinical Compliance, Survey & Documentation Audit",
    "policyIds": [
      "CO-RA-003",
      "CO-RA-004",
      "CO-RA-005",
      "CO-RA-006",
      "CO-DC-001",
      "CO-DC-002",
      "CO-DC-003",
      "CO-DC-004",
      "FN-CM-001",
      "FN-CM-002",
      "FN-CM-003",
      "FN-CM-004",
      "FN-CM-005",
      "CO-FA-002",
      "CO-FW-101"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "DON-08",
    "courseId": "DON-08",
    "pathway": "DON",
    "title": "Clinical Workforce, Emergency & Risk Leadership",
    "policyIds": [
      "HR-TA-005",
      "HR-TA-006",
      "HR-TD-001",
      "HR-TD-003",
      "HR-TD-005",
      "HR-TR-101",
      "HR-WM-001",
      "HR-WM-003",
      "HR-WM-004",
      "HR-WM-007",
      "HR-ER-001",
      "HR-ER-002",
      "HR-ER-004",
      "RM-EP-001",
      "RM-EP-002",
      "RM-EP-003",
      "RM-ER-001",
      "RM-ER-002",
      "RM-ER-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-01",
    "courseId": "GB-01",
    "pathway": "GB",
    "title": "Governing Body Authority & Responsibilities",
    "policyIds": [
      "GV-GB-001"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-02",
    "courseId": "GB-02",
    "pathway": "GB",
    "title": "Board Meetings, Minutes & Evidence",
    "policyIds": [
      "GV-GB-002"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-03",
    "courseId": "GB-03",
    "pathway": "GB",
    "title": "Conflict of Interest, Ethics & Referral Integrity",
    "policyIds": [
      "GV-GB-003",
      "CO-CP-004",
      "CO-FA-001"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-04",
    "courseId": "GB-04",
    "pathway": "GB",
    "title": "Succession Planning & Delegation",
    "policyIds": [
      "GV-GB-004",
      "GV-OG-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-05",
    "courseId": "GB-05",
    "pathway": "GB",
    "title": "Annual Governance Self-Assessment",
    "policyIds": [
      "GV-GB-005"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-06",
    "courseId": "GB-06",
    "pathway": "GB",
    "title": "Organization, Administrator & Scope of Services",
    "policyIds": [
      "GV-OG-001",
      "GV-OG-002",
      "GV-OG-003",
      "HR-JD-001"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-07",
    "courseId": "GB-07",
    "pathway": "GB",
    "title": "Strategic Planning & Annual Goals",
    "policyIds": [
      "GV-OG-004"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-08",
    "courseId": "GB-08",
    "pathway": "GB",
    "title": "Policy Approval, Review & Staff Attestation Governance",
    "policyIds": [
      "GV-PM-001",
      "GV-PM-002",
      "GV-PM-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-09",
    "courseId": "GB-09",
    "pathway": "GB",
    "title": "Compliance, Reporting, Privacy & Oversight",
    "policyIds": [
      "CO-CP-001",
      "CO-CP-002",
      "CO-CP-003",
      "CO-CP-005",
      "CO-CP-008",
      "CO-FW-101",
      "CO-HP-101",
      "IT-UP-004"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-10",
    "courseId": "GB-10",
    "pathway": "GB",
    "title": "QAPI Governance & Performance Improvement",
    "policyIds": [
      "QA-PG-001",
      "QA-PG-002",
      "QA-PG-003",
      "QA-PI-001",
      "QA-PI-002",
      "QA-PI-004"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-11",
    "courseId": "GB-11",
    "pathway": "GB",
    "title": "Financial Stewardship & Overpayment Controls",
    "policyIds": [
      "FN-FP-005",
      "FN-FP-007",
      "FN-BC-004"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-12",
    "courseId": "GB-12",
    "pathway": "GB",
    "title": "Emergency Preparedness & Enterprise Risk Oversight",
    "policyIds": [
      "RM-EP-001",
      "RM-EP-002",
      "RM-ER-001",
      "RM-ER-003"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  },
  {
    "bundleId": "GB-13",
    "courseId": "GB-13",
    "pathway": "GB",
    "title": "Licensure, Certification, Closure & Change of Ownership",
    "policyIds": [
      "GV-EA-004",
      "GV-EA-005",
      "CO-RA-004",
      "CO-RA-005",
      "CO-RA-006"
    ],
    "passScore": 80,
    "maxAttempts": 3,
    "questionCount": 10,
    "bankStatus": "MISSING",
    "note": "No approved question bank exists yet. Quiz UI must render \"Quiz not yet published\" and block completion."
  }
];

export function getQuizBundle(courseId: string): GeneratedQuizBundle | undefined {
  return POLICY_QUIZ_MAP.find((q) => q.courseId === courseId);
}

