import type { RoleRequirement } from '../types';
import { POL } from './policies';

/** Convenience builder. */
function r(p: Omit<RoleRequirement, 'version'>): RoleRequirement {
  return { ...p, version: 1 };
}

/** Canonical RoleRequirement catalog (per docs 02 + 05). */
export const REQUIREMENTS: RoleRequirement[] = [
  /* ── Universal ───────────────────────────────────────────── */
  r({
    id: 'REQ-UNIV-HIPAA',
    roleIds: ['ADMIN','CLINICAL_MANAGER','RN','LVN','HHA','THERAPIST','QAPI_MEMBER','COMPLIANCE_OFFICER','PRIVACY_OFFICER','SECURITY_OFFICER','OFFICE_STAFF','INTAKE','BILLING','GOVERNING_BODY','MEDICAL_DIRECTOR','VOLUNTEER'],
    name: 'HIPAA Workforce Training & Acknowledgment',
    description: 'Workforce HIPAA Privacy and Security training, with eCIgn acknowledgment bound to the current policy versions.',
    policyRefs: [POL.IT_HIPAA_PRIV, POL.IT_HIPAA_SEC],
    workflowId: 'WF-HIPAA-WORKFORCE',
    formIds: ['FRM-HIPAA-ACK'],
    evidenceSchema: [
      { objectType: 'TrainingRecord', requiredFields: ['contentHash','score','duration'] },
      { objectType: 'SignedPolicy',   requiredFields: ['policyVersion','signedAt'] },
    ],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'SystemAccessClearance', weight: 'Required' }],
    phase: 'Training', slaDays: 14,
  }),
  r({
    id: 'REQ-UNIV-COC',
    roleIds: ['ADMIN','CLINICAL_MANAGER','RN','LVN','HHA','THERAPIST','QAPI_MEMBER','COMPLIANCE_OFFICER','PRIVACY_OFFICER','SECURITY_OFFICER','OFFICE_STAFF','INTAKE','BILLING','GOVERNING_BODY','MEDICAL_DIRECTOR','VOLUNTEER'],
    name: 'Code of Conduct Acknowledgment',
    description: 'Acknowledgment of CO-CP-001 Compliance Program Code of Conduct.',
    policyRefs: [POL.CO_CP_001],
    workflowId: 'WF-COC-ACK',
    formIds: ['FRM-COC-ACK'],
    evidenceSchema: [{ objectType: 'SignedPolicy', requiredFields: ['policyVersion','signedAt'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [
      { gateId: 'SystemAccessClearance', weight: 'Required' },
      { gateId: 'FieldClearance',        weight: 'Required' },
    ],
    phase: 'Acknowledgments', slaDays: 7,
  }),
  r({
    id: 'REQ-UNIV-AUP',
    roleIds: ['ADMIN','CLINICAL_MANAGER','RN','LVN','HHA','THERAPIST','QAPI_MEMBER','COMPLIANCE_OFFICER','PRIVACY_OFFICER','SECURITY_OFFICER','OFFICE_STAFF','INTAKE','BILLING','GOVERNING_BODY','MEDICAL_DIRECTOR'],
    name: 'Acceptable Use Policy Acknowledgment',
    description: 'Acknowledgment of IT-AUP Acceptable Use Policy at current version.',
    policyRefs: [POL.IT_AUP],
    workflowId: 'WF-AUP-ACK',
    formIds: ['FRM-AUP-ACK'],
    evidenceSchema: [{ objectType: 'SignedPolicy', requiredFields: ['policyVersion','signedAt'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'SystemAccessClearance', weight: 'Required' }],
    phase: 'Acknowledgments', slaDays: 7,
  }),
  r({
    id: 'REQ-UNIV-BG',
    roleIds: ['ADMIN','CLINICAL_MANAGER','RN','LVN','HHA','THERAPIST','OFFICE_STAFF','INTAKE','BILLING'],
    name: 'Background Check',
    description: 'Workforce background check executed via approved vendor with HR adjudication.',
    policyRefs: [POL.HR_BG],
    workflowId: 'WF-BACKGROUND-CHECK',
    formIds: ['FRM-BG-AUTH','FRM-BG-RESULT'],
    evidenceSchema: [
      { objectType: 'FileUpload',          requiredFields: ['filename','contentHash'] },
      { objectType: 'ExternalSystemRecord', requiredFields: ['vendor','reportId'] },
    ],
    signatureSpecs: [
      { signerRole: 'Subject',           count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
      { signerRole: 'ComplianceOfficer', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
    ],
    cadence: { initial: true },
    gateContributions: [
      { gateId: 'FieldClearance',        weight: 'Required' },
      { gateId: 'SystemAccessClearance', weight: 'Required' },
    ],
    phase: 'PreHire', slaDays: 10,
  }),
  r({
    id: 'REQ-UNIV-EXCLUSION',
    roleIds: ['ADMIN','CLINICAL_MANAGER','RN','LVN','HHA','THERAPIST','OFFICE_STAFF','INTAKE','BILLING','MEDICAL_DIRECTOR','VENDOR'],
    name: 'OIG / SAM / State Exclusion Screening',
    description: 'OIG LEIE, SAM.gov, and state Medicaid exclusion screening at hire and monthly thereafter.',
    policyRefs: [POL.CO_CP_001],
    workflowId: 'WF-EXCLUSION-SCREEN',
    formIds: ['FRM-EXCL-RESULT'],
    evidenceSchema: [{ objectType: 'ScreeningResult', requiredFields: ['source','timestamp','result','contentHash'] }],
    signatureSpecs: [],
    cadence: { initial: true, recurrence: { kind: 'Monthly' } },
    gateContributions: [
      { gateId: 'FieldClearance',        weight: 'Required' },
      { gateId: 'BillingClearance',      weight: 'Required' },
      { gateId: 'VendorEngagement',      weight: 'Required' },
    ],
    phase: 'PreHire', slaDays: 3,
  }),
  r({
    id: 'REQ-UNIV-EP',
    roleIds: ['ADMIN','CLINICAL_MANAGER','RN','LVN','HHA','THERAPIST','OFFICE_STAFF','INTAKE','BILLING'],
    name: 'Emergency Preparedness Orientation',
    description: 'Emergency Preparedness orientation per RM-EP-001.',
    policyRefs: [POL.RM_EP_001],
    workflowId: 'WF-EP-ORIENT',
    formIds: ['FRM-EP-ACK'],
    evidenceSchema: [{ objectType: 'TrainingRecord', requiredFields: ['contentHash'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Conditional' }],
    phase: 'Orientation', slaDays: 14,
  }),

  /* ── Clinical (RN/LVN/Therapist) ─────────────────────────── */
  r({
    id: 'REQ-CL-LICENSE-PSV',
    roleIds: ['RN','LVN','THERAPIST','MEDICAL_DIRECTOR'],
    name: 'License Primary Source Verification',
    description: 'Primary source verification of state license against the issuing state board.',
    policyRefs: [POL.CO_RA_001],
    workflowId: 'WF-LICENSE-PSV',
    formIds: ['FRM-LICENSE-PSV-RESULT'],
    evidenceSchema: [{ objectType: 'PSVResult', requiredFields: ['source','licenseNumber','expiry','timestamp'] }],
    signatureSpecs: [],
    cadence: { initial: true, recurrence: { kind: 'Monthly' }, preExpiryWindowDays: 60 },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'PreHire', slaDays: 3,
  }),
  r({
    id: 'REQ-CL-BLS',
    roleIds: ['RN','LVN','THERAPIST'],
    name: 'BLS / CPR Certification',
    description: 'Current BLS or CPR certification card on file with expiry tracking.',
    policyRefs: [POL.CO_RA_001],
    workflowId: 'WF-BLS-VERIFY',
    formIds: ['FRM-BLS-CARD'],
    evidenceSchema: [{ objectType: 'FileUpload', requiredFields: ['filename','expiry','contentHash'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true, recurrence: { kind: 'PerCardExpiry' }, preExpiryWindowDays: 60 },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'PreHire', slaDays: 7,
  }),
  r({
    id: 'REQ-CL-TB',
    roleIds: ['RN','LVN','HHA','THERAPIST'],
    name: 'TB Screening',
    description: 'TB screening per RM-OS-001 with provider signature and employee acknowledgment.',
    policyRefs: [POL.RM_OS_001],
    workflowId: 'WF-TB-SCREEN',
    formIds: ['FRM-TB-RESULT'],
    evidenceSchema: [{ objectType: 'FileUpload', requiredFields: ['filename','providerSignature'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'PreHire', slaDays: 7,
  }),
  r({
    id: 'REQ-CL-DRUG',
    roleIds: ['RN','LVN','HHA','THERAPIST'],
    name: 'Drug Screen',
    description: 'Pre-field drug screening per HR cadence.',
    policyRefs: [POL.HR_BG],
    workflowId: 'WF-DRUG-SCREEN',
    formIds: ['FRM-DRUG-AUTH','FRM-DRUG-RESULT'],
    evidenceSchema: [{ objectType: 'FileUpload', requiredFields: ['filename'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'PreHire', slaDays: 5,
  }),
  r({
    id: 'REQ-CL-BBP',
    roleIds: ['RN','LVN','HHA','THERAPIST'],
    name: 'Bloodborne Pathogens Training',
    description: 'OSHA bloodborne pathogens training, annual.',
    policyRefs: [POL.RM_OS_001],
    workflowId: 'WF-BBP-TRAIN',
    formIds: ['FRM-BBP-ACK'],
    evidenceSchema: [{ objectType: 'TrainingRecord', requiredFields: ['contentHash','duration'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Conditional' }],
    phase: 'Training', slaDays: 14,
  }),
  r({
    id: 'REQ-CL-DOC-HIER',
    roleIds: ['RN','LVN','CLINICAL_MANAGER','THERAPIST'],
    name: 'Documentation Hierarchy Training (CL-OA-006)',
    description: 'Training on the clinical documentation hierarchy and acknowledgment.',
    policyRefs: [POL.CL_OA_006],
    workflowId: 'WF-DOC-HIERARCHY',
    formIds: ['FRM-DOC-HIER-ACK'],
    evidenceSchema: [
      { objectType: 'TrainingRecord', requiredFields: ['contentHash'] },
      { objectType: 'SignedPolicy',   requiredFields: ['policyVersion','signedAt'] },
    ],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'Training', slaDays: 7,
  }),
  r({
    id: 'REQ-RN-OASIS',
    roleIds: ['RN'],
    name: 'OASIS Competency',
    description: 'RN OASIS competency assessment with Clinical Manager co-signature.',
    policyRefs: [POL.CL_OA_006],
    workflowId: 'WF-OASIS-COMPETENCY',
    formIds: ['FRM-OASIS-COMP'],
    evidenceSchema: [{ objectType: 'CompetencyArtifact', requiredFields: ['skills','outcome','contentHash'] }],
    signatureSpecs: [
      { signerRole: 'Subject',         count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
      { signerRole: 'ClinicalManager', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
    ],
    competencyRef: 'COMP-RN-OASIS',
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'Competency', slaDays: 21,
  }),
  r({
    id: 'REQ-RN-MEDRECON',
    roleIds: ['RN'],
    name: 'Medication Reconciliation Competency',
    description: 'Observed medication reconciliation competency.',
    policyRefs: [POL.CL_OA_006],
    workflowId: 'WF-MED-RECON-COMP',
    formIds: ['FRM-MED-RECON'],
    evidenceSchema: [{ objectType: 'CompetencyArtifact', requiredFields: ['skills','outcome'] }],
    signatureSpecs: [
      { signerRole: 'Subject',         count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
      { signerRole: 'ClinicalManager', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
    ],
    competencyRef: 'COMP-RN-MEDRECON',
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'Competency', slaDays: 21,
  }),
  r({
    id: 'REQ-CL-FIELD-CLEAR',
    roleIds: ['RN','LVN','HHA','THERAPIST'],
    name: 'Field Clearance Aggregate',
    description: 'Compliance Officer or delegate signature attesting Field Clearance gate is satisfied.',
    policyRefs: [POL.CO_RA_001],
    workflowId: 'WF-FIELD-CLEARANCE',
    formIds: ['FRM-FIELD-CLEARANCE'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['attestation'] }],
    signatureSpecs: [{ signerRole: 'ComplianceOfficer', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true },
    preConditions: ['REQ-CL-LICENSE-PSV','REQ-CL-BLS','REQ-CL-TB','REQ-CL-DRUG','REQ-UNIV-BG','REQ-UNIV-EXCLUSION','REQ-UNIV-HIPAA','REQ-UNIV-COC'],
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'Clearance', slaDays: 30,
  }),

  /* ── HHA-specific ─────────────────────────────────────────── */
  r({
    id: 'REQ-HHA-QUALIFY',
    roleIds: ['HHA'],
    name: 'HHA Training Program / Competency Exam',
    description: 'HHA qualification per CoP §484.80(a) — training program completion or competency exam.',
    policyRefs: [POL.CL_484_80],
    workflowId: 'WF-HHA-QUALIFY',
    formIds: ['FRM-HHA-TRAINING-CERT'],
    evidenceSchema: [{ objectType: 'FileUpload', requiredFields: ['filename','contentHash'] }],
    signatureSpecs: [{ signerRole: 'ClinicalManager', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'PreHire', slaDays: 5,
  }),
  r({
    id: 'REQ-HHA-COMP-12',
    roleIds: ['HHA'],
    name: 'HHA 12-Subject Competency',
    description: 'HHA competency in all 12 CoP §484.80(c) subject areas, observed in patient or simulated setting.',
    policyRefs: [POL.CL_484_80],
    workflowId: 'WF-HHA-COMPETENCY-12',
    formIds: ['FRM-HHA-COMP-12'],
    evidenceSchema: [{ objectType: 'CompetencyArtifact', requiredFields: ['skills','outcome','setting'] }],
    signatureSpecs: [
      { signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
      { signerRole: 'Custom',  count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }, // RN observer
    ],
    competencyRef: 'COMP-HHA-12',
    cadence: { initial: true, recurrence: { kind: 'Biennial' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'Competency', slaDays: 21,
  }),
  r({
    id: 'REQ-HHA-INSERVICE-12HR',
    roleIds: ['HHA'],
    name: 'HHA 12-Hour Annual In-Service',
    description: 'HHA 12 hours in-service per rolling 12-month period.',
    policyRefs: [POL.CL_484_80],
    workflowId: 'WF-HHA-INSERVICE-12HR',
    formIds: ['FRM-HHA-INSERVICE-LOG'],
    evidenceSchema: [{ objectType: 'TrainingRecord', requiredFields: ['hours','subjects'] }],
    signatureSpecs: [{ signerRole: 'Custom', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: false, recurrence: { kind: 'Rolling12mo' } },
    gateContributions: [{ gateId: 'FieldClearance', weight: 'Required' }],
    phase: 'PostActivation', slaDays: 365,
  }),

  /* ── Governance / Officers ────────────────────────────────── */
  r({
    id: 'REQ-ADMIN-APPT',
    roleIds: ['ADMIN'],
    name: 'Administrator Appointment',
    description: 'Governing Body appointment of Administrator with eCIgn acceptance.',
    policyRefs: [POL.EN_GB, POL.EN_CM_001],
    workflowId: 'WF-ADMIN-APPOINTMENT',
    formIds: ['FRM-ADMIN-APPOINTMENT-LETTER'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['letter'] }],
    signatureSpecs: [
      { signerRole: 'GoverningBodyChair', count: 1, order: 'Sequential', bindsTo: 'Appointment' },
      { signerRole: 'Subject',            count: 1, order: 'Sequential', bindsTo: 'Appointment' },
    ],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'GovernanceActive', weight: 'Required' }],
    phase: 'PreHire', slaDays: 1,
  }),
  r({
    id: 'REQ-CO-APPT',
    roleIds: ['COMPLIANCE_OFFICER'],
    name: 'Compliance Officer Appointment',
    description: 'CO appointment + charter; binds CO-CP-001 owner.',
    policyRefs: [POL.CO_CP_001],
    workflowId: 'WF-CO-APPOINTMENT',
    formIds: ['FRM-CO-APPOINTMENT','FRM-CO-CHARTER'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['letter','charter'] }],
    signatureSpecs: [
      { signerRole: 'GoverningBodyChair', count: 1, order: 'Sequential', bindsTo: 'Appointment' },
      { signerRole: 'Subject',            count: 1, order: 'Sequential', bindsTo: 'Appointment' },
    ],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'GovernanceActive', weight: 'Required' }],
    phase: 'PreHire', slaDays: 1,
  }),
  r({
    id: 'REQ-PRIVACY-APPT',
    roleIds: ['PRIVACY_OFFICER'],
    name: 'Privacy Officer Appointment',
    description: 'HIPAA Privacy Officer appointment per IT-HIPAA-PRIVACY.',
    policyRefs: [POL.IT_HIPAA_PRIV],
    workflowId: 'WF-PRIVACY-APPOINTMENT',
    formIds: ['FRM-PRIVACY-APPOINTMENT'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['letter'] }],
    signatureSpecs: [
      { signerRole: 'Administrator', count: 1, order: 'Sequential', bindsTo: 'Appointment' },
      { signerRole: 'Subject',       count: 1, order: 'Sequential', bindsTo: 'Appointment' },
    ],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'GovernanceActive', weight: 'Required' }],
    phase: 'PreHire', slaDays: 1,
  }),
  r({
    id: 'REQ-GB-APPT',
    roleIds: ['GOVERNING_BODY'],
    name: 'Governing Body Appointment + COI',
    description: 'Governing body member appointment with annual conflict of interest disclosure.',
    policyRefs: [POL.EN_GB],
    workflowId: 'WF-GB-APPOINTMENT',
    formIds: ['FRM-GB-APPOINTMENT','FRM-GB-COI'],
    evidenceSchema: [
      { objectType: 'FormSubmission', requiredFields: ['letter'] },
      { objectType: 'FormSubmission', requiredFields: ['coiDisclosure'] },
    ],
    signatureSpecs: [
      { signerRole: 'GoverningBodyChair', count: 1, order: 'Sequential', bindsTo: 'Appointment' },
      { signerRole: 'Subject',            count: 1, order: 'Sequential', bindsTo: 'Appointment' },
    ],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'GovernanceActive', weight: 'Required' }],
    phase: 'PreHire', slaDays: 1,
  }),

  /* ── QAPI ────────────────────────────────────────────────── */
  r({
    id: 'REQ-QAPI-MEMBER',
    roleIds: ['QAPI_MEMBER'],
    name: 'QAPI Roster Onboarding',
    description: 'QAPI committee onboarding with confidentiality acknowledgment.',
    policyRefs: [POL.QA_QAPI],
    workflowId: 'WF-QAPI-ONBOARD',
    formIds: ['FRM-QAPI-MEMBER','FRM-QAPI-CONFIDENTIALITY'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['rosterEntry','confidentiality'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [],
    phase: 'PreHire', slaDays: 7,
  }),

  /* ── Billing ─────────────────────────────────────────────── */
  r({
    id: 'REQ-BILLING-SOP',
    roleIds: ['BILLING'],
    name: 'Billing SOP Training (FN-BC-001)',
    description: 'FN-BC-001 billing SOP training plus competency sample.',
    policyRefs: [POL.FN_BC_001],
    workflowId: 'WF-BILLING-SOP',
    formIds: ['FRM-BILLING-SOP-ACK'],
    evidenceSchema: [
      { objectType: 'TrainingRecord', requiredFields: ['contentHash'] },
      { objectType: 'SignedPolicy',   requiredFields: ['policyVersion','signedAt'] },
    ],
    signatureSpecs: [
      { signerRole: 'Subject',    count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' },
      { signerRole: 'Supervisor', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' },
    ],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'BillingClearance', weight: 'Required' }],
    phase: 'Training', slaDays: 14,
  }),
  r({
    id: 'REQ-BILLING-FWA',
    roleIds: ['BILLING','COMPLIANCE_OFFICER'],
    name: 'Fraud, Waste & Abuse Training',
    description: 'FWA training and acknowledgment per CO-CP-001.',
    policyRefs: [POL.CO_CP_001],
    workflowId: 'WF-FWA-TRAIN',
    formIds: ['FRM-FWA-ACK'],
    evidenceSchema: [{ objectType: 'TrainingRecord', requiredFields: ['contentHash'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'BillingClearance', weight: 'Required' }],
    phase: 'Training', slaDays: 14,
  }),
  r({
    id: 'REQ-BILLING-CLEAR',
    roleIds: ['BILLING'],
    name: 'Billing Clearance Aggregate',
    description: 'Compliance Officer attestation of Billing Clearance gate satisfaction.',
    policyRefs: [POL.FN_BC_001, POL.CO_CP_001],
    workflowId: 'WF-BILLING-CLEARANCE',
    formIds: ['FRM-BILLING-CLEARANCE'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['attestation'] }],
    signatureSpecs: [{ signerRole: 'ComplianceOfficer', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true },
    preConditions: ['REQ-BILLING-SOP','REQ-BILLING-FWA','REQ-UNIV-HIPAA','REQ-UNIV-AUP','REQ-UNIV-EXCLUSION'],
    gateContributions: [{ gateId: 'BillingClearance', weight: 'Required' }],
    phase: 'Clearance', slaDays: 30,
  }),

  /* ── Vendor ──────────────────────────────────────────────── */
  r({
    id: 'REQ-VENDOR-INTAKE',
    roleIds: ['VENDOR'],
    name: 'Vendor Intake',
    description: 'Vendor intake record collection.',
    policyRefs: [POL.CO_CP_001],
    workflowId: 'WF-VENDOR-INTAKE',
    formIds: ['FRM-VENDOR-INTAKE'],
    evidenceSchema: [{ objectType: 'FormSubmission', requiredFields: ['intake'] }],
    signatureSpecs: [{ signerRole: 'Vendor', count: 1, order: 'Sequential', bindsTo: 'EvidenceObject' }],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'VendorEngagement', weight: 'Required' }],
    phase: 'PreHire', slaDays: 5,
  }),
  r({
    id: 'REQ-VENDOR-BAA',
    roleIds: ['VENDOR'],
    name: 'BAA Execution',
    description: 'Business Associate Agreement signed at the current BAA template version.',
    policyRefs: [POL.IT_HIPAA_PRIV, POL.IT_HIPAA_SEC],
    workflowId: 'WF-BAA-EXECUTE',
    formIds: ['FRM-BAA'],
    evidenceSchema: [{ objectType: 'SignedPolicy', requiredFields: ['policyVersion','signedAt','contentHash'] }],
    signatureSpecs: [
      { signerRole: 'Vendor',         count: 1, order: 'Parallel', bindsTo: 'PolicyVersion' },
      { signerRole: 'PrivacyOfficer', count: 1, order: 'Parallel', bindsTo: 'PolicyVersion' },
    ],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'VendorEngagement', weight: 'Required' }],
    phase: 'Acknowledgments', slaDays: 7,
  }),
  r({
    id: 'REQ-VENDOR-INSURANCE',
    roleIds: ['VENDOR'],
    name: 'Insurance Certificate',
    description: 'Vendor insurance certificate of insurance with expiry tracking.',
    policyRefs: [POL.CO_CP_001],
    workflowId: 'WF-VENDOR-INSURANCE',
    formIds: ['FRM-INSURANCE-COI'],
    evidenceSchema: [{ objectType: 'FileUpload', requiredFields: ['filename','expiry'] }],
    signatureSpecs: [],
    cadence: { initial: true, preExpiryWindowDays: 30 },
    gateContributions: [{ gateId: 'VendorEngagement', weight: 'Required' }],
    phase: 'PreHire', slaDays: 5,
  }),

  /* ── Office staff / Intake ───────────────────────────────── */
  r({
    id: 'REQ-OFFICE-CONFID',
    roleIds: ['OFFICE_STAFF','INTAKE','BILLING','VOLUNTEER'],
    name: 'Workforce Confidentiality',
    description: 'Workforce confidentiality acknowledgment.',
    policyRefs: [POL.IT_HIPAA_PRIV],
    workflowId: 'WF-CONFIDENTIALITY',
    formIds: ['FRM-CONFIDENTIALITY'],
    evidenceSchema: [{ objectType: 'SignedPolicy', requiredFields: ['policyVersion'] }],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true },
    gateContributions: [{ gateId: 'SystemAccessClearance', weight: 'Required' }],
    phase: 'Acknowledgments', slaDays: 7,
  }),
  r({
    id: 'REQ-INTAKE-SOP',
    roleIds: ['INTAKE'],
    name: 'Intake SOP Training',
    description: 'Intake SOP training and acknowledgment per OP-IN-001.',
    policyRefs: [POL.OP_INTAKE],
    workflowId: 'WF-INTAKE-SOP',
    formIds: ['FRM-INTAKE-SOP-ACK'],
    evidenceSchema: [
      { objectType: 'TrainingRecord', requiredFields: ['contentHash'] },
      { objectType: 'SignedPolicy',   requiredFields: ['policyVersion'] },
    ],
    signatureSpecs: [{ signerRole: 'Subject', count: 1, order: 'Sequential', bindsTo: 'PolicyVersion' }],
    cadence: { initial: true, recurrence: { kind: 'Annual' } },
    gateContributions: [{ gateId: 'SystemAccessClearance', weight: 'Required' }],
    phase: 'Training', slaDays: 14,
  }),
];

export function getRequirement(id: string): RoleRequirement | undefined {
  return REQUIREMENTS.find(r => r.id === id);
}

export function requirementsForRole(roleId: string): RoleRequirement[] {
  return REQUIREMENTS.filter(r => (r.roleIds as string[]).includes(roleId));
}
