import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const repoRoot = resolve(process.cwd());

const sourceFiles = [
  'gv-manual-achc-tag-dataset.json',
  'cl-manual-achc-tag-dataset.json',
  'co-manual-achc-tag-dataset.json',
  'qa-manual-achc-tag-dataset.json',
  'rm-manual-achc-tag-dataset.json',
  'hr-manual-achc-tag-dataset.json',
  'it-manual-achc-tag-dataset.json',
  'non-gv-manual-achc-tag-dataset.json',
];

const docsCandidates = [
  resolve(repoRoot, 'Builder/Documentations/MigratedRepoRoot/docs'),
  resolve(repoRoot, 'docs'),
];

function normalizeList(value) {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => String(item ?? '').trim())
    .filter(Boolean);
}

function normalizeMappingType(record) {
  const raw = String(record.mappingType ?? '').toUpperCase();
  const flags = normalizeList(record.flags).map((f) => f.toUpperCase());
  const hasSmeFlag = flags.some((f) => f.includes('SME'));
  if (hasSmeFlag || raw.includes('SME') || raw.includes('REQUIRES_SME_REVIEW')) return 'SME_REVIEW';
  if (raw === 'DIRECT') return 'DIRECT';
  if (raw === 'PARTIAL') return 'PARTIAL';
  return 'NONE';
}

function uniqueSorted(values) {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b));
}

function mappingRank(mappingType) {
  if (mappingType === 'DIRECT') return 4;
  if (mappingType === 'PARTIAL') return 3;
  if (mappingType === 'SME_REVIEW') return 2;
  return 1;
}

function recordScore(rec) {
  return (
    mappingRank(rec.mappingType) * 1000 +
    rec.achcStandards.length * 50 +
    rec.evidenceCodes.length * 20 +
    rec.title22.length * 5 +
    rec.medicareCop.length * 5 +
    (rec.corridorPolicyNo ? 2 : 0) +
    (rec.surveyNotes ? 1 : 0)
  );
}

async function main() {
  const all = [];
  let docsDir = '';
  for (const candidate of docsCandidates) {
    try {
      await readFile(resolve(candidate, sourceFiles[0]), 'utf8');
      docsDir = candidate;
      break;
    } catch {
      // try next
    }
  }
  if (!docsDir) {
    throw new Error('Could not locate ACHC manual dataset directory.');
  }

  for (const rel of sourceFiles) {
    const abs = resolve(docsDir, rel);
    const content = await readFile(abs, 'utf8');
    const parsed = JSON.parse(content);
    if (Array.isArray(parsed)) all.push(...parsed);
  }

  const byPolicy = new Map();
  for (const rec of all) {
    const policyId = String(rec.policyId ?? '').trim();
    if (!policyId) continue;
    const normalized = {
      policyId,
      policyTitle: String(rec.policyTitle ?? '').trim(),
      domain: String(rec.domain ?? '').trim(),
      achcStandards: uniqueSorted(normalizeList(rec.achcStandards)),
      title22: uniqueSorted(normalizeList(rec.title22)),
      medicareCop: uniqueSorted(normalizeList(rec.cop)),
      evidenceCodes: uniqueSorted(normalizeList(rec.surveyEvidenceMethods)),
      mappingType: normalizeMappingType(rec),
      corridorPolicyNo: String(rec.corridorPolicyNo ?? '').trim(),
      corridorPolicyTitle: String(rec.corridorPolicyTitle ?? '').trim(),
      realEvidenceArtifacts: uniqueSorted(normalizeList(rec.realEvidenceArtifacts)),
      surveyNotes: String(rec.justification ?? '').trim(),
    };
    const existing = byPolicy.get(policyId);
    if (!existing || recordScore(normalized) >= recordScore(existing)) {
      byPolicy.set(policyId, normalized);
    }
  }

  const rows = [...byPolicy.values()].sort((a, b) => a.policyId.localeCompare(b.policyId));
  const mapObj = Object.fromEntries(rows.map((row) => [row.policyId, row]));

  const output = `/* Auto-generated by scripts/buildAchcSurveyProjection.mjs */
/* Source of truth: manual ACHC domain datasets under docs/*.json */

export type AchcMappingType = 'DIRECT' | 'PARTIAL' | 'NONE' | 'SME_REVIEW';
export type AchcEvidenceCode = 'P' | 'D' | 'I' | 'O' | 'S';

export interface AchcSurveyMetadata {
  policyId: string;
  policyTitle: string;
  domain: string;
  achcStandards: string[];
  title22: string[];
  medicareCop: string[];
  evidenceCodes: AchcEvidenceCode[];
  mappingType: AchcMappingType;
  corridorPolicyNo: string;
  corridorPolicyTitle: string;
  realEvidenceArtifacts: string[];
  surveyNotes: string;
}

export const achcSurveyRows: AchcSurveyMetadata[] = ${JSON.stringify(rows, null, 2)} as AchcSurveyMetadata[];

export const achcSurveyByPolicyId: Record<string, AchcSurveyMetadata> = ${JSON.stringify(mapObj, null, 2)} as Record<string, AchcSurveyMetadata>;
`;

  const outputPath = resolve(repoRoot, 'src/policy/data/achcSurveyProjection.generated.ts');
  await writeFile(outputPath, output, 'utf8');
  console.log(`Wrote ${outputPath} (${rows.length} policies)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
