/**
 * Mapping coverage report generator — PRD §29 #11 / #12.
 *
 * Walks EVENT_PACKET_MAP, writes docs/packets/COVERAGE_REPORT.md with:
 * - per-family table (family, title, archetype, template, workflow, status)
 * - totals
 * - explicit UNRESOLVED/GAP section
 *
 * Exits non-zero if any distinct event family from the three sources
 * is missing entirely from the map (unmapped). Gap/needs-review entries
 * are reported but do not fail the exit code by themselves.
 *
 * I/O is strict UTF-8. Titles from source files that contain classic
 * Windows-1252 mojibake of UTF-8 multi-byte sequences are repaired so
 * em-dashes and similar characters render correctly in the report.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { RegulatoryEvent } from '../src/policy/data/regulatoryEvents';
import { REGULATORY_EVENTS } from '../src/policy/data/regulatoryEvents';
import { MANDATED_EVENTS_EXPANDED } from '../src/policy/data/mandatedEventsExpanded';
import { MULTI_YEAR_EVENTS } from '../src/policy/data/multiYearEvents';
import {
  EVENT_PACKET_MAP,
  listUnresolvedOrGapEntries,
} from '../src/policy/packets/registries/eventPacketMap';
import { templatesForEventFamily } from '../src/policy/packets/registries/templateRegistry';

/** UTF-8 encoding option used for all report writes. */
const UTF8 = 'utf8' as const;

/**
 * Windows-1252 reverse map for C1 controls that differ from ISO-8859-1.
 * Used to recover UTF-8 bytes that were mis-decoded as Windows-1252 and
 * then re-encoded as UTF-8 (classic `â€"` mojibake for U+2014).
 */
const WIN1252_REVERSE: ReadonlyMap<number, number> = new Map([
  [0x20ac, 0x80], // euro
  [0x201a, 0x82],
  [0x0192, 0x83],
  [0x201e, 0x84],
  [0x2026, 0x85],
  [0x2020, 0x86],
  [0x2021, 0x87],
  [0x02c6, 0x88],
  [0x2030, 0x89],
  [0x0160, 0x8a],
  [0x2039, 0x8b],
  [0x0152, 0x8c],
  [0x017d, 0x8e],
  [0x2018, 0x91],
  [0x2019, 0x92],
  [0x201c, 0x93],
  [0x201d, 0x94],
  [0x2022, 0x95],
  [0x2013, 0x96],
  [0x2014, 0x97],
  [0x02dc, 0x98],
  [0x2122, 0x99],
  [0x0161, 0x9a],
  [0x203a, 0x9b],
  [0x0153, 0x9c],
  [0x017e, 0x9e],
  [0x0178, 0x9f],
]);

function codePointToWin1252Byte(cp: number): number | null {
  if (cp < 0x80) return cp;
  if (cp >= 0xa0 && cp <= 0xff) return cp;
  return WIN1252_REVERSE.get(cp) ?? null;
}

/**
 * Repair text that is Unicode mojibake of UTF-8 (e.g. `â€"` → `—`).
 * Leaves clean strings unchanged. Never throws.
 */
export function repairUtf8Mojibake(input: string): string {
  if (!input) return input;
  // Fast path: no high characters and no classic markers.
  let hasHigh = false;
  for (const ch of input) {
    if ((ch.codePointAt(0) ?? 0) > 0x7f) {
      hasHigh = true;
      break;
    }
  }
  if (!hasHigh) return input;

  const bytes: number[] = [];
  for (const ch of input) {
    const cp = ch.codePointAt(0)!;
    const b = codePointToWin1252Byte(cp);
    if (b === null) {
      // Cannot reverse this code point as a single Windows-1252 byte.
      return input;
    }
    bytes.push(b);
  }

  try {
    const decoded = Buffer.from(bytes).toString(UTF8);
    if (decoded.includes('\uFFFD')) return input;
    // Prefer decoded only when it actually improved something (fewer high
    // control-looking sequences or contains expected punctuation).
    return decoded;
  } catch {
    return input;
  }
}

function distinctFamiliesFromSources(): Set<string> {
  const families = new Set<string>();
  const sources: readonly (readonly RegulatoryEvent[])[] = [
    REGULATORY_EVENTS,
    MANDATED_EVENTS_EXPANDED,
    MULTI_YEAR_EVENTS,
  ];
  for (const src of sources) {
    for (const e of src) {
      if (e.eventSubType) families.add(e.eventSubType);
    }
  }
  return families;
}

function escapeCell(value: string): string {
  return repairUtf8Mojibake(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function buildReport(): { markdown: string; unmapped: string[] } {
  const sourceFamilies = distinctFamiliesFromSources();
  const mappedIds = new Set(EVENT_PACKET_MAP.map((d) => d.eventFamilyId));
  const unmapped = [...sourceFamilies].filter((id) => !mappedIds.has(id)).sort();

  const resolved = EVENT_PACKET_MAP.filter((d) => d.status === 'resolved');
  const needsReview = EVENT_PACKET_MAP.filter((d) => d.status === 'needs-review');
  const gaps = EVENT_PACKET_MAP.filter((d) => d.status === 'gap');
  const unresolved = listUnresolvedOrGapEntries();

  const lines: string[] = [];
  lines.push('# Packet Mapping Coverage Report');
  lines.push('');
  lines.push('> Generated by `scripts/reportPacketCoverage.ts` (PRD §29 #11 / #12).');
  lines.push('> Source: EVENT_PACKET_MAP + three mandated-event data sources.');
  lines.push('> Encoding: UTF-8 (strict); source-title mojibake is repaired on write.');
  lines.push('');
  lines.push('## Scope');
  lines.push('');
  lines.push(
    'Event families are derived from `eventSubType` across three sources (deduped):',
  );
  lines.push('');
  lines.push('- `src/policy/data/regulatoryEvents.ts`');
  lines.push('- `src/policy/data/mandatedEventsExpanded.ts`');
  lines.push('- `src/policy/data/multiYearEvents.ts`');
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|---|---:|');
  lines.push(`| Distinct source families | ${sourceFamilies.size} |`);
  lines.push(`| Map entries | ${EVENT_PACKET_MAP.length} |`);
  lines.push(`| status = resolved | ${resolved.length} |`);
  lines.push(`| status = needs-review | ${needsReview.length} |`);
  lines.push(`| status = gap | ${gaps.length} |`);
  lines.push(`| Unmapped (missing entirely) | ${unmapped.length} |`);
  lines.push('');

  lines.push('## Per-family coverage');
  lines.push('');
  lines.push('| Family | Title | Archetype | Template | Workflow | Status |');
  lines.push('|---|---|---|---|---|---|');

  for (const d of EVENT_PACKET_MAP) {
    const templates = templatesForEventFamily(d.eventFamilyId)
      .map((t) => t.packet_template_id)
      .join(', ');
    const templateCell = templates || '—';
    const workflowCell = d.canonicalWorkflowId || '—';
    lines.push(
      `| ${escapeCell(d.eventFamilyId)} | ${escapeCell(d.eventTitle)} | ${escapeCell(d.archetypeId)} | ${escapeCell(templateCell)} | ${escapeCell(workflowCell)} | ${escapeCell(d.status)} |`,
    );
  }
  lines.push('');

  lines.push('## UNRESOLVED / GAP');
  lines.push('');
  lines.push(
    'Explicit gap and needs-review entries (PRD §29 #11 mapping coverage + §29 #12 unresolved workflow/form/event gap report). Uncertain mappings are never silently resolved.',
  );
  lines.push('');

  if (unmapped.length > 0) {
    lines.push('### Unmapped families (missing entirely — FAIL)');
    lines.push('');
    for (const id of unmapped) {
      lines.push(`- \`${id}\``);
    }
    lines.push('');
  } else {
    lines.push('### Unmapped families (missing entirely)');
    lines.push('');
    lines.push('_None — every distinct source family has a map entry (resolved, needs-review, or gap)._');
    lines.push('');
  }

  if (unresolved.length === 0) {
    lines.push('### needs-review and gap entries');
    lines.push('');
    lines.push('_None._');
    lines.push('');
  } else {
    lines.push('### needs-review and gap entries');
    lines.push('');
    lines.push('| Family | Status | Workflow | gapReason |');
    lines.push('|---|---|---|---|');
    for (const d of unresolved) {
      lines.push(
        `| ${escapeCell(d.eventFamilyId)} | ${escapeCell(d.status)} | ${escapeCell(d.canonicalWorkflowId || '—')} | ${escapeCell(d.gapReason ?? '')} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push(
    '- `resolved` requires a `canonicalWorkflowId` present in `WORKFLOWS` and does not retain unresolvable form ids.',
  );
  lines.push(
    '- Form ids must resolve against `FORMS_CATALOG` and/or `FORMS_DATASET`; unknown ids force `needs-review` with reason.',
  );
  lines.push(
    '- Family `qapi_meeting` is compatible with templates `qapi-quarterly` and `qapi-monthly` (shared `eventSubType`; archetype `analytical-report`).',
  );
  lines.push(
    '- Final retention periods remain open decision PRD §28 #7 and are disclosed on every entry.',
  );
  lines.push(
    '- Personnel/credentialing/HR/competency/personnel-review families use restricted aggregate-only confidentiality rules (PRD §13.4 / §20.2), classified by family semantics not archetype alone.',
  );
  lines.push('');

  return { markdown: lines.join('\n'), unmapped };
}

function main(): void {
  const { markdown, unmapped } = buildReport();
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, '..', 'docs', 'packets', 'COVERAGE_REPORT.md');
  mkdirSync(dirname(outPath), { recursive: true });
  // Strict UTF-8 write (no BOM). Buffer ensures binary-clean encoding on Windows.
  writeFileSync(outPath, Buffer.from(markdown, UTF8));
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath} (UTF-8)`);
  // eslint-disable-next-line no-console
  console.log(
    `Map entries: ${EVENT_PACKET_MAP.length}; unmapped: ${unmapped.length}; unresolved/gap: ${listUnresolvedOrGapEntries().length}`,
  );

  if (unmapped.length > 0) {
    // eslint-disable-next-line no-console
    console.error(
      `FAIL: ${unmapped.length} event famil(ies) unmapped (missing entirely): ${unmapped.join(', ')}`,
    );
    process.exit(1);
  }
}

main();
