/**
 * Mapping coverage report generator — PRD §29 #11 / #12.
 *
 * Walks EVENT_PACKET_MAP, writes docs/packets/COVERAGE_REPORT.md with:
 * - per-family table (family, title, archetype, template, workflow, status)
 * - totals
 * - explicit UNRESOLVED/GAP section
 *
 * Exits non-zero if any distinct event family from the three sources
 * is missing entirely from the map (unmapped). Gap/needs-review entries
 * are reported but do not fail the exit code by themselves.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { RegulatoryEvent } from '../src/policy/data/regulatoryEvents';
import { REGULATORY_EVENTS } from '../src/policy/data/regulatoryEvents';
import { MANDATED_EVENTS_EXPANDED } from '../src/policy/data/mandatedEventsExpanded';
import { MULTI_YEAR_EVENTS } from '../src/policy/data/multiYearEvents';
import {
  EVENT_PACKET_MAP,
  listUnresolvedOrGapEntries,
} from '../src/policy/packets/registries/eventPacketMap';
import { templatesForEventFamily } from '../src/policy/packets/registries/templateRegistry';

function distinctFamiliesFromSources(): Set<string> {
  const families = new Set<string>();
  const sources: readonly (readonly RegulatoryEvent[])[] = [
    REGULATORY_EVENTS,
    MANDATED_EVENTS_EXPANDED,
    MULTI_YEAR_EVENTS,
  ];
  for (const src of sources) {
    for (const e of src) {
      if (e.eventSubType) families.add(e.eventSubType);
    }
  }
  return families;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function buildReport(): { markdown: string; unmapped: string[] } {
  const sourceFamilies = distinctFamiliesFromSources();
  const mappedIds = new Set(EVENT_PACKET_MAP.map((d) => d.eventFamilyId));
  const unmapped = [...sourceFamilies].filter((id) => !mappedIds.has(id)).sort();

  const resolved = EVENT_PACKET_MAP.filter((d) => d.status === 'resolved');
  const needsReview = EVENT_PACKET_MAP.filter((d) => d.status === 'needs-review');
  const gaps = EVENT_PACKET_MAP.filter((d) => d.status === 'gap');
  const unresolved = listUnresolvedOrGapEntries();

  const generatedAt = new Date().toISOString();

  const lines: string[] = [];
  lines.push('# Packet Mapping Coverage Report');
  lines.push('');
  lines.push('> Generated by `scripts/reportPacketCoverage.ts` (PRD §29 #11 / #12).');
  lines.push(`> Generated at: ${generatedAt}`);
  lines.push('');
  lines.push('## Scope');
  lines.push('');
  lines.push(
    'Event families are derived from `eventSubType` across three sources (deduped):',
  );
  lines.push('');
  lines.push('- `src/policy/data/regulatoryEvents.ts`');
  lines.push('- `src/policy/data/mandatedEventsExpanded.ts`');
  lines.push('- `src/policy/data/multiYearEvents.ts`');
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|---|---:|');
  lines.push(`| Distinct source families | ${sourceFamilies.size} |`);
  lines.push(`| Map entries | ${EVENT_PACKET_MAP.length} |`);
  lines.push(`| status = resolved | ${resolved.length} |`);
  lines.push(`| status = needs-review | ${needsReview.length} |`);
  lines.push(`| status = gap | ${gaps.length} |`);
  lines.push(`| Unmapped (missing entirely) | ${unmapped.length} |`);
  lines.push('');

  lines.push('## Per-family coverage');
  lines.push('');
  lines.push('| Family | Title | Archetype | Template | Workflow | Status |');
  lines.push('|---|---|---|---|---|---|');

  for (const d of EVENT_PACKET_MAP) {
    const templates = templatesForEventFamily(d.eventFamilyId)
      .map((t) => t.packet_template_id)
      .join(', ');
    const templateCell = templates || '—';
    const workflowCell = d.canonicalWorkflowId || '—';
    lines.push(
      `| ${escapeCell(d.eventFamilyId)} | ${escapeCell(d.eventTitle)} | ${escapeCell(d.archetypeId)} | ${escapeCell(templateCell)} | ${escapeCell(workflowCell)} | ${escapeCell(d.status)} |`,
    );
  }
  lines.push('');

  lines.push('## UNRESOLVED / GAP');
  lines.push('');
  lines.push(
    'Explicit gap and needs-review entries (PRD §29 #11 mapping coverage + §29 #12 unresolved workflow/form/event gap report). Uncertain mappings are never silently resolved.',
  );
  lines.push('');

  if (unmapped.length > 0) {
    lines.push('### Unmapped families (missing entirely — FAIL)');
    lines.push('');
    for (const id of unmapped) {
      lines.push(`- \`${id}\``);
    }
    lines.push('');
  } else {
    lines.push('### Unmapped families (missing entirely)');
    lines.push('');
    lines.push('_None — every distinct source family has a map entry (resolved, needs-review, or gap)._');
    lines.push('');
  }

  if (unresolved.length === 0) {
    lines.push('### needs-review and gap entries');
    lines.push('');
    lines.push('_None._');
    lines.push('');
  } else {
    lines.push('### needs-review and gap entries');
    lines.push('');
    lines.push('| Family | Status | Workflow | gapReason |');
    lines.push('|---|---|---|---|');
    for (const d of unresolved) {
      lines.push(
        `| ${escapeCell(d.eventFamilyId)} | ${escapeCell(d.status)} | ${escapeCell(d.canonicalWorkflowId || '—')} | ${escapeCell(d.gapReason ?? '')} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push(
    '- `resolved` requires a `canonicalWorkflowId` present in `WORKFLOWS` and does not retain unresolvable form ids.',
  );
  lines.push(
    '- Form ids must resolve against `FORMS_CATALOG` and/or `FORMS_DATASET`; unknown ids force `needs-review` with reason.',
  );
  lines.push(
    '- Family `qapi_meeting` is compatible with templates `qapi-quarterly` and `qapi-monthly` (shared `eventSubType`; archetype `analytical-report`).',
  );
  lines.push(
    '- Final retention periods remain open decision PRD §28 #7 and are disclosed on every entry.',
  );
  lines.push('');

  return { markdown: lines.join('\n'), unmapped };
}

function main(): void {
  const { markdown, unmapped } = buildReport();
  const here = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(here, '..', 'docs', 'packets', 'COVERAGE_REPORT.md');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, markdown, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outPath}`);
  // eslint-disable-next-line no-console
  console.log(
    `Map entries: ${EVENT_PACKET_MAP.length}; unmapped: ${unmapped.length}; unresolved/gap: ${listUnresolvedOrGapEntries().length}`,
  );

  if (unmapped.length > 0) {
    // eslint-disable-next-line no-console
    console.error(
      `FAIL: ${unmapped.length} event famil(ies) unmapped (missing entirely): ${unmapped.join(', ')}`,
    );
    process.exit(1);
  }
}

main();
