import type { EventTemplate, TemplateStep, TemplateForm } from './types';

/* ═══════════════════════════════════════════════════════════════
   Template Registry
   ----------------------------------------------------------------
   Reusable templates that cover every regulatorily-required
   recurring meeting, review, and cycle for a Medicare-certified
   home health agency. Templates use the actual RegulatoryEvent
   type system (full-name domains, Title-Case cadences).
   ═══════════════════════════════════════════════════════════════ */

/** Mini-helper so the registry stays compact but strictly-typed. */
const step = (s: TemplateStep): TemplateStep => s;
const form = (f: TemplateForm): TemplateForm => f;

export const TEMPLATE_REGISTRY: EventTemplate[] = [
  /* ── Governance ───────────────────────────────────── */
  {
    id: 'TPL-GV-QUARTERLY-GB',
    title: 'Governing Body Meeting',
    domain: 'Governance',
    category: 'board',
    cadence: 'Quarterly',
    regulatoryDriver: 'CoP §484.105 Governing Body',
    policyRefs: ['GV-GB-001'],
    owner: 'Board Chair',
    ownerRole: 'Governing Body',
    urgency: 'scheduled',
    summary: 'Quarterly oversight meeting covering QAPI, compliance, financial, clinical quality, and strategic risk.',
    recurrence: { frequency: 'quarterly', quarterMonths: [1, 4, 7, 10], nth: 2, dayOfWeek: 5, time: '10:00', timeEnd: '12:00' }, // second Friday 10am per schedule alignment (QAPI governance)
    preferredScheduleRule: 'second Friday of January, April, July, October at 10:00 AM',
    scopeType: 'previous_calendar_quarter',
    processFlow: [
      step({ id: 'gb-prep',    label: 'Prepare board packet',      description: 'Assemble QAPI summary, financials, compliance dashboard, clinical quality report.', dueOffsetDays: -7 }),
      step({ id: 'gb-notice',  label: 'Distribute meeting notice', description: 'Send packet + agenda to all board members.', dueOffsetDays: -5 }),
      step({ id: 'gb-meeting', label: 'Hold meeting',              description: 'Convene quorum; capture motions and resolutions.', dueOffsetDays:  0 }),
      step({ id: 'gb-minutes', label: 'Draft, circulate, finalize minutes', description: 'Produce draft minutes within 5 business days; circulate for sign-off.', dueOffsetDays:  5 }),
      step({ id: 'gb-file',    label: 'File signed minutes',       description: 'File signed minutes and the action-item register.', dueOffsetDays:  7 }),
    ],
    requiredForms: [
      form({ id: 'gb-agenda',    label: 'Board Agenda',                    formId: 'FRM-GV-001' }),
      form({ id: 'gb-packet',    label: 'Board Packet',                    formId: 'FRM-GV-002' }),
      form({ id: 'gb-attest',    label: 'Conflict of Interest Attestation', formId: 'FRM-GV-003' }),
      form({ id: 'gb-minutes-f', label: 'Signed Meeting Minutes',          formId: 'FRM-GV-004' }),
    ],
    minutes: {
      dueOffsetDays: 10,
      requiredSections: ['Attendance & Quorum', 'Call to Order', 'Approval of Prior Minutes', 'QAPI Report', 'Compliance Report', 'Financial Report', 'Clinical Quality Report', 'Risk & Safety Report', 'New Business', 'Resolutions & Action Items', 'Adjournment'],
      signOffRoles: ['Board Chair', 'Board Secretary'],
    },
    approvals: [
      { id: 'gb-rule-minutes', targetKind: 'minutes', targetLabel: 'Governing Body meeting minutes', approverRole: 'Board Chair', escalateToRole: 'Governing Body', required: true, escalationDays: 7 },
      { id: 'gb-rule-event',   targetKind: 'event',   targetLabel: 'Close Governing Body meeting',    approverRole: 'Board Chair', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: 'CoP §484.105(b)', auditRisk: 'critical', overdueAfterDays: 7 },
    followUps: [
      { id: 'gb-fu-actions', label: 'Complete all Board action items', ownerRole: 'Administrator', dueOffsetDays: 60, closureCriteria: 'All action items signed off by owners', escalationDays: 14 },
    ],
    dependencies: { dependsOn: ['TPL-QA-MONTHLY-QAPI'], feeds: [] },
  },

  {
    id: 'TPL-GV-ANNUAL-COI',
    title: 'Annual Conflict of Interest Disclosure Cycle',
    domain: 'Governance',
    category: 'compliance-cycle',
    cadence: 'Annual',
    regulatoryDriver: 'CoP §484.105(c); 42 CFR §424.516',
    policyRefs: ['GV-GB-003'],
    owner: 'Board Secretary',
    ownerRole: 'Board Secretary',
    urgency: 'scheduled',
    summary: 'Board + executive conflict-of-interest disclosures compiled into register for Governing Body review.',
    recurrence: { frequency: 'annual', anchorMonth: 1, dayOfMonth: 15, time: '09:00' },
    processFlow: [
      step({ id: 'coi-distribute', label: 'Distribute disclosure forms', description: 'Send COI disclosure forms to board + executives.', dueOffsetDays: -14 }),
      step({ id: 'coi-collect',    label: 'Collect signed disclosures',  description: 'Track collection; follow-up on outstanding.',     dueOffsetDays:  -1 }),
      step({ id: 'coi-register',   label: 'Update conflict register',    description: 'Compile disclosures into register.',                dueOffsetDays:   2 }),
      step({ id: 'coi-review',     label: 'Board review',                description: 'Governing Body reviews register at next meeting.', dueOffsetDays:  30 }),
    ],
    requiredForms: [
      form({ id: 'coi-form',     label: 'Signed COI Disclosure', formId: 'FRM-GV-003' }),
      form({ id: 'coi-register', label: 'Conflict Register',     formId: 'FRM-GV-005' }),
    ],
    approvals: [
      { id: 'coi-rule-event', targetKind: 'event', targetLabel: 'Close COI cycle', approverRole: 'Board Chair', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: 'CoP §484.105(c)', auditRisk: 'high', overdueAfterDays: 14 },
  },

  /* ── QAPI ─────────────────────────────────────────── */
  {
    id: 'TPL-QA-MONTHLY-QAPI',
    title: 'QAPI Committee Meeting',
    domain: 'QAPI',
    category: 'committee',
    cadence: 'Monthly',
    regulatoryDriver: 'CoP §484.65 QAPI',
    policyRefs: ['QA-PI-001'],
    owner: 'QAPI Coordinator',
    ownerRole: 'QAPI Coordinator',
    urgency: 'scheduled',
    summary: 'Monthly QAPI committee — OASIS outcomes, adverse events, PIP progress, Governing Body packet.',
    recurrence: { frequency: 'monthly', dayOfWeek: 5, nth: 1, time: '10:00', timeEnd: '12:00' }, // first Friday 10am per schedule alignment
    preferredScheduleRule: 'first Friday of the month at 10:00 AM',
    scopeType: 'previous_calendar_month',
    processFlow: [
      step({ id: 'qapi-data',    label: 'Pull metrics',         description: 'Pull OASIS, HHVBP, clinical quality metrics.', dueOffsetDays: -4 }),
      step({ id: 'qapi-packet',  label: 'Assemble QAPI packet', description: 'Compile metrics, PIP status, incident trends into packet.', dueOffsetDays: -2 }),
      step({ id: 'qapi-meeting', label: 'Hold committee meeting', description: 'Convene QAPI committee; review + decide on actions.',    dueOffsetDays:  0 }),
      step({ id: 'qapi-minutes', label: 'Finalize minutes',     description: 'Finalize minutes with required sections + sign-offs.',    dueOffsetDays:  3 }),
      step({ id: 'qapi-feed',    label: 'Package GB summary',   description: 'Produce summary deck for next Governing Body meeting.',   dueOffsetDays:  5 }),
    ],
    requiredForms: [
      form({ id: 'qapi-agenda',  label: 'QAPI Agenda',          formId: 'FRM-QA-001' }),
      form({ id: 'qapi-report',  label: 'QAPI Metrics Report',  formId: 'FRM-QA-002' }),
      form({ id: 'qapi-pip',     label: 'Active PIP Status',    formId: 'FRM-QA-003' }),
      form({ id: 'qapi-minutes', label: 'QAPI Meeting Minutes', formId: 'FRM-QA-004' }),
    ],
    minutes: {
      dueOffsetDays: 5,
      requiredSections: ['Attendance', 'Review of Prior Actions', 'OASIS / Outcomes Review', 'Adverse Events & Trends', 'Active PIPs', 'Infection Control Summary', 'Risk & Safety Summary', 'Decisions & Action Items'],
      signOffRoles: ['QAPI Committee Chair'],
    },
    approvals: [
      { id: 'qapi-rule-minutes', targetKind: 'minutes', targetLabel: 'QAPI Minutes', approverRole: 'QAPI Committee Chair', required: true, escalationDays: 5 },
      { id: 'qapi-rule-event',   targetKind: 'event',   targetLabel: 'Close QAPI meeting', approverRole: 'QAPI Committee Chair', required: true, escalationDays: 7 },
    ],
    complianceFlags: { citation: 'CoP §484.65', auditRisk: 'critical', overdueAfterDays: 5 },
    followUps: [
      { id: 'qapi-fu', label: 'Execute QAPI action items', ownerRole: 'QAPI Coordinator', dueOffsetDays: 30, closureCriteria: 'All action items closed or carried forward', escalationDays: 10 },
    ],
    dependencies: { dependsOn: ['TPL-CL-MONTHLY-AUDIT'], feeds: ['TPL-GV-QUARTERLY-GB'] },
  },

  /* ── Clinical ─────────────────────────────────────── */
  {
    id: 'TPL-CL-MONTHLY-AUDIT',
    title: 'Monthly Clinical Record Audit',
    domain: 'Clinical',
    category: 'audit',
    cadence: 'Monthly',
    regulatoryDriver: 'CoP §484.110 Clinical Records',
    policyRefs: ['CL-OA-006'],
    owner: 'Director of Nursing',
    ownerRole: 'Director of Nursing',
    urgency: 'scheduled',
    summary: 'Statistical sample of clinical records audited for completeness, signature, frequency, and order accuracy.',
    recurrence: { frequency: 'monthly', dayOfMonth: 20, time: '10:00', timeEnd: '12:00' },
    processFlow: [
      step({ id: 'cl-sample',   label: 'Draw statistical sample', description: 'Pull representative sample using audit rubric.', dueOffsetDays: -3 }),
      step({ id: 'cl-audit',    label: 'Audit against checklist', description: 'Reviewer scores each chart against the audit checklist.', dueOffsetDays:  0 }),
      step({ id: 'cl-findings', label: 'Document findings',       description: 'Capture findings and required corrective actions.', dueOffsetDays:  3 }),
      step({ id: 'cl-feed',     label: 'Feed summary to QAPI',    description: 'Publish summary for QAPI packet.', dueOffsetDays:  5 }),
    ],
    requiredForms: [
      form({ id: 'cl-checklist', label: 'Audit Checklist',     formId: 'FRM-CL-010' }),
      form({ id: 'cl-summary',   label: 'Audit Summary Report', formId: 'FRM-CL-011' }),
    ],
    approvals: [
      { id: 'cl-rule-event', targetKind: 'event', targetLabel: 'Close record audit', approverRole: 'Director of Nursing', required: true, escalationDays: 7 },
    ],
    complianceFlags: { citation: 'CoP §484.110', auditRisk: 'high', overdueAfterDays: 7 },
    dependencies: { feeds: ['TPL-QA-MONTHLY-QAPI'] },
  },

  {
    id: 'TPL-CL-WEEKLY-PHYSIGN',
    title: 'Physician Signature Tracking',
    domain: 'Clinical',
    category: 'tracking',
    cadence: 'Weekly',
    regulatoryDriver: 'CoP §484.60 Care Planning',
    policyRefs: ['CL-OA-007'],
    owner: 'Clinical Director',
    ownerRole: 'Clinical Director',
    urgency: 'scheduled',
    summary: 'Track outstanding physician signatures on plan of care, orders, and certifications.',
    recurrence: { frequency: 'weekly', dayOfWeek: 2, time: '09:00', timeEnd: '10:00' },
    processFlow: [
      step({ id: 'sig-pull',     label: 'Pull outstanding-signature report', description: 'Run outstanding signature report from EMR.', dueOffsetDays: 0 }),
      step({ id: 'sig-outreach', label: 'Physician outreach',                 description: 'Contact physicians for outstanding signatures.', dueOffsetDays: 2 }),
      step({ id: 'sig-log',      label: 'Log outreach',                       description: 'Document outreach attempts and outcomes.',      dueOffsetDays: 4 }),
    ],
    requiredForms: [
      form({ id: 'sig-report', label: 'Outstanding Signature Report', formId: 'FRM-CL-020' }),
    ],
    complianceFlags: { citation: 'CoP §484.60', auditRisk: 'medium', overdueAfterDays: 5 },
  },

  /* ── Compliance ───────────────────────────────────── */
  {
    id: 'TPL-CO-MONTHLY-REPORT',
    title: 'Monthly Compliance Report',
    domain: 'Compliance',
    category: 'report',
    cadence: 'Monthly',
    regulatoryDriver: '42 CFR §483.85',
    policyRefs: ['CO-CP-001'],
    owner: 'Compliance Officer',
    ownerRole: 'Compliance Officer',
    urgency: 'scheduled',
    summary: 'Monthly compliance report — hotline activity, investigations, training status, policy exceptions, trend summary.',
    recurrence: { frequency: 'monthly', dayOfMonth: 10, time: '09:00', timeEnd: '10:00' },
    processFlow: [
      step({ id: 'co-gather',  label: 'Gather data',    description: 'Collect hotline, investigation, training, exception data.', dueOffsetDays: -3 }),
      step({ id: 'co-report',  label: 'Draft report',   description: 'Draft compliance report narrative + KPIs.',                  dueOffsetDays: -1 }),
      step({ id: 'co-deliver', label: 'Deliver report', description: 'Deliver to Administrator + Governing Body.',                  dueOffsetDays:  0 }),
    ],
    requiredForms: [
      form({ id: 'co-report-form', label: 'Compliance Report', formId: 'FRM-CO-001' }),
    ],
    approvals: [
      { id: 'co-rule-event', targetKind: 'event', targetLabel: 'Close compliance report', approverRole: 'Compliance Officer', required: true, escalationDays: 5 },
    ],
    complianceFlags: { citation: '42 CFR §483.85', auditRisk: 'high', overdueAfterDays: 5 },
    dependencies: { feeds: ['TPL-GV-QUARTERLY-GB'] },
  },

  {
    id: 'TPL-CO-ANNUAL-EFFECTIVENESS',
    title: 'Annual Compliance Program Effectiveness Review',
    domain: 'Compliance',
    category: 'assessment',
    cadence: 'Annual',
    regulatoryDriver: 'OIG Compliance Guidance; 42 CFR §483.85',
    policyRefs: ['CO-CP-002'],
    owner: 'Compliance Officer',
    ownerRole: 'Compliance Officer',
    urgency: 'scheduled',
    summary: 'Evaluate the seven elements of the compliance program against OIG guidance.',
    recurrence: { frequency: 'annual', anchorMonth: 10, dayOfMonth: 15, time: '13:00', timeEnd: '15:00' },
    processFlow: [
      step({ id: 'co-ef-survey',  label: 'Workforce survey',   description: 'Distribute workforce compliance survey.', dueOffsetDays: -30 }),
      step({ id: 'co-ef-analyze', label: 'Analyze KPIs',       description: 'Analyze seven-element effectiveness KPIs.', dueOffsetDays:  -7 }),
      step({ id: 'co-ef-report',  label: 'Produce report',     description: 'Publish effectiveness report.',             dueOffsetDays:   0 }),
      step({ id: 'co-ef-present', label: 'Present to Board',    description: 'Present results at next Governing Body.',   dueOffsetDays:  30 }),
    ],
    requiredForms: [
      form({ id: 'co-ef-survey-f', label: 'Workforce Compliance Survey', formId: 'FRM-CO-010' }),
      form({ id: 'co-ef-report-f', label: 'Effectiveness Report',        formId: 'FRM-CO-011' }),
    ],
    approvals: [
      { id: 'co-ef-rule-event', targetKind: 'event', targetLabel: 'Approve effectiveness report', approverRole: 'Board Chair', required: true, escalationDays: 14 },
    ],
    complianceFlags: { citation: 'OIG Compliance Guidance', auditRisk: 'critical', overdueAfterDays: 30 },
  },

  /* ── IT / Security ────────────────────────────────── */
  {
    id: 'TPL-IT-QUARTERLY-VULN',
    title: 'Quarterly Vulnerability Scan',
    domain: 'IT/Security',
    category: 'security-scan',
    cadence: 'Quarterly',
    regulatoryDriver: 'HIPAA §164.308(a)(1)(ii)(A)',
    policyRefs: ['IT-SC-001'],
    owner: 'Information Security Officer',
    ownerRole: 'Information Security Officer',
    urgency: 'scheduled',
    summary: 'Authenticated vulnerability scan of ePHI systems; findings logged, remediated, and reported.',
    recurrence: { frequency: 'quarterly', quarterMonths: [3, 6, 9, 12], dayOfMonth: 10, time: '09:00', timeEnd: '12:00' },
    processFlow: [
      step({ id: 'vm-scan',      label: 'Run scan',       description: 'Run authenticated scan against ePHI systems.', dueOffsetDays:  0 }),
      step({ id: 'vm-triage',    label: 'Triage findings', description: 'Categorize findings by severity.',              dueOffsetDays:  3 }),
      step({ id: 'vm-remediate', label: 'Remediate',       description: 'Remediate critical + high findings.',            dueOffsetDays: 14 }),
      step({ id: 'vm-report',    label: 'Report to QAPI',  description: 'Publish summary + trend report to QAPI.',        dueOffsetDays: 21 }),
    ],
    requiredForms: [
      form({ id: 'vm-scan-f', label: 'Scan Results Export', formId: 'FRM-IS-010' }),
      form({ id: 'vm-rem-f',  label: 'Remediation Tracker', formId: 'FRM-IS-011' }),
    ],
    approvals: [
      { id: 'vm-rule-event', targetKind: 'event', targetLabel: 'Close vulnerability cycle', approverRole: 'Information Security Officer', required: true, escalationDays: 21 },
    ],
    complianceFlags: { citation: 'HIPAA §164.308', auditRisk: 'critical', overdueAfterDays: 14 },
    dependencies: { feeds: ['TPL-QA-MONTHLY-QAPI'] },
  },

  /* ── Operations ───────────────────────────────────── */
  {
    id: 'TPL-OP-ANNUAL-EP',
    title: 'Annual Emergency Preparedness Full-Scale Exercise',
    domain: 'Operations',
    category: 'drill',
    cadence: 'Annual',
    regulatoryDriver: 'CoP §484.102 Emergency Preparedness',
    policyRefs: ['OP-FM-005'],
    owner: 'Administrator',
    ownerRole: 'Administrator',
    urgency: 'scheduled',
    summary: 'Full-scale EP exercise — mass casualty, loss of power, cybersecurity event, or weather scenario.',
    recurrence: { frequency: 'annual', anchorMonth: 9, dayOfMonth: 20, time: '08:00', timeEnd: '13:00' },
    processFlow: [
      step({ id: 'ep-plan',    label: 'Plan scenario',     description: 'Scenario + objectives plan.',                dueOffsetDays: -30 }),
      step({ id: 'ep-invite',  label: 'Invite partners',   description: 'Invite community partners and regulators.',  dueOffsetDays: -21 }),
      step({ id: 'ep-run',     label: 'Run exercise',      description: 'Conduct full-scale exercise with evaluators.', dueOffsetDays:   0 }),
      step({ id: 'ep-debrief', label: 'Hot-wash / AAR',     description: 'Debrief; produce after-action report.',      dueOffsetDays:   5 }),
      step({ id: 'ep-update',  label: 'Update EP plan',     description: 'Incorporate findings into EP plan.',           dueOffsetDays:  30 }),
    ],
    requiredForms: [
      form({ id: 'ep-plan-f',    label: 'Exercise Plan',      formId: 'FRM-OP-020' }),
      form({ id: 'ep-aar',       label: 'After-Action Report', formId: 'FRM-OP-021' }),
      form({ id: 'ep-updates-f', label: 'Plan Revision',      formId: 'FRM-OP-022' }),
    ],
    approvals: [
      { id: 'ep-rule-event', targetKind: 'event', targetLabel: 'Sign off EP exercise', approverRole: 'Administrator', required: true, escalationDays: 14 },
    ],
    complianceFlags: { citation: 'CoP §484.102', auditRisk: 'critical', overdueAfterDays: 30 },
  },

  /* ── Finance / Billing ────────────────────────────── */
  {
    id: 'TPL-FN-WEEKLY-CLAIMS',
    title: 'Weekly Claims Submission Cycle',
    domain: 'Finance',
    category: 'revenue-cycle',
    cadence: 'Weekly',
    regulatoryDriver: 'Medicare Claims Processing Manual',
    policyRefs: ['FN-BC-001'],
    owner: 'Revenue Cycle Director',
    ownerRole: 'Revenue Cycle Director',
    urgency: 'scheduled',
    summary: 'Weekly Medicare / Medicaid claims file submission and 835 reconciliation.',
    recurrence: { frequency: 'weekly', dayOfWeek: 3, time: '09:00', timeEnd: '11:00' },
    processFlow: [
      step({ id: 'cl-prep',        label: 'Pre-bill scrub',      description: 'Pre-bill scrub against edits.', dueOffsetDays: -1 }),
      step({ id: 'cl-submit',      label: 'Submit claims',       description: 'Submit claims file to MAC / MCO.', dueOffsetDays:  0 }),
      step({ id: 'cl-acknowledge', label: 'Acknowledge 277CA',   description: 'Acknowledge 277CA and action rejections.', dueOffsetDays:  1 }),
      step({ id: 'cl-reconcile',   label: 'Reconcile 835',       description: 'Reconcile 835 and post cash.', dueOffsetDays:  5 }),
    ],
    requiredForms: [
      form({ id: 'cl-log', label: 'Claims Submission Log', formId: 'FRM-FN-010' }),
    ],
    complianceFlags: { citation: 'CMS Pub 100-04', auditRisk: 'high', overdueAfterDays: 3 },
  },

  /* ── Risk & Safety ────────────────────────────────── */
  {
    id: 'TPL-RM-MONTHLY-IC',
    title: 'Monthly Infection Control Review',
    domain: 'Risk',
    category: 'surveillance',
    cadence: 'Monthly',
    regulatoryDriver: 'CoP §484.70 Infection Prevention',
    policyRefs: ['RM-ER-001'],
    owner: 'Risk Manager',
    ownerRole: 'Risk Manager',
    urgency: 'scheduled',
    summary: 'Infection surveillance data review, trend analysis, and QAPI feed.',
    recurrence: { frequency: 'monthly', dayOfMonth: 18, time: '10:00', timeEnd: '11:00' },
    processFlow: [
      step({ id: 'ic-pull',    label: 'Pull infection logs', description: 'Pull infection logs from clinical systems.', dueOffsetDays: -2 }),
      step({ id: 'ic-analyze', label: 'Trend analysis',      description: 'Analyze trends and anomalies.',              dueOffsetDays:  0 }),
      step({ id: 'ic-qapi',    label: 'Feed QAPI',           description: 'Publish summary + trend packet to QAPI.',    dueOffsetDays:  3 }),
    ],
    requiredForms: [
      form({ id: 'ic-log',     label: 'Infection Log',  formId: 'FRM-RM-010' }),
      form({ id: 'ic-summary', label: 'Trend Summary',  formId: 'FRM-RM-011' }),
    ],
    complianceFlags: { citation: 'CoP §484.70', auditRisk: 'high', overdueAfterDays: 5 },
    dependencies: { feeds: ['TPL-QA-MONTHLY-QAPI'] },
  },

  /* ── HR / Training ────────────────────────────────── */
  {
    id: 'TPL-HR-ANNUAL-OSHA-BBP',
    title: 'Annual OSHA Bloodborne Pathogen Training',
    domain: 'Operations',
    category: 'training',
    cadence: 'Annual',
    regulatoryDriver: '29 CFR §1910.1030',
    policyRefs: ['HR-TD-001'],
    owner: 'HR Training Coordinator',
    ownerRole: 'HR Training Coordinator',
    urgency: 'scheduled',
    summary: 'All at-risk workforce members complete annual OSHA BBP training; competency verified.',
    recurrence: { frequency: 'annual', anchorMonth: 3, dayOfMonth: 15, time: '09:00', timeEnd: '11:00' },
    processFlow: [
      step({ id: 'bbp-assign',   label: 'Assign modules',      description: 'Assign training modules to at-risk workforce.', dueOffsetDays: -30 }),
      step({ id: 'bbp-complete', label: 'Workforce completes', description: 'Workforce completes training.',                  dueOffsetDays:   0 }),
      step({ id: 'bbp-verify',   label: 'Verify competency',   description: 'Verify competency + file certificates.',         dueOffsetDays:   7 }),
    ],
    requiredForms: [
      form({ id: 'bbp-roster', label: 'Training Roster',         formId: 'FRM-HR-040' }),
      form({ id: 'bbp-certs',  label: 'Completion Certificates', formId: 'FRM-HR-041' }),
    ],
    approvals: [
      { id: 'bbp-rule-event', targetKind: 'event', targetLabel: 'Close BBP training cycle', approverRole: 'Administrator', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: '29 CFR §1910.1030', auditRisk: 'critical', overdueAfterDays: 14 },
  },

  {
    id: 'TPL-HR-ANNUAL-HIPAA',
    title: 'Annual HIPAA Workforce Training',
    domain: 'Operations',
    category: 'training',
    cadence: 'Annual',
    regulatoryDriver: 'HIPAA §164.530(b)(1)',
    policyRefs: ['HR-TD-002'],
    owner: 'HR Training Coordinator',
    ownerRole: 'HR Training Coordinator',
    urgency: 'scheduled',
    summary: 'All workforce complete annual HIPAA Privacy & Security training.',
    recurrence: { frequency: 'annual', anchorMonth: 4, dayOfMonth: 15, time: '09:00', timeEnd: '10:30' },
    processFlow: [
      step({ id: 'hipaa-assign',   label: 'Assign modules',        description: 'Assign HIPAA modules to workforce.', dueOffsetDays: -30 }),
      step({ id: 'hipaa-complete', label: 'Workforce completes',   description: 'Workforce completes HIPAA training.', dueOffsetDays:   0 }),
      step({ id: 'hipaa-attest',   label: 'Attestations filed',    description: 'File attestations and certificates.',  dueOffsetDays:   5 }),
    ],
    requiredForms: [
      form({ id: 'hipaa-roster',   label: 'Training Roster',        formId: 'FRM-HR-050' }),
      form({ id: 'hipaa-attest-f', label: 'Workforce Attestations', formId: 'FRM-HR-051' }),
    ],
    approvals: [
      { id: 'hipaa-rule-event', targetKind: 'event', targetLabel: 'Close HIPAA training cycle', approverRole: 'Information Security Officer', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: 'HIPAA §164.530(b)(1)', auditRisk: 'critical', overdueAfterDays: 14 },
  },

  {
    id: 'TPL-HR-MONTHLY-OIG',
    title: 'Monthly OIG / SAM Exclusion Check',
    domain: 'Operations',
    category: 'compliance-check',
    cadence: 'Monthly',
    regulatoryDriver: '42 CFR §1001; OIG Special Advisory',
    policyRefs: ['HR-TA-003'],
    owner: 'HR Training Coordinator',
    ownerRole: 'HR Training Coordinator',
    urgency: 'scheduled',
    summary: 'All employees, contractors, and vendors screened against OIG LEIE and SAM.gov.',
    recurrence: { frequency: 'monthly', dayOfMonth: 5, time: '09:00' },
    processFlow: [
      step({ id: 'oig-roster', label: 'Export roster', description: 'Export active employee + vendor roster.', dueOffsetDays: -1 }),
      step({ id: 'oig-check',  label: 'Run checks',     description: 'Run OIG LEIE and SAM.gov checks.',        dueOffsetDays:  0 }),
      step({ id: 'oig-log',    label: 'File screening log', description: 'File exclusion screening log.',       dueOffsetDays:  1 }),
    ],
    requiredForms: [
      form({ id: 'oig-log-f', label: 'Exclusion Screening Log', formId: 'FRM-HR-030' }),
    ],
    complianceFlags: { citation: '42 CFR §1001', auditRisk: 'critical', overdueAfterDays: 3 },
  },

  /* ── New Q1 2026 Blueprint Event Types ───────────────────────────────────── */

  {
    id: 'TPL-GV-ANNUAL-GOVPKT',
    title: 'Annual Governance Packet Review',
    domain: 'Governance',
    category: 'board-annual',
    cadence: 'Annual',
    mandateType: 'federal-required',
    regulatoryDriver: '42 CFR §484.105(b) — Governing Body CoP',
    policyRefs: ['GV-GB-001', 'GV-GB-002'],
    owner: 'Administrator',
    ownerRole: 'Administrator',
    urgency: 'scheduled',
    summary: 'Annual board review of the institutional plan, budget, acceptance-to-service criteria, and public-facing service information.',
    recurrence: { frequency: 'annual', anchorMonth: 1, dayOfMonth: 8, time: '09:00', timeEnd: '11:00' },
    processFlow: [
      step({ id: 'gvpkt-assemble',    label: 'Assemble governance packet',        description: 'Compile annual budget, institutional plan, acceptance-to-service criteria, patient rights notice, and public-facing program information.', dueOffsetDays: -14 }),
      step({ id: 'gvpkt-adminreview', label: 'Administrator pre-review',           description: 'Review packet for accuracy and regulatory alignment; annotate required changes.', dueOffsetDays: -7 }),
      step({ id: 'gvpkt-boardvote',   label: 'Governing Body review and vote',     description: 'Convene quorum; board reviews each document and votes to approve.', dueOffsetDays: 0 }),
      step({ id: 'gvpkt-minutes',     label: 'Draft, circulate, finalize minutes', description: 'Record motions, approvals, and action items.', dueOffsetDays: 5 }),
      step({ id: 'gvpkt-file',        label: 'File approved packet',               description: 'Archive signed, version-stamped packet in governance record.', dueOffsetDays: 7 }),
    ],
    requiredForms: [
      form({ id: 'gvpkt-budget',     label: 'Annual Budget (approved)',             formId: 'GV-FM-010' }),
      form({ id: 'gvpkt-instplan',   label: 'Institutional Plan (current year)',    formId: 'GV-FM-011' }),
      form({ id: 'gvpkt-acceptance', label: 'Acceptance-to-Service Criteria',      formId: 'GV-FM-012' }),
      form({ id: 'gvpkt-rights',     label: 'Patient Rights Notice',               formId: 'GV-FM-013' }),
      form({ id: 'gvpkt-minutesdoc', label: 'Governing Body Approval Minutes',     formId: 'GV-FM-002' }),
    ],
    minutes: {
      dueOffsetDays: 7,
      requiredSections: ['Attendance & Quorum', 'Annual Budget Review', 'Institutional Plan Approval', 'Acceptance-to-Service Review', 'Patient Rights & Public Information', 'Resolutions & Approvals', 'Adjournment'],
      signOffRoles: ['Board Chair', 'Board Secretary'],
    },
    approvals: [
      { id: 'gvpkt-rule-budget', targetKind: 'form',  targetLabel: 'Annual Budget', approverRole: 'Board Chair', required: true, escalationDays: 7 },
      { id: 'gvpkt-rule-event',  targetKind: 'event', targetLabel: 'Annual Governance Packet', approverRole: 'Board Chair', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: '42 CFR §484.105(b)', auditRisk: 'critical', overdueAfterDays: 0 },
    dependencies: { feeds: ['TPL-GV-QUARTERLY-GB'] },
  },

  {
    id: 'TPL-OP-BIENNIAL-EP-REVIEW',
    title: 'Biennial Emergency Preparedness Plan Review & Update',
    domain: 'Operations',
    category: 'ep-biennial-review',
    cadence: 'Biennial',
    mandateType: 'federal-required',
    regulatoryDriver: '42 CFR §484.102(a)–(b) — Emergency Preparedness Plan',
    policyRefs: ['OP-FM-005', 'RM-EP-001'],
    owner: 'Administrator',
    ownerRole: 'Administrator',
    urgency: 'scheduled',
    summary: 'Full biennial review and update of all four EP plan elements: risk assessment, EP plan, policies/procedures, and communication plan.',
    recurrence: { frequency: 'biennial', anchorMonth: 1, dayOfMonth: 15, time: '09:00', timeEnd: '12:00' },
    processFlow: [
      step({ id: 'ep-rev-assemble',    label: 'Assemble current EP plan for review',         description: 'Pull current EP plan; flag elements last updated > 2 years.', dueOffsetDays: -14 }),
      step({ id: 'ep-rev-riskassess',  label: 'Review and update risk assessment (HVA)',      description: 'Reassess hazard vulnerability analysis; update probabilities and impact scores.', dueOffsetDays: -7 }),
      step({ id: 'ep-rev-plan',        label: 'Review and update all EP plan elements',       description: 'Update continuity-of-operations, evacuation, shelter-in-place, and communication procedures.', dueOffsetDays: 0 }),
      step({ id: 'ep-rev-approve',     label: 'Administrator approval + version stamp',       description: 'Administrator signs the updated, versioned EP plan.', dueOffsetDays: 5 }),
      step({ id: 'ep-rev-archive',     label: 'Archive versioned plan and distribute',        description: 'File approved plan; distribute to all staff.', dueOffsetDays: 7 }),
    ],
    requiredForms: [
      form({ id: 'ep-rev-hva',    label: 'Hazard Vulnerability Analysis (updated)',       formId: 'RM-FM-001' }),
      form({ id: 'ep-rev-plan-f', label: 'Emergency Preparedness Plan (all 4 elements)', formId: 'RM-F-020' }),
      form({ id: 'ep-rev-polpro', label: 'EP Policies & Procedures',                     formId: 'CL-FM-043' }),
      form({ id: 'ep-rev-comm',   label: 'Communication Plan',                           formId: 'RM-FM-002' }),
      form({ id: 'ep-rev-sig',    label: 'EP Plan Approval Signature Page',              formId: 'EN-FM-008' }),
    ],
    approvals: [
      { id: 'ep-rev-rule-plan',  targetKind: 'form',  targetLabel: 'EP Plan (all 4 elements)', approverRole: 'Administrator', required: true, escalationDays: 7 },
      { id: 'ep-rev-rule-event', targetKind: 'event', targetLabel: 'Biennial EP Plan Review',   approverRole: 'Administrator', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: '42 CFR §484.102(a)–(b)', auditRisk: 'critical', overdueAfterDays: 0 },
    followUps: [
      { id: 'ep-rev-fu-train', label: 'Initiate EP training if plan materially changed', ownerRole: 'Administrator', dueOffsetDays: 30, closureCriteria: 'Training completed or change deemed non-material', escalationDays: 14 },
    ],
  },

  {
    id: 'TPL-OP-BIENNIAL-EP-TRAINING',
    title: 'Biennial Emergency Preparedness Staff Training',
    domain: 'Operations',
    category: 'ep-biennial-training',
    cadence: 'Biennial',
    mandateType: 'federal-required',
    regulatoryDriver: '42 CFR §484.102(c) — Emergency Preparedness Training',
    policyRefs: ['OP-FM-005'],
    owner: 'Administrator',
    ownerRole: 'Administrator',
    urgency: 'scheduled',
    summary: 'Biennial all-staff training on EP policies and procedures. Also triggered when the EP plan has materially changed.',
    recurrence: { frequency: 'biennial', anchorMonth: 1, dayOfMonth: 22, time: '08:00', timeEnd: '12:00' },
    processFlow: [
      step({ id: 'ep-trn-curriculum', label: 'Develop / update training curriculum',  description: 'Update slides to reflect any EP plan changes since last cycle.', dueOffsetDays: -14 }),
      step({ id: 'ep-trn-schedule',   label: 'Schedule sessions and notify staff',    description: 'Schedule all-staff sessions; send mandatory-attendance notices.', dueOffsetDays: -7 }),
      step({ id: 'ep-trn-deliver',    label: 'Deliver training to all staff',         description: 'Deliver training; capture signed attendance rosters.', dueOffsetDays: 0 }),
      step({ id: 'ep-trn-verify',     label: 'Verify 100% completion',                description: 'Cross-reference roster against active staff list; chase gaps.', dueOffsetDays: 7 }),
    ],
    requiredForms: [
      form({ id: 'ep-trn-roster',      label: 'Training Attendance Roster',           formId: 'OP-FM-040' }),
      form({ id: 'ep-trn-curriculum-f',label: 'Training Curriculum / Agenda',         formId: 'OP-FM-041' }),
      form({ id: 'ep-trn-trainer',     label: 'Trainer Credentials / Role Verification', formId: 'OP-FM-042' }),
    ],
    approvals: [
      { id: 'ep-trn-rule-event', targetKind: 'event', targetLabel: 'EP Training Cycle', approverRole: 'Administrator', required: true, escalationDays: 14 },
    ],
    complianceFlags: { citation: '42 CFR §484.102(c)', auditRisk: 'critical', overdueAfterDays: 0 },
  },

  {
    id: 'TPL-QA-QUARTERLY-GOVREVIEW',
    title: 'Quarterly QAPI Governance Review',
    domain: 'QAPI',
    category: 'qapi-quarterly-governance',
    cadence: 'Quarterly',
    mandateType: 'policy-driven',
    regulatoryDriver: '42 CFR §484.65 — QAPI CoP. Quarterly governance review cadence is POLICY-DRIVEN, not a universal federal quarterly mandate. Annual PIP is federally required.',
    policyRefs: ['QA-PI-001', 'QA-PI-002'],
    owner: 'QAPI Coordinator',
    ownerRole: 'QAPI Coordinator',
    urgency: 'scheduled',
    summary: 'Policy-driven quarterly QAPI dashboard review, action log, escalation logic, and report-out to Governing Body. Q1 occurrence initiates the annual PIP.',
    recurrence: { frequency: 'quarterly', quarterMonths: [2, 5, 8, 11], nth: 1, dayOfWeek: 4, time: '13:00', timeEnd: '15:00' },
    processFlow: [
      step({ id: 'qapi-gov-dashboard', label: 'Compile QAPI dashboard',                    description: 'Pull OASIS outcomes, HHVBP metrics, adverse events, hotline, and infection surveillance data.', dueOffsetDays: -5 }),
      step({ id: 'qapi-gov-pip',       label: 'PIP status review (or kickoff in Q1)',       description: 'Q1: establish baseline + PIP charter. Q2–Q4: review active PIP remeasurement.', dueOffsetDays: 0 }),
      step({ id: 'qapi-gov-review',    label: 'QAPI governance review session',             description: 'Review dashboard and action log; assign/close escalations.', dueOffsetDays: 0 }),
      step({ id: 'qapi-gov-report',    label: 'Produce quarterly report-out packet',        description: 'Build QAPI quarterly report for Governing Body (dashboard, PIP, action log).', dueOffsetDays: 5 }),
      step({ id: 'qapi-gov-deliver',   label: 'Deliver to Governing Body',                  description: 'Submit quarterly QAPI report 7 days before next board meeting.', dueOffsetDays: 7 }),
    ],
    requiredForms: [
      form({ id: 'qapi-gov-dash-f',    label: 'QAPI Data Dashboard (quarterly)',        formId: 'QA-FM-020' }),
      form({ id: 'qapi-gov-pip-f',     label: 'Annual PIP Charter / Status Update',    formId: 'QA-FM-021' }),
      form({ id: 'qapi-gov-actionlog', label: 'QAPI Action Item Log',                  formId: 'QA-FM-022' }),
      form({ id: 'qapi-gov-report-f',  label: 'Quarterly QAPI Governance Report',      formId: 'QA-FM-023' }),
    ],
    approvals: [
      { id: 'qapi-gov-rule-pip',   targetKind: 'form',  targetLabel: 'Annual PIP Charter',        approverRole: 'QAPI Committee Chair', required: true, escalationDays: 7 },
      { id: 'qapi-gov-rule-event', targetKind: 'event', targetLabel: 'QAPI Governance Review',    approverRole: 'QAPI Committee Chair', required: true, escalationDays: 7 },
    ],
    complianceFlags: { citation: '42 CFR §484.65 — QAPI CoP', auditRisk: 'high', overdueAfterDays: 0 },
    dependencies: { feeds: ['TPL-GV-QUARTERLY-GB'], dependsOn: ['TPL-QA-MONTHLY-QAPI'] },
  },

  {
    id: 'TPL-CL-ANNUAL-HHA-INSERVICE',
    title: 'Annual Aide In-Service Training Campaign',
    domain: 'Clinical',
    category: 'hha-annual-inservice',
    cadence: 'Annual',
    mandateType: 'federal-required',
    regulatoryDriver: '42 CFR §484.80(b)(3) — Home Health Aide Annual In-Service Training',
    policyRefs: ['CL-SD-006'],
    owner: 'Director of Nursing',
    ownerRole: 'Director of Nursing',
    urgency: 'scheduled',
    summary: 'At least 12 hours of in-service training per aide per calendar year. RN educator supervision required.',
    recurrence: { frequency: 'annual', anchorMonth: 2, dayOfMonth: 9, time: '08:00' },
    allDay: true,
    processFlow: [
      step({ id: 'hha-inserv-plan',    label: 'Develop in-service curriculum (≥12 hrs)',  description: 'Design training covering at least 12 hours; include infection control, patient rights, medication safety, and QAPI-identified topics.', dueOffsetDays: -14 }),
      step({ id: 'hha-inserv-roster',  label: 'Build aide roster and schedule sessions',  description: 'Roster all active aides; schedule sessions to achieve 100% coverage by Feb 20.', dueOffsetDays: -7 }),
      step({ id: 'hha-inserv-deliver', label: 'Deliver all training sessions',            description: 'Conduct sessions; capture signed attendance rosters per session.', dueOffsetDays: 0 }),
      step({ id: 'hha-inserv-verify',  label: 'Verify 12-hr minimum per aide',            description: 'Tally hours per aide; schedule make-ups for anyone below minimum.', dueOffsetDays: 7 }),
      step({ id: 'hha-inserv-file',    label: 'File evidence and RN attestation',         description: 'File signed rosters, curriculum, and RN educator attestation.', dueOffsetDays: 11 }),
    ],
    requiredForms: [
      form({ id: 'hha-inserv-curriculum-f', label: 'In-Service Curriculum (≥12 hrs)',          formId: 'CL-FM-040' }),
      form({ id: 'hha-inserv-roster-f',     label: 'Aide Attendance Roster (all sessions)',    formId: 'CL-FM-041' }),
      form({ id: 'hha-inserv-hours-f',      label: 'Hours Tally per Aide (≥12 hrs verified)', formId: 'CL-FM-042' }),
      form({ id: 'hha-inserv-rnattest',     label: 'RN Educator Attestation',                 formId: 'CL-FM-043' }),
    ],
    approvals: [
      { id: 'hha-inserv-rule-rn',    targetKind: 'form',  targetLabel: 'RN Educator Attestation', approverRole: 'Director of Nursing', required: true, escalationDays: 7 },
      { id: 'hha-inserv-rule-event', targetKind: 'event', targetLabel: 'Annual Aide In-Service',   approverRole: 'Director of Nursing', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: '42 CFR §484.80(b)(3)', auditRisk: 'critical', overdueAfterDays: 0 },
  },

  {
    id: 'TPL-CL-ANNUAL-HHA-SKILLOBS',
    title: 'Annual Skilled-Patient Aide Observation',
    domain: 'Clinical',
    category: 'hha-annual-skilled-obs',
    cadence: 'Annual',
    mandateType: 'federal-required',
    regulatoryDriver: '42 CFR §484.80(h)(1) — Skilled-Patient Aide Annual Observation',
    policyRefs: ['CL-SD-007'],
    owner: 'Director of Nursing',
    ownerRole: 'Director of Nursing',
    urgency: 'scheduled',
    summary: 'Annual in-home observation of aides serving patients who also receive concurrent skilled nursing or therapy. Distinct from semiannual aide-only observation.',
    recurrence: { frequency: 'annual', anchorMonth: 2, dayOfMonth: 25, time: '09:00', timeEnd: '12:00' },
    processFlow: [
      step({ id: 'hha-skillobs-identify',  label: 'Identify skilled + aide patient cohort',  description: 'Pull patients receiving both skilled and aide services; these require annual (not semiannual) observation.', dueOffsetDays: -7 }),
      step({ id: 'hha-skillobs-schedule',  label: 'Schedule and assign RN observers',        description: 'Assign RN to each aide-patient pair; coordinate with field schedule.', dueOffsetDays: -3 }),
      step({ id: 'hha-skillobs-observe',   label: 'Conduct in-home observations',            description: 'RN observes aide in the home using the standard observation form.', dueOffsetDays: 0 }),
      step({ id: 'hha-skillobs-deficiency','label': 'Track deficiencies and corrective actions', description: 'Log deficiencies; assign corrective actions; re-observe if needed.', dueOffsetDays: 3 }),
      step({ id: 'hha-skillobs-file',      label: 'File per-aide records',                   description: 'Archive observation forms and corrective action records in aide personnel files.', dueOffsetDays: 7 }),
    ],
    requiredForms: [
      form({ id: 'hha-skillobs-obsform', label: 'Aide Observation Form (skilled-patient)', formId: 'CL-FM-050' }),
      form({ id: 'hha-skillobs-deflog',  label: 'Deficiency & Corrective Action Log',      formId: 'CL-FM-051' }),
      form({ id: 'hha-skillobs-summary', label: 'Observation Summary (all aides)',         formId: 'CL-FM-052' }),
    ],
    approvals: [
      { id: 'hha-skillobs-rule-event', targetKind: 'event', targetLabel: 'Skilled-Patient Aide Observation Cycle', approverRole: 'Director of Nursing', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: '42 CFR §484.80(h)(1)', auditRisk: 'critical', overdueAfterDays: 0 },
  },

  {
    id: 'TPL-CL-SEMIANNUAL-HHA-AIDEOBS',
    title: 'Semiannual Aide-Only Patient Observation',
    domain: 'Clinical',
    category: 'hha-semiannual-aideonly-obs',
    cadence: 'Semiannual',
    mandateType: 'federal-required',
    regulatoryDriver: '42 CFR §484.80(h)(2) — Aide-Only Patient Semiannual Observation',
    policyRefs: ['CL-SD-007'],
    owner: 'Director of Nursing',
    ownerRole: 'Director of Nursing',
    urgency: 'scheduled',
    summary: 'Semiannual in-home observation for aides serving patients with NO concurrent skilled services. Distinct from the annual skilled-patient observation.',
    recurrence: { frequency: 'semi-annual', anchorMonth: 3, dayOfMonth: 11, time: '09:00', timeEnd: '12:00' },
    processFlow: [
      step({ id: 'hha-aideobs-identify', label: 'Identify aide-only patient cohort',      description: 'Pull aide-only patients (no concurrent skilled care). Do not mix with §484.80(h)(1) cohort.', dueOffsetDays: -7 }),
      step({ id: 'hha-aideobs-schedule', label: 'Schedule observations',                  description: 'Assign RN observer to each aide-patient pair.', dueOffsetDays: -3 }),
      step({ id: 'hha-aideobs-observe',  label: 'Conduct in-home observations',           description: 'RN observes aide using standard observation form.', dueOffsetDays: 0 }),
      step({ id: 'hha-aideobs-deficiency','label': 'Track deficiencies and corrective actions', description: 'Document any deficiency with corrective action and re-observation timeline.', dueOffsetDays: 3 }),
      step({ id: 'hha-aideobs-file',     label: 'File records',                           description: 'Archive observation forms in aide personnel files. Next semiannual due +6 months.', dueOffsetDays: 7 }),
    ],
    requiredForms: [
      form({ id: 'hha-aideobs-obsform', label: 'Aide Observation Form (aide-only)',       formId: 'CL-FM-060' }),
      form({ id: 'hha-aideobs-deflog',  label: 'Deficiency & Corrective Action Log',      formId: 'CL-FM-061' }),
      form({ id: 'hha-aideobs-summary', label: 'Observation Summary (aide-only cohort)', formId: 'CL-FM-062' }),
    ],
    approvals: [
      { id: 'hha-aideobs-rule-event', targetKind: 'event', targetLabel: 'Semiannual Aide-Only Observation Cycle', approverRole: 'Director of Nursing', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: '42 CFR §484.80(h)(2)', auditRisk: 'critical', overdueAfterDays: 0 },
  },

  {
    id: 'TPL-CO-ANNUAL-HHCAHPS',
    title: 'HHCAHPS Participation Decision & Annual Filing',
    domain: 'Compliance',
    category: 'hhcahps-annual',
    cadence: 'Annual',
    mandateType: 'conditional-federal',
    regulatoryDriver: '42 CFR §484.250 / §484.245 — HHCAHPS Participation',
    policyRefs: ['CO-RA-002'],
    owner: 'Administrator',
    ownerRole: 'Administrator',
    urgency: 'scheduled',
    summary: 'Annual HHCAHPS participation decision: file low-volume exemption OR document active vendor participation. Conditional federal requirement.',
    recurrence: { frequency: 'annual', anchorMonth: 3, dayOfMonth: 31, time: '09:00', timeEnd: '10:30' },
    processFlow: [
      step({ id: 'hhcahps-volume', label: 'Determine survey volume and exemption eligibility', description: 'Pull prior-year discharge count. If < 60 surveys projected, agency is eligible for the CMS exemption.', dueOffsetDays: -14 }),
      step({ id: 'hhcahps-branch', label: 'Execute exemption OR vendor oversight branch',     description: 'Branch A (exemption): submit CMS form + file confirmation. Branch B (participation): confirm vendor contract, review submission rates, resolve gaps.', dueOffsetDays: 0 }),
      step({ id: 'hhcahps-packet', label: 'Compile and archive annual participation packet',  description: 'File volume determination, exemption letter OR vendor contract, submission tracking, compliance confirmation.', dueOffsetDays: 3 }),
    ],
    requiredForms: [
      form({ id: 'hhcahps-volume-f',    label: 'Survey Volume Determination',                formId: 'CO-FM-030' }),
      form({ id: 'hhcahps-exempt-or-v', label: 'CMS Exemption Letter OR Vendor Contract',   formId: 'CO-FM-031' }),
      form({ id: 'hhcahps-track',       label: 'Submission / Response Rate Tracking',       formId: 'CO-FM-032' }),
    ],
    approvals: [
      { id: 'hhcahps-rule-event', targetKind: 'event', targetLabel: 'HHCAHPS Annual Filing', approverRole: 'Administrator', required: true, escalationDays: 7 },
    ],
    complianceFlags: { citation: '42 CFR §484.250', auditRisk: 'high', overdueAfterDays: 0 },
  },

  {
    id: 'TPL-HR-QUARTERLY-COMPETENCY',
    title: 'Quarterly Competency Validation Cycle',
    domain: 'Clinical',
    category: 'competency',
    cadence: 'Quarterly',
    regulatoryDriver: 'CoP §484.80 Home Health Aide Services',
    policyRefs: ['HR-TA-004'],
    owner: 'Clinical Director',
    ownerRole: 'Clinical Director',
    urgency: 'scheduled',
    summary: 'Clinical competency validation cycle for nurses, aides, and therapy disciplines.',
    recurrence: { frequency: 'quarterly', quarterMonths: [3, 6, 9, 12], dayOfMonth: 22, time: '09:00', timeEnd: '15:00' },
    processFlow: [
      step({ id: 'cv-schedule', label: 'Schedule windows', description: 'Schedule competency validation windows.', dueOffsetDays: -21 }),
      step({ id: 'cv-observe',  label: 'Observations',      description: 'Direct observations + return demos.',    dueOffsetDays:   0 }),
      step({ id: 'cv-file',     label: 'File packets',      description: 'File competency packets in personnel file.', dueOffsetDays:   5 }),
    ],
    requiredForms: [
      form({ id: 'cv-packet', label: 'Competency Packet', formId: 'FRM-HR-060' }),
    ],
    complianceFlags: { citation: 'CoP §484.80', auditRisk: 'high', overdueAfterDays: 7 },
  },
];

/* ─── Trigger-only templates ─────────────────────────── */

export const TRIGGER_TEMPLATES: EventTemplate[] = [
  {
    id: 'TPL-RM-TRIGGER-RCA',
    title: 'Sentinel Event Root Cause Analysis',
    domain: 'Risk',
    category: 'investigation',
    cadence: 'Trigger-based',
    regulatoryDriver: 'CoP §484.65(d)(2); TJC Sentinel Events',
    policyRefs: ['RM-ER-002'],
    owner: 'Risk Manager',
    ownerRole: 'Risk Manager',
    urgency: 'critical',
    summary: 'Structured RCA launched in response to a sentinel event; 45-day close.',
    recurrence: { frequency: 'trigger' },
    trigger: { kind: 'sentinel', daysFromTrigger: 1, minSeverity: 'high', description: 'A sentinel event (unexpected death, major permanent loss of function, etc.) was reported.' },
    processFlow: [
      step({ id: 'rca-team',     label: 'Convene RCA team',    description: 'Convene multidisciplinary RCA team.',  dueOffsetDays:  0 }),
      step({ id: 'rca-timeline', label: 'Build timeline',       description: 'Build event timeline from source data.', dueOffsetDays:  5 }),
      step({ id: 'rca-analysis', label: 'Root-cause analysis',  description: 'Identify root cause and contributors.',  dueOffsetDays: 20 }),
      step({ id: 'rca-actions',  label: 'Corrective actions',   description: 'Develop corrective action plan.',        dueOffsetDays: 30 }),
      step({ id: 'rca-close',    label: 'Closure + effectiveness', description: 'Close with effectiveness check.',    dueOffsetDays: 45 }),
    ],
    requiredForms: [
      form({ id: 'rca-form',   label: 'RCA Report',            formId: 'FRM-RM-020' }),
      form({ id: 'rca-action', label: 'Corrective Action Plan', formId: 'FRM-RM-021' }),
    ],
    approvals: [
      { id: 'rca-rule-event', targetKind: 'event', targetLabel: 'Close RCA', approverRole: 'Administrator', required: true, escalationDays: 10 },
    ],
    complianceFlags: { citation: 'TJC Sentinel Events', auditRisk: 'critical', overdueAfterDays: 10 },
    dependencies: { feeds: ['TPL-QA-MONTHLY-QAPI'] },
  },
];
