export type EvidencePacketFrequency = 'monthly' | 'quarterly' | 'annual' | 'event_based' | 'custom';
export type EvidencePacketMappingStatus = 'ready' | 'partial' | 'needs_mapping';

export type EvidencePacketSection = {
  sectionId: string;
  title: string;
  sourceType:
    | 'event_metadata'
    | 'workflow_step'
    | 'form'
    | 'signed_package'
    | 'evidence'
    | 'audit_log'
    | 'brad_summary'
    | 'manual_upload'
    | 'appendix';
  required: boolean;
  formId?: string;
  policyId?: string;
  evidenceType?: string;
};

export type EvidencePacketType = {
  packetTypeId: string;
  label: string;
  description: string;
  eventTypeIds: string[];
  workflowIds: string[];
  requiredPolicyIds: string[];
  requiredFormIds: string[];
  requiredEvidenceTypes: string[];
  requiredSignerRoles: string[];
  packetSections: EvidencePacketSection[];
  frequency?: EvidencePacketFrequency;
  mappingStatus: EvidencePacketMappingStatus;
};

const baseSections = (sectionPrefix: string, options: {
  forms?: string[];
  policies?: string[];
  evidence?: string[];
  signed?: boolean;
  appendix?: boolean;
} = {}): EvidencePacketSection[] => [
  { sectionId: `${sectionPrefix}-metadata`, title: 'Event metadata and packet cover', sourceType: 'event_metadata', required: true },
  { sectionId: `${sectionPrefix}-brad-summary`, title: 'Brad-generated executive summary', sourceType: 'brad_summary', required: true },
  ...(options.policies ?? []).map((policyId) => ({
    sectionId: `${sectionPrefix}-policy-${policyId}`,
    title: `Policy reference ${policyId}`,
    sourceType: 'appendix' as const,
    required: true,
    policyId,
  })),
  ...(options.forms ?? []).map((formId) => ({
    sectionId: `${sectionPrefix}-form-${formId}`,
    title: `Required form ${formId}`,
    sourceType: 'form' as const,
    required: true,
    formId,
  })),
  ...(options.evidence ?? ['supporting-evidence']).map((evidenceType) => ({
    sectionId: `${sectionPrefix}-evidence-${evidenceType}`,
    title: evidenceType.replace(/-/g, ' '),
    sourceType: 'evidence' as const,
    required: true,
    evidenceType,
  })),
  ...(options.signed ? [{ sectionId: `${sectionPrefix}-signed`, title: 'Signed package and approvals', sourceType: 'signed_package' as const, required: true }] : []),
  { sectionId: `${sectionPrefix}-audit-log`, title: 'Audit trail and readiness checklist', sourceType: 'audit_log', required: true },
  ...(options.appendix ? [{ sectionId: `${sectionPrefix}-appendix`, title: 'Manual appendix and uploaded sources', sourceType: 'manual_upload' as const, required: false }] : []),
];

export const EVIDENCE_PACKET_TYPES: EvidencePacketType[] = [
  {
    packetTypeId: 'qapi-quarterly-committee',
    label: 'QAPI Quarterly Committee Meeting Packet',
    description: 'Quarterly QAPI dashboard, chart audit, incident trends, infection control inputs, CAPA, minutes, and approvals.',
    eventTypeIds: ['qapi', 'committee', 'quality'],
    workflowIds: ['QA-WF-03'],
    requiredPolicyIds: ['QA-PI-001'],
    requiredFormIds: [
      'QA-FM-001', // QAPI Committee Meeting Minutes Template
      'QA-FM-002', // PIP Charter
      'QA-FM-003', // Quality Indicator Monthly Dashboard
      'QA-FM-004', // Adverse Event RCA Worksheet
      'QA-FM-005', // CAP Tracking Tool
      'QA-FM-006', // Infection Control Line List & Surveillance Log
      'QA-FM-021', // PIP Remeasurement & Status
      'CO-FM-024', // Compliance Committee Meeting Minutes
      'EN-FM-022', // Enterprise Policy Compliance Scorecard
      'GV-FM-023', // Annual Compliance Report to Governing Body
    ],
    requiredEvidenceTypes: ['qapi-dashboard', 'chart-audit-summary', 'incident-log', 'infection-log'],
    requiredSignerRoles: ['Administrator', 'QAPI Lead'],
    packetSections: baseSections('qapi-quarterly', {
      forms: [
        // Required child forms for QA-WF-03 (must be present for validation to pass)
        'QA-FM-001', 'QA-FM-002', 'QA-FM-003', 'QA-FM-004', 'QA-FM-005', 'QA-FM-006',
        'QA-FM-021', 'CO-FM-024', 'EN-FM-022', 'GV-FM-023',
        // Supporting report sections (may be included)
        'QA-FM-020', 'QA-FM-025', 'QA-FM-026', 'QA-FM-027',
      ],
      policies: ['QA-PI-001'],
      evidence: ['qapi-dashboard', 'chart-audit-summary'],
      signed: true,
      appendix: true,
    }),
    frequency: 'quarterly',
    mappingStatus: 'ready',
  },
  {
    packetTypeId: 'governing-body-board',
    label: 'Governing Body / Board Meeting Packet',
    description: 'Board agenda, prior minutes, compliance report, QAPI report, risk report, financial summary, and governing approvals.',
    eventTypeIds: ['governing', 'board'],
    workflowIds: ['GV-WF-01'],
    requiredPolicyIds: ['GV-GB-001'],
    requiredFormIds: ['GV-F-001', 'CO-F-004', 'QA-F-020', 'RM-F-010'],
    requiredEvidenceTypes: ['board-agenda', 'prior-minutes', 'compliance-report'],
    requiredSignerRoles: ['Administrator', 'Governing Body Chair'],
    packetSections: baseSections('governing-board', { forms: ['GV-F-001', 'CO-F-004', 'RM-F-010'], policies: ['GV-GB-001'], signed: true, appendix: true }),
    frequency: 'quarterly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'clinical-record-review',
    label: 'Clinical Record Review Committee Packet',
    description: 'Record review roster, chart audit summary, POC/OASIS findings, corrective actions, and clinical manager signoff.',
    eventTypeIds: ['clinical-record', 'chart-audit', 'record-review'],
    workflowIds: ['CL-WF-26'],
    requiredPolicyIds: ['CL-CR-001'],
    requiredFormIds: ['QA-FM-025'],
    requiredEvidenceTypes: ['sample-roster', 'chart-audit-summary', 'corrective-actions'],
    requiredSignerRoles: ['Clinical Manager'],
    packetSections: baseSections('clinical-record', { forms: ['QA-FM-025'], evidence: ['sample-roster', 'chart-audit-summary'], signed: true }),
    frequency: 'quarterly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'infection-control-committee',
    label: 'Infection Control Committee Packet',
    description: 'Infection surveillance logs, trend analysis, outbreak response, staff education, and QAPI escalation record.',
    eventTypeIds: ['infection', 'infection-control'],
    workflowIds: [],
    requiredPolicyIds: ['IC-PR-001'],
    requiredFormIds: ['CL-FM-IC-001'],
    requiredEvidenceTypes: ['infection-surveillance-log', 'trend-analysis'],
    requiredSignerRoles: ['Infection Control Coordinator'],
    packetSections: baseSections('infection-control', { forms: ['CL-FM-IC-001'], evidence: ['infection-surveillance-log', 'trend-analysis'], signed: true }),
    frequency: 'quarterly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'patient-safety-committee',
    label: 'Patient Safety Committee Packet',
    description: 'Patient safety incidents, adverse event reviews, risk mitigations, education actions, and committee follow-up.',
    eventTypeIds: ['patient-safety', 'risk', 'adverse-event'],
    workflowIds: [],
    requiredPolicyIds: ['RM-ER-002'],
    requiredFormIds: ['RM-F-010', 'QA-FM-030'],
    requiredEvidenceTypes: ['incident-summary', 'risk-report', 'capa-log'],
    requiredSignerRoles: ['Risk Manager', 'Administrator'],
    packetSections: baseSections('patient-safety', { forms: ['RM-F-010', 'QA-FM-030'], evidence: ['incident-summary', 'risk-report'], signed: true }),
    frequency: 'quarterly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'cag-pac-advisory',
    label: 'CAG / PAC Advisory Meeting Packet',
    description: 'Advisory agenda, member roster, recommendations, follow-up actions, and administrator response.',
    eventTypeIds: ['cag', 'pac', 'advisory'],
    workflowIds: [],
    requiredPolicyIds: ['GV-AD-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['agenda', 'advisory-recommendations', 'attendance-roster'],
    requiredSignerRoles: ['Administrator'],
    packetSections: baseSections('advisory', { evidence: ['agenda', 'advisory-recommendations', 'attendance-roster'], appendix: true }),
    frequency: 'quarterly',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'staff-training-inservice',
    label: 'Staff In-Service / Training Packet',
    description: 'Training roster, curriculum, attestations, post-test evidence, and remediation follow-up.',
    eventTypeIds: ['training', 'in-service', 'education'],
    workflowIds: [],
    requiredPolicyIds: ['HR-TD-001'],
    requiredFormIds: ['HR-F-003', 'HR-F-004'],
    requiredEvidenceTypes: ['training-roster', 'curriculum', 'attestations'],
    requiredSignerRoles: ['HR Training Coordinator'],
    packetSections: baseSections('staff-training', { forms: ['HR-F-003', 'HR-F-004'], policies: ['HR-TD-001'], evidence: ['training-roster', 'attestations'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'emergency-preparedness-drill',
    label: 'Emergency Preparedness Drill Packet',
    description: 'Drill plan, attendance, after-action findings, corrective actions, and annual EP review support.',
    eventTypeIds: ['emergency', 'preparedness', 'drill'],
    workflowIds: [],
    requiredPolicyIds: ['EP-PR-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['drill-plan', 'attendance', 'after-action-report'],
    requiredSignerRoles: ['Administrator'],
    packetSections: baseSections('ep-drill', { evidence: ['drill-plan', 'attendance', 'after-action-report'], appendix: true }),
    frequency: 'annual',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'hipaa-training-completion',
    label: 'Annual HIPAA Training Completion Packet',
    description: 'Annual HIPAA workforce training completion, attestations, roster, and remediation evidence.',
    eventTypeIds: ['hipaa', 'training'],
    workflowIds: [],
    requiredPolicyIds: ['CO-HP-001', 'CO-HP-002'],
    requiredFormIds: ['IS-F-010'],
    requiredEvidenceTypes: ['training-roster', 'hipaa-attestation', 'non-completer-remediation'],
    requiredSignerRoles: ['Privacy Officer', 'HR Training Coordinator'],
    packetSections: baseSections('hipaa-training', { forms: ['IS-F-010'], policies: ['CO-HP-001', 'CO-HP-002'], evidence: ['training-roster', 'hipaa-attestation'], signed: true }),
    frequency: 'annual',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'tb-employee-health',
    label: 'TB Screening / Employee Health Packet',
    description: 'Employee health screening roster, TB clearance evidence, exceptions, and follow-up actions.',
    eventTypeIds: ['tb', 'employee-health'],
    workflowIds: [],
    requiredPolicyIds: ['HR-EH-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['employee-health-roster', 'tb-clearance', 'exceptions-log'],
    requiredSignerRoles: ['HR Manager'],
    packetSections: baseSections('tb-health', { evidence: ['employee-health-roster', 'tb-clearance', 'exceptions-log'] }),
    frequency: 'annual',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'personnel-file-audit',
    label: 'Annual Personnel File Audit Packet',
    description: 'Personnel file checklist, missing credentials, remediation, and administrator review.',
    eventTypeIds: ['personnel', 'file-audit', 'credential'],
    workflowIds: [],
    requiredPolicyIds: ['HR-PE-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['personnel-file-checklist', 'credential-gap-log'],
    requiredSignerRoles: ['HR Manager', 'Administrator'],
    packetSections: baseSections('personnel-file', { policies: ['HR-PE-001'], evidence: ['personnel-file-checklist', 'credential-gap-log'], signed: true }),
    frequency: 'annual',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'oig-sam-exclusion-check',
    label: 'Annual OIG / SAM Exclusion Check Packet',
    description: 'OIG LEIE/SAM screening evidence, exception handling, and compliance officer review.',
    eventTypeIds: ['oig', 'sam', 'exclusion'],
    workflowIds: [],
    requiredPolicyIds: ['HR-TA-003'],
    requiredFormIds: ['CO-F-010'],
    requiredEvidenceTypes: ['screening-log', 'source-screenshots', 'exception-review'],
    requiredSignerRoles: ['Compliance Officer'],
    packetSections: baseSections('oig-sam', { forms: ['CO-F-010'], policies: ['HR-TA-003'], evidence: ['screening-log', 'source-screenshots'], signed: true }),
    frequency: 'annual',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'policy-annual-review',
    label: 'Annual Policy Review Packet',
    description: 'Annual policy review roster, approvals, publication evidence, and governing oversight.',
    eventTypeIds: ['policy', 'annual-review'],
    workflowIds: [],
    requiredPolicyIds: [],
    requiredFormIds: [],
    requiredEvidenceTypes: ['policy-review-roster', 'approval-log', 'publication-log'],
    requiredSignerRoles: ['Administrator', 'Policy Owner'],
    packetSections: baseSections('policy-annual', { evidence: ['policy-review-roster', 'approval-log', 'publication-log'], signed: true }),
    frequency: 'annual',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'physician-signature-tracking',
    label: 'Monthly Physician Signature Tracking Packet',
    description: 'Monthly physician signature aging report, outreach log, billing hold support, and escalation summary.',
    eventTypeIds: ['physician-signature', 'poc-signature'],
    workflowIds: [],
    requiredPolicyIds: ['CL-CP-009', 'FN-BC-003'],
    requiredFormIds: ['CL-F-001', 'FN-F-004'],
    requiredEvidenceTypes: ['signature-tracker', 'aged-unsigned-poc-report', 'outreach-log'],
    requiredSignerRoles: ['Clinical Manager'],
    packetSections: baseSections('physician-signature', { forms: ['CL-F-001', 'FN-F-004'], evidence: ['signature-tracker', 'outreach-log'], signed: true }),
    frequency: 'monthly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'plan-of-care-audit',
    label: 'Plan of Care Audit Packet',
    description: 'Plan of care audit sample, physician signature status, visit frequency findings, and corrective actions.',
    eventTypeIds: ['plan-of-care', 'poc-audit'],
    workflowIds: ['CL-WF-26'],
    requiredPolicyIds: ['CL-CP-009'],
    requiredFormIds: ['CL-F-001'],
    requiredEvidenceTypes: ['poc-sample', 'signature-status', 'corrective-actions'],
    requiredSignerRoles: ['Clinical Manager'],
    packetSections: baseSections('poc-audit', { forms: ['CL-F-001'], policies: ['CL-CP-009'], evidence: ['poc-sample', 'corrective-actions'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'oasis-accuracy-audit',
    label: 'OASIS Accuracy Audit Packet',
    description: 'OASIS accuracy review, coding validation, clinical corrections, and final lock evidence.',
    eventTypeIds: ['oasis', 'accuracy-audit'],
    workflowIds: [],
    requiredPolicyIds: ['CL-OA-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['oasis-sample', 'coding-review', 'correction-log'],
    requiredSignerRoles: ['Clinical Manager'],
    packetSections: baseSections('oasis-audit', { evidence: ['oasis-sample', 'coding-review', 'correction-log'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'medication-reconciliation-audit',
    label: 'Medication Reconciliation Audit Packet',
    description: 'Medication reconciliation audit findings, clinical follow-up, and correction evidence.',
    eventTypeIds: ['medication', 'reconciliation'],
    workflowIds: [],
    requiredPolicyIds: ['CL-MR-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['med-rec-audit', 'follow-up-log'],
    requiredSignerRoles: ['Clinical Manager'],
    packetSections: baseSections('med-rec', { evidence: ['med-rec-audit', 'follow-up-log'] }),
    frequency: 'event_based',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'incident-adverse-event-review',
    label: 'Incident / Adverse Event Review Packet',
    description: 'Incident report, RCA, adverse event review, risk escalation, and CAPA evidence.',
    eventTypeIds: ['incident', 'adverse-event', 'sentinel'],
    workflowIds: [],
    requiredPolicyIds: ['RM-ER-002'],
    requiredFormIds: ['QA-FM-030'],
    requiredEvidenceTypes: ['incident-report', 'rca', 'capa-log'],
    requiredSignerRoles: ['Risk Manager', 'Administrator'],
    packetSections: baseSections('incident-review', { forms: ['QA-FM-030'], policies: ['RM-ER-002'], evidence: ['incident-report', 'rca', 'capa-log'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'complaint-grievance-investigation',
    label: 'Complaint / Grievance Investigation Packet',
    description: 'Complaint intake, investigation notes, response letter, closure evidence, and trend escalation.',
    eventTypeIds: ['complaint', 'grievance'],
    workflowIds: [],
    requiredPolicyIds: ['PR-GR-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['complaint-intake', 'investigation-notes', 'closure-letter'],
    requiredSignerRoles: ['Administrator'],
    packetSections: baseSections('complaint-grievance', { evidence: ['complaint-intake', 'investigation-notes', 'closure-letter'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'infection-surveillance-monthly',
    label: 'Monthly Infection Surveillance Review Packet',
    description: 'Monthly infection surveillance review, threshold comparison, and escalation evidence.',
    eventTypeIds: ['infection', 'surveillance'],
    workflowIds: [],
    requiredPolicyIds: ['IC-PR-001'],
    requiredFormIds: ['CL-FM-IC-001'],
    requiredEvidenceTypes: ['infection-event-log', 'threshold-comparison'],
    requiredSignerRoles: ['Infection Control Coordinator'],
    packetSections: baseSections('infection-monthly', { forms: ['CL-FM-IC-001'], evidence: ['infection-event-log', 'threshold-comparison'] }),
    frequency: 'monthly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'vulnerability-scan-it-security',
    label: 'Vulnerability Scan / IT Security Packet',
    description: 'System activity review, vulnerability scan output, remediation, and security officer review.',
    eventTypeIds: ['security', 'vulnerability', 'it'],
    workflowIds: [],
    requiredPolicyIds: ['IT-UP-001', 'CO-HP-002'],
    requiredFormIds: ['IS-F-001'],
    requiredEvidenceTypes: ['scan-report', 'remediation-log', 'system-activity-review'],
    requiredSignerRoles: ['Security Officer'],
    packetSections: baseSections('it-security', { forms: ['IS-F-001'], policies: ['CO-HP-002'], evidence: ['scan-report', 'remediation-log'] }),
    frequency: 'monthly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'compliance-validation-checklist',
    label: 'Compliance Validation Checklist Packet',
    description: 'Validation checklist, control evidence, missing item register, and compliance officer signoff.',
    eventTypeIds: ['compliance', 'validation'],
    workflowIds: [],
    requiredPolicyIds: ['CO-CP-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['validation-checklist', 'missing-item-register'],
    requiredSignerRoles: ['Compliance Officer'],
    packetSections: baseSections('compliance-validation', { policies: ['CO-CP-001'], evidence: ['validation-checklist', 'missing-item-register'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'monthly-compliance-report',
    label: 'Monthly Compliance Report Packet',
    description: 'Monthly compliance report, hotline activity, exclusions, training, open CAPA, and executive summary.',
    eventTypeIds: ['monthly-compliance', 'compliance-report'],
    workflowIds: [],
    requiredPolicyIds: ['CO-CP-001'],
    requiredFormIds: ['CO-F-004'],
    requiredEvidenceTypes: ['monthly-compliance-report', 'hotline-log', 'capa-status'],
    requiredSignerRoles: ['Compliance Officer'],
    packetSections: baseSections('monthly-compliance', { forms: ['CO-F-004'], policies: ['CO-CP-001'], evidence: ['monthly-compliance-report', 'capa-status'], signed: true }),
    frequency: 'monthly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'claims-billing-compliance',
    label: 'Monthly Claims Submission / Billing Compliance Packet',
    description: 'Claims readiness, billing hold support, POC/OASIS gates, and release approval evidence.',
    eventTypeIds: ['claims', 'billing', 'pre-billing'],
    workflowIds: [],
    requiredPolicyIds: ['FN-BC-003'],
    requiredFormIds: ['FN-F-001', 'FN-F-002'],
    requiredEvidenceTypes: ['pre-billing-checklist', 'hold-register', 'release-log'],
    requiredSignerRoles: ['Billing Manager'],
    packetSections: baseSections('billing-compliance', { forms: ['FN-F-001', 'FN-F-002'], policies: ['FN-BC-003'], evidence: ['pre-billing-checklist', 'hold-register'] }),
    frequency: 'monthly',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'competency-validation',
    label: 'Annual Competency Validation Packet',
    description: 'Competency validation records, remediation plans, supervisor review, and annual personnel evidence.',
    eventTypeIds: ['competency', 'validation'],
    workflowIds: [],
    requiredPolicyIds: ['HR-TD-003'],
    requiredFormIds: ['HR-F-020', 'HR-F-021'],
    requiredEvidenceTypes: ['competency-records', 'remediation-plan'],
    requiredSignerRoles: ['Supervisor', 'HR Training Coordinator'],
    packetSections: baseSections('competency', { forms: ['HR-F-020', 'HR-F-021'], policies: ['HR-TD-003'], evidence: ['competency-records', 'remediation-plan'], signed: true }),
    frequency: 'annual',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'wound-clinical-protocol-update',
    label: 'Wound Protocol / Clinical Protocol Update Packet',
    description: 'Protocol update, education evidence, clinical signoff, and staff communication.',
    eventTypeIds: ['wound', 'protocol', 'clinical-update'],
    workflowIds: [],
    requiredPolicyIds: ['CL-WC-001'],
    requiredFormIds: [],
    requiredEvidenceTypes: ['protocol-update', 'education-record', 'clinical-signoff'],
    requiredSignerRoles: ['DON', 'Clinical Manager'],
    packetSections: baseSections('wound-protocol', { evidence: ['protocol-update', 'education-record', 'clinical-signoff'], signed: true }),
    frequency: 'event_based',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'audit-mode-survey',
    label: 'Audit Mode Survey Packet',
    description: 'Survey export bundle, evidence gaps, signed forms, hashes, and external surveyor readiness view.',
    eventTypeIds: ['audit', 'survey'],
    workflowIds: [],
    requiredPolicyIds: [],
    requiredFormIds: [],
    requiredEvidenceTypes: ['survey-export', 'evidence-gap-log', 'hash-manifest'],
    requiredSignerRoles: ['Administrator'],
    packetSections: baseSections('audit-survey', { evidence: ['survey-export', 'evidence-gap-log', 'hash-manifest'], signed: true, appendix: true }),
    frequency: 'event_based',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'annual-qapi-program-evaluation',
    label: 'Annual QAPI Program Evaluation Packet',
    description: 'Annual QAPI program evaluation, PIP outcomes, quarterly rollups, and governing body visibility.',
    eventTypeIds: ['qapi', 'annual', 'program-evaluation'],
    workflowIds: [],
    requiredPolicyIds: ['QA-PI-001'],
    requiredFormIds: ['QA-FM-020'],
    requiredEvidenceTypes: ['annual-qapi-evaluation', 'quarterly-rollups', 'pip-outcomes'],
    requiredSignerRoles: ['QAPI Lead', 'Administrator'],
    packetSections: baseSections('annual-qapi', { forms: ['QA-FM-020'], policies: ['QA-PI-001'], evidence: ['annual-qapi-evaluation', 'quarterly-rollups'], signed: true }),
    frequency: 'annual',
    mappingStatus: 'partial',
  },
  {
    packetTypeId: 'monthly-evidence-readiness',
    label: 'Monthly Evidence Readiness Packet',
    description: 'Monthly evidence readiness rollup, missing items, stale signatures, and Brad-recommended next actions.',
    eventTypeIds: ['evidence-readiness'],
    workflowIds: [],
    requiredPolicyIds: [],
    requiredFormIds: [],
    requiredEvidenceTypes: ['missing-evidence-register', 'signature-aging', 'readiness-scorecard'],
    requiredSignerRoles: ['Compliance Officer'],
    packetSections: baseSections('monthly-evidence', { evidence: ['missing-evidence-register', 'signature-aging', 'readiness-scorecard'], appendix: true }),
    frequency: 'monthly',
    mappingStatus: 'needs_mapping',
  },
  {
    packetTypeId: 'custom-event-packet',
    label: 'Custom Event Packet',
    description: 'Human-reviewable custom packet assembled from manual uploads, Brad draft text, selected forms, and event notes.',
    eventTypeIds: ['custom'],
    workflowIds: [],
    requiredPolicyIds: [],
    requiredFormIds: [],
    requiredEvidenceTypes: ['manual-upload'],
    requiredSignerRoles: [],
    packetSections: baseSections('custom', { evidence: ['manual-upload'], appendix: true }),
    frequency: 'custom',
    mappingStatus: 'needs_mapping',
  },
];

export const EVIDENCE_PACKET_TYPES_BY_ID = new Map(EVIDENCE_PACKET_TYPES.map((packet) => [packet.packetTypeId, packet]));

