import type { AnnualRequirement, EvidenceRecord, Learner, LearningItem, PolicyActivity, RoleCode, RoleProfile } from './types';

export const roleProfiles: Record<RoleCode, RoleProfile> = {
  GEN: { code: 'GEN', label: 'General Employee', shortLabel: 'General onboarding only', reportsTo: 'Department Manager / People Operations', moduleCount: 27, connectedCount: 27, supervisedPractice: false, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  LVN: { code: 'LVN', label: 'Licensed Vocational Nurse', shortLabel: 'LVN pathway', reportsTo: 'RN Supervisor / Clinical Manager', moduleCount: 13, connectedCount: 4, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  RN: { code: 'RN', label: 'Registered Nurse', shortLabel: 'RN pathway', reportsTo: 'Clinical Manager / DON', moduleCount: 16, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  HHA: { code: 'HHA', label: 'Home Health Aide', shortLabel: 'HHA pathway', reportsTo: 'RN Supervisor / DON', moduleCount: 13, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  PT: { code: 'PT', label: 'Physical Therapist', shortLabel: 'PT pathway', reportsTo: 'Clinical Manager / Rehabilitation Lead', moduleCount: 11, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  PTA: { code: 'PTA', label: 'Physical Therapist Assistant', shortLabel: 'PTA pathway', reportsTo: 'Supervising Physical Therapist', moduleCount: 11, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  OT: { code: 'OT', label: 'Occupational Therapist', shortLabel: 'OT pathway', reportsTo: 'Clinical Manager / Rehabilitation Lead', moduleCount: 11, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  COTA: { code: 'COTA', label: 'Occupational Therapy Assistant', shortLabel: 'COTA pathway', reportsTo: 'Supervising Occupational Therapist', moduleCount: 11, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  SLP: { code: 'SLP', label: 'Speech-Language Pathologist', shortLabel: 'SLP pathway', reportsTo: 'Clinical Manager / Rehabilitation Lead', moduleCount: 9, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  MSW: { code: 'MSW', label: 'Medical Social Worker', shortLabel: 'MSW pathway', reportsTo: 'Clinical Manager / Administrator', moduleCount: 9, connectedCount: 0, supervisedPractice: true, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  ADM: { code: 'ADM', label: 'Administrator', shortLabel: 'Administrator pathway', reportsTo: 'Governing Body', moduleCount: 15, connectedCount: 0, supervisedPractice: false, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  DON: { code: 'DON', label: 'Director of Nursing / Clinical Manager', shortLabel: 'Clinical leadership pathway', reportsTo: 'Administrator / Governing Body', moduleCount: 16, connectedCount: 0, supervisedPractice: false, evidenceDestination: 'personnel_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
  GB: { code: 'GB', label: 'Governing Body Member', shortLabel: 'Governing Body pathway', reportsTo: 'Governing Body Chair', moduleCount: 13, connectedCount: 13, supervisedPractice: false, evidenceDestination: 'governance_file', accent: '#F36A21', accentStrong: '#D95715', accentSoft: '#FFF0E7' },
};

export const roleOrder: RoleCode[] = ['GEN', 'LVN', 'RN', 'HHA', 'PT', 'PTA', 'OT', 'COTA', 'SLP', 'MSW', 'ADM', 'DON', 'GB'];

export const learners: Record<RoleCode, Learner> = {
  GEN: { id: 'demo-gen-001', name: 'Olivia Chen', preferredName: 'Olivia', title: 'General Employee', role: 'GEN', hireDate: '2026-07-13', supervisor: 'Department Manager', location: 'Campbell', hoursAvailableToday: 1.5 },
  LVN: { id: 'demo-lvn-104', name: 'Maya Santos', preferredName: 'Maya', title: 'Licensed Vocational Nurse', role: 'LVN', hireDate: '2026-07-13', supervisor: 'Jordan Lee, RN', location: 'Campbell', hoursAvailableToday: 1.5 },
  RN: { id: 'demo-rn-201', name: 'Amelia Brooks', preferredName: 'Amelia', title: 'Registered Nurse', role: 'RN', hireDate: '2026-07-13', supervisor: 'Dana Whitfield, Clinical Manager', location: 'Campbell', hoursAvailableToday: 1.25 },
  HHA: { id: 'demo-hha-318', name: 'Alex Reyes', preferredName: 'Alex', title: 'Home Health Aide', role: 'HHA', hireDate: '2026-07-13', supervisor: 'Jordan Lee, RN', location: 'Campbell', hoursAvailableToday: 1.5 },
  PT: { id: 'demo-pt-224', name: 'Marcus Chen', preferredName: 'Marcus', title: 'Physical Therapist', role: 'PT', hireDate: '2026-07-13', supervisor: 'Dana Whitfield, Clinical Manager', location: 'Campbell', hoursAvailableToday: 1.25 },
  PTA: { id: 'demo-pta-225', name: 'Sofia Ramirez', preferredName: 'Sofia', title: 'Physical Therapist Assistant', role: 'PTA', hireDate: '2026-07-13', supervisor: 'Marcus Chen, PT', location: 'Campbell', hoursAvailableToday: 1.25 },
  OT: { id: 'demo-ot-226', name: 'Priya Shah', preferredName: 'Priya', title: 'Occupational Therapist', role: 'OT', hireDate: '2026-07-13', supervisor: 'Dana Whitfield, Clinical Manager', location: 'Campbell', hoursAvailableToday: 1.25 },
  COTA: { id: 'demo-cota-227', name: 'Mia Torres', preferredName: 'Mia', title: 'Occupational Therapy Assistant', role: 'COTA', hireDate: '2026-07-13', supervisor: 'Priya Shah, OT', location: 'Campbell', hoursAvailableToday: 1.25 },
  SLP: { id: 'demo-slp-228', name: 'Grace Park', preferredName: 'Grace', title: 'Speech-Language Pathologist', role: 'SLP', hireDate: '2026-07-13', supervisor: 'Dana Whitfield, Clinical Manager', location: 'Campbell', hoursAvailableToday: 1.25 },
  MSW: { id: 'demo-msw-229', name: 'Jordan Bell', preferredName: 'Jordan', title: 'Medical Social Worker', role: 'MSW', hireDate: '2026-07-13', supervisor: 'Noah Kim, Administrator', location: 'Campbell', hoursAvailableToday: 1.25 },
  ADM: { id: 'demo-adm-003', name: 'Noah Kim', preferredName: 'Noah', title: 'Administrator', role: 'ADM', hireDate: '2026-07-13', supervisor: 'Governing Body Chair', location: 'Campbell', hoursAvailableToday: 1 },
  DON: { id: 'demo-don-004', name: 'Dana Whitfield', preferredName: 'Dana', title: 'Director of Nursing / Clinical Manager', role: 'DON', hireDate: '2026-07-13', supervisor: 'Noah Kim, Administrator', location: 'Campbell', hoursAvailableToday: 1 },
  GB: { id: 'demo-gb-009', name: 'Elena Ortiz', preferredName: 'Elena', title: 'Governing Body Member', role: 'GB', hireDate: '2026-07-13', supervisor: 'Governing Body Chair', location: 'Campbell', hoursAvailableToday: 1 },
};

export const policyActivities: PolicyActivity[] = [
  { activityId: 'GAO-004-PP-CO-CP-001', moduleId: 'GAO-004', policyId: 'CO-CP-001', title: 'Corporate Compliance Program', dueDay: 5, scope: 'all_staff', verification: 'verified', fullTextAvailable: true, state: 'blocked', quizBankConnected: false, quizQuestions: 10, passScore: 80, maxAttempts: 3, attempts: 0, attestationRequired: true, certificateGate: true, authorityLabel: 'Policy text verified; approved quiz bank needs source' },
  { activityId: 'GAO-007-PP-CO-HP-001', moduleId: 'GAO-007', policyId: 'CO-HP-001', title: 'HIPAA Privacy Program', dueDay: 7, scope: 'all_staff', verification: 'verified', fullTextAvailable: true, state: 'blocked', quizBankConnected: false, quizQuestions: 10, passScore: 80, maxAttempts: 3, attempts: 0, attestationRequired: true, certificateGate: true, authorityLabel: 'Policy text verified; approved quiz bank needs source' },
  { activityId: 'GAO-007-PP-CO-HP-004', moduleId: 'GAO-007', policyId: 'CO-HP-004', title: 'Minimum Necessary Standard', dueDay: 7, scope: 'all_staff', verification: 'verified', fullTextAvailable: true, state: 'blocked', quizBankConnected: false, quizQuestions: 10, passScore: 80, maxAttempts: 3, attempts: 0, attestationRequired: true, certificateGate: true, authorityLabel: 'Policy text verified; approved quiz bank needs source' },
  { activityId: 'GAO-019-PP-HR-ER-004', moduleId: 'GAO-019', policyId: 'HR-ER-004', title: 'Anti-Harassment & Non-Discrimination', dueDay: 14, scope: 'all_staff', verification: 'verified', fullTextAvailable: true, state: 'blocked', quizBankConnected: false, quizQuestions: 10, passScore: 80, maxAttempts: 3, attempts: 0, attestationRequired: true, certificateGate: true, authorityLabel: 'Policy text verified; approved quiz bank needs source' },
  { activityId: 'GAO-014-PP-RM-OS-003', moduleId: 'GAO-014', policyId: 'RM-OS-003', title: 'Bloodborne Pathogen Exposure Control Plan', dueDay: 14, scope: 'patient_facing', verification: 'verified', fullTextAvailable: true, state: 'blocked', quizBankConnected: false, quizQuestions: 10, passScore: 80, maxAttempts: 3, attempts: 0, attestationRequired: true, certificateGate: true, authorityLabel: 'Policy text verified; approved quiz bank needs source' },
  { activityId: 'GAO-015-PP-RM-EP-001', moduleId: 'GAO-015', policyId: 'RM-EP-001', title: 'Emergency Preparedness Program', dueDay: 18, scope: 'all_staff', verification: 'needs_review', fullTextAvailable: true, state: 'blocked', quizBankConnected: false, quizQuestions: 10, passScore: 80, maxAttempts: 3, attempts: 0, attestationRequired: true, certificateGate: false, authorityLabel: 'Policy mapping and approved quiz bank both need source review' },
];

export const annualRequirements: AnnualRequirement[] = [
  { id: 'ANN-HIPAA', title: 'HIPAA privacy & security refresher', cadence: 'Agency annual + material-change trigger', due: 'Jan 31, 2027', state: 'ready', evidence: 'LMS completion, score, acknowledgment', authorityLabel: 'Agency cadence; workforce change training also applies', role: 'all' },
  { id: 'ANN-FWA', title: 'Fraud, waste & abuse refresher', cadence: 'Agency annual / contract-applicable', due: 'Feb 28, 2027', state: 'ready', evidence: 'Completion log and score', authorityLabel: 'Assignment depends on role and program applicability', role: 'all' },
  { id: 'ANN-EP', title: 'Emergency preparedness training', cadence: 'At least biennial + significant-update trigger', due: 'Cycle controlled', state: 'ready', evidence: 'Roster, post-test, role attestation', authorityLabel: '42 CFR 484.102(d)', role: 'all' },
  { id: 'ANN-HHA-12H', title: 'HHA in-service education', cadence: '12 hours each 12-month period', due: 'Rolling anniversary', state: 'locked', evidence: 'Hour log, curriculum, RN-supervised evidence', authorityLabel: '42 CFR 484.80(d)', role: 'HHA' },
  { id: 'ANN-GB', title: 'Governing Body annual governance refresh', cadence: 'Agency annual control', due: 'Annual governance cycle', state: 'locked', evidence: 'Governance-file completion record', authorityLabel: 'Agency governance control', role: 'GB' },
];

export const evidenceRecords: EvidenceRecord[] = [
  { id: 'EV-2026-101', label: 'Appendix F readiness record', type: 'Prerequisite clearance', completedAt: 'Jul 13, 2026 · 9:14 AM', destination: 'Personnel file', integrity: 'recorded' },
  { id: 'EV-2026-114', label: 'GAO-004 Corporate Compliance', type: 'Module completion', completedAt: 'Jul 16, 2026 · 2:42 PM', score: '90%', destination: 'Learning record', integrity: 'recorded' },
  { id: 'EV-2026-115', label: 'CO-CP-001 acknowledgment · sample', type: 'Prototype policy attestation', completedAt: 'Jul 16, 2026 · 2:47 PM', destination: 'Personnel file', integrity: 'recorded' },
  { id: 'EV-PENDING', label: 'Role-pathway certificate', type: 'Certificate gate', completedAt: 'Waiting on role training and sign-off', destination: 'Personnel file', integrity: 'pending' },
];

export const connectedRoleModules: Record<RoleCode, LearningItem[]> = {
  GEN: [],
  LVN: [
    { id: 'LVN-001', title: 'LVN Role & Scope of Practice', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Archive repair needed', durationMinutes: 0, sourceAdapter: 'LVN-001 supplied archive', requiredFor: 'LVN pathway', note: 'The supplied archive fails integrity testing and cannot be launched.' },
    { id: 'LVN-002', title: 'LVN Supervision Requirements', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Source needed', durationMinutes: 0, sourceAdapter: 'No package supplied', requiredFor: 'LVN pathway', note: 'Registry entry exists; module package is not connected.' },
    { id: 'LVN-003', title: 'Skilled Nursing Visits — LVN Scope', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Archive repair needed', durationMinutes: 0, sourceAdapter: 'LVN-003 supplied archive', requiredFor: 'LVN pathway', note: 'The supplied archive fails integrity testing and cannot be launched.' },
    { id: 'LVN-004', title: 'Clinical Documentation Standards', track: 'ROLE', kind: 'module', state: 'blocked', dueLabel: 'Manifest review needed', durationMinutes: 45, sourceAdapter: 'Readable LVN-004 PASS5 package', requiredFor: 'LVN pathway', note: 'Readable package; its title/content conflicts with the draft v2.3 registry and needs owner reconciliation.' },
    { id: 'LVN-005', title: 'Plan of Care', track: 'ROLE', kind: 'module', state: 'blocked', dueLabel: 'Manifest review needed', durationMinutes: 48, sourceAdapter: 'Readable LVN-005 PASS5 package', requiredFor: 'LVN pathway', note: 'Readable package; its title/content conflicts with the draft v2.3 registry and needs owner reconciliation.' },
    { id: 'LVN-012', title: 'Skills Check-Off', track: 'COMP', kind: 'competency', state: 'blocked', dueLabel: 'Manifest review needed', durationMinutes: 0, sourceAdapter: 'Readable LVN-012 PASS5 package', requiredFor: 'LVN pathway', note: 'Readable package; its title/content conflicts with the draft v2.3 registry and needs owner reconciliation.' },
    { id: 'LVN-SUP', title: 'LVN Supervised Practice & Competency Validation', track: 'COMP', kind: 'competency', state: 'blocked', dueLabel: 'Manifest review needed', durationMinutes: 0, sourceAdapter: 'Readable LVN-SUP PASS5 package', requiredFor: 'Independent-practice clearance', note: 'Readable package; release remains gated until its canonical manifest is reconciled.' },
  ],
  RN: [{ id: 'RN-REGISTRY', title: '16 RN registry requirements', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Existing Journey registry only', requiredFor: 'RN pathway', note: 'No RN module packages are present in this workspace.' }],
  HHA: [{ id: 'HHA-REGISTRY', title: '12 HHA modules + supervised practice', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Existing Journey registry only', requiredFor: 'HHA pathway', note: 'No HHA module packages are present in this workspace.' }],
  PT: [{ id: 'PT-REGISTRY', title: '10 PT modules + supervisory validation', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'PT pathway', note: 'The PT pathway is mapped, but its current module export was not supplied.' }],
  PTA: [{ id: 'PTA-REGISTRY', title: '10 PTA modules + supervisory validation', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'PTA pathway', note: 'The PTA pathway is mapped, but its current module export was not supplied.' }],
  OT: [{ id: 'OT-REGISTRY', title: '10 OT modules + supervisory validation', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'OT pathway', note: 'The OT pathway is mapped, but its current module export was not supplied.' }],
  COTA: [{ id: 'COTA-REGISTRY', title: '10 COTA modules + supervisory validation', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'COTA pathway', note: 'The COTA pathway is mapped, but its current module export was not supplied.' }],
  SLP: [{ id: 'SLP-REGISTRY', title: '8 SLP modules + supervisory validation', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'SLP pathway', note: 'The SLP pathway is mapped, but its current module export was not supplied.' }],
  MSW: [{ id: 'MSW-REGISTRY', title: '8 MSW modules + supervisory validation', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'MSW pathway', note: 'The MSW pathway is mapped, but its current module export was not supplied.' }],
  ADM: [{ id: 'ADM-REGISTRY', title: '15 Administrator registry requirements', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Existing Journey registry only', requiredFor: 'Administrator pathway', note: 'No Administrator module packages are present in this workspace.' }],
  DON: [{ id: 'DON-REGISTRY', title: '16 DON / Clinical Manager registry requirements', track: 'ROLE', kind: 'module', state: 'not_connected', dueLabel: 'Content adapter needed', durationMinutes: 0, sourceAdapter: 'Declared onboarding registry', requiredFor: 'Clinical leadership pathway', note: 'The DON pathway is mapped, but its current module export was not supplied.' }],
  GB: [{ id: 'GB-ACADEMY', title: '12 Governing Body modules + integrated capstone', track: 'ROLE', kind: 'module', state: 'ready', dueLabel: 'Complete within 30 days', durationMinutes: 620, sourceAdapter: 'Governing Body Academy RC1', requiredFor: 'Governing Body pathway', note: 'All executive labs and remediation are available. Certification remains policy/crosswalk gated.' }],
};
