/**
 * Brad Session State — Stateful Case-Based Chat
 *
 * Each chat thread is its own persistent case context.
 * The session state drives:
 *   - retrieval scoping (conversation-aware query expansion)
 *   - mode locking (emergency locks until explicit close)
 *   - prompt injection (case summary + active context)
 *   - UI panel (ActiveCasePanel shows current state)
 *
 * Architecture rule: session state is NEVER generated by the LLM.
 * It is deterministically managed by the session classifier and manager.
 */

export type BradMode =
  | 'general'
  | 'emergency_response'
  | 'clinical_protocol'
  | 'policy_interpretation'
  | 'action_plan'
  | 'form_completion'
  | 'incident_reporting'
  | 'qapi_followup'
  | 'survey_readiness'
  | 'compliance_investigation'
  | 'context_assist';

export type BradUrgency = 'low' | 'moderate' | 'high' | 'critical';

export type IncidentType =
  | 'suspected_heart_attack'
  | 'stroke'
  | 'fall_with_injury'
  | 'medication_error'
  | 'abuse_allegation'
  | 'data_breach'
  | 'survey_event'
  | 'infection_control'
  | 'documentation_deficiency'
  | 'respiratory_emergency'
  | 'other';

export type UserRole =
  | 'administrator'
  | 'director_of_nursing'
  | 'clinical_manager'
  | 'field_clinician'
  | 'intake'
  | 'hr'
  | 'billing'
  | 'compliance'
  | 'unknown';

export type UserIntent =
  | 'ask_protocol'
  | 'ask_next_step'
  | 'ask_documentation'
  | 'ask_policy_basis'
  | 'ask_notification_chain'
  | 'ask_form'
  | 'ask_qapi'
  | 'ask_summary'
  | 'report_incident'
  | 'general_question'
  | 'context_assist_request'
  | 'unknown';

export interface BradTimelineEvent {
  id: string;
  timestamp: string;
  actor: 'user' | 'brad' | 'system';
  eventType:
    | 'case_opened'
    | 'user_message'
    | 'brad_response'
    | 'mode_change'
    | 'urgency_change'
    | 'incident_detected'
    | 'life_safety_flagged'
    | 'task_added'
    | 'task_completed'
    | 'form_referenced'
    | 'policy_cited'
    | 'case_closed';
  summary: string;
  metadata?: Record<string, unknown>;
}

/** Stored in session history for context re-injection */
export interface StoredMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;        // raw user input or directAnswer snippet
  timestamp: string;
  mode: BradMode;
  urgency: BradUrgency;
}

export type CaseStatus = 'active' | 'resolved' | 'requires_followup' | 'closed';

export interface BradSessionState {
  sessionId: string;
  threadId: string;
  createdAt: string;
  updatedAt: string;

  mode: BradMode;
  urgency: BradUrgency;
  caseStatus: CaseStatus;

  caseTitle: string | null;
  caseSummary: string | null;

  detectedIncidentType: IncidentType | null;
  userRole: UserRole;

  activeDomains: string[];
  activeSubdomains: string[];
  activePolicies: string[];
  activeForms: string[];

  lastUserIntent: UserIntent;

  lifeSafetyFlag: boolean;
  escalationRequired: boolean;
  formsRequired: boolean;
  qapiTriggerPossible: boolean;
  complianceRiskLevel: 'none' | 'low' | 'medium' | 'high';

  immediateActions: string[];
  pendingTasks: string[];
  completedTasks: string[];
  openQuestions: string[];

  timeline: BradTimelineEvent[];
  recentMessages: StoredMessage[];   // last 6 messages for context assembly
  messageCount: number;
}

/** Classification result from analyzing a single user turn */
export interface ClassificationResult {
  mode: BradMode;
  urgency: BradUrgency;
  incidentType: IncidentType | null;
  intent: UserIntent;
  isContinuation: boolean;    // true = continues active case
  isTopicShift: boolean;      // true = user explicitly changed topic
  lifeSafetyFlag: boolean;
  escalationRequired: boolean;
  qapiTriggerPossible: boolean;
  detectedDomains: string[];
  detectedRole: UserRole | null;
  confidence: number;         // 0-1 classification confidence
}

/** Light state returned with every chat response (no messages array) */
export interface SessionSummary {
  threadId: string;
  mode: BradMode;
  urgency: BradUrgency;
  caseStatus: CaseStatus;
  caseTitle: string | null;
  caseSummary: string | null;
  detectedIncidentType: IncidentType | null;
  lifeSafetyFlag: boolean;
  escalationRequired: boolean;
  formsRequired: boolean;
  qapiTriggerPossible: boolean;
  immediateActions: string[];
  pendingTasks: string[];
  activePolicies: string[];
  activeForms: string[];
  messageCount: number;
  createdAt: string;
  updatedAt: string;
}
