#!/usr/bin/env python3
"""
Generate PolicyContent TypeScript from ALL_POLICIES.md.
Uses Policy ID rows in header tables to locate all 227 policies.
Output: src/policy/data/allPoliciesContent.generated.ts
        src/policy/data/policyContentMap.ts
"""

import re
import json
import os

ROOT = r"C:\AI\Git\training\HomeHealth\Policies_and_Procedures"
SOURCE = os.path.join(ROOT, "Builder", "Policies", "ALL_POLICIES.md")
OUT_TS = os.path.join(ROOT, "src", "policy", "data", "allPoliciesContent.generated.ts")
MAP_TS = os.path.join(ROOT, "src", "policy", "data", "policyContentMap.ts")


def slugify(text):
    text = re.sub(r'[^\w\s-]', '', text.lower())
    text = re.sub(r'[\s_]+', '-', text)
    return re.sub(r'-+', '-', text).strip('-')[:60]


def parse_policies(content):
    lines = content.split('\n')

    # Find every "| Policy ID | XX-XX-NNN |" row — one per policy
    id_row_re = re.compile(r'^\|\s*Policy ID\s*\|\s*([A-Z]{2}-[A-Z]{2}-\d{3})\s*\|')
    policy_header_lines = []  # (line_index, policy_id)
    for i, line in enumerate(lines):
        m = id_row_re.match(line)
        if m:
            policy_header_lines.append((i, m.group(1)))

    # Deduplicate — keep first occurrence per ID
    seen = set()
    deduped = []
    for entry in policy_header_lines:
        if entry[1] not in seen:
            seen.add(entry[1])
            deduped.append(entry)
    policy_header_lines = deduped
    print(f"  Found {len(policy_header_lines)} unique policy IDs via header tables")

    policies = []

    for idx, (hdr_line, pid) in enumerate(policy_header_lines):
        # Scan back from the Policy ID row to find the nearest ## or # heading
        # that begins this policy's block
        block_start = hdr_line
        for back in range(hdr_line - 1, max(hdr_line - 30, -1), -1):
            l = lines[back].strip()
            if l.startswith('# '):
                block_start = back
                break
            if l.startswith('## '):
                block_start = back
                break

        # Block ends just before the next policy's block_start (approx)
        if idx + 1 < len(policy_header_lines):
            next_hdr = policy_header_lines[idx + 1][0]
            # Find where next block starts
            block_end = next_hdr
            for back in range(next_hdr - 1, max(next_hdr - 30, -1), -1):
                l = lines[back].strip()
                if l.startswith('# ') or l.startswith('## '):
                    block_end = back
                    break
        else:
            block_end = len(lines)

        policy_lines = lines[block_start:block_end]

        # Extract title
        title = pid
        for line in policy_lines[:15]:
            s = line.strip()
            if s.startswith('# ') and not s.startswith('## '):
                t = s[2:].strip()
                t = re.sub(r'^[A-Z]{2}-[A-Z]{2}-\d{3}\s*[—\-]\s*', '', t)
                if t:
                    title = t
                    break
        if title == pid:
            for line in policy_lines:
                m2 = re.match(r'^\|\s*Policy Title\s*\|\s*(.+?)\s*\|', line)
                if m2:
                    t = m2.group(1).strip()
                    if t and t != 'Policy Title':
                        title = t
                        break

        # Split into ## sections
        sections = []
        cur_heading = None
        cur_body = []

        for line in policy_lines:
            h2 = re.match(r'^## (.+)$', line)
            if h2:
                if cur_heading is not None:
                    sections.append((cur_heading, '\n'.join(cur_body).strip()))
                cur_heading = h2.group(1).strip().replace('\\.', '.')
                cur_body = []
            elif cur_heading is not None:
                cur_body.append(line)

        if cur_heading is not None:
            sections.append((cur_heading, '\n'.join(cur_body).strip()))

        if sections:
            policies.append((pid, title, sections))

    return policies


def generate_ts(policies):
    lines = []
    lines.append("/* Auto-generated by Builder/Policies/generate_policy_content.py */")
    lines.append("/* DO NOT EDIT MANUALLY — re-run generate_policy_content.py to update */")
    lines.append("import type { PolicyContent } from '../types';")
    lines.append("")

    var_names = []

    for pid, title, sections in policies:
        # GV-GB-001 has its own specimenContent.generated.ts — skip
        if pid == 'GV-GB-001':
            continue

        var_name = re.sub(r'[^a-zA-Z0-9]', '_', pid) + '_content'
        var_names.append((pid, var_name))

        lines.append(f"export const {var_name}: PolicyContent = {{")
        lines.append(f"  policyId: {json.dumps(pid)},")
        lines.append(f"  sourceType: 'markdown',")
        lines.append(f"  sourceRef: {json.dumps(f'Builder/Policies/ALL_POLICIES.md#{pid}')},")
        lines.append(f"  sections: [")

        for order, (sec_title, sec_body) in enumerate(sections, start=1):
            sec_id = f"{order + 1}-{slugify(sec_title)}"
            lines.append(f"    {{")
            lines.append(f"      id: {json.dumps(sec_id)},")
            lines.append(f"      title: {json.dumps(sec_title)},")
            lines.append(f"      level: 2,")
            lines.append(f"      order: {order + 1},")
            lines.append(f"      body: {json.dumps(sec_body)},")
            lines.append(f"      scormChunkHint: 'module',")
            lines.append(f"    }},")

        lines.append(f"  ],")
        lines.append(f"}};")
        lines.append(f"")

    lines.append("export const ALL_GENERATED_POLICIES: Record<string, PolicyContent> = {")
    for pid, var_name in var_names:
        lines.append(f"  {json.dumps(pid)}: {var_name},")
    lines.append("};")
    lines.append("")

    return '\n'.join(lines)


def update_content_map():
    return """import { specimenPolicyContent } from '@/policy/data/specimenContent.generated';
import { ALL_GENERATED_POLICIES } from '@/policy/data/allPoliciesContent.generated';
import type { PolicyContent } from '@/policy/types';

const contentMap: Record<string, PolicyContent> = {
  [specimenPolicyContent.policyId]: specimenPolicyContent,
  ...ALL_GENERATED_POLICIES,
};

export function getPolicyBody(policyId: string): string | null {
  const content = contentMap[policyId];
  if (!content) return null;
  return content.sections
    .map(section => `## ${section.title}\\n\\n${section.body}`)
    .join('\\n\\n');
}

export function getPolicyContent(policyId: string): PolicyContent | null {
  return contentMap[policyId] || null;
}
"""


def main():
    print(f"Reading {SOURCE}...")
    with open(SOURCE, 'r', encoding='utf-8') as f:
        content = f.read()

    print("Parsing policies...")
    policies = parse_policies(content)
    print(f"Total policies parsed: {len(policies)}")
    for pid, title, sections in policies[:5]:
        print(f"  {pid}: {title} ({len(sections)} sections)")

    print(f"\nWriting {OUT_TS}...")
    ts_content = generate_ts(policies)
    with open(OUT_TS, 'w', encoding='utf-8') as f:
        f.write(ts_content)
    print(f"Done. {len(ts_content):,} chars")

    print(f"\nWriting {MAP_TS}...")
    with open(MAP_TS, 'w', encoding='utf-8') as f:
        f.write(update_content_map())

    print("\nAll done. Run: npm run build")


if __name__ == '__main__':
    main()
